import Mathlib
import BezoutCounterexample.Constructive.Attr

/-!
# Duality by `𝔭`-adic jets

Proposition 3.2 of `bezout-direct.tex`: for any `ℚ`-algebra `S`, elements `x₁, …, x_j` and
derivations `∂₁, …, ∂_j` with `∂ᵢ xₖ = δᵢₖ`, and positive integer weights `w`,

  `g ∈ F_t  ↔  ∂^α g ∈ 𝔭` for all `α` with `w · α < t`,

where `F_t = (x^α : w · α ≥ t)` and `𝔭 = (x₁, …, x_j)`. No Noetherian hypothesis, no locality,
no Krull intersection theorem, no coefficient field: this replaces `IsCentred.mem_F_iff` /
`mem_RF_iff` (whose proof uses `Ideal.iInf_pow_eq_bot_of_isLocalRing`).

The derivations need not commute: `∂^α` is taken in a fixed order (`Dl` on lists of indices).

Multi-indices are functions `Fin j → ℕ` (decidable, no `Finsupp`).
-/

namespace BezoutCounterexample.Constructive

open Finset

variable {S : Type*} [CommRing S] [Algebra ℚ S] {j : ℕ}

/-- A partial chart: `j` elements with dual derivations. -/
structure PChart (S : Type*) [CommRing S] [Algebra ℚ S] (j : ℕ) where
  x : Fin j → S
  d : Fin j → Derivation ℚ S S
  dual : ∀ i k, d i (x k) = if i = k then 1 else 0

/-- The multi-index `eᵢ`. -/
def unit (i : Fin j) : Fin j → ℕ := fun k => if k = i then 1 else 0

/-- Total degree. -/
def deg (β : Fin j → ℕ) : ℕ := ∑ i, β i

/-- Weighted degree. -/
def wt (w : Fin j → ℕ) (β : Fin j → ℕ) : ℕ := ∑ i, w i * β i

/-- Descending-factorial coefficient `∏ βᵢ (βᵢ - 1) ⋯ (βᵢ - αᵢ + 1)`; zero unless `α ≤ β`. -/
def coef (α β : Fin j → ℕ) : ℕ := ∏ i, (β i).descFactorial (α i)

/-- The multi-indices of degree `N`, as a finite type. -/
abbrev Tup (j N : ℕ) : Type := (Finset.Nat.antidiagonalTuple j N : Set (Fin j → ℕ))

instance (j N : ℕ) : DecidableEq (Tup j N) := fun a b =>
  decidable_of_iff ((a : Fin j → ℕ) = b) Subtype.ext_iff.symm

namespace PChart

variable (c : PChart S j)

/-- The monomial `x^β`. -/
def mono (β : Fin j → ℕ) : S := ∏ i, c.x i ^ β i

/-- The weighted monomial ideal `F_t`. -/
def F (w : Fin j → ℕ) (t : ℕ) : Ideal S := Ideal.span {m | ∃ β, t ≤ wt w β ∧ m = c.mono β}

/-- The ideal generated by the (finitely many) monomials of degree `N` (this is `𝔭^N`). -/
def Q (N : ℕ) : Ideal S := Ideal.span (Set.range fun β : Tup j N => c.mono β)

/-- `𝔭 = (x₁, …, x_j)`. -/
def P : Ideal S := Ideal.span (Set.range c.x)

/-- Iterated derivative along a list of indices (applied right to left). -/
def Dl (c : PChart S j) : List (Fin j) → S → S
  | [] => fun s => s
  | i :: l => fun s => c.d i (Dl c l s)

/-- The multi-index counted by a list. -/
def cnt (l : List (Fin j)) : Fin j → ℕ := fun i => l.count i

/-- A list realizing the multi-index `α`. -/
def ofIdx (α : Fin j → ℕ) : List (Fin j) := (List.finRange j).flatMap fun i => List.replicate (α i) i

/-- `∂^α`. -/
def D (α : Fin j → ℕ) : S → S := c.Dl (ofIdx α)

/-! ## Multi-index arithmetic -/

lemma cnt_cons (i : Fin j) (l : List (Fin j)) : cnt (i :: l) = cnt l + unit i := by
  funext k
  simp only [cnt, List.count_cons, unit, Pi.add_apply, beq_iff_eq]
  by_cases h : k = i
  · subst h; simp
  · simp [h, Ne.symm h]

lemma cnt_ofIdx (α : Fin j → ℕ) : cnt (ofIdx α) = α := by
  funext k
  simp only [cnt, ofIdx, List.count_flatMap, List.count_replicate]
  rw [List.sum_map_eq_nsmul_single k]
  · simp
  · intro i hne _
    simp [List.count_replicate, hne]

lemma deg_add (α β : Fin j → ℕ) : deg (α + β) = deg α + deg β := by
  simp [deg, Finset.sum_add_distrib]

lemma deg_unit (i : Fin j) : deg (unit i) = 1 := by
  simp [deg, unit]

lemma wt_add (w α β : Fin j → ℕ) : wt w (α + β) = wt w α + wt w β := by
  simp [wt, mul_add, Finset.sum_add_distrib]

lemma wt_unit (w : Fin j → ℕ) (i : Fin j) : wt w (unit i) = w i := by
  simp [wt, unit]

lemma deg_le_wt {w : Fin j → ℕ} (hw : ∀ i, 1 ≤ w i) (β : Fin j → ℕ) : deg β ≤ wt w β := by
  unfold deg wt
  exact Finset.sum_le_sum fun i _ => Nat.le_mul_of_pos_left _ (hw i)

lemma deg_cnt (l : List (Fin j)) : deg (cnt l) = l.length := by
  induction l with
  | nil => simp [deg, cnt]
  | cons i l ih => rw [cnt_cons, deg_add, deg_unit, ih, List.length_cons]

/-- Subtracting `eᵢ` from a multi-index with `βᵢ ≥ 1`. -/
lemma sub_unit_add {β : Fin j → ℕ} {i : Fin j} (h : 1 ≤ β i) : (β - unit i) + unit i = β := by
  funext k
  simp only [Pi.add_apply, Pi.sub_apply, unit]
  split_ifs with hk
  · subst hk; omega
  · omega

/-- A multi-index of positive degree has a positive entry (decidable search). -/
lemma exists_pos_of_deg_pos {β : Fin j → ℕ} (h : 0 < deg β) : ∃ i, 1 ≤ β i := by
  unfold deg at h
  obtain ⟨i, _, hi⟩ := Finset.exists_lt_of_sum_lt (s := Finset.univ) (f := fun _ => 0)
    (g := β) (by simpa using h)
  exact ⟨i, hi⟩

/-- Two different multi-indices of the same degree: some entry of the first exceeds the second. -/
lemma exists_gt_of_ne {α β : Fin j → ℕ} (hd : deg α = deg β) (hne : α ≠ β) :
    ∃ i, β i < α i := by
  by_contra h
  push Not at h
  apply hne
  have hsum : ∑ i, α i = ∑ i, β i := hd
  exact funext fun i => (Finset.sum_eq_sum_iff_of_le fun i _ => h i).1 hsum i (Finset.mem_univ i)

lemma coef_eq_zero_of_lt {α β : Fin j → ℕ} {i : Fin j} (h : β i < α i) : coef α β = 0 :=
  Finset.prod_eq_zero (Finset.mem_univ i) (Nat.descFactorial_eq_zero_iff_lt.2 h)

lemma coef_self (α : Fin j → ℕ) : coef α α = ∏ i, (α i).factorial := by
  simp [coef, Nat.descFactorial_self]

lemma coef_add_unit (α β : Fin j → ℕ) (i : Fin j) :
    coef (α + unit i) β = (β i - α i) * coef α β := by
  unfold coef
  rw [← Finset.mul_prod_erase _ _ (Finset.mem_univ i),
    ← Finset.mul_prod_erase (s := Finset.univ) (f := fun k => (β k).descFactorial (α k))
      (Finset.mem_univ i)]
  have h1 : ∀ k ∈ Finset.univ.erase i, (β k).descFactorial ((α + unit i) k) =
      (β k).descFactorial (α k) := by
    intro k hk
    have : k ≠ i := Finset.ne_of_mem_erase hk
    simp [unit, this]
  rw [Finset.prod_congr rfl h1]
  have hi : (α + unit i) i = α i + 1 := by simp [unit]
  rw [hi, Nat.descFactorial_succ]
  ring

/-! ## Monomials -/

lemma mono_zero : c.mono 0 = 1 := by simp [mono]

lemma mono_add (α β : Fin j → ℕ) : c.mono (α + β) = c.mono α * c.mono β := by
  simp [mono, pow_add, Finset.prod_mul_distrib]

lemma mono_unit (i : Fin j) : c.mono (unit i) = c.x i := by
  unfold mono unit
  rw [Finset.prod_eq_single i]
  · simp
  · intro k _ hk; simp [hk]
  · simp

/-- The derivative of a monomial: `∂ᵢ x^β = βᵢ x^{β - eᵢ}`. -/
lemma d_mono (i : Fin j) (β : Fin j → ℕ) :
    c.d i (c.mono β) = (β i : S) * c.mono (β - unit i) := by
  -- split off the `i`-th factor
  have hsplit : ∀ γ : Fin j → ℕ, c.mono γ =
      c.x i ^ γ i * ∏ k ∈ Finset.univ.erase i, c.x k ^ γ k := fun γ =>
    (Finset.mul_prod_erase _ _ (Finset.mem_univ i)).symm
  have hrest : c.d i (∏ k ∈ Finset.univ.erase i, c.x k ^ β k) = 0 := by
    have key : ∀ s : Finset (Fin j), i ∉ s → c.d i (∏ k ∈ s, c.x k ^ β k) = 0 := by
      intro s
      induction s using Finset.induction_on with
      | empty => intro _; simp
      | insert a s ha ih =>
        intro hi
        have hai : i ≠ a := fun h => hi (h ▸ Finset.mem_insert_self _ _)
        rw [Finset.prod_insert ha, Derivation.leibniz, ih (fun h => hi (Finset.mem_insert_of_mem h)),
          Derivation.leibniz_pow, c.dual, if_neg hai]
        simp
    exact key _ (Finset.notMem_erase i _)
  have hrest' : ∏ k ∈ Finset.univ.erase i, c.x k ^ (β - unit i) k =
      ∏ k ∈ Finset.univ.erase i, c.x k ^ β k := by
    refine Finset.prod_congr rfl fun k hk => ?_
    have : k ≠ i := Finset.ne_of_mem_erase hk
    simp [unit, this]
  rw [hsplit β, hsplit (β - unit i), Derivation.leibniz, hrest, Derivation.leibniz_pow, c.dual,
    if_pos rfl, hrest']
  simp only [Pi.sub_apply, unit, if_pos rfl, smul_eq_mul, mul_one, nsmul_eq_mul, if_true]
  ring

/-! ## The ideals `Q N` -/

lemma mono_mem_Q (β : Fin j → ℕ) : c.mono β ∈ c.Q (deg β) :=
  Ideal.subset_span ⟨⟨β, by simp [deg, Finset.Nat.mem_antidiagonalTuple]⟩, rfl⟩

lemma Q_zero : c.Q 0 = ⊤ := by
  rw [Ideal.eq_top_iff_one, ← c.mono_zero]
  have : deg (0 : Fin j → ℕ) = 0 := by simp [deg]
  exact this ▸ c.mono_mem_Q 0

lemma deg_of_mem {N : ℕ} (β : Tup j N) :
    deg (β : Fin j → ℕ) = N := by
  have h := β.2
  rw [Finset.mem_coe, Finset.Nat.mem_antidiagonalTuple] at h
  exact h

lemma Q_succ_le (N : ℕ) : c.Q (N + 1) ≤ c.Q N := by
  rw [Q, Ideal.span_le]
  rintro _ ⟨⟨β, hβ'⟩, rfl⟩
  have hβ : deg β = N + 1 := deg_of_mem ⟨β, hβ'⟩
  show c.mono β ∈ c.Q N
  obtain ⟨i, hi⟩ := exists_pos_of_deg_pos (β := β) (by omega)
  have hdeg : deg (β - unit i) = N := by
    have := deg_add (β - unit i) (unit i)
    rw [sub_unit_add hi, deg_unit] at this; omega
  rw [← sub_unit_add hi, c.mono_add]
  exact Ideal.mul_mem_right _ _ (hdeg ▸ c.mono_mem_Q _)

lemma Q_anti {M N : ℕ} (h : M ≤ N) : c.Q N ≤ c.Q M := by
  induction N, h using Nat.le_induction with
  | base => exact le_rfl
  | succ N _ ih => exact (c.Q_succ_le N).trans ih

lemma Q_one : c.Q 1 = c.P := by
  apply le_antisymm
  · rw [Q, Ideal.span_le]
    rintro _ ⟨⟨β, hβ'⟩, rfl⟩
    have hβ : deg β = 1 := deg_of_mem ⟨β, hβ'⟩
    obtain ⟨i, hi⟩ := exists_pos_of_deg_pos (β := β) (by omega)
    show c.mono β ∈ c.P
    rw [← sub_unit_add hi, c.mono_add, c.mono_unit]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)
  · rw [P, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    rw [← c.mono_unit]
    exact deg_unit i ▸ c.mono_mem_Q (unit i)

/-- `𝔭 · Q N ⊆ Q (N + 1)`, elementwise. -/
lemma mul_mono_mem_Q {r : S} (hr : r ∈ c.P) (β : Fin j → ℕ) :
    r * c.mono β ∈ c.Q (deg β + 1) := by
  rw [← c.Q_one] at hr
  refine Submodule.span_induction (p := fun r _ => r * c.mono β ∈ c.Q (deg β + 1)) ?_ ?_ ?_ ?_ hr
  · rintro _ ⟨⟨γ, hγ'⟩, rfl⟩
    have hγ : deg γ = 1 := deg_of_mem ⟨γ, hγ'⟩
    show c.mono γ * c.mono β ∈ _
    rw [← c.mono_add]
    have : deg (γ + β) = deg β + 1 := by rw [deg_add, hγ]; omega
    exact this ▸ c.mono_mem_Q _
  · simp
  · intro a b _ _ ha hb; rw [add_mul]; exact add_mem ha hb
  · intro a b _ hb; rw [smul_eq_mul, mul_assoc]; exact Ideal.mul_mem_left _ _ hb

/-- Derivations lower the degree filtration by one. -/
lemma d_mem_Q (i : Fin j) (N : ℕ) {s : S} (hs : s ∈ c.Q (N + 1)) : c.d i s ∈ c.Q N := by
  refine Submodule.span_induction (p := fun s _ => c.d i s ∈ c.Q N) ?_ ?_ ?_ ?_ hs
  · rintro _ ⟨⟨β, hβ'⟩, rfl⟩
    have hβ : deg β = N + 1 := deg_of_mem ⟨β, hβ'⟩
    show c.d i (c.mono β) ∈ _
    rw [c.d_mono]
    rcases Nat.eq_zero_or_pos (β i) with h0 | hpos
    · simp [h0]
    · have hdeg : deg (β - unit i) = N := by
        have := deg_add (β - unit i) (unit i)
        rw [sub_unit_add hpos, deg_unit] at this; omega
      exact Ideal.mul_mem_left _ _ (hdeg ▸ c.mono_mem_Q _)
  · simp
  · intro a b _ _ ha hb; rw [map_add]; exact add_mem ha hb
  · intro a b hb hdb
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    refine add_mem (Ideal.mul_mem_left _ _ hdb) (Ideal.mul_mem_right _ _ ?_)
    exact c.Q_succ_le N hb

/-! ## Iterated derivatives -/

lemma Dl_add (l : List (Fin j)) (a b : S) : c.Dl l (a + b) = c.Dl l a + c.Dl l b := by
  induction l with
  | nil => rfl
  | cons i l ih => simp [Dl, ih]

lemma Dl_sub (l : List (Fin j)) (a b : S) : c.Dl l (a - b) = c.Dl l a - c.Dl l b := by
  induction l with
  | nil => rfl
  | cons i l ih => simp [Dl, ih]

lemma Dl_zero (l : List (Fin j)) : c.Dl l 0 = 0 := by
  induction l with
  | nil => rfl
  | cons i l ih => simp [Dl, ih]

lemma Dl_sum {ι : Type*} [DecidableEq ι] (l : List (Fin j)) (s : Finset ι) (f : ι → S) :
    c.Dl l (∑ k ∈ s, f k) = ∑ k ∈ s, c.Dl l (f k) := by
  induction s using Finset.induction_on with
  | empty => simp [Dl_zero]
  | insert a s ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, Dl_add, ih]

lemma Dl_smul (l : List (Fin j)) (q : ℚ) (a : S) : c.Dl l (q • a) = q • c.Dl l a := by
  induction l with
  | nil => rfl
  | cons i l ih => simp [Dl, ih]

/-- **Leibniz modulo the degree filtration.** -/
lemma Dl_mul_mono (l : List (Fin j)) (r : S) (β : Fin j → ℕ) (hl : l.length ≤ deg β) :
    c.Dl l (r * c.mono β) - (coef (cnt l) β : S) * (r * c.mono (β - cnt l)) ∈
      c.Q (deg β + 1 - l.length) := by
  induction l with
  | nil =>
    have h0 : cnt ([] : List (Fin j)) = 0 := by funext k; simp [cnt]
    simp [Dl, h0, coef]
  | cons i l ih =>
    have hl' : l.length ≤ deg β := by simp at hl; omega
    have ih := ih hl'
    set m := deg β + 1 - l.length with hm
    have hm1 : deg β + 1 - (i :: l).length + 1 = m := by simp at hl ⊢; omega
    -- apply `∂ᵢ` to the inductive statement
    have h1 : c.d i (c.Dl l (r * c.mono β) - (coef (cnt l) β : S) * (r * c.mono (β - cnt l))) ∈
        c.Q (deg β + 1 - (i :: l).length) :=
      c.d_mem_Q i _ (hm1 ▸ ih)
    -- the main term
    set δ := β - cnt l with hδ
    have h2 : c.d i ((coef (cnt l) β : S) * (r * c.mono δ)) =
        (coef (cnt l) β : S) * (c.d i r * c.mono δ) +
          (coef (cnt (i :: l)) β : S) * (r * c.mono (β - cnt (i :: l))) := by
      have hc : (coef (cnt (i :: l)) β : S) = ((δ i : ℕ) : S) * (coef (cnt l) β : S) := by
        rw [cnt_cons, coef_add_unit]; push_cast; rfl
      have hsub : β - cnt (i :: l) = δ - unit i := by
        rw [cnt_cons]; funext k; simp only [hδ, Pi.sub_apply, Pi.add_apply]; omega
      rw [hc, hsub, Derivation.leibniz, Derivation.leibniz, c.d_mono, Derivation.map_natCast]
      simp only [smul_eq_mul, mul_zero, add_zero]
      ring
    -- the error term from `∂ᵢ r`
    have h3 : (coef (cnt l) β : S) * (c.d i r * c.mono δ) ∈ c.Q (deg β + 1 - (i :: l).length) := by
      rcases Nat.eq_zero_or_pos (coef (cnt l) β) with hz | hpos
      · rw [hz]; simp
      have hle : ∀ k, cnt l k ≤ β k := fun k =>
        Nat.le_of_not_lt fun hk => (Nat.pos_iff_ne_zero.1 hpos) (coef_eq_zero_of_lt hk)
      refine Ideal.mul_mem_left _ _ (Ideal.mul_mem_left _ _ ?_)
      have hδc : δ + cnt l = β := by
        funext k; simp only [hδ, Pi.add_apply, Pi.sub_apply]; have := hle k; omega
      have hdeg : deg δ = deg β - l.length := by
        have := deg_add δ (cnt l)
        rw [hδc, deg_cnt] at this; omega
      have : deg β + 1 - (i :: l).length = deg δ := by simp; omega
      exact this ▸ c.mono_mem_Q δ
    have e : c.Dl (i :: l) (r * c.mono β) - (coef (cnt (i :: l)) β : S) * (r * c.mono (β - cnt (i :: l))) =
        c.d i (c.Dl l (r * c.mono β) - (coef (cnt l) β : S) * (r * c.mono (β - cnt l))) +
          (coef (cnt l) β : S) * (c.d i r * c.mono δ) := by
      rw [map_sub, h2]; simp only [Dl]; ring
    rw [e]
    exact add_mem h1 h3

/-! ## The weighted ideals `F_t` -/

variable {w : Fin j → ℕ}

lemma mono_mem_F {β : Fin j → ℕ} {t : ℕ} (h : t ≤ wt w β) : c.mono β ∈ c.F w t :=
  Ideal.subset_span ⟨β, h, rfl⟩

lemma F_anti {s t : ℕ} (h : s ≤ t) : c.F w t ≤ c.F w s := by
  rw [F, Ideal.span_le]
  rintro _ ⟨β, hβ, rfl⟩
  exact c.mono_mem_F (le_trans h hβ)

/-- `∂ᵢ F_t ⊆ F_{t - wᵢ}`. -/
lemma d_mem_F (i : Fin j) (t : ℕ) {s : S} (hs : s ∈ c.F w t) : c.d i s ∈ c.F w (t - w i) := by
  refine Submodule.span_induction (p := fun s _ => c.d i s ∈ c.F w (t - w i)) ?_ ?_ ?_ ?_ hs
  · rintro _ ⟨β, hβ, rfl⟩
    rw [c.d_mono]
    rcases Nat.eq_zero_or_pos (β i) with h0 | hpos
    · simp [h0]
    · refine Ideal.mul_mem_left _ _ (c.mono_mem_F ?_)
      have := wt_add w (β - unit i) (unit i)
      rw [sub_unit_add hpos, wt_unit] at this
      omega
  · simp
  · intro a b _ _ ha hb; rw [map_add]; exact add_mem ha hb
  · intro a b hb hdb
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact add_mem (Ideal.mul_mem_left _ _ hdb) (Ideal.mul_mem_right _ _ (c.F_anti (Nat.sub_le t (w i)) hb))

lemma Dl_mem_F (l : List (Fin j)) (t : ℕ) {s : S} (hs : s ∈ c.F w t) :
    c.Dl l s ∈ c.F w (t - wt w (cnt l)) := by
  induction l with
  | nil =>
    have h0 : wt w (cnt ([] : List (Fin j))) = 0 := by simp [wt, cnt]
    simpa [Dl, h0] using hs
  | cons i l ih =>
    have h := c.d_mem_F i _ ih
    rw [cnt_cons, wt_add, wt_unit, ← Nat.sub_sub]
    exact h

lemma F_le_P {t : ℕ} (ht : 1 ≤ t) : c.F w t ≤ c.P := by
  rw [F, Ideal.span_le]
  rintro _ ⟨β, hβ, rfl⟩
  have hpos : 0 < wt w β := lt_of_lt_of_le ht hβ
  obtain ⟨k, _, hk⟩ := Finset.exists_lt_of_sum_lt (s := Finset.univ) (f := fun _ => 0)
    (g := fun i => w i * β i) (by simpa [wt] using hpos)
  have hβk : 1 ≤ β k := Nat.pos_of_ne_zero fun h => by simp [h] at hk
  rw [← c.Q_one]
  have hdeg : 1 ≤ deg β := le_trans hβk (Finset.single_le_sum (fun i _ => Nat.zero_le _) (Finset.mem_univ k))
  exact c.Q_anti hdeg (c.mono_mem_Q β)

lemma Q_le_F (hw : ∀ i, 1 ≤ w i) (t : ℕ) : c.Q t ≤ c.F w t := by
  rw [Q, Ideal.span_le]
  rintro _ ⟨β, rfl⟩
  refine c.mono_mem_F ?_
  have := deg_le_wt hw (β : Fin j → ℕ)
  rw [deg_of_mem β] at this
  exact this

/-! ## The duality theorem -/

/-- The easy direction. -/
theorem D_mem_P_of_mem_F {t : ℕ} {g : S} (hg : g ∈ c.F w t) (α : Fin j → ℕ) (hα : wt w α < t) :
    c.D α g ∈ c.P := by
  have h := c.Dl_mem_F (ofIdx α) t hg
  rw [cnt_ofIdx] at h
  exact c.F_le_P (by omega) h

lemma length_ofIdx (α : Fin j → ℕ) : (ofIdx α).length = deg α := by
  rw [← deg_cnt, cnt_ofIdx]

/-- Rational multiples. -/
lemma mem_of_nat_mul_mem {I : Ideal S} {n : ℕ} (hn : n ≠ 0) {r : S} (h : (n : S) * r ∈ I) : r ∈ I := by
  have e : r = algebraMap ℚ S (n : ℚ)⁻¹ * ((n : S) * r) := by
    rw [← mul_assoc, ← map_natCast (algebraMap ℚ S) n, ← map_mul, inv_mul_cancel₀ (by exact_mod_cast hn),
      map_one, one_mul]
  rw [e]
  exact Ideal.mul_mem_left _ _ h

lemma factorial_prod_ne_zero (β : Fin j → ℕ) : (∏ i, (β i).factorial) ≠ 0 :=
  Finset.prod_ne_zero_iff.2 fun i _ => Nat.factorial_ne_zero _

/-- One step of the induction: the coefficients of low weight lie in `𝔭`. -/
lemma step {t N : ℕ} {g : S} (hD : ∀ α, wt w α < t → c.D α g ∈ c.P)
    (hg : g ∈ c.F w t ⊔ c.Q N) (hw : ∀ i, 1 ≤ w i) : g ∈ c.F w t ⊔ c.Q (N + 1) := by
  obtain ⟨f, hf, h, hh, rfl⟩ := Submodule.mem_sup.1 hg
  obtain ⟨r, hr⟩ := (Ideal.mem_span_range_iff_exists_fun).1 hh
  -- each coefficient of weight `< t` is in `𝔭`
  have key : ∀ β : Tup j N, wt w (β : Fin j → ℕ) < t → r β ∈ c.P := by
    intro β hβ
    have hdegβ : deg (β : Fin j → ℕ) = N := deg_of_mem β
    have h1 : c.D β (f + h) ∈ c.P := hD β hβ
    have h2 : c.D β f ∈ c.P := c.D_mem_P_of_mem_F hf β hβ
    have hlen : (ofIdx (β : Fin j → ℕ)).length = N := by rw [length_ofIdx, hdegβ]
    -- the terms of `D β h`
    have hterm : ∀ γ : Tup j N, c.D β (r γ * c.mono γ) - (if γ = β then (coef (β : Fin j → ℕ) β : S) * r γ else 0)
        ∈ c.P := by
      intro γ
      have hdegγ : deg (γ : Fin j → ℕ) = N := deg_of_mem γ
      have hL := c.Dl_mul_mono (ofIdx (β : Fin j → ℕ)) (r γ) γ (by rw [hlen, hdegγ])
      rw [cnt_ofIdx, hlen, hdegγ, Nat.add_sub_cancel_left, c.Q_one] at hL
      unfold D
      by_cases hγβ : γ = β
      · subst hγβ
        rw [if_pos rfl]
        have hz : (γ : Fin j → ℕ) - γ = 0 := by funext k; simp
        rw [hz, c.mono_zero, mul_one] at hL
        exact hL
      · rw [if_neg hγβ, sub_zero]
        have hne : (β : Fin j → ℕ) ≠ γ := fun e => hγβ (Subtype.ext e.symm)
        obtain ⟨i, hi⟩ := exists_gt_of_ne (by rw [hdegβ, hdegγ]) hne
        rw [coef_eq_zero_of_lt hi] at hL
        simpa using hL
    have h3 : c.D β h - (coef (β : Fin j → ℕ) β : S) * r β ∈ c.P := by
      have e : c.D β h - (coef (β : Fin j → ℕ) β : S) * r β = ∑ γ : Tup j N,
          (c.D β (r γ * c.mono γ) - (if γ = β then (coef (β : Fin j → ℕ) β : S) * r γ else 0)) := by
        rw [Finset.sum_sub_distrib, ← hr]
        unfold D
        rw [c.Dl_sum, Finset.sum_ite_eq' Finset.univ β, if_pos (Finset.mem_univ β)]
      rw [e]
      exact Ideal.sum_mem _ fun γ _ => hterm γ
    have h4 : (coef (β : Fin j → ℕ) β : S) * r β ∈ c.P := by
      have e : (coef (β : Fin j → ℕ) β : S) * r β =
          (c.D β (f + h) - c.D β f) - (c.D β h - (coef (β : Fin j → ℕ) β : S) * r β) := by
        unfold D; rw [c.Dl_add]; ring
      rw [e]
      exact sub_mem (sub_mem h1 h2) h3
    rw [coef_self] at h4
    exact mem_of_nat_mul_mem (factorial_prod_ne_zero _) (by exact_mod_cast h4)
  -- reassemble
  rw [← hr]
  refine add_mem (Submodule.mem_sup_left hf) (Ideal.sum_mem _ fun β _ => ?_)
  rcases Nat.lt_or_ge (wt w (β : Fin j → ℕ)) t with hlt | hge
  · apply Submodule.mem_sup_right
    have := c.mul_mono_mem_Q (key β hlt) β
    rwa [deg_of_mem β] at this
  · exact Submodule.mem_sup_left (Ideal.mul_mem_left _ _ (c.mono_mem_F hge))

/-- **Duality by `𝔭`-adic jets.** -/
theorem mem_F_iff (hw : ∀ i, 1 ≤ w i) (t : ℕ) (g : S) :
    g ∈ c.F w t ↔ ∀ α, wt w α < t → c.D α g ∈ c.P := by
  refine ⟨fun hg α hα => c.D_mem_P_of_mem_F hg α hα, fun hD => ?_⟩
  have hall : ∀ N, g ∈ c.F w t ⊔ c.Q N := by
    intro N
    induction N with
    | zero => rw [c.Q_zero]; exact Submodule.mem_sup_right Submodule.mem_top
    | succ N ih => exact c.step hD ih hw
  have h := hall t
  rw [sup_eq_left.2 (c.Q_le_F hw t)] at h
  exact h

end PChart

end BezoutCounterexample.Constructive
