import Mathlib

/-!
# Kernels onto finite-dimensional algebras are finitely generated (multiplication table)

Let `φ : ℚ[Y₁, …, Y_N] → L` be a `ℚ`-algebra map to an algebra with a finite basis `B`, and let
`b₁, …, b_d` be polynomials with `φ bₖ = Bₖ`. Then `ker φ` is generated by the explicit relations

* `1 - ∑ₖ (B-coordinate k of 1) · bₖ`,
* `Yᵢ bⱼ - ∑ₖ (B-coordinate k of φ(Yᵢ) Bⱼ) · bₖ`

(`ker_eq_span_tableRel`). No Hilbert basis theorem: every `p` is congruent modulo these
relations to its canonical representative `∑ₖ (B-coordinate k of φ p) · bₖ` (induction on `p`),
and a representative in the kernel is `0` because `B` is a basis.

This is how the finite generation hypotheses `(maximalIdeal R).FG` (`Chart.exists_centred`) are
to be discharged at an explicit point `z`: `L = κ(z)` is a finite extension of `ℚ` with a given basis.
-/

noncomputable section

namespace BezoutCounterexample.Constructive

open MvPolynomial

variable {N d : ℕ} {L : Type*} [CommRing L] [Algebra ℚ L]
  (φ : MvPolynomial (Fin N) ℚ →ₐ[ℚ] L) (B : Module.Basis (Fin d) ℚ L)
  (b : Fin d → MvPolynomial (Fin N) ℚ)

/-- The canonical representative `∑ₖ (B-coordinate k of φ p) · bₖ`. -/
def tableRep (p : MvPolynomial (Fin N) ℚ) : MvPolynomial (Fin N) ℚ :=
  ∑ k, C (B.repr (φ p) k) * b k

/-- The multiplication-table relations. -/
def tableRel : Option (Fin N × Fin d) → MvPolynomial (Fin N) ℚ
  | none => 1 - ∑ k, C (B.repr 1 k) * b k
  | some (i, j) => X i * b j - ∑ k, C (B.repr (φ (X i) * B j) k) * b k

variable {φ B b}

lemma phi_sum_C_mul (hb : ∀ k, φ (b k) = B k) (c : Fin d → ℚ) :
    φ (∑ k, C (c k) * b k) = ∑ k, c k • B k := by
  rw [map_sum]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [map_mul, algHom_C, hb, Algebra.smul_def]

lemma tableRel_mem_ker (hb : ∀ k, φ (b k) = B k) (o : Option (Fin N × Fin d)) :
    tableRel φ B b o ∈ RingHom.ker φ := by
  rw [RingHom.mem_ker]
  rcases o with _ | ⟨i, j⟩
  · simp only [tableRel]
    rw [map_sub, map_one, phi_sum_C_mul hb, B.sum_repr, sub_self]
  · simp only [tableRel]
    rw [map_sub, map_mul, phi_sum_C_mul hb, B.sum_repr, hb, sub_self]

/-- The coordinates of `φ (p Yᵢ)` from those of `φ p` and the multiplication table. -/
lemma repr_phi_mul_X (p : MvPolynomial (Fin N) ℚ) (i : Fin N) (l : Fin d) :
    B.repr (φ (p * X i)) l = ∑ k, B.repr (φ p) k * B.repr (φ (X i) * B k) l := by
  have h : φ (p * X i) = ∑ k, B.repr (φ p) k • (φ (X i) * B k) := by
    rw [map_mul]
    conv_lhs => rw [← B.sum_repr (φ p)]
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl fun k _ => ?_
    rw [smul_mul_assoc, mul_comm]
  rw [h, map_sum, Finsupp.finsetSum_apply]
  refine Finset.sum_congr rfl fun k _ => ?_
  rw [map_smul, Finsupp.smul_apply, smul_eq_mul]

/-- The ring identity behind the `Yᵢ`-step. -/
lemma table_aux {R : Type*} [CommRing R] (x : R) (lam : Fin d → R) (c : Fin d → Fin d → R)
    (b : Fin d → R) :
    (∑ k, lam k * b k) * x - ∑ l, (∑ k, lam k * c k l) * b l =
      ∑ k, lam k * (x * b k - ∑ l, c k l * b l) := by
  simp only [Finset.sum_mul, Finset.mul_sum, mul_sub, Finset.sum_sub_distrib]
  rw [Finset.sum_comm (f := fun l k => lam k * c k l * b l)]
  congr 1
  · exact Finset.sum_congr rfl fun k _ => by ring
  · exact Finset.sum_congr rfl fun k _ => Finset.sum_congr rfl fun l _ => by ring

/-- Every polynomial is congruent to its canonical representative. -/
lemma sub_tableRep_mem (p : MvPolynomial (Fin N) ℚ) :
    p - tableRep φ B b p ∈ Ideal.span (Set.range (tableRel φ B b)) := by
  set I := Ideal.span (Set.range (tableRel φ B b))
  induction p using MvPolynomial.induction_on with
  | C a =>
    have h2 : ∀ k, B.repr (φ (C a)) k = a * B.repr 1 k := by
      intro k
      rw [algHom_C, Algebra.algebraMap_eq_smul_one, map_smul, Finsupp.smul_apply, smul_eq_mul]
    have h : C a - tableRep φ B b (C a) = C a * tableRel φ B b none := by
      simp only [tableRep, tableRel, h2, mul_sub, mul_one, Finset.mul_sum, C_mul, mul_assoc]
    rw [h]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨none, rfl⟩)
  | add p q hp hq =>
    have h : p + q - tableRep φ B b (p + q) =
        (p - tableRep φ B b p) + (q - tableRep φ B b q) := by
      simp only [tableRep, map_add, Finsupp.add_apply, add_mul, Finset.sum_add_distrib]
      ring
    rw [h]
    exact Ideal.add_mem _ hp hq
  | mul_X p i hp =>
    have h2 : tableRep φ B b p * X i - tableRep φ B b (p * X i) =
        ∑ k, C (B.repr (φ p) k) * tableRel φ B b (some (i, k)) := by
      have hr : tableRep φ B b (p * X i) =
          ∑ l, (∑ k, C (B.repr (φ p) k) * C (B.repr (φ (X i) * B k) l)) * b l := by
        unfold tableRep
        refine Finset.sum_congr rfl fun l _ => ?_
        rw [repr_phi_mul_X, map_sum]
        simp only [C_mul]
      rw [hr]
      exact table_aux _ _ _ _
    have h : p * X i - tableRep φ B b (p * X i) =
        (p - tableRep φ B b p) * X i +
          (tableRep φ B b p * X i - tableRep φ B b (p * X i)) := by ring
    rw [h, h2]
    refine Ideal.add_mem _ (Ideal.mul_mem_right _ _ hp) (Ideal.sum_mem _ fun k _ => ?_)
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨some (i, k), rfl⟩)

/-- **The kernel is generated by the multiplication table.** -/
theorem ker_eq_span_tableRel (hb : ∀ k, φ (b k) = B k) :
    RingHom.ker φ = Ideal.span (Set.range (tableRel φ B b)) := by
  refine le_antisymm (fun p hp => ?_) ?_
  · have h0 : tableRep φ B b p = 0 := by
      rw [RingHom.mem_ker] at hp
      simp only [tableRep, hp, map_zero, Finsupp.zero_apply, zero_mul, Finset.sum_const_zero]
    have := sub_tableRep_mem (φ := φ) (B := B) (b := b) p
    rwa [h0, sub_zero] at this
  · rw [Ideal.span_le]
    rintro _ ⟨o, rfl⟩
    exact tableRel_mem_ker hb o

theorem fg_ker_of_basis (hb : ∀ k, φ (b k) = B k) : (RingHom.ker φ).FG := by
  rw [ker_eq_span_tableRel hb]
  exact Submodule.fg_span (Set.finite_range _)

/-- **Points of finite-type algebras.** If `A = ℚ[Y]/…` (via a surjection `π`) maps onto an
algebra with a finite basis `B`, and polynomials `bₖ` lift `B`, then the kernel is f.g. -/
theorem fg_ker_of_quotient_basis {A : Type*} [CommRing A] [Algebra ℚ A]
    (π : MvPolynomial (Fin N) ℚ →ₐ[ℚ] A) (hπ : Function.Surjective π) (ψ : A →ₐ[ℚ] L)
    (hb : ∀ k, ψ (π (b k)) = B k) : (RingHom.ker ψ).FG := by
  have h := fg_ker_of_basis (φ := ψ.comp π) (B := B) (b := b) hb
  have hk : RingHom.ker (ψ.comp π) =
      (RingHom.ker ψ).comap (π : MvPolynomial (Fin N) ℚ →+* A) := by
    ext p; simp only [RingHom.mem_ker, Ideal.mem_comap, AlgHom.comp_apply, RingHom.coe_coe]
  rw [hk] at h
  have := h.map (π : MvPolynomial (Fin N) ℚ →+* A)
  rwa [Ideal.map_comap_of_surjective (π : MvPolynomial (Fin N) ℚ →+* A) hπ] at this

/-- The extension of `𝔪` to `A_𝔪` (the maximal ideal there) is f.g. as soon as `𝔪` is. Stated
without `IsLocalRing`, whose instance for `A_𝔪` (`IsUnit a ∨ IsUnit (1 - a)`) is not
constructive in general; the identification with `maximalIdeal` is
`Localization.AtPrime.map_eq_maximalIdeal`. -/
theorem fg_map_atPrime {A : Type*} [CommRing A] (𝔪 : Ideal A) [𝔪.IsPrime] (h : 𝔪.FG) :
    (𝔪.map (algebraMap A (Localization.AtPrime 𝔪))).FG :=
  h.map _

end BezoutCounterexample.Constructive
