import BezoutCounterexample.Constructive.Groebner

/-!
# Elimination with lexicographic Gröbner bases

For the lex order on `ℚ[Y₀, …, Y_{N-1}]` (`Y₀` most significant), a polynomial whose leading
monomial avoids `Y₀, …, Y_{k-1}` avoids them altogether (`inVars_of_lowZero_degree`). Hence, for a
Gröbner basis `G`, the elimination ideal `(G) ∩ ℚ[Y_k, …]` is generated by the elements of `G`
whose leading monomial avoids `Y₀, …, Y_{k-1}` (`mem_lspan_elim`).

This is the tool for presentations of subalgebras (kernels `(I + (Zⱼ - fⱼ)) ∩ ℚ[Z]`), contractions
and intersections of ideals.
-/

namespace BezoutCounterexample.Constructive

open MvPolynomial

variable {N : ℕ}

/-- The monomial `μ` does not involve `Y₀, …, Y_{k-1}`. -/
def LowZero (k : ℕ) (μ : Fin N →₀ ℕ) : Prop := ∀ i : Fin N, (i : ℕ) < k → μ i = 0

/-- `f` does not involve `Y₀, …, Y_{k-1}`. -/
def InVars (k : ℕ) (f : MvPolynomial (Fin N) ℚ) : Prop := ∀ μ ∈ f.support, LowZero k μ

lemma lowZero_dec (k : ℕ) (μ : Fin N →₀ ℕ) : LowZero k μ ∨ ¬ LowZero k μ := by
  rcases fin_forall_or_exists (A := fun i : Fin N => (i : ℕ) < k → μ i = 0)
    (B := fun i : Fin N => (i : ℕ) < k ∧ μ i ≠ 0) (fun i =>
      if hi : (i : ℕ) < k then (if h0 : μ i = 0 then Or.inl fun _ => h0 else Or.inr ⟨hi, h0⟩)
      else Or.inl fun h => absurd h hi) with h | ⟨i, hi, h0⟩
  · exact Or.inl h
  · exact Or.inr fun h => h0 (h i hi)

/-- Below a monomial avoiding `Y₀, …, Y_{k-1}` in lex, every monomial avoids them. -/
lemma lowZero_of_le {k : ℕ} {μ ν : Fin N →₀ ℕ} (hν : LowZero k ν)
    (h : (mo N).toSyn μ ≤ (mo N).toSyn ν) : LowZero k μ := by
  suffices H : ∀ n : ℕ, ∀ i : Fin N, (i : ℕ) = n → (i : ℕ) < k → μ i = 0 from
    fun i hi => H _ i rfl hi
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro i hin hik
  rcases Nat.eq_zero_or_pos (μ i) with h0 | hpos
  · exact h0
  exfalso
  have hlt : toLex ν < toLex μ := Finsupp.Lex.lt_iff.2 ⟨i, fun j hj => by
      have hjk : (j : ℕ) < k := lt_trans hj hik
      show ν j = μ j
      rw [hν j hjk, ih j (hin ▸ hj) j rfl hjk], by
      show ν i < μ i
      rw [hν i hik]; exact hpos⟩
  exact (lt_irrefl _ (lt_of_le_of_lt h hlt))

lemma inVars_of_lowZero_degree {k : ℕ} {f : MvPolynomial (Fin N) ℚ}
    (h : LowZero k ((mo N).degree f)) : InVars k f :=
  fun _ hμ => lowZero_of_le h ((mo N).le_degree hμ)

lemma lowZero_add {k : ℕ} {μ ν : Fin N →₀ ℕ} (hμ : LowZero k μ) (hν : LowZero k ν) :
    LowZero k (μ + ν) := fun i hi => by rw [Finsupp.add_apply, hμ i hi, hν i hi]

lemma lowZero_of_le_pointwise {k : ℕ} {μ ν : Fin N →₀ ℕ} (hν : LowZero k ν) (h : μ ≤ ν) :
    LowZero k μ := fun i hi => Nat.eq_zero_of_le_zero ((h i).trans (hν i hi).le)

lemma InVars.add {k : ℕ} {f g : MvPolynomial (Fin N) ℚ} (hf : InVars k f) (hg : InVars k g) :
    InVars k (f + g) := fun μ hμ =>
  (Finset.mem_union.1 (MvPolynomial.support_add hμ)).elim (hf μ) (hg μ)

lemma InVars.neg {k : ℕ} {f : MvPolynomial (Fin N) ℚ} (hf : InVars k f) : InVars k (-f) :=
  fun μ hμ => hf μ (by rwa [MvPolynomial.support_neg] at hμ)

lemma InVars.mul {k : ℕ} {f g : MvPolynomial (Fin N) ℚ} (hf : InVars k f) (hg : InVars k g) :
    InVars k (f * g) := fun μ hμ => by
  obtain ⟨x, hx, y, hy, rfl⟩ := Finset.mem_add.1 (MvPolynomial.support_mul f g hμ)
  exact lowZero_add (hf x hx) (hg y hy)

lemma inVars_monomial {k : ℕ} {β : Fin N →₀ ℕ} (hβ : LowZero k β) (c : ℚ) :
    InVars k (monomial β c : MvPolynomial (Fin N) ℚ) := fun μ hμ => by
  rw [Finset.mem_singleton.1 (MvPolynomial.support_monomial_subset hμ)]; exact hβ

/-- The elements of `G` whose leading monomial avoids `Y₀, …, Y_{k-1}`. -/
noncomputable def elimList (k : ℕ) (G : List (MvPolynomial (Fin N) ℚ)) :
    List (MvPolynomial (Fin N) ℚ) :=
  G.filter fun g => (List.finRange N).all fun i => !decide ((i : ℕ) < k) || decide ((mo N).degree g i = 0)

lemma mem_elimList {k : ℕ} {G : List (MvPolynomial (Fin N) ℚ)} {g : MvPolynomial (Fin N) ℚ} :
    g ∈ elimList k G ↔ g ∈ G ∧ LowZero k ((mo N).degree g) := by
  simp only [elimList, List.mem_filter, List.all_eq_true, List.mem_finRange, true_implies,
    Bool.or_eq_true, Bool.not_eq_eq_eq_not, Bool.not_true, decide_eq_false_iff_not, not_lt,
    decide_eq_true_eq]
  refine and_congr_right fun _ => ⟨fun h i hi => (h i).resolve_left (not_le.2 hi), fun h i => ?_⟩
  rcases Nat.lt_or_ge (i : ℕ) k with hi | hi
  · exact Or.inr (h i hi)
  · exact Or.inl hi

/-- **The elimination theorem**: for a Gröbner basis `G`, an element of `(G)` not involving
`Y₀, …, Y_{k-1}` lies in the ideal generated by `elimList k G`. -/
theorem mem_lspan_elim {k : ℕ} {G : List (MvPolynomial (Fin N) ℚ)} (hG : ∀ g ∈ G, g ≠ 0)
    (hgb : IsGB G) {f : MvPolynomial (Fin N) ℚ} (hf : f ∈ lspan G) (hk : InVars k f) :
    f ∈ lspan (elimList k G) := by
  suffices H : ∀ d : (mo N).syn, ∀ f : MvPolynomial (Fin N) ℚ,
      (mo N).toSyn ((mo N).degree f) = d → f ∈ lspan G → InVars k f →
        f ∈ lspan (elimList k G) from H _ f rfl hf hk
  intro d
  induction d using WellFoundedLT.induction with
  | _ d ih =>
  intro f hfd hf hk
  rcases deq f 0 with rfl | hf0
  · exact zero_mem _
  rcases hgb f hf with h | ⟨g, hgG, hgf⟩
  · exact absurd h hf0
  have hlf : LowZero k ((mo N).degree f) := hk _ ((mo N).degree_mem_support hf0)
  have hlg : LowZero k ((mo N).degree g) := lowZero_of_le_pointwise hlf hgf
  have hgE : g ∈ elimList k G := mem_elimList.2 ⟨hgG, hlg⟩
  have hg0 := hG g hgG
  have hgspan : Ideal.span {g} ≤ lspan (elimList k G) :=
    Ideal.span_le.2 fun z hz => by rw [Set.mem_singleton_iff.1 hz]; exact Ideal.subset_span hgE
  rcases deq ((mo N).degree f) 0 with hdeg | hdeg
  · have hg : (mo N).degree g = 0 := le_antisymm (hdeg ▸ hgf) zero_le
    exact hgspan (mem_span_of_degree_eq_zero hg0 hg f)
  have hb : IsUnit ((mo N).leadingCoeff g) :=
    isUnit_iff_ne_zero.2 ((mo N).leadingCoeff_ne_zero_iff.2 hg0)
  have hlt := (mo N).degree_reduce_lt hb hgf hdeg
  set q := monomial ((mo N).degree f - (mo N).degree g) (hb.unit⁻¹ * (mo N).leadingCoeff f) * g
  have hred : (mo N).reduce hb f = f - q := rfl
  have hq : q ∈ lspan (elimList k G) :=
    hgspan (Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self g))
  have hqG : q ∈ lspan G := Ideal.mul_mem_left _ _ (Ideal.subset_span hgG)
  have hqk : InVars k q :=
    (inVars_monomial (lowZero_of_le_pointwise hlf tsub_le_self) _).mul
      (inVars_of_lowZero_degree hlg)
  have hrk : InVars k (f - q) := by rw [sub_eq_add_neg]; exact hk.add hqk.neg
  have hr := ih _ (hfd ▸ hlt) ((mo N).reduce hb f) rfl (by rw [hred]; exact sub_mem hf hqG)
    (by rw [hred]; exact hrk)
  rw [hred] at hr
  have := add_mem hr hq
  rwa [sub_add_cancel] at this

end BezoutCounterexample.Constructive
