import BezoutCounterexample.Constructive.Presented

/-!
# Contraction and intersection of ideals by elimination

Eliminating the variable `0` of `ℚ[X₀, Y₁, …, Yₙ]` (`exists_elim0`): for an explicit list `J`,
`J ∩ ℚ[Y]` is generated by an explicit list. Consequences:

* `exists_contract`: the contraction to `ℚ[Y]` of an ideal of `ℚ[W, Y] ⧸ (G, W p - 1)`, i.e.
  `{x | x / 1 ∈ J'}` for an ideal `J'` of `A[1/g]` (saturation);
* `exists_inter_list`: `(L₁) ∩ (L₂) = (t L₁ + (1 - t) L₂) ∩ ℚ[Y]`.
-/

namespace BezoutCounterexample.Constructive

open MvPolynomial

variable {n : ℕ}

/-- Killing the variable `0`, `ℚ[X₀, Y] → ℚ[Y]`. -/
noncomputable def back0 : MvPolynomial (Fin (n + 1)) ℚ →ₐ[ℚ] MvPolynomial (Fin n) ℚ :=
  aeval (Fin.cons 0 X)

lemma back0_jY (h : MvPolynomial (Fin n) ℚ) : back0 (jY h) = h := by
  rw [back0, jY, aeval_rename]
  convert aeval_X_left_apply h using 3
  funext i
  simp

lemma jY_back0 {g : MvPolynomial (Fin (n + 1)) ℚ} (hg : InVars 1 g) : jY (back0 g) = g := by
  have hcomp : (jY (n := n)).comp (back0 (n := n)) =
      aeval (fun k : Fin (n + 1) => if k ∈ {k : Fin (n + 1) | 1 ≤ (k : ℕ)} then X k else 0) := by
    apply MvPolynomial.algHom_ext
    intro k
    refine Fin.cases ?_ (fun i => ?_) k
    · simp [back0]
    · simp [back0]
  have := congrArg (fun φ => φ g) hcomp
  simp only [AlgHom.comp_apply] at this
  rw [this]
  refine aeval_ite_mem_eq_self g fun k hk => ?_
  obtain ⟨μ, hμ, hkμ⟩ := (mem_vars k).1 hk
  simp only [Set.mem_setOf_eq]
  by_contra hlt
  push Not at hlt
  exact (Finsupp.mem_support_iff.1 hkμ) (hg μ hμ k hlt)

lemma inVars_jY (h : MvPolynomial (Fin n) ℚ) : InVars 1 (jY h) := by
  intro μ hμ i hi
  rw [jY, support_rename_of_injective (Fin.succ_injective _)] at hμ
  obtain ⟨ν, -, rfl⟩ := Finset.mem_image.1 hμ
  rw [Finsupp.mapDomain_notin_range]
  rintro ⟨j, rfl⟩
  simp at hi

/-- **Elimination of the variable `0`.** -/
theorem exists_elim0 (J : List (MvPolynomial (Fin (n + 1)) ℚ)) :
    ∃ L : List (MvPolynomial (Fin n) ℚ), ∀ h, jY h ∈ lspan J ↔ h ∈ lspan L := by
  obtain ⟨G, hGspan, hG0, hgb⟩ := exists_gb J
  refine ⟨(elimList 1 G).map back0, fun h => ?_⟩
  have hE : ∀ e ∈ elimList 1 G, InVars 1 e := fun e he =>
    inVars_of_lowZero_degree (mem_elimList.1 he).2
  rw [← hGspan]
  constructor
  · intro hh
    have hm := mem_lspan_elim hG0 hgb hh (inVars_jY h)
    have hb := Ideal.mem_map_of_mem (back0 (n := n)).toRingHom hm
    rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, back0_jY] at hb
    have hle : Ideal.map (back0 (n := n)).toRingHom (lspan (elimList 1 G)) ≤
        lspan ((elimList 1 G).map back0) := by
      show Ideal.map _ (Ideal.span _) ≤ _
      rw [Ideal.map_span, Ideal.span_le]
      rintro _ ⟨x, hx, rfl⟩
      exact Ideal.subset_span (List.mem_map_of_mem hx)
    exact hle hb
  · intro hh
    have hle : Ideal.map (jY (n := n)).toRingHom (lspan ((elimList 1 G).map back0)) ≤
        lspan (elimList 1 G) := by
      show Ideal.map _ (Ideal.span _) ≤ _
      rw [Ideal.map_span, Ideal.span_le]
      rintro _ ⟨x, hx, rfl⟩
      obtain ⟨e, he, rfl⟩ := List.mem_map.1 hx
      show jY (back0 e) ∈ _
      rw [jY_back0 (hE e he)]
      exact Ideal.subset_span he
    exact Ideal.span_mono (fun x hx => (mem_elimList.1 hx).1) (hle (Ideal.mem_map_of_mem _ hh))

/-- **Contraction from `A[1/g]`**: for `A[1/g] = ℚ[W, Y] ⧸ (G, W p - 1)` and an ideal of `A[1/g]`
given by lifts `M`, the elements `x` of `ℚ[Y]` with `x / 1` in it form an explicitly generated
ideal. -/
theorem exists_contract (G : List (MvPolynomial (Fin n) ℚ)) (p : MvPolynomial (Fin n) ℚ)
    (M : List (MvPolynomial (Fin (n + 1)) ℚ)) :
    ∃ L : List (MvPolynomial (Fin n) ℚ), ∀ h, jY h ∈ lspan (awayList G p ++ M) ↔ h ∈ lspan L :=
  exists_elim0 _

/-- **Intersection of ideals**: `(L₁) ∩ (L₂) = (t L₁ + (1 - t) L₂) ∩ ℚ[Y]`. -/
theorem exists_inter_list (L₁ L₂ : List (MvPolynomial (Fin n) ℚ)) :
    ∃ L : List (MvPolynomial (Fin n) ℚ), lspan L = lspan L₁ ⊓ lspan L₂ := by
  let J : List (MvPolynomial (Fin (n + 1)) ℚ) :=
    L₁.map (fun a => X 0 * jY a) ++ L₂.map (fun b => (1 - X 0) * jY b)
  obtain ⟨L, hL⟩ := exists_elim0 J
  refine ⟨L, ?_⟩
  ext h
  rw [← hL, Submodule.mem_inf]
  -- evaluations at `t = 1` and `t = 0`
  let ev : ℚ → MvPolynomial (Fin (n + 1)) ℚ →ₐ[ℚ] MvPolynomial (Fin n) ℚ := fun c =>
    aeval (Fin.cons (C c) X)
  have hevY : ∀ c q, ev c (jY q) = q := fun c q => by
    simp only [ev, jY, aeval_rename]
    convert aeval_X_left_apply q using 3
    funext i; simp
  have hspanY : ∀ (L' : List (MvPolynomial (Fin n) ℚ)) (q : MvPolynomial (Fin n) ℚ),
      q ∈ lspan L' → jY q ∈ Ideal.map (jY (n := n)).toRingHom (lspan L') := fun L' q hq =>
    Ideal.mem_map_of_mem _ hq
  constructor
  · intro hJ
    have hmap : ∀ c, Ideal.map (ev c).toRingHom (lspan J) ≤
        (if c = 1 then lspan L₁ else ⊤) ⊓ (if c = 0 then lspan L₂ else ⊤) := by
      intro c
      show Ideal.map _ (Ideal.span _) ≤ _
      rw [Ideal.map_span, Ideal.span_le]
      rintro _ ⟨x, hx, rfl⟩
      rcases List.mem_append.1 hx with hx | hx
      · obtain ⟨a, ha, rfl⟩ := List.mem_map.1 hx
        simp only [SetLike.mem_coe, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, map_mul,
          hevY, Submodule.mem_inf]
        refine ⟨?_, ?_⟩
        · split_ifs
          · exact Ideal.mul_mem_left _ _ (Ideal.subset_span ha)
          · trivial
        · split_ifs with h0
          · simp [ev, h0]
          · trivial
      · obtain ⟨b, hb, rfl⟩ := List.mem_map.1 hx
        simp only [SetLike.mem_coe, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, map_mul,
          hevY, Submodule.mem_inf]
        refine ⟨?_, ?_⟩
        · split_ifs with h1
          · simp [ev, h1]
          · trivial
        · split_ifs
          · exact Ideal.mul_mem_left _ _ (Ideal.subset_span hb)
          · trivial
    have h1 := hmap 1 (Ideal.mem_map_of_mem _ hJ)
    have h0 := hmap 0 (Ideal.mem_map_of_mem _ hJ)
    simp only [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, hevY, if_true, Submodule.mem_inf,
      one_ne_zero, zero_ne_one, if_false] at h1 h0
    exact ⟨h1.1, h0.2⟩
  · rintro ⟨h1, h2⟩
    have key : ∀ (u : MvPolynomial (Fin (n + 1)) ℚ) (L' : List (MvPolynomial (Fin n) ℚ)),
        (∀ a ∈ L', u * jY a ∈ lspan J) → ∀ q ∈ lspan L', u * jY q ∈ lspan J := by
      intro u L' hL' q hq
      induction hq using Submodule.span_induction with
      | mem x hx => exact hL' x hx
      | zero => simp
      | add x y _ _ hx hy => rw [map_add, mul_add]; exact add_mem hx hy
      | smul c x _ hx =>
        rw [smul_eq_mul, map_mul, mul_left_comm]; exact Ideal.mul_mem_left _ _ hx
    have e1 := key (X 0) L₁ (fun a ha => Ideal.subset_span
      (List.mem_append_left _ (List.mem_map_of_mem (f := fun a => X 0 * jY a) ha))) h h1
    have e2 := key (1 - X 0) L₂ (fun b hb => Ideal.subset_span
      (List.mem_append_right _ (List.mem_map_of_mem (f := fun b => (1 - X 0) * jY b) hb))) h h2
    have := add_mem e1 e2
    rwa [← add_mul, add_sub_cancel, one_mul] at this

end BezoutCounterexample.Constructive
