import BezoutCounterexample.Constructive.GCDPoly

/-!
# Locally principal ideals of GCD domains are principal (`~/COLL/bezout-gcd.tex`, Prop. 4.1)

Let `I = (a₁, …, a_r)` be an ideal of a GCD domain and `D(g₁), …, D(g_q)` a cover
(`(g₁, …, g_q) = 1`) such that each `I A[1/gᵢ]` is principal. Then `I = (d)` with
`d = gcd(a₁, …, a_r)`. In the divisorial step this replaces Kaplansky's prime element
(`ReesData.exists_prime_mem`) and `eq_span_of_loc_principal`: the generator is computed, and is
prime when `I` is.

The local generator `x` divides every `aⱼ`, so it divides the gcd up to a power of `gᵢ`
(`isGcdFam_mul_left`); hence `gᵢᴺ d ∈ I`, and the cover gives `d ∈ I`. The finitely many
exponents are combined by `exists_common_exponent` (induction on the index set, no choice).
-/

namespace BezoutCounterexample.Constructive

section Fam

variable {A : Type*} [CommRing A] [IsDomain A]

/-- `d` is a gcd of the family `a`. -/
def IsGcdFam {r : ℕ} (d : A) (a : Fin r → A) : Prop :=
  (∀ j, d ∣ a j) ∧ ∀ c, (∀ j, c ∣ a j) → c ∣ d

omit [IsDomain A] in
/-- Finite families have gcds. -/
lemma exists_isGcdFam (hG : HasGcd A) : ∀ {r : ℕ} (a : Fin r → A), ∃ d, IsGcdFam d a
  | 0, _ => ⟨0, fun j => j.elim0, fun c _ => dvd_zero c⟩
  | r + 1, a => by
    obtain ⟨d, hd, hdc⟩ := exists_isGcdFam hG (fun j : Fin r => a j.succ)
    obtain ⟨g, hg0, hgd, hgc⟩ := hG (a 0) d
    refine ⟨g, fun j => Fin.cases hg0 (fun j => hgd.trans (hd j)) j, fun c hc => ?_⟩
    exact hgc c (hc 0) (hdc c fun j => hc j.succ)

/-- `gcd(c aⱼ) = c gcd(aⱼ)`. -/
lemma isGcdFam_mul_left (hG : HasGcd A) (hz : ∀ a : A, a = 0 ∨ a ≠ 0) {r : ℕ} {d : A}
    {a : Fin r → A} (hd : IsGcdFam d a) (c : A) : IsGcdFam (c * d) (fun j => c * a j) := by
  obtain ⟨h, hh, hhc⟩ := exists_isGcdFam hG (fun j => c * a j)
  have hhd : h ∣ c * d := by
    rcases hz c with rfl | hc
    · rw [zero_mul]; exact dvd_zero h
    obtain ⟨h', rfl⟩ := hhc c fun j => dvd_mul_right c (a j)
    exact mul_dvd_mul_left c (hd.2 h' fun j => (mul_dvd_mul_iff_left hc).1 (hh j))
  exact ⟨fun j => mul_dvd_mul_left c (hd.1 j), fun e he => (hhc e he).trans hhd⟩

omit [CommRing A] [IsDomain A] in
/-- Finitely many monotone conditions on `ℕ` hold simultaneously. -/
lemma exists_common_exponent {r : ℕ} (P : Fin r → ℕ → Prop)
    (hmono : ∀ j n k, P j n → P j (n + k)) (h : ∀ j, ∃ n, P j n) : ∃ N, ∀ j, P j N := by
  induction r with
  | zero => exact ⟨0, fun j => j.elim0⟩
  | succ r ih =>
    obtain ⟨N, hN⟩ := ih (fun j => P j.succ) (fun j => hmono j.succ) (fun j => h j.succ)
    obtain ⟨n, hn⟩ := h 0
    refine ⟨n + N, fun j => Fin.cases ?_ (fun j => ?_) j⟩
    · exact hmono 0 n N hn
    · rw [add_comm]; exact hmono j.succ N n (hN j)

end Fam

section Principal

variable {A : Type*} [CommRing A] [IsDomain A]

/-- **Locally principal ideals of a GCD domain are generated by the gcd.** -/
theorem eq_span_gcd_of_locallyPrincipal (hG : HasGcd A) (hz : ∀ a : A, a = 0 ∨ a ≠ 0)
    {r q : ℕ} (a : Fin r → A) (g : Fin q → A) (hg : Ideal.span (Set.range g) = ⊤)
    (hloc : ∀ i, ∃ x : Localization.Away (g i),
      (Ideal.span (Set.range a)).map (algebraMap A (Localization.Away (g i))) = Ideal.span {x})
    {d : A} (hd : IsGcdFam d a) : Ideal.span (Set.range a) = Ideal.span {d} := by
  set I := Ideal.span (Set.range a)
  refine le_antisymm (Ideal.span_le.2 ?_) ?_
  · rintro _ ⟨j, rfl⟩; exact Ideal.mem_span_singleton.2 (hd.1 j)
  rw [Ideal.span_le, Set.singleton_subset_iff]
  -- `gᵢᴺ d ∈ I` for each `i`
  have hloc' : ∀ i, ∃ n, g i ^ n * d ∈ I := by
    intro i
    obtain ⟨x, hx⟩ := hloc i
    let L := Localization.Away (g i)
    obtain ⟨⟨c, u⟩, hcu⟩ := IsLocalization.mk'_surjective (Submonoid.powers (g i)) x
    simp only at hcu
    rw [← hcu] at hx
    have hu : IsUnit (algebraMap A L u) := IsLocalization.map_units L u
    -- `c ∣ gᵢⁿ aⱼ`
    have hca : ∀ j, ∃ n, c ∣ g i ^ n * a j := by
      intro j
      have hmem : algebraMap A L (a j) ∈ Ideal.span {IsLocalization.mk' L c u} := by
        rw [← hx]; exact Ideal.mem_map_of_mem _ (Ideal.subset_span ⟨j, rfl⟩)
      obtain ⟨w, hw⟩ := Ideal.mem_span_singleton'.1 hmem
      have hdiv : algebraMap A L c ∣ algebraMap A L (a j) := by
        rw [← IsLocalization.mk'_spec L c u, hu.mul_right_dvd, ← hw]
        exact dvd_mul_left _ _
      obtain ⟨σ, ⟨n, rfl⟩, hσ⟩ := exists_dvd_of_dvd_localization (Submonoid.powers (g i)) L hdiv
      exact ⟨n, hσ⟩
    obtain ⟨N, hN⟩ := exists_common_exponent (fun j n => c ∣ g i ^ n * a j)
      (fun j n k h => by rw [pow_add, mul_comm (g i ^ n), mul_assoc]; exact h.mul_left _) hca
    have hcd : c ∣ g i ^ N * d := (isGcdFam_mul_left hG hz hd (g i ^ N)).2 c hN
    have hxd : algebraMap A L d ∈ Ideal.span {IsLocalization.mk' L c u} := by
      have hgu : IsUnit (algebraMap A L (g i ^ N)) :=
        IsLocalization.map_units L (⟨g i ^ N, N, rfl⟩ : Submonoid.powers (g i))
      refine Ideal.mem_span_singleton.2 ?_
      have h1 : algebraMap A L c ∣ algebraMap A L d := by
        rw [← hgu.dvd_mul_left, ← map_mul]; exact _root_.map_dvd _ hcd
      exact (show IsLocalization.mk' L c u ∣ algebraMap A L c from
        ⟨algebraMap A L u, (IsLocalization.mk'_spec L c u).symm⟩).trans h1
    rw [← hx] at hxd
    obtain ⟨⟨y, ⟨_, m, rfl⟩⟩, hy⟩ := (IsLocalization.mem_map_algebraMap_iff
      (Submonoid.powers (g i)) L).1 hxd
    have h2 : algebraMap A L (d * g i ^ m) = algebraMap A L y := by rw [map_mul]; exact hy
    obtain ⟨⟨_, k, rfl⟩, hk⟩ := (IsLocalization.eq_iff_exists (Submonoid.powers (g i)) L).1 h2
    refine ⟨k + m, ?_⟩
    have : g i ^ (k + m) * d = g i ^ k * y := by simp only at hk; rw [pow_add]; linear_combination hk
    rw [this]; exact I.mul_mem_left _ y.2
  obtain ⟨N, hN⟩ := exists_common_exponent (fun i n => g i ^ n * d ∈ I)
    (fun i n k h => by rw [pow_add, mul_comm (g i ^ n), mul_assoc]; exact I.mul_mem_left _ h)
    hloc'
  have htop := Ideal.span_pow_eq_top (Set.range g) hg N
  let J : Ideal A := Submodule.comap (LinearMap.mulRight A d) I
  have hJ : ∀ y, y ∈ J ↔ y * d ∈ I := fun y => by
    simp only [J, Submodule.mem_comap, LinearMap.mulRight_apply]
  have hle : Ideal.span ((fun x => x ^ N) '' Set.range g) ≤ J := by
    rw [Ideal.span_le]
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    exact (hJ _).2 (hN i)
  rw [htop, top_le_iff] at hle
  have h1 : (1 : A) ∈ J := by rw [hle]; trivial
  rw [hJ, one_mul] at h1
  exact h1

end Principal

end BezoutCounterexample.Constructive
