import BezoutCounterexample.Constructive.GroebnerElim

/-!
# Kernels by elimination

For `G₀ ⊆ ℚ[Y₁, …, Yₙ]` and `f : Fin m → ℚ[Y]`, the kernel of
`φ : ℚ[Z₁, …, Z_m] → ℚ[Y] ⧸ (G₀)`, `Zⱼ ↦ fⱼ`, is generated by an explicit finite list
(`exists_ker_list`): the elimination ideal `(G₀, Zⱼ - fⱼ) ∩ ℚ[Z]`, computed from a lex Gröbner basis
with the `Y` variables first (`mem_lspan_elim`).

* `sub_subst_mem`: `P - P(Y, f(Y)) ∈ (Zⱼ - fⱼ)` (induction on `P`);
* `ker_iff_mem`: `φ h = 0 ↔ h(Z) ∈ (G₀, Zⱼ - fⱼ)`;
* `exists_ker_list`: `∃ L, ∀ h, φ h = 0 ↔ h ∈ (L)`.

This is the basic tool for presentations of subalgebras (the Rees algebra of the tower) and, with a
decision of membership (`mem_lspan_dec`), for decidable equality in them.
-/

namespace BezoutCounterexample.Constructive

open MvPolynomial

variable {n m : ℕ}

/-- `Y`-variables of `ℚ[Y, Z]`, first. -/
noncomputable abbrev iY : MvPolynomial (Fin n) ℚ →ₐ[ℚ] MvPolynomial (Fin (n + m)) ℚ :=
  rename (Fin.castAdd m)

/-- `Z`-variables of `ℚ[Y, Z]`, last. -/
noncomputable abbrev iZ : MvPolynomial (Fin m) ℚ →ₐ[ℚ] MvPolynomial (Fin (n + m)) ℚ :=
  rename (Fin.natAdd n)

/-- The substitution `Zⱼ ↦ fⱼ`, `ℚ[Y, Z] → ℚ[Y]`. -/
noncomputable def substY (f : Fin m → MvPolynomial (Fin n) ℚ) :
    MvPolynomial (Fin (n + m)) ℚ →ₐ[ℚ] MvPolynomial (Fin n) ℚ :=
  aeval (Fin.addCases X f)

/-- The list `Zⱼ - fⱼ`. -/
noncomputable def zDiffs (f : Fin m → MvPolynomial (Fin n) ℚ) :
    List (MvPolynomial (Fin (n + m)) ℚ) :=
  List.ofFn fun j => X (Fin.natAdd n j) - iY (f j)

/-- The list `(G₀, Zⱼ - fⱼ)` in `ℚ[Y, Z]`. -/
noncomputable def elimIdealList (G₀ : List (MvPolynomial (Fin n) ℚ))
    (f : Fin m → MvPolynomial (Fin n) ℚ) : List (MvPolynomial (Fin (n + m)) ℚ) :=
  G₀.map iY ++ zDiffs f

lemma substY_iY (f : Fin m → MvPolynomial (Fin n) ℚ) (g : MvPolynomial (Fin n) ℚ) :
    substY f (iY g) = g := by
  rw [substY, iY, aeval_rename]
  convert aeval_X_left_apply g using 3
  funext i
  simp [Fin.addCases_left]

lemma substY_iZ (f : Fin m → MvPolynomial (Fin n) ℚ) (h : MvPolynomial (Fin m) ℚ) :
    substY f (iZ h) = aeval f h := by
  rw [substY, iZ, aeval_rename]
  congr 2
  funext j
  simp [Fin.addCases_right]

lemma mem_zDiffs (f : Fin m → MvPolynomial (Fin n) ℚ) (j : Fin m) :
    X (Fin.natAdd n j) - iY (f j) ∈ zDiffs f :=
  List.mem_ofFn.2 ⟨j, rfl⟩

/-- `P - iY (substY P) ∈ (Zⱼ - fⱼ)`. -/
theorem sub_subst_mem (f : Fin m → MvPolynomial (Fin n) ℚ) (P : MvPolynomial (Fin (n + m)) ℚ) :
    P - iY (substY f P) ∈ lspan (zDiffs f) := by
  induction P using MvPolynomial.induction_on with
  | C a => simp [substY]
  | add p q hp hq =>
    rw [map_add, map_add, add_sub_add_comm]; exact add_mem hp hq
  | mul_X p k hp =>
    rw [map_mul, map_mul]
    have hX : X k - iY (substY f (X k)) ∈ lspan (zDiffs f) := by
      refine Fin.addCases (fun i => ?_) (fun j => ?_) k
      · simp [substY, Fin.addCases_left]
      · simp only [substY, aeval_X, Fin.addCases_right]
        exact Ideal.subset_span (mem_zDiffs f j)
    have : p * X k - iY (substY f p) * iY (substY f (X k)) =
        (p - iY (substY f p)) * X k + iY (substY f p) * (X k - iY (substY f (X k))) := by ring
    rw [this]
    exact add_mem (Ideal.mul_mem_right _ _ hp) (Ideal.mul_mem_left _ _ hX)

lemma iY_mem_lspan_map {G₀ : List (MvPolynomial (Fin n) ℚ)} {g : MvPolynomial (Fin n) ℚ}
    (hg : g ∈ lspan G₀) : iY (m := m) g ∈ lspan (G₀.map iY) := by
  have : Ideal.map (iY (m := m)) (lspan G₀) ≤ lspan (G₀.map iY) := by
    rw [lspan, Ideal.map_span, Ideal.span_le]
    rintro _ ⟨x, hx, rfl⟩
    exact Ideal.subset_span (List.mem_map_of_mem hx)
  exact this (Ideal.mem_map_of_mem _ hg)

/-- **The kernel as an elimination ideal.** -/
theorem ker_iff_mem (G₀ : List (MvPolynomial (Fin n) ℚ)) (f : Fin m → MvPolynomial (Fin n) ℚ)
    (h : MvPolynomial (Fin m) ℚ) :
    aeval f h ∈ lspan G₀ ↔ iZ (n := n) h ∈ lspan (elimIdealList G₀ f) := by
  constructor
  · intro hh
    have h1 := sub_subst_mem f (iZ (n := n) h)
    rw [substY_iZ] at h1
    have h2 : iY (m := m) (aeval f h) ∈ lspan (elimIdealList G₀ f) :=
      Ideal.span_mono (fun x hx => List.mem_append_left _ hx) (iY_mem_lspan_map hh)
    have h3 : iZ (n := n) h - iY (aeval f h) ∈ lspan (elimIdealList G₀ f) :=
      Ideal.span_mono (fun x hx => List.mem_append_right _ hx) h1
    have := add_mem h3 h2
    rwa [sub_add_cancel] at this
  · intro hh
    have hle : lspan (elimIdealList G₀ f) ≤ (lspan G₀).comap (substY f).toRingHom := by
      rw [lspan, Ideal.span_le]
      intro x hx
      rcases List.mem_append.1 hx with hx | hx
      · obtain ⟨g, hg, rfl⟩ := List.mem_map.1 hx
        show substY f (iY g) ∈ lspan G₀
        rw [substY_iY]; exact Ideal.subset_span hg
      · obtain ⟨j, rfl⟩ := List.mem_ofFn.1 hx
        show substY f (X (Fin.natAdd n j) - iY (f j)) ∈ lspan G₀
        rw [map_sub, substY_iY]
        simp [substY, Fin.addCases_right]
    have := hle hh
    rwa [Ideal.mem_comap, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, substY_iZ] at this

/-- Killing the `Y`-variables, `ℚ[Y, Z] → ℚ[Z]`. -/
noncomputable def backZ : MvPolynomial (Fin (n + m)) ℚ →ₐ[ℚ] MvPolynomial (Fin m) ℚ :=
  aeval (Fin.addCases (fun _ => 0) X)

lemma backZ_iZ (h : MvPolynomial (Fin m) ℚ) : backZ (n := n) (iZ h) = h := by
  rw [backZ, iZ, aeval_rename]
  convert aeval_X_left_apply h using 3
  funext j
  simp [Fin.addCases_right]

lemma iZ_backZ {g : MvPolynomial (Fin (n + m)) ℚ} (hg : InVars n g) : iZ (backZ g) = g := by
  have hcomp : (iZ (n := n)).comp (backZ (n := n) (m := m)) =
      aeval (fun k : Fin (n + m) => if k ∈ {k : Fin (n + m) | n ≤ (k : ℕ)} then X k else 0) := by
    apply MvPolynomial.algHom_ext
    intro k
    refine Fin.addCases (fun i => ?_) (fun j => ?_) k
    · simp [backZ, Fin.addCases_left, i.2]
    · simp [backZ, Fin.addCases_right]
  have := congrArg (fun φ => φ g) hcomp
  simp only [AlgHom.comp_apply] at this
  rw [this]
  refine aeval_ite_mem_eq_self g fun k hk => ?_
  obtain ⟨μ, hμ, hkμ⟩ := (mem_vars k).1 hk
  simp only [Set.mem_setOf_eq]
  by_contra hlt
  push Not at hlt
  exact (Finsupp.mem_support_iff.1 hkμ) (hg μ hμ k hlt)

/-- **Explicit generators of the kernel.** -/
theorem exists_ker_list (G₀ : List (MvPolynomial (Fin n) ℚ))
    (f : Fin m → MvPolynomial (Fin n) ℚ) :
    ∃ L : List (MvPolynomial (Fin m) ℚ), ∀ h, aeval f h ∈ lspan G₀ ↔ h ∈ lspan L := by
  obtain ⟨G, hGspan, hG0, hgb⟩ := exists_gb (elimIdealList G₀ f)
  refine ⟨(elimList n G).map backZ, fun h => ?_⟩
  have hE : ∀ e ∈ elimList n G, InVars n e := fun e he =>
    inVars_of_lowZero_degree (mem_elimList.1 he).2
  rw [ker_iff_mem, ← hGspan]
  constructor
  · intro hh
    have hin : InVars n (iZ (n := n) h) := by
      intro μ hμ i hi
      rw [iZ, support_rename_of_injective (Fin.natAdd_injective _ _)] at hμ
      obtain ⟨ν, -, rfl⟩ := Finset.mem_image.1 hμ
      rw [Finsupp.mapDomain_notin_range]
      rintro ⟨j, rfl⟩
      simp at hi
    have hm := mem_lspan_elim hG0 hgb hh hin
    have hb := Ideal.mem_map_of_mem (backZ (n := n) (m := m)).toRingHom hm
    rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, backZ_iZ, lspan, Ideal.map_span] at hb
    refine Ideal.span_mono ?_ hb
    rintro _ ⟨x, hx, rfl⟩
    exact List.mem_map_of_mem hx
  · intro hh
    have hle : Ideal.map (iZ (n := n) (m := m)).toRingHom (lspan ((elimList n G).map backZ)) ≤
        lspan (elimList n G) := by
      rw [lspan, Ideal.map_span, Ideal.span_le]
      rintro _ ⟨x, hx, rfl⟩
      obtain ⟨e, he, rfl⟩ := List.mem_map.1 hx
      show iZ (backZ e) ∈ _
      rw [iZ_backZ (hE e he)]
      exact Ideal.subset_span he
    have h1 := hle (Ideal.mem_map_of_mem _ hh)
    exact Ideal.span_mono (fun x hx => (mem_elimList.1 hx).1) h1

end BezoutCounterexample.Constructive
