import BezoutCounterexample.Constructive.PolyNoeth

/-!
# Krull intersection for an arbitrary ideal (Lemma 6.3 of `kunz-constructive.pdf`)

If `B` is inductively Noetherian together with its polynomial rings (`PolyIndNoeth B`) and `I` is
*any* ideal of `B` (no generators given), then every `d ∈ ⋂ₙ Iⁿ` lies in `d I`; if moreover
`1 - c` is a unit for every `c ∈ I` (`I ⊆ Jac B`), then `⋂ₙ Iⁿ = 0`.

Proof ("do as if", Coquand–Lombardi): run the bar of `B` on lists `σ ⊆ I` with the predicate
`σ ⊆ I → Good σ ∨ d ∈ d I`. In the bar step, the hypothesis gives, for each `a ∈ I`,
`a ∈ ⟨σ⟩ ∨ D` (`D := Good σ ∨ d ∈ d I`); one argues as if `I` were `J := ⟨σ⟩`, running the bar of
the Rees ring `B[Jt]` (inductively Noetherian: an image of `B[T₁, …, Tₖ]`) on the lists
`d, d t, …, d tᵏ⁻¹`. To extend such a list one needs `d ∈ Jᵏ`; from `d ∈ Iᵏ` this costs finitely
many consultations of the escape branch, packaged as `pow_mem_or` (`Iᵏ` is generated by products,
and `{x | x ∈ Jᵏ ∨ D}` is an ideal). A good list in `B[Jt]` gives `d ∈ d J` by comparing the
coefficients of the newest entry (`mem_mul_of_good`, the degree argument of `KrullP`).

* `pow_mem_or` — `(∀ a ∈ I, a ∈ J ∨ D) → ∀ x ∈ Iᵏ, x ∈ Jᵏ ∨ D`.
* `mem_mul_of_good` — a stationarity relation among `d, d t, …` in `B[Jt]` gives `d ∈ J · d`.
* `IndNoeth.mem_mul_of_mem_iInf_pow` — Lemma 6.3: `d ∈ ⋂ Iⁿ → ∃ c ∈ I, d = c * d`.
* `IndNoeth.eq_zero_of_mem_iInf_pow` — with `1 - c` a unit on `I`, `d = 0`.
* `IndNoeth.le_of_le_sup_sq` — the use made of it: `I ≤ K ⊔ I²` with `1 - c` a unit on `I` gives
  `I ≤ K` (Nakayama without finite generation, via `B ⧸ K`).

No choice: the elements `d tᵏ` are produced one at a time inside the bar induction.
-/

namespace BezoutCounterexample.Constructive

open Polynomial

variable {B : Type*} [CommRing B]

/-! ### Consulting the escape branch finitely often -/

/-- If every `a ∈ I` lies in `J` unless `D` holds, the same holds for `Iᵏ` and `Jᵏ`. -/
theorem pow_mem_or {I J : Ideal B} {D : Prop} (h : ∀ a ∈ I, a ∈ J ∨ D) :
    ∀ k : ℕ, ∀ x ∈ I ^ k, x ∈ J ^ k ∨ D := by
  intro k
  induction k with
  | zero =>
    intro x _
    exact Or.inl (by rw [pow_zero, Ideal.one_eq_top]; trivial)
  | succ k ih =>
    let K : Ideal B :=
      { carrier := {x | x ∈ J ^ (k + 1) ∨ D}
        add_mem' := fun {x y} hx hy => by
          rcases hx with hx | hx
          · rcases hy with hy | hy
            · exact Or.inl (add_mem hx hy)
            · exact Or.inr hy
          · exact Or.inr hx
        zero_mem' := Or.inl (zero_mem _)
        smul_mem' := fun c x hx => by
          rcases hx with hx | hx
          · exact Or.inl (Ideal.mul_mem_left _ c hx)
          · exact Or.inr hx }
    have hle : I ^ (k + 1) ≤ K := by
      rw [pow_succ]
      refine Ideal.mul_le.2 fun r hr s hs => ?_
      rcases ih r hr with hr' | hD
      · rcases h s hs with hs' | hD
        · show r * s ∈ J ^ (k + 1) ∨ D
          rw [pow_succ]
          exact Or.inl (Ideal.mul_mem_mul hr' hs')
        · exact Or.inr hD
      · exact Or.inr hD
    intro x hx
    exact hle hx

/-! ### A good list of `d, d t, …` in the Rees ring -/

/-- The polynomials `d tʲ`. -/
noncomputable def dPow (d : B) (j : ℕ) : B[X] := C d * X ^ j

lemma coeff_dPow (d : B) (j q : ℕ) : (dPow d j).coeff q = if q = j then d else 0 := by
  rw [dPow, coeff_C_mul_X_pow]

/-- Every element of the ideal of `B[Jt]` generated by `d, d t, …, d tᵐ⁻¹` has its coefficient
of `tᑫ` in `J^(q + 1 - m) · d`. -/
lemma coeff_mem_of_mem_lspan {J : Ideal B} {d : B} {m : ℕ} {l : List (reesSubring J)}
    (hl : l.map Subtype.val = pre (dPow d) m) {z : reesSubring J} (hz : z ∈ lspan l) :
    ∀ q, (z : B[X]).coeff q ∈ J ^ (q + 1 - m) * Ideal.span {d} := by
  refine Submodule.span_induction
    (p := fun (z : reesSubring J) _ => ∀ q, (z : B[X]).coeff q ∈ J ^ (q + 1 - m) * Ideal.span {d}) ?_ ?_ ?_ ?_ hz
  · intro z hz q
    have hz' : (z : B[X]) ∈ pre (dPow d) m := by
      rw [← hl]; exact List.mem_map_of_mem hz
    obtain ⟨i, hi, hiz⟩ := mem_pre hz'
    rw [← hiz, coeff_dPow]
    split_ifs with hq
    · have h0 : q + 1 - m = 0 := by omega
      rw [h0, pow_zero, Ideal.one_eq_top, Ideal.top_mul]
      exact Ideal.subset_span rfl
    · exact zero_mem _
  · intro q
    rw [ZeroMemClass.coe_zero, coeff_zero]
    exact zero_mem _
  · intro x y _ _ hx hy q
    rw [Subring.coe_add, coeff_add]
    exact add_mem (hx q) (hy q)
  · intro g x _ hx q
    rw [smul_eq_mul, Subring.coe_mul, coeff_mul]
    refine Ideal.sum_mem _ fun p hp => ?_
    rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
    have h1 : (g : B[X]).coeff p.1 * (x : B[X]).coeff p.2 ∈
        J ^ p.1 * (J ^ (p.2 + 1 - m) * Ideal.span {d}) :=
      Ideal.mul_mem_mul (g.2 p.1) (hx p.2)
    rw [← mul_assoc, ← pow_add] at h1
    refine Ideal.mul_mono_left (Ideal.pow_le_pow_right ?_) h1
    omega

/-- **Stationarity in the Rees ring** (clause (1) of the inner bar): if `d tᵐ` lies in the ideal
of `B[Jt]` generated by `d, d t, …, d tᵐ⁻¹`, then `d ∈ J · d`. -/
theorem mem_mul_of_good {J : Ideal B} {d : B} {m : ℕ} {l : List (reesSubring J)}
    (hl : l.map Subtype.val = pre (dPow d) m) {a : reesSubring J} (ha : (a : B[X]) = dPow d m)
    (hmem : a ∈ lspan l) : ∃ c ∈ J, d = c * d := by
  have h := coeff_mem_of_mem_lspan hl hmem m
  have hm : (dPow d m).coeff m = d := by rw [coeff_dPow]; exact ite_eq_left_iff.2 (absurd rfl)
  rw [ha, hm, show m + 1 - m = 1 by omega, pow_one] at h
  obtain ⟨c, hc, hcd⟩ := Submodule.mem_mul_span_singleton.1 h
  exact ⟨c, hc, hcd.symm⟩

/-! ### The inner bar: the Rees ring of `J` -/

/-- Inner bar (clause (3) of the outer bar). If every `a ∈ I` lies in `J` unless `D`, and
`d ∈ ⋂ Iⁿ`, the bar of `B[Jt]` gives `d ∈ J · d` or `D`. -/
theorem NBar.rees_or {I J : Ideal B} {D : Prop} (h : ∀ a ∈ I, a ∈ J ∨ D) {d : B}
    (hd : ∀ n, d ∈ I ^ n) {L : List (reesSubring J)} (hL : NBar L) :
    ∀ k, L.map Subtype.val = pre (dPow d) k → (∃ c ∈ J, d = c * d) ∨ D := by
  induction hL with
  | @good a l ha =>
    intro k hk
    cases k with
    | zero => exact absurd hk (List.cons_ne_nil _ _)
    | succ m =>
      rw [List.map_cons, pre] at hk
      obtain ⟨h1, h2⟩ := List.cons.inj hk
      exact Or.inl (mem_mul_of_good h2 h1 ha)
  | @step l _ ih =>
    intro k hk
    rcases pow_mem_or h k d (hd k) with hJ | hD
    · exact ih ⟨dPow d k, C_mul_X_pow_mem hJ⟩ (k + 1) (by rw [List.map_cons, hk]; rfl)
    · exact Or.inr hD

/-- The Rees ring of the ideal generated by a list is inductively Noetherian. -/
theorem PolyIndNoeth.indNoeth_rees_lspan (hB : PolyIndNoeth B) (l : List B) :
    IndNoeth (reesSubring (lspan l)) := by
  have h := indNoeth_rees l.get (hB l.length)
  have he : Ideal.span (Set.range l.get) = lspan l := by
    congr 1
    ext x
    exact List.mem_iff_get.symm
  rwa [he] at h

/-! ### The outer bar: `B` itself -/

/-- `Good σ`: some entry of `σ` (newest first) lies in the ideal of the older ones. -/
def Good : List B → Prop
  | [] => False
  | a :: l => a ∈ lspan l ∨ Good l

/-- Outer bar invariant: `σ ⊆ I → Good σ ∨ d ∈ I · d`. -/
theorem NBar.good_or (hB : PolyIndNoeth B) {I : Ideal B} {d : B} (hd : ∀ n, d ∈ I ^ n)
    {L : List B} (hL : NBar L) : (∀ x ∈ L, x ∈ I) → Good L ∨ ∃ c ∈ I, d = c * d := by
  induction hL with
  | @good a l ha => exact fun _ => Or.inl (Or.inl ha)
  | @step l _ ih =>
    intro hl
    -- (4): every `a ∈ I` lies in `⟨l⟩` unless `D`
    have h4 : ∀ a ∈ I, a ∈ lspan l ∨ (Good l ∨ ∃ c ∈ I, d = c * d) := by
      intro a ha
      have hal : ∀ x ∈ a :: l, x ∈ I := by
        intro x hx
        rcases List.mem_cons.1 hx with rfl | hx
        · exact ha
        · exact hl x hx
      rcases ih a hal with (h | h) | h
      · exact Or.inl h
      · exact Or.inr (Or.inl h)
      · exact Or.inr (Or.inr h)
    have hJI : lspan l ≤ I := Ideal.span_le.2 fun x hx => hl x hx
    rcases NBar.rees_or h4 hd (hB.indNoeth_rees_lspan l) 0 rfl with ⟨c, hc, hcd⟩ | hD
    · exact Or.inr ⟨c, hJI hc, hcd⟩
    · exact hD

/-- **Krull intersection for an arbitrary ideal** (Lemma 6.3 of `kunz-constructive.pdf`):
every `d ∈ ⋂ Iⁿ` lies in `I · d`. No generators of `I`, no Jacobson hypothesis. -/
theorem PolyIndNoeth.mem_mul_of_mem_iInf_pow (hB : PolyIndNoeth B) (I : Ideal B) {d : B}
    (hd : ∀ n, d ∈ I ^ n) : ∃ c ∈ I, d = c * d := by
  rcases NBar.good_or hB hd hB.indNoeth (fun x hx => absurd hx List.not_mem_nil) with h | h
  · exact h.elim
  · exact h

/-- **Krull intersection**, conclusion: if `1 - c` is a unit for every `c ∈ I`, `⋂ Iⁿ = 0`. -/
theorem PolyIndNoeth.eq_zero_of_mem_iInf_pow (hB : PolyIndNoeth B) {I : Ideal B}
    (hJ : ∀ c ∈ I, IsUnit (1 - c)) {d : B} (hd : ∀ n, d ∈ I ^ n) : d = 0 := by
  obtain ⟨c, hc, hdc⟩ := hB.mem_mul_of_mem_iInf_pow I hd
  obtain ⟨u, hu⟩ := hJ c hc
  have h1 : (1 - c) * d = 0 := by rw [sub_mul, one_mul, ← hdc, sub_self]
  rw [← hu] at h1
  calc d = ↑u⁻¹ * (↑u * d) := by rw [← mul_assoc, Units.inv_mul, one_mul]
    _ = 0 := by rw [h1, mul_zero]

/-- An ideal contained in its square, with `1 - c` a unit on it, is zero. -/
theorem PolyIndNoeth.eq_bot_of_le_sq (hB : PolyIndNoeth B) {I : Ideal B}
    (hJ : ∀ c ∈ I, IsUnit (1 - c)) (hI : I ≤ I ^ 2) : I = ⊥ := by
  have hpow : ∀ n, I ≤ I ^ (n + 1) := by
    intro n
    induction n with
    | zero => rw [zero_add, pow_one]
    | succ n ih =>
      calc I ≤ I ^ 2 := hI
        _ = I * I := pow_two I
        _ ≤ I ^ (n + 1) * I := Ideal.mul_mono_left ih
        _ = I ^ (n + 1 + 1) := (pow_succ I (n + 1)).symm
  refine le_bot_iff.1 fun d hd => ?_
  have hdn : ∀ n, d ∈ I ^ n := by
    intro n
    cases n with
    | zero => rw [pow_zero, Ideal.one_eq_top]; trivial
    | succ n => exact hpow n hd
  rw [hB.eq_zero_of_mem_iInf_pow hJ hdn]
  exact zero_mem _

/-- **Nakayama without finite generation**: if `I ≤ K ⊔ I²` and `1 - c` is a unit for every
`c ∈ I`, then `I ≤ K`. Proof: in `B ⧸ K` the image of `I` is contained in its square. -/
theorem PolyIndNoeth.le_of_le_sup_sq (hB : PolyIndNoeth B) {I K : Ideal B}
    (hJ : ∀ c ∈ I, IsUnit (1 - c)) (hI : I ≤ K ⊔ I ^ 2) : I ≤ K := by
  set π := Ideal.Quotient.mk K with hπ
  have hπs : Function.Surjective π := Ideal.Quotient.mk_surjective
  have hJ' : ∀ c ∈ I.map π, IsUnit (1 - c) := by
    intro c hc
    obtain ⟨c', hc', rfl⟩ := (Ideal.mem_map_iff_of_surjective π hπs).1 hc
    rw [← map_one π, ← map_sub]
    exact (hJ c' hc').map π
  have hsq : I.map π ≤ (I.map π) ^ 2 := by
    rw [← Ideal.map_pow, Ideal.map_le_iff_le_comap]
    intro x hx
    obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.1 (hI hx)
    rw [Ideal.mem_comap, map_add, Ideal.Quotient.eq_zero_iff_mem.2 hy, zero_add]
    exact Ideal.mem_map_of_mem π hz
  have hbot := (hB.quotient K).eq_bot_of_le_sq hJ' hsq
  intro x hx
  have h0 : π x = 0 := by
    have : π x ∈ I.map π := Ideal.mem_map_of_mem π hx
    rw [hbot] at this
    exact this
  exact Ideal.Quotient.eq_zero_iff_mem.1 h0

end BezoutCounterexample.Constructive
