import Mathlib
import BezoutCounterexample.Constructive.Attr

/-!
# The Krull intersection step (Perdry; Kuroki's Rees-ring form)

Perdry (Amer. Math. Monthly 111, 2004) proves Krull's intersection theorem from one stationarity
step of one chain of finitely generated ideals; Kuroki's version (`kunz-constructive.pdf`,
Prop. 6.2) runs it in the Rees ring `R[It] ⊆ R[t]`. Here we isolate the purely algebraic part:
the stationarity relation

  `b tᵐ⁺¹ = ∑_{i ≤ m} gᵢ · b tⁱ`  with `gᵢ ∈ R[It]`

gives `b ∈ b I`, hence `b = 0` when `1 - c` is a unit for every `c ∈ I` (`I ⊆ Jac R`).

Obtaining the relation is the Noetherian input (Richman–Seidenberg chain condition for the Rees
ring, Perdry–Schuster; or the Coquand–Persson bar, Kuroki); it is kept as a hypothesis.

`R[It]` is described by its coefficients: `g ∈ R[It]` iff `coeff g j ∈ I ^ j` for all `j`.
-/

namespace BezoutCounterexample.Constructive

open Polynomial

variable {R : Type*} [CommRing R]

/-- Membership in the Rees ring `R[It]`, coefficientwise. -/
def InRees (I : Ideal R) (g : R[X]) : Prop := ∀ j, g.coeff j ∈ I ^ j

/-- **Krull step.** A stationarity relation in the Rees ring puts `b` into `b I`. -/
theorem mem_mul_of_rees {I : Ideal R} {b : R} {m : ℕ} (g : Fin (m + 1) → R[X])
    (hg : ∀ i, InRees I (g i))
    (hrel : C b * X ^ (m + 1) = ∑ i : Fin (m + 1), g i * (C b * X ^ (i : ℕ))) :
    ∃ c ∈ I, b = c * b := by
  -- compare the coefficients of `t ^ (m + 1)`
  have h := congrArg (fun p : R[X] => p.coeff (m + 1)) hrel
  simp only [coeff_C_mul_X_pow, finsetSum_coeff] at h
  have hterm : ∀ i : Fin (m + 1), (g i * (C b * X ^ (i : ℕ))).coeff (m + 1) =
      (g i).coeff (m + 1 - i) * b := by
    intro i
    rw [← mul_assoc, mul_comm (g i) (C b), mul_assoc, coeff_C_mul,
      coeff_mul_X_pow' (g i) (i : ℕ) (m + 1), ite_eq_left_iff.2 (fun h => absurd (by omega) h)]
    ring
  simp only [hterm, ← Finset.sum_mul] at h
  refine ⟨∑ i : Fin (m + 1), (g i).coeff (m + 1 - i), Ideal.sum_mem _ fun i _ => ?_, h⟩
  have hpos : 1 ≤ m + 1 - (i : ℕ) := by omega
  exact Ideal.pow_le_self (by omega) (hg i (m + 1 - i))

/-- **Krull intersection, the conclusion.** If moreover `1 - c` is a unit for `c ∈ I`, then
`b = 0`. -/
theorem eq_zero_of_rees {I : Ideal R} (hJ : ∀ c ∈ I, IsUnit (1 - c)) {b : R} {m : ℕ}
    (g : Fin (m + 1) → R[X]) (hg : ∀ i, InRees I (g i))
    (hrel : C b * X ^ (m + 1) = ∑ i : Fin (m + 1), g i * (C b * X ^ (i : ℕ))) : b = 0 := by
  obtain ⟨c, hc, hb⟩ := mem_mul_of_rees g hg hrel
  obtain ⟨u, hu⟩ := hJ c hc
  have h1 : (1 - c) * b = 0 := by rw [sub_mul, one_mul, ← hb, sub_self]
  rw [← hu] at h1
  calc b = ↑u⁻¹ * (↑u * b) := by rw [← mul_assoc, Units.inv_mul, one_mul]
    _ = 0 := by rw [h1, mul_zero]

/-! ## From a chain condition on the Rees ring -/

/-- The Rees ring `R[It] ⊆ R[t]`. -/
def reesSubring (I : Ideal R) : Subring R[X] where
  carrier := {g | InRees I g}
  mul_mem' {f g} hf hg j := by
    rw [coeff_mul]
    refine Ideal.sum_mem _ fun p hp => ?_
    rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
    rw [← hp, pow_add]
    exact Ideal.mul_mem_mul (hf p.1) (hg p.2)
  one_mem' j := by
    rw [coeff_one]
    split_ifs with h
    · subst h; simp
    · exact zero_mem _
  add_mem' {f g} hf hg j := by rw [coeff_add]; exact add_mem (hf j) (hg j)
  zero_mem' j := by rw [coeff_zero]; exact zero_mem _
  neg_mem' {f} hf j := by rw [coeff_neg]; exact neg_mem (hf j)

/-- The chain condition used once, in the form of Richman–Seidenberg / Coquand–Persson: every
sequence meets an element in the ideal generated by its predecessors. -/
def SeqCond (A : Type*) [CommRing A] : Prop :=
  ∀ s : ℕ → A, ∃ m, s (m + 1) ∈ Ideal.span (Set.range fun i : Fin (m + 1) => s i)

lemma C_mul_X_pow_mem {I : Ideal R} {b : R} {k : ℕ} (hb : b ∈ I ^ k) :
    C b * X ^ k ∈ reesSubring I := by
  intro j
  rw [coeff_C_mul_X_pow]
  split_ifs with h
  · subst h; exact hb
  · exact zero_mem _

/-- **Krull intersection** (Perdry; Kuroki): from the chain condition on the Rees ring, every
`b ∈ ⋂ Iᵏ` lies in `b I`. No Artin–Rees, no primary decomposition. -/
theorem mem_mul_of_iInf (I : Ideal R) (hN : SeqCond (reesSubring I)) {b : R}
    (hb : ∀ k, b ∈ I ^ k) : ∃ c ∈ I, b = c * b := by
  obtain ⟨m, hm⟩ := hN fun k => ⟨C b * X ^ k, C_mul_X_pow_mem (hb k)⟩
  obtain ⟨g, hg⟩ := (Ideal.mem_span_range_iff_exists_fun).1 hm
  refine mem_mul_of_rees (fun i => (g i : R[X])) (fun i => (g i).2) ?_
  have := congrArg (fun z : reesSubring I => (z : R[X])) hg
  simpa using this.symm

/-- **Krull intersection**, conclusion: with `1 - c` a unit for `c ∈ I`, `⋂ Iᵏ = 0`. -/
theorem eq_zero_of_iInf (I : Ideal R) (hN : SeqCond (reesSubring I))
    (hJ : ∀ c ∈ I, IsUnit (1 - c)) {b : R} (hb : ∀ k, b ∈ I ^ k) : b = 0 := by
  obtain ⟨c, hc, hbc⟩ := mem_mul_of_iInf I hN hb
  obtain ⟨u, hu⟩ := hJ c hc
  have h1 : (1 - c) * b = 0 := by rw [sub_mul, one_mul, ← hbc, sub_self]
  rw [← hu] at h1
  calc b = ↑u⁻¹ * (↑u * b) := by rw [← mul_assoc, Units.inv_mul, one_mul]
    _ = 0 := by rw [h1, mul_zero]

end BezoutCounterexample.Constructive
