import Mathlib
import BezoutCounterexample.Constructive.KrullP

/-!
# Inductive Noetherianity (Coquand–Persson) and the chain condition for Rees rings

`SeqCond A` (every sequence meets the ideal of its predecessors) is what Perdry's Krull argument
consumes (`KrullP`). As a statement about sequences `ℕ → A` it does not pass along surjections or
localisations without countable choice: a sequence downstairs has to be lifted. The inductive
(bar) form does pass, since each step lifts one element:

* `NBar l` — the tree of lists (newest entry first) that are not yet *good* (an entry in the ideal
  of the older ones) is well founded above `l`; `IndNoeth A := NBar []`
  (Richman, Seidenberg; Jacobsson–Löfwall; Coquand–Persson, *Gröbner bases in type theory*).
* `IndNoeth.seqCond` — `IndNoeth A → SeqCond A`.
* `IndNoeth.of_surjective`, `IndNoeth.of_isLocalization` — transfer, no choice.
* `indNoeth_of_field` — a field with decidable equality.
* `reesHom_surjective` — the Rees ring `A[It]` of `I = (x₁, …, xₖ)` is an image of
  `A[T₁, …, Tₖ]`; hence `indNoeth_rees`.
* `seqCond_rees_of_finiteType` — for a finitely generated `ℚ`-algebra `A`, any localisation `R`
  of `A`, any ideal `J` of `R` and any finitely generated ideal `I` of `R ⧸ J`, the Rees ring of
  `I` satisfies `SeqCond`, provided `ℚ[Y₁, …, Y_N]` is inductively Noetherian for every `N`.
  The latter is the Hilbert basis theorem in Coquand–Persson's form (Dickson's lemma as an
  inductive bar plus Gröbner reduction); it is the one hypothesis left.
-/

namespace BezoutCounterexample.Constructive

open Polynomial

section Bar

variable {A : Type*} [CommRing A]

/-- The ideal generated by the entries of a list. -/
abbrev lspan (l : List A) : Ideal A := Ideal.span {x | x ∈ l}

/-- `NBar l`: every way of extending `l` (newest entry first) eventually becomes good, i.e. adds
an entry lying in the ideal of the older ones. -/
inductive NBar : List A → Prop
  | good {a : A} {l : List A} : a ∈ lspan l → NBar (a :: l)
  | step {l : List A} : (∀ a, NBar (a :: l)) → NBar l

/-- Inductive Noetherianity. -/
def IndNoeth (A : Type*) [CommRing A] : Prop := NBar ([] : List A)

/-- The first `k` terms of a sequence, newest first. -/
def pre (s : ℕ → A) : ℕ → List A
  | 0 => []
  | k + 1 => s k :: pre s k

omit [CommRing A] in
lemma mem_pre {s : ℕ → A} {k : ℕ} {x : A} (hx : x ∈ pre s k) : ∃ i < k, s i = x := by
  induction k with
  | zero => exact absurd hx List.not_mem_nil
  | succ k ih =>
    rcases List.mem_cons.1 hx with h | h
    · exact ⟨k, Nat.lt_succ_self k, h.symm⟩
    · obtain ⟨i, hi, hix⟩ := ih h
      exact ⟨i, Nat.lt_succ_of_lt hi, hix⟩

lemma NBar.exists_mem {l : List A} (h : NBar l) :
    ∀ (s : ℕ → A) (k : ℕ), pre s k = l → ∃ j, s j ∈ lspan (pre s j) := by
  induction h with
  | @good a l ha =>
    intro s k hk
    cases k with
    | zero => exact absurd hk (List.cons_ne_nil a l).symm
    | succ k =>
      obtain ⟨h1, h2⟩ := List.cons.inj hk
      exact ⟨k, by rw [h1, h2]; exact ha⟩
  | @step l _ ih =>
    intro s k hk
    exact ih (s k) s (k + 1) (by rw [pre, hk])

/-- **Bar ⇒ sequence condition.** -/
theorem IndNoeth.seqCond (h : IndNoeth A) : SeqCond A := by
  intro s
  obtain ⟨j, hj⟩ := NBar.exists_mem h (fun i => s (i + 1)) 0 rfl
  refine ⟨j, Ideal.span_mono ?_ hj⟩
  intro x hx
  obtain ⟨i, hi, hix⟩ := mem_pre hx
  exact ⟨⟨i + 1, Nat.succ_lt_succ hi⟩, hix⟩

/-! ### Transfer -/

variable {B : Type*} [CommRing B]

lemma NBar.map (f : A →+* B) (hf : Function.Surjective f) {l : List A} (h : NBar l) :
    NBar (l.map f) := by
  induction h with
  | @good a l ha =>
    refine NBar.good ?_
    have hle : lspan l ≤ (lspan (l.map f)).comap f :=
      Ideal.span_le.2 fun x hx => Ideal.subset_span (List.mem_map.2 ⟨x, hx, rfl⟩)
    exact hle ha
  | @step l _ ih =>
    refine NBar.step fun b => ?_
    obtain ⟨a, rfl⟩ := hf b
    exact ih a

/-- Inductive Noetherianity passes to images. -/
theorem IndNoeth.of_surjective (f : A →+* B) (hf : Function.Surjective f) (h : IndNoeth A) :
    IndNoeth B :=
  NBar.map f hf h

/-- `y` is a unit multiple of the image of `x`. -/
def AssocImage [Algebra A B] (y : B) (x : A) : Prop := ∃ u : Bˣ, y = u * algebraMap A B x

lemma mem_lspan_of_forall₂ [Algebra A B] {l' : List B} {l : List A}
    (h : List.Forall₂ AssocImage l' l) {x : A} (hx : x ∈ l) : algebraMap A B x ∈ lspan l' := by
  induction h with
  | nil => exact absurd hx List.not_mem_nil
  | @cons y x' l' l hyx _ ih =>
    rcases List.mem_cons.1 hx with h | h
    · obtain ⟨u, hu⟩ := hyx
      have : algebraMap A B x = ↑u⁻¹ * y := by
        rw [hu, h, ← mul_assoc, Units.inv_mul, one_mul]
      rw [this]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span (List.mem_cons_self))
    · exact Ideal.span_mono (fun z hz => List.mem_cons_of_mem y hz) (ih h)

lemma NBar.of_isLocalization (M : Submonoid A) [Algebra A B] [IsLocalization M B] {l : List A}
    (h : NBar l) : ∀ l' : List B, List.Forall₂ AssocImage l' l → NBar l' := by
  induction h with
  | @good a l ha =>
    intro l' hl'
    cases hl' with
    | @cons b _ l'' _ hba hrest =>
      refine NBar.good ?_
      have hle : lspan l ≤ (lspan l'').comap (algebraMap A B) :=
        Ideal.span_le.2 fun x hx => mem_lspan_of_forall₂ hrest hx
      obtain ⟨u, hu⟩ := hba
      rw [hu]
      exact Ideal.mul_mem_left _ _ (hle ha)
  | @step l _ ih =>
    intro l' hl'
    refine NBar.step fun b => ?_
    obtain ⟨⟨a, m⟩, hm⟩ := IsLocalization.surj M b
    obtain ⟨v, hv⟩ := IsLocalization.map_units B m
    refine ih a (b :: l') (List.Forall₂.cons ⟨v⁻¹, ?_⟩ hl')
    simp only at hm
    rw [← hm, ← hv, mul_comm (↑v⁻¹ : B), mul_assoc, Units.mul_inv, mul_one]

/-- Inductive Noetherianity passes to localisations. -/
theorem IndNoeth.of_isLocalization (M : Submonoid A) [Algebra A B] [IsLocalization M B]
    (h : IndNoeth A) : IndNoeth B :=
  NBar.of_isLocalization M h [] List.Forall₂.nil

/-- A field with decidable equality is inductively Noetherian. -/
theorem indNoeth_of_field (K : Type*) [Field K] [DecidableEq K] : IndNoeth K := by
  refine NBar.step fun a => ?_
  if ha : a = 0 then
    refine NBar.good ?_
    rw [ha]
    exact zero_mem _
  else
    refine NBar.step fun b => NBar.good ?_
    have hb : b = b * a⁻¹ * a := by rw [mul_assoc, inv_mul_cancel₀ ha, mul_one]
    rw [hb]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span (List.mem_singleton_self a))

end Bar

/-! ### The Rees ring of a finitely generated ideal is an image of a polynomial ring -/

section Rees

variable {A : Type*} [CommRing A] {ι : Type*} (x : ι → A)

lemma C_mem_rees (I : Ideal A) (a : A) : C a ∈ reesSubring I := by
  have h := C_mul_X_pow_mem (I := I) (k := 0) (b := a) (by rw [pow_zero, Ideal.one_eq_top]; trivial)
  rwa [pow_zero, mul_one] at h

/-- `A[T] → A[It]`, `Tᵢ ↦ xᵢ t`, as a map into `A[t]`. -/
noncomputable def reesPoly : MvPolynomial ι A →+* A[X] :=
  MvPolynomial.eval₂Hom C fun i => C (x i) * X

/-- `A[T] → A[It]`, `Tᵢ ↦ xᵢ t`. -/
noncomputable def reesHom : MvPolynomial ι A →+* reesSubring (Ideal.span (Set.range x)) :=
  MvPolynomial.eval₂Hom ((C : A →+* A[X]).codRestrict _ (C_mem_rees _))
    fun i => ⟨C (x i) * X, by
      have h := C_mul_X_pow_mem (I := Ideal.span (Set.range x)) (k := 1) (b := x i)
        (by rw [pow_one]; exact Ideal.subset_span ⟨i, rfl⟩)
      rwa [pow_one] at h⟩

lemma reesHom_coe (p : MvPolynomial ι A) : (reesHom x p : A[X]) = reesPoly x p := by
  have : (reesSubring (Ideal.span (Set.range x))).subtype.comp (reesHom x) = reesPoly x :=
    MvPolynomial.ringHom_ext (fun a => by
      rw [RingHom.comp_apply, reesHom, reesPoly, MvPolynomial.eval₂Hom_C,
        MvPolynomial.eval₂Hom_C]; rfl) (fun i => by
      rw [RingHom.comp_apply, reesHom, reesPoly, MvPolynomial.eval₂Hom_X',
        MvPolynomial.eval₂Hom_X']; rfl)
  exact congrArg (fun φ : MvPolynomial ι A →+* A[X] => φ p) this

/-- The ideal of `c` with `c tʲ` in the image of `A[T]`. -/
def reesLevel (j : ℕ) : Ideal A where
  carrier := {c | C c * X ^ j ∈ (reesPoly x).range}
  add_mem' {c d} hc hd := by
    simp only [Set.mem_ofPred_eq, map_add, add_mul] at hc hd ⊢
    exact add_mem hc hd
  zero_mem' := by
    simp only [Set.mem_ofPred_eq, map_zero, zero_mul]
    exact zero_mem _
  smul_mem' a c hc := by
    simp only [Set.mem_ofPred_eq, smul_eq_mul, map_mul, mul_assoc] at hc ⊢
    exact mul_mem ⟨MvPolynomial.C a, MvPolynomial.eval₂Hom_C _ _ _⟩ hc

lemma pow_le_reesLevel (j : ℕ) : Ideal.span (Set.range x) ^ j ≤ reesLevel x j := by
  induction j with
  | zero =>
    intro c _
    show C c * X ^ 0 ∈ (reesPoly x).range
    rw [pow_zero, mul_one]
    exact ⟨MvPolynomial.C c, MvPolynomial.eval₂Hom_C _ _ _⟩
  | succ j ih =>
    have h1 : Ideal.span (Set.range x) ≤ reesLevel x 1 := by
      rw [Ideal.span_le]
      rintro _ ⟨i, rfl⟩
      show C (x i) * X ^ 1 ∈ (reesPoly x).range
      rw [pow_one]
      exact ⟨MvPolynomial.X i, MvPolynomial.eval₂Hom_X' _ _ _⟩
    rw [pow_succ]
    refine Ideal.mul_le.2 fun r hr s hs => ?_
    show C (r * s) * X ^ (j + 1) ∈ (reesPoly x).range
    have : C (r * s) * X ^ (j + 1) = (C r * X ^ j) * (C s * X ^ 1) := by
      rw [map_mul, pow_succ, pow_one]; ring
    rw [this]
    exact mul_mem (ih hr) (h1 hs)

/-- **The Rees ring is generated by the `xᵢ t`.** -/
theorem reesHom_surjective : Function.Surjective (reesHom x) := by
  rintro ⟨g, hg⟩
  have hmem : g ∈ (reesPoly x).range := by
    rw [g.as_sum_support_C_mul_X_pow]
    exact Subring.sum_mem _ fun j _ => pow_le_reesLevel x j (hg j)
  obtain ⟨p, hp⟩ := hmem
  exact ⟨p, Subtype.ext (by rw [reesHom_coe, hp])⟩

theorem indNoeth_rees (h : IndNoeth (MvPolynomial ι A)) :
    IndNoeth (reesSubring (Ideal.span (Set.range x))) :=
  h.of_surjective _ (reesHom_surjective x)

end Rees

/-! ### Rees rings over localisations of finitely generated `ℚ`-algebras -/

section FiniteType

/-- `ℚ[Y₁, …, Y_N]` is inductively Noetherian for every `N` (Coquand–Persson). -/
def PolyBar : Prop := ∀ N : ℕ, IndNoeth (MvPolynomial (Fin N) ℚ)

variable {A : Type*} [CommRing A] [Algebra ℚ A]

attribute [local instance] MvPolynomial.algebraMvPolynomial

lemma indNoeth_mvPolynomial_of_finiteType (hP : PolyBar) [hA : Algebra.FiniteType ℚ A]
    (k : ℕ) : IndNoeth (MvPolynomial (Fin k) A) := by
  obtain ⟨N, f, hf⟩ := Algebra.FiniteType.iff_quotient_mvPolynomial''.1 hA
  have h1 : IndNoeth (MvPolynomial (Fin k) (MvPolynomial (Fin N) ℚ)) := by
    refine (hP (k + N)).of_surjective
      ((MvPolynomial.sumRingEquiv ℚ (Fin k) (Fin N)).toRingHom.comp
        (MvPolynomial.renameEquiv ℚ finSumFinEquiv.symm).toRingEquiv.toRingHom) ?_
    exact (MvPolynomial.sumRingEquiv ℚ (Fin k) (Fin N)).surjective.comp
      (MvPolynomial.renameEquiv ℚ finSumFinEquiv.symm).surjective
  exact h1.of_surjective (MvPolynomial.map f.toRingHom) (MvPolynomial.map_surjective _ hf)

/-- **SeqCond for Rees rings** of finitely generated ideals of quotients of localisations of
finitely generated `ℚ`-algebras, from `PolyBar`. -/
theorem seqCond_rees_of_finiteType (hP : PolyBar) [Algebra.FiniteType ℚ A] (M : Submonoid A)
    {R : Type*} [CommRing R] [Algebra A R] [IsLocalization M R] (J : Ideal R) {k : ℕ}
    (y : Fin k → R ⧸ J) : SeqCond (reesSubring (Ideal.span (Set.range y))) := by
  have h1 : IndNoeth (MvPolynomial (Fin k) R) :=
    (indNoeth_mvPolynomial_of_finiteType hP k).of_isLocalization
      (M.map (MvPolynomial.C (σ := Fin k)))
  have h2 : IndNoeth (MvPolynomial (Fin k) (R ⧸ J)) :=
    h1.of_surjective (MvPolynomial.map (Ideal.Quotient.mk J))
      (MvPolynomial.map_surjective _ Ideal.Quotient.mk_surjective)
  exact (indNoeth_rees y h2).seqCond

end FiniteType

end BezoutCounterexample.Constructive
