import BezoutCounterexample.Constructive.Presented
import BezoutCounterexample.Jouanolou

/-!
# Presentations through the ring constructions of the tower

* `HasPres.mvPolynomial`: `A[Z₁, …, Z_k]` is `ℚ[Y, Z] ⧸ (G)`; the kernel of
  `ℚ[Y, Z] → A[Z]` is `(G)` extended (`MvPolynomial.ker_map`).
* `HasPres.polynomial`, `HasPres.laurent`: `A[X]`, `A[T, T⁻¹] = A[X][1/X]`.
* `HasPres.quotient`: `A ⧸ (L)` for an explicit list `L`.
* `HasPres.jou`: the Jouanolou ring `J_A(c) = A[σ] ⧸ (Σ cᵢ σᵢ - 1)`.
* `HasPres.adjoin`: the subalgebra generated by finitely many elements, with kernel generators
  computed by elimination (`exists_ker_list`).
-/

namespace BezoutCounterexample.Constructive

open MvPolynomial

section Surj

variable {B : Type*} [CommRing B]

/-- A surjection from a polynomial ring with an explicitly generated kernel. -/
theorem HasPres.of_surjective {N : ℕ} (φ : MvPolynomial (Fin N) ℚ →+* B)
    (hφ : Function.Surjective φ) (L : List (MvPolynomial (Fin N) ℚ))
    (hker : RingHom.ker φ = lspan L) : HasPres B :=
  ⟨N, L, ⟨(Ideal.quotEquivOfEq hker.symm).trans (RingHom.quotientKerEquivOfSurjective hφ)⟩⟩

end Surj

variable {A : Type*} [CommRing A]

/-- **Polynomial rings over presented rings.** -/
theorem HasPres.mvPolynomial (h : HasPres A) (k : ℕ) : HasPres (MvPolynomial (Fin k) A) := by
  obtain ⟨n, G, ⟨e⟩⟩ := h
  let ε : Fin (n + k) ≃ Fin k ⊕ Fin n := finSumFinEquiv.symm.trans (Equiv.sumComm _ _)
  let ι : MvPolynomial (Fin (n + k)) ℚ ≃+* MvPolynomial (Fin k) (MvPolynomial (Fin n) ℚ) :=
    (renameEquiv ℚ ε).toRingEquiv.trans (sumRingEquiv ℚ (Fin k) (Fin n))
  have hιY : (ι.symm.toRingHom).comp C = (iY (m := k) : MvPolynomial (Fin n) ℚ →ₐ[ℚ] _).toRingHom := by
    apply MvPolynomial.ringHom_ext
    · intro c
      simp [ι, sumRingEquiv_symm_C_C]
    · intro i
      simp only [RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe,
        AlgHom.coe_toRingHom, iY, rename_X]
      apply ι.injective
      rw [RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom, RingEquiv.apply_symm_apply]
      simp [ι, ε, renameEquiv, sumRingEquiv_X_inr]
  let ψ : MvPolynomial (Fin n) ℚ →+* A := e.toRingHom.comp (Ideal.Quotient.mk _)
  have hψker : RingHom.ker ψ = lspan G := by
    ext x
    simp [ψ, RingHom.mem_ker, Ideal.Quotient.eq_zero_iff_mem]
  refine HasPres.of_surjective ((MvPolynomial.map ψ).comp ι.toRingHom) ?_ (G.map iY) ?_
  · refine (MvPolynomial.map_surjective _ ?_).comp ι.surjective
    exact e.surjective.comp Ideal.Quotient.mk_surjective
  · ext x
    rw [RingHom.mem_ker, RingHom.comp_apply, ← RingHom.mem_ker, MvPolynomial.ker_map, hψker]
    constructor
    · intro hx
      have h1 : ι.symm.toRingHom (ι.toRingHom x) ∈
          Ideal.map ι.symm.toRingHom (Ideal.map C (lspan G)) := Ideal.mem_map_of_mem _ hx
      have hxx : ι.symm.toRingHom (ι.toRingHom x) = x := by simp
      rw [hxx, Ideal.map_map, hιY] at h1
      have h2 : Ideal.map (iY (m := k) : MvPolynomial (Fin n) ℚ →ₐ[ℚ] _).toRingHom (lspan G) ≤
          lspan (G.map iY) := by
        show Ideal.map _ (Ideal.span _) ≤ _
        rw [Ideal.map_span, Ideal.span_le]
        rintro _ ⟨g, hg, rfl⟩
        exact Ideal.subset_span (List.mem_map_of_mem hg)
      exact h2 h1
    · intro hx
      have : Ideal.map ι.toRingHom (lspan (G.map iY)) ≤ Ideal.map C (lspan G) := by
        show Ideal.map _ (Ideal.span _) ≤ _
        rw [Ideal.map_span, Ideal.span_le]
        rintro _ ⟨y, hy, rfl⟩
        obtain ⟨g, hg, rfl⟩ := List.mem_map.1 hy
        have : ι.toRingHom (iY (m := k) g) = C g := by
          have h2 := congrArg (fun φ : MvPolynomial (Fin n) ℚ →+* _ => φ g) hιY
          simp only [RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe,
            AlgHom.coe_toRingHom, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom] at h2
          rw [← h2]
          simp
        rw [SetLike.mem_coe, this]
        exact Ideal.mem_map_of_mem _ (Ideal.subset_span hg)
      exact this (Ideal.mem_map_of_mem _ hx)

theorem HasPres.polynomial (h : HasPres A) : HasPres (Polynomial A) :=
  (h.mvPolynomial 1).of_ringEquiv ((MvPolynomial.finSuccEquiv A 0).toRingEquiv.trans
    (Polynomial.mapEquiv (MvPolynomial.isEmptyRingEquiv A (Fin 0))))

theorem HasPres.laurent (h : HasPres A) : HasPres (LaurentPolynomial A) :=
  h.polynomial.away (Polynomial.X : Polynomial A) _

/-- **Quotients by explicit lists.** -/
theorem HasPres.quotient (h : HasPres A) (L : List A) : HasPres (A ⧸ lspan L) := by
  obtain ⟨n, G, ⟨e⟩⟩ := h
  obtain ⟨L', hL'⟩ := exists_lift_list (lspan G) (L.map e.symm)
  let ψ : MvPolynomial (Fin n) ℚ →+* A ⧸ lspan L :=
    (Ideal.Quotient.mk _).comp (e.toRingHom.comp (Ideal.Quotient.mk _))
  refine HasPres.of_surjective ψ ((Ideal.Quotient.mk_surjective).comp
    (e.surjective.comp Ideal.Quotient.mk_surjective)) (L' ++ G) ?_
  have hmap : Ideal.map (e.toRingHom.comp (Ideal.Quotient.mk (lspan G))) (lspan L') = lspan L := by
    show Ideal.map _ (Ideal.span _) = Ideal.span _
    rw [Ideal.map_span]
    congr 1
    ext y
    simp only [Set.mem_image, Set.mem_ofPred_eq]
    constructor
    · rintro ⟨x, hx, rfl⟩
      have : Ideal.Quotient.mk (lspan G) x ∈ L.map e.symm := hL' ▸ List.mem_map_of_mem hx
      obtain ⟨a, ha, hae⟩ := List.mem_map.1 this
      simp only [RingHom.coe_comp, Function.comp_apply, ← hae]
      simpa using ha
    · intro hy
      have : e.symm y ∈ L'.map (Ideal.Quotient.mk (lspan G)) := hL'.symm ▸ List.mem_map_of_mem hy
      obtain ⟨x, hx, hxe⟩ := List.mem_map.1 this
      exact ⟨x, hx, by simp [hxe]⟩
  ext x
  rw [RingHom.mem_ker, lspan_append_eq_sup]
  simp only [ψ, RingHom.coe_comp, Function.comp_apply, Ideal.Quotient.eq_zero_iff_mem]
  rw [← hmap]
  change (e.toRingHom.comp (Ideal.Quotient.mk (lspan G))) x ∈ _ ↔ _
  have hsurj : Function.Surjective (e.toRingHom.comp (Ideal.Quotient.mk (lspan G))) :=
    e.surjective.comp Ideal.Quotient.mk_surjective
  rw [Ideal.mem_map_iff_of_surjective (e.toRingHom.comp (Ideal.Quotient.mk (lspan G))) hsurj,
    Submodule.mem_sup]
  constructor
  · rintro ⟨y, hy, hyx⟩
    refine ⟨y, hy, x - y, ?_, add_sub_cancel _ _⟩
    have : e (Ideal.Quotient.mk (lspan G) (x - y)) = 0 := by
      simp only [RingHom.coe_comp, Function.comp_apply, RingEquiv.toRingHom_eq_coe,
        RingEquiv.coe_toRingHom] at hyx
      rw [map_sub, map_sub, hyx, sub_self]
    rwa [map_eq_zero_iff _ e.injective, Ideal.Quotient.eq_zero_iff_mem] at this
  · rintro ⟨y, hy, z, hz, rfl⟩
    refine ⟨y, hy, ?_⟩
    simp only [RingHom.coe_comp, Function.comp_apply, map_add,
      Ideal.Quotient.eq_zero_iff_mem.2 hz, map_zero, add_zero]

lemma lspan_singleton {R : Type*} [CommRing R] (x : R) : lspan [x] = Ideal.span {x} := by
  rw [lspan]; congr 1; ext y; simp

/-- **Jouanolou rings over presented rings.** -/
theorem HasPres.jou (h : HasPres A) {r : ℕ} (c : Fin r → A) : HasPres (Jou.J c) :=
  ((h.mvPolynomial r).quotient [Jou.rel c]).of_ringEquiv
    (Ideal.quotEquivOfEq (lspan_singleton _))

/-- Finite choice over `Fin m` (induction, no axiom of choice). -/
theorem fin_choice {α : Type*} : ∀ {m : ℕ} {P : Fin m → α → Prop}, (∀ j, ∃ a, P j a) →
    ∃ f : Fin m → α, ∀ j, P j (f j)
  | 0, _, _ => ⟨fun j => j.elim0, fun j => j.elim0⟩
  | m + 1, P, h => by
    obtain ⟨a, ha⟩ := h 0
    obtain ⟨f, hf⟩ := fin_choice (P := fun j => P j.succ) (fun j => h j.succ)
    exact ⟨Fin.cons a f, fun j => Fin.cases (by simpa using ha) (fun j => by simpa using hf j) j⟩

/-- **Finitely generated subalgebras of presented algebras**: kernel by elimination. -/
theorem HasPres.adjoin [Algebra ℚ A] (h : HasPres A) {m : ℕ} (v : Fin m → A) :
    HasPres (Algebra.adjoin ℚ (Set.range v)) := by
  obtain ⟨n, G, ⟨e⟩⟩ := h
  have hf : ∀ j, ∃ q : MvPolynomial (Fin n) ℚ, e (Ideal.Quotient.mk _ q) = v j := fun j =>
    (e.surjective.comp Ideal.Quotient.mk_surjective) (v j)
  obtain ⟨f, hf⟩ := fin_choice hf
  obtain ⟨L, hL⟩ := exists_ker_list G f
  have hcomp : ∀ q : MvPolynomial (Fin m) ℚ, aeval v q = e (Ideal.Quotient.mk _ (aeval f q)) := by
    intro q
    have : (aeval v : MvPolynomial (Fin m) ℚ →ₐ[ℚ] A).toRingHom =
        (e.toRingHom.comp (Ideal.Quotient.mk _)).comp (aeval f).toRingHom := by
      apply MvPolynomial.ringHom_ext
      · intro c
        exact RingHom.congr_fun (RingHom.ext_rat
          ((aeval v : MvPolynomial (Fin m) ℚ →ₐ[ℚ] A).toRingHom.comp C)
          (((e.toRingHom.comp (Ideal.Quotient.mk _)).comp (aeval f).toRingHom).comp C)) c
      · intro j; simp [hf]
    exact congrArg (fun φ : MvPolynomial (Fin m) ℚ →+* A => φ q) this
  have hrange : Algebra.adjoin ℚ (Set.range v) = (aeval v).range :=
    Algebra.adjoin_range_eq_range_aeval ℚ v
  let φ : MvPolynomial (Fin m) ℚ →+* Algebra.adjoin ℚ (Set.range v) :=
    ((Subalgebra.equivOfEq _ _ hrange.symm).toRingEquiv.toRingHom).comp
      (aeval v).rangeRestrict.toRingHom
  refine HasPres.of_surjective φ ?_ L ?_
  · exact (Subalgebra.equivOfEq _ _ hrange.symm).surjective.comp (aeval v).rangeRestrict_surjective
  · ext q
    rw [RingHom.mem_ker, ← hL]
    simp only [φ, RingHom.coe_comp, Function.comp_apply, AlgHom.toRingHom_eq_coe,
      AlgHom.coe_toRingHom, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom,
      AlgEquiv.coe_ringEquiv]
    rw [map_eq_zero_iff _ (Subalgebra.equivOfEq _ _ hrange.symm).injective, ← Subtype.coe_inj,
      ZeroMemClass.coe_zero]
    change aeval v q = 0 ↔ _
    rw [hcomp, map_eq_zero_iff _ e.injective, Ideal.Quotient.eq_zero_iff_mem]

end BezoutCounterexample.Constructive
