import BezoutCounterexample.Principalization.ChartAtPrime

/-!
# Section 3.3: marked centers (Definition 3.2)

Let `A` be a smooth finitely generated `ℚ`-domain and let `𝔪` be a maximal ideal. Then `A_𝔪` is a
regular local ring (`isRegularLocalRing_localization`) of dimension `n = dim A`
(`ringKrullDim_localization`), and its residue field is a finite extension of `ℚ`
(`finite_residueField`). If `x = (x₁, …, xₙ)` is a regular system of parameters of `A_𝔪`, then
`dx₁, …, dxₙ` is a basis of `Ω_{A_𝔪/ℚ}` (`IsRegularSystemOfParameters.exists_basis`); let
`∂₁, …, ∂ₙ` be the dual derivations (`IsRegularSystemOfParameters.exists_dual`).

* `IsRegularSystemOfParameters x`: `x₁, …, xₙ` generate the maximal ideal and `n = dim`.
* **Definition 3.2** (`def:marked-centre`): `MarkedCenter 𝔪` (a regular system of parameters
  and rational weights `e₁ ≥ ⋯ ≥ eₙ ≥ 0`), its weighted ideals `MarkedCenter.F` and admissibility
  `MarkedCenter.IsAdmissible`.
* Weight vectors are regarded as elements of `ℚ^ℕ` by appending zeros (`MarkedCenter.weights`);
  `e ⪯ e'` means `e' ≤_lex e` (`WeightLE`), and `e ≺ e'` means `e ⪯ e'` and `e ≠ e'`.
* `ord I 𝔪 = max {b ∈ ℕ : I A_𝔪 ⊆ 𝔪^b A_𝔪}`.

Lean indices start at `0`: the weights `e₁, e₂, …` of the paper are `e 0, e 1, …`.

*Relation to `Principalization/`.* The engine works with *charts* (families whose differentials
form a basis of `Ω`, with dual derivations). The coordinates of a centred chart of `A_𝔪` form a
regular system of parameters (`Chart.IsCentred.isRegularSystemOfParameters`), and every regular
system of parameters is the coordinate family of a centred chart
(`IsRegularSystemOfParameters.exists_chart`). Hence marked centers are the engine's `MC`s
(`MarkedCenter.ofMC`, `MarkedCenter.exists_mc`), with the same weighted ideals.
-/

noncomputable section

namespace BezoutCounterexample

open IsLocalRing Principalization

/-! ## Regular systems of parameters -/

/-- A *regular system of parameters* of a local ring `S`: `n = dim S` elements generating the
maximal ideal. -/
def IsRegularSystemOfParameters {S : Type*} [CommRing S] [IsLocalRing S] {n : ℕ}
    (x : Fin n → S) : Prop :=
  Ideal.span (Set.range x) = maximalIdeal S ∧ ringKrullDim S = n

section Chart

variable {S : Type*} [CommRing S] [Algebra ℚ S] [IsLocalRing S] [IsNoetherianRing S] {n : ℕ}

omit [IsNoetherianRing S] in
/-- The maximal ideal of a local ring with a centred chart of size `n` is generated by `n`
elements. -/
lemma Principalization.Chart.IsCentred.spanFinrank_le {c : Chart S n} (hc : c.IsCentred) :
    (maximalIdeal S).spanFinrank ≤ n := by
  rw [hc]
  refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range c.x)).trans ?_
  rw [← Set.image_univ]
  refine (Set.ncard_image_le Set.finite_univ).trans ?_
  simp

/-- A Noetherian local `ℚ`-algebra with a centred chart of size `n` has dimension `n`: the
coordinates generate the maximal ideal (so `dim ≤ n` by Krull's height theorem), and the primes
`(x₀, …, x_{i-1})`, `0 ≤ i ≤ n`, form a strictly increasing chain. -/
theorem Principalization.Chart.IsCentred.ringKrullDim_eq {c : Chart S n} (hc : c.IsCentred) :
    ringKrullDim S = n := by
  apply le_antisymm
  · refine (ringKrullDim_le_spanFinrank_maximalIdeal S).trans ?_
    exact_mod_cast hc.spanFinrank_le
  · have hprime : ∀ k : ℕ, (Ideal.span (c.x '' {j | (j : ℕ) < k})).IsPrime :=
      fun k => Chart.IsCentred.span_x_isPrime c hc k
    let P : Fin (n + 1) → PrimeSpectrum S := fun i => ⟨_, hprime i⟩
    have hP : StrictMono P := by
      rw [Fin.strictMono_iff_lt_succ]
      intro i
      rw [← PrimeSpectrum.asIdeal_lt_asIdeal]
      refine lt_of_le_of_ne (Ideal.span_mono (Set.image_mono fun j hj => ?_)) fun h => ?_
      · simp only [Set.mem_ofPred_eq, Fin.val_castSucc, Fin.val_succ] at hj ⊢
        omega
      · have hmem : c.x i ∈ (P i.succ).asIdeal :=
          Ideal.subset_span ⟨i, by simp, rfl⟩
        rw [← h] at hmem
        refine hc.x_not_mem_RF (indW_nonneg _) i (t := 1) (e := indW (i : ℕ))
          (by simp [indW]) ?_
        rw [c.RF_indW]
        exact hmem
    exact Order.LTSeries.length_le_krullDim (LTSeries.mk n P hP)

/-- The coordinates of a centred chart form a regular system of parameters. -/
theorem Principalization.Chart.IsCentred.isRegularSystemOfParameters {c : Chart S n} (hc : c.IsCentred) :
    IsRegularSystemOfParameters c.x :=
  ⟨hc.symm, hc.ringKrullDim_eq⟩

end Chart

/-- Smooth finitely generated `ℚ`-algebras are Noetherian. -/
instance (priority := 100) isNoetherianRing_of_smooth {A : Type*} [CommRing A] [Algebra ℚ A]
    [Algebra.Smooth ℚ A] : IsNoetherianRing A :=
  Algebra.FiniteType.isNoetherianRing ℚ A

instance isNoetherianRing_localization_of_smooth {A : Type*} [CommRing A] [Algebra ℚ A]
    [Algebra.Smooth ℚ A] (𝔭 : Ideal A) [𝔭.IsPrime] :
    IsNoetherianRing (Localization.AtPrime 𝔭) :=
  IsLocalization.isNoetherianRing 𝔭.primeCompl _ inferInstance

section Smooth

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  (𝔪 : Ideal A) [𝔪.IsMaximal]

/-- There is a centred chart at every maximal ideal of a smooth finitely generated `ℚ`-domain. -/
theorem exists_centred_chart :
    ∃ (n : ℕ) (c : Chart (Localization.AtPrime 𝔪) n), c.IsCentred := by
  obtain ⟨n, ⟨c⟩⟩ := exists_chart_atPrime 𝔪
  have := residueField_isIntegral 𝔪
  obtain ⟨c', hc', -⟩ := c.exists_centred (IsNoetherian.noetherian _)
  exact ⟨n, c', hc'⟩

/-- All charts of a smooth finitely generated `ℚ`-domain, at all primes, have size `dim A`. -/
theorem chart_size_eq_ringKrullDim {𝔭 : Ideal A} [𝔭.IsPrime] {n : ℕ}
    (c : Chart (Localization.AtPrime 𝔭) n) : ringKrullDim A = n := by
  have hmax : ∀ (𝔪' : Ideal A) [𝔪'.IsMaximal], 𝔪'.height = n := by
    intro 𝔪' _
    obtain ⟨n', c', hc'⟩ := exists_centred_chart 𝔪'
    have h1 := hc'.ringKrullDim_eq
    rw [IsLocalization.AtPrime.ringKrullDim_eq_height 𝔪' (Localization.AtPrime 𝔪')] at h1
    obtain rfl : n' = n := chart_card_eq_of_domain 𝔪' 𝔭 c' c
    exact_mod_cast h1
  apply le_antisymm
  · rw [ringKrullDim_le_iff_isMaximal_height_le]
    intro 𝔪' h𝔪'
    have := (hmax 𝔪').le
    exact_mod_cast this
  · obtain ⟨𝔪', h𝔪'⟩ := Ideal.exists_maximal A
    have := Ideal.height_le_ringKrullDim_of_ne_top h𝔪'.ne_top
    rw [hmax 𝔪'] at this
    exact_mod_cast this

/-- The dimension of a smooth finitely generated `ℚ`-domain is a natural number. -/
theorem exists_ringKrullDim_eq_natCast (A : Type) [CommRing A] [IsDomain A] [Algebra ℚ A]
    [Algebra.Smooth ℚ A] : ∃ n : ℕ, ringKrullDim A = n := by
  obtain ⟨𝔪', h𝔪'⟩ := Ideal.exists_maximal A
  obtain ⟨n, c, -⟩ := exists_centred_chart 𝔪'
  exact ⟨n, chart_size_eq_ringKrullDim c⟩

/-- `A_𝔪` has dimension `n = dim A`. -/
theorem ringKrullDim_localization :
    ringKrullDim (Localization.AtPrime 𝔪) = ringKrullDim A := by
  obtain ⟨n, c, hc⟩ := exists_centred_chart 𝔪
  rw [hc.ringKrullDim_eq, chart_size_eq_ringKrullDim c]

/-- `A_𝔪` is a regular local ring. -/
theorem isRegularLocalRing_localization : IsRegularLocalRing (Localization.AtPrime 𝔪) := by
  obtain ⟨n, c, hc⟩ := exists_centred_chart 𝔪
  apply IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
  rw [hc.ringKrullDim_eq]
  exact_mod_cast hc.spanFinrank_le

omit [IsDomain A] in
/-- The residue field of `A_𝔪` is a finite extension of `ℚ`. -/
theorem finite_residueField : Module.Finite ℚ (ResidueField (Localization.AtPrime 𝔪)) := by
  let := Ideal.Quotient.field 𝔪
  have : Module.Finite ℚ (A ⧸ 𝔪) := finite_of_finite_type_of_isJacobsonRing ℚ (A ⧸ 𝔪)
  exact Module.Finite.of_surjective
    (IsScalarTower.toAlgHom ℚ (A ⧸ 𝔪) 𝔪.ResidueField).toLinearMap
    𝔪.bijective_algebraMap_quotient_residueField.surjective

/-- `A_𝔪` has a regular system of parameters. -/
theorem exists_isRegularSystemOfParameters :
    ∃ (n : ℕ) (x : Fin n → Localization.AtPrime 𝔪), IsRegularSystemOfParameters x := by
  obtain ⟨n, c, hc⟩ := exists_centred_chart 𝔪
  exact ⟨n, c.x, hc.isRegularSystemOfParameters⟩

variable {𝔪}

/-- Every regular system of parameters of `A_𝔪` is the coordinate family of a centred chart. -/
theorem IsRegularSystemOfParameters.exists_chart {n : ℕ} {x : Fin n → Localization.AtPrime 𝔪}
    (hx : IsRegularSystemOfParameters x) :
    ∃ c : Chart (Localization.AtPrime 𝔪) n, c.x = x ∧ c.IsCentred := by
  classical
  obtain ⟨n₀, c₀, hc₀⟩ := exists_centred_chart 𝔪
  have hn : n₀ = n := by
    have h := hc₀.ringKrullDim_eq
    rw [hx.2] at h
    exact_mod_cast h.symm
  subst hn
  have hxm : ∀ j, x j ∈ maximalIdeal (Localization.AtPrime 𝔪) := fun j => by
    rw [← hx.1]; exact Ideal.subset_span ⟨j, rfl⟩
  -- `xⱼ = ∑ᵢ aⱼᵢ c₀.xᵢ` and `c₀.xᵢ = ∑ₗ bᵢₗ xₗ`
  choose a ha using fun j => Ideal.mem_span_range_iff_exists_fun.1 (hc₀ ▸ hxm j)
  choose b hb using fun i => Ideal.mem_span_range_iff_exists_fun.1 (hx.1 ▸ hc₀.x_mem i)
  -- the `xₗ` are minimal generators: relations have coefficients in `𝔪`
  have hmin : ∀ w : Fin n₀ → Localization.AtPrime 𝔪, ∑ l, w l * x l = 0 →
      ∀ l, w l ∈ maximalIdeal (Localization.AtPrime 𝔪) := by
    intro w hw l₀
    by_contra hl₀
    obtain ⟨u, hu⟩ := (IsLocalRing.notMem_maximalIdeal).1 hl₀
    have hx0 : x l₀ ∈ Ideal.span (x '' {l | l ≠ l₀}) := by
      have h := hw
      rw [← Finset.add_sum_erase _ _ (Finset.mem_univ l₀), ← hu] at h
      have hx0' : x l₀ = -(↑u⁻¹ * ∑ l ∈ Finset.univ.erase l₀, w l * x l) := by
        calc x l₀ = ↑u⁻¹ * (↑u * x l₀) := by rw [← mul_assoc, Units.inv_mul, one_mul]
          _ = _ := by rw [eq_neg_of_add_eq_zero_left h]; ring
      rw [hx0']
      refine neg_mem (Ideal.mul_mem_left _ _ (Ideal.sum_mem _ fun l hl =>
        Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨l, Finset.ne_of_mem_erase hl, rfl⟩)))
    have heq : maximalIdeal (Localization.AtPrime 𝔪) = Ideal.span (x '' {l | l ≠ l₀}) := by
      refine le_antisymm ?_ (Ideal.span_le.2 (by rintro _ ⟨l, -, rfl⟩; exact hxm l))
      rw [← hx.1, Ideal.span_le]
      rintro _ ⟨l, rfl⟩
      by_cases hl : l = l₀
      · subst hl; exact hx0
      · exact Ideal.subset_span ⟨l, hl, rfl⟩
    have h1 : (maximalIdeal (Localization.AtPrime 𝔪)).spanFinrank < n₀ := by
      rw [heq]
      refine lt_of_le_of_lt (Submodule.spanFinrank_span_le_ncard_of_finite (Set.toFinite _)) ?_
      refine lt_of_le_of_lt (Set.ncard_image_le (Set.toFinite _)) ?_
      have hss : {l : Fin n₀ | l ≠ l₀} ⊂ Set.univ :=
        Set.ssubset_univ_iff.2 fun h => (h ▸ Set.mem_univ l₀ : l₀ ∈ {l : Fin n₀ | l ≠ l₀}) rfl
      calc {l : Fin n₀ | l ≠ l₀}.ncard < (Set.univ : Set (Fin n₀)).ncard :=
            Set.ncard_lt_ncard hss Set.finite_univ
        _ = n₀ := by simp
    have h2 := ringKrullDim_le_spanFinrank_maximalIdeal (Localization.AtPrime 𝔪)
    rw [hx.2] at h2
    have h3 : n₀ ≤ (maximalIdeal (Localization.AtPrime 𝔪)).spanFinrank := by exact_mod_cast h2
    omega
  -- `∂ₖ xⱼ ≡ aⱼₖ` modulo `𝔪`
  have hd : ∀ k j, c₀.d k (x j) - a j k ∈ maximalIdeal (Localization.AtPrime 𝔪) := by
    intro k j
    have h : c₀.d k (x j) = a j k + ∑ i, c₀.x i * c₀.d k (a j i) := by
      rw [← ha j, map_sum]
      have : ∀ i, c₀.d k (a j i * c₀.x i) =
          (if k = i then a j i else 0) + c₀.x i * c₀.d k (a j i) := by
        intro i
        rw [Derivation.leibniz, c₀.d_x, smul_eq_mul, smul_eq_mul]
        split_ifs <;> ring
      simp only [this, Finset.sum_add_distrib, Finset.sum_ite_eq, Finset.mem_univ, ite_true]
    rw [h, add_sub_cancel_left]
    exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (hc₀.x_mem i)
  -- `a b ≡ 1` modulo `𝔪`
  have hab : ∀ j l, (∑ i, a j i * b i l) - (if j = l then 1 else 0) ∈
      maximalIdeal (Localization.AtPrime 𝔪) := by
    intro j
    apply hmin
    have h1 : x j = ∑ l, (∑ i, a j i * b i l) * x l := by
      calc x j = ∑ i, a j i * c₀.x i := (ha j).symm
        _ = ∑ i, a j i * ∑ l, b i l * x l := by simp only [hb]
        _ = ∑ l, (∑ i, a j i * b i l) * x l := by
          simp only [Finset.mul_sum, Finset.sum_mul, mul_assoc]
          exact Finset.sum_comm
    simp only [sub_mul, Finset.sum_sub_distrib, ite_mul, one_mul, zero_mul, Finset.sum_ite_eq,
      Finset.mem_univ, ite_true]
    rw [← h1, sub_self]
  -- reduce modulo `𝔪`
  set Ab : Matrix (Fin n₀) (Fin n₀) (ResidueField (Localization.AtPrime 𝔪)) :=
    Matrix.of fun j i => residue _ (a j i) with hAb
  set Bb : Matrix (Fin n₀) (Fin n₀) (ResidueField (Localization.AtPrime 𝔪)) :=
    Matrix.of fun i l => residue _ (b i l) with hBb
  have hAB : Ab * Bb = 1 := by
    ext j l
    rw [Matrix.mul_apply, Matrix.one_apply]
    simp only [hAb, hBb, Matrix.of_apply, ← map_mul, ← map_sum]
    have := (residue_eq_zero_iff _).2 (hab j l)
    rw [map_sub, sub_eq_zero] at this
    rw [this]
    split_ifs <;> simp
  have hdetA : Ab.det ≠ 0 := by
    intro h0
    have := congrArg Matrix.det hAB
    rw [Matrix.det_mul, h0, zero_mul, Matrix.det_one] at this
    exact zero_ne_one this
  have hjac : (c₀.jac x).map (residue _) = Ab.transpose := by
    ext k j
    simp only [Matrix.map_apply, Chart.jac, Matrix.of_apply, Matrix.transpose_apply, hAb]
    have := (residue_eq_zero_iff _).2 (hd k j)
    rwa [map_sub, sub_eq_zero] at this
  have hunit : IsUnit (c₀.jac x).det := by
    rw [← IsLocalRing.notMem_maximalIdeal, ← residue_eq_zero_iff, RingHom.map_det,
      RingHom.mapMatrix_apply, hjac, Matrix.det_transpose]
    exact hdetA
  exact ⟨c₀.change x hunit, rfl, hx.1.symm⟩

/-- If `x` is a regular system of parameters of `A_𝔪`, then `dx₁, …, dxₙ` is a basis of
`Ω_{A_𝔪/ℚ}`. -/
theorem IsRegularSystemOfParameters.exists_basis {n : ℕ} {x : Fin n → Localization.AtPrime 𝔪}
    (hx : IsRegularSystemOfParameters x) :
    ∃ b : Module.Basis (Fin n) (Localization.AtPrime 𝔪) Ω[Localization.AtPrime 𝔪⁄ℚ],
      ∀ i, b i = KaehlerDifferential.D ℚ (Localization.AtPrime 𝔪) (x i) := by
  obtain ⟨c, rfl, -⟩ := hx.exists_chart
  exact ⟨c.basis, c.basis_apply⟩

/-- The derivations `∂₁, …, ∂ₙ` dual to a regular system of parameters. -/
theorem IsRegularSystemOfParameters.exists_dual {n : ℕ} {x : Fin n → Localization.AtPrime 𝔪}
    (hx : IsRegularSystemOfParameters x) :
    ∃ D : Fin n → Derivation ℚ (Localization.AtPrime 𝔪) (Localization.AtPrime 𝔪),
      ∀ i j, D i (x j) = if i = j then 1 else 0 := by
  obtain ⟨c, rfl, -⟩ := hx.exists_chart
  exact ⟨c.d, c.d_x⟩

end Smooth

/-! ## Definition 3.2: marked centers -/

section MarkedCenter

variable {A : Type*} [CommRing A]

/-- **Definition 3.2** (`def:marked-centre`). A *marked center* at `𝔪` is a pair `J = (x, e)`
consisting of a regular system of parameters `x` of `A_𝔪` and rational weights
`e₁ ≥ e₂ ≥ ⋯ ≥ eₙ ≥ 0`. -/
structure MarkedCenter (𝔪 : Ideal A) [𝔪.IsPrime] where
  /-- The number of parameters (`n = dim A_𝔪`). -/
  n : ℕ
  /-- The regular system of parameters. -/
  x : Fin n → Localization.AtPrime 𝔪
  /-- The weights. -/
  e : Fin n → ℚ
  isRegular : IsRegularSystemOfParameters x
  antitone : Antitone e
  nonneg : ∀ i, 0 ≤ e i

namespace MarkedCenter

variable {𝔪 : Ideal A} [𝔪.IsPrime] (J : MarkedCenter 𝔪)

/-- The *weighted ideal of level `t`* of `J`: the ideal of `A_𝔪` generated by the monomials
`x^α` with `α ∈ ℕⁿ`, `αᵢ = 0` if `eᵢ = 0`, and `∑ eᵢ αᵢ ≥ t`. -/
def F (t : ℚ) : Ideal (Localization.AtPrime 𝔪) :=
  Ideal.span {f | ∃ α : Fin J.n → ℕ, (∀ i, J.e i = 0 → α i = 0) ∧ t ≤ ∑ i, J.e i * α i ∧
    f = ∏ i, J.x i ^ α i}

/-- `J` is *admissible* for an ideal `I ⊆ 𝔪` if `I A_𝔪 ⊆ F₁(J)`. -/
def IsAdmissible (I : Ideal A) : Prop :=
  I.map (algebraMap A (Localization.AtPrime 𝔪)) ≤ J.F 1

/-- The weight vector of `J`, regarded as an element of `ℚ^ℕ` by appending zeros. -/
def weights : ℕ → ℚ := fun i => if h : i < J.n then J.e ⟨i, h⟩ else 0

end MarkedCenter

end MarkedCenter

/-! ## The order `⪯` on weight vectors -/

/-- `e ⪯ e'` if `e' ≤_lex e`: the opposite of the lexicographic order on `ℚ^ℕ`. -/
def WeightLE (e e' : ℕ → ℚ) : Prop := toLex e' ≤ toLex e

/-- `e ≺ e'` if `e ⪯ e'` and `e ≠ e'`. -/
def WeightLT (e e' : ℕ → ℚ) : Prop := WeightLE e e' ∧ e ≠ e'

@[inherit_doc] scoped infix:50 " ⪯ " => WeightLE
@[inherit_doc] scoped infix:50 " ≺ " => WeightLT

lemma weightLT_iff {e e' : ℕ → ℚ} : e ≺ e' ↔ toLex e' < toLex e := by
  constructor
  · rintro ⟨h1, h2⟩
    exact lt_of_le_of_ne h1 (fun h => h2 (toLex.injective h).symm)
  · intro h
    exact ⟨h.le, fun h' => h.ne (congrArg toLex h'.symm)⟩

/-- The number of nonzero entries of a weight vector (`k` in the paper). -/
def numNonzero (e : ℕ → ℚ) : ℕ := {i | e i ≠ 0}.ncard

/-! ## The order of an ideal -/

/-- `ord_𝔪(I) = max {b ∈ ℕ : I A_𝔪 ⊆ 𝔪^b A_𝔪}`. -/
def ord {A : Type*} [CommRing A] (I 𝔪 : Ideal A) [𝔪.IsPrime] : ℕ :=
  sSup {b : ℕ | I.map (algebraMap A (Localization.AtPrime 𝔪)) ≤
    maximalIdeal (Localization.AtPrime 𝔪) ^ b}

/-! ## Marked centers and the engine's `MC` -/

section Bridge

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  {𝔪 : Ideal A} [𝔪.IsMaximal]

omit [IsDomain A] [Algebra.Smooth ℚ A] in
/-- The weighted ideals of a marked center are the engine's `Chart.RF`. -/
theorem MarkedCenter.F_eq_RF (J : MarkedCenter 𝔪) (c : Chart (Localization.AtPrime 𝔪) J.n)
    (hc : c.x = J.x) (t : ℚ) : J.F t = c.RF J.e t := by
  rw [MarkedCenter.F, Chart.RF, hc]
  congr 1
  ext f
  constructor
  · rintro ⟨α, h0, ht, rfl⟩
    refine ⟨Finsupp.equivFunOnFinite.symm α, fun i hi => by simpa using h0 i hi, ?_, by simp⟩
    simpa [lam, mul_comm] using ht
  · rintro ⟨α, h0, ht, rfl⟩
    exact ⟨α, h0, by simpa [lam, mul_comm] using ht, rfl⟩

/-- An engine marked center (centred chart and antitone nonnegative weights) as a marked center. -/
def MarkedCenter.ofMC {n : ℕ} (J : MC (Localization.AtPrime 𝔪) n) : MarkedCenter 𝔪 :=
  ⟨n, J.c.x, J.e, J.centred.isRegularSystemOfParameters, J.anti, J.nonneg⟩

omit [IsDomain A] in
@[simp] lemma MarkedCenter.ofMC_F {n : ℕ} (J : MC (Localization.AtPrime 𝔪) n) (t : ℚ) :
    (MarkedCenter.ofMC J).F t = J.RF t :=
  MarkedCenter.F_eq_RF (MarkedCenter.ofMC J) J.c (Eq.refl J.c.x) t

omit [IsDomain A] in
@[simp] lemma MarkedCenter.ofMC_weights {n : ℕ} (J : MC (Localization.AtPrime 𝔪) n) :
    (MarkedCenter.ofMC J).weights = ext0 J.e := rfl

/-- Every marked center comes from an engine marked center with the same weighted ideals. -/
theorem MarkedCenter.exists_mc (J : MarkedCenter 𝔪) :
    ∃ J' : MC (Localization.AtPrime 𝔪) J.n, J'.c.x = J.x ∧ J'.e = J.e ∧
      ∀ t, J'.RF t = J.F t := by
  obtain ⟨c, hcx, hc⟩ := J.isRegular.exists_chart
  exact ⟨⟨c, J.e, hc, J.nonneg, J.antitone⟩, hcx, rfl,
    fun t => (J.F_eq_RF c hcx t).symm⟩

end Bridge

end BezoutCounterexample
