import Mathlib
import BezoutCounterexample.Principalization.ReesGlobal
import BezoutCounterexample.Principalization.ChainLiftReesPres

/-!
# Integer Rees generators of the component filtration (Task B, Rees layer S6, producer input)

For `Φ = compFil` and a presentation `e : QB G ≃+* A`, the generators `yᵢ = C(gᵢ) T^{δᵢ}` of the
weighted-chart model come from coll-7c's canonical generators (`canonGenPairs`, R2 as data), each
lifted to `ℤ[Y]` up to a positive integer (`int_clear`; `gᵢ` and `Dᵢ gᵢ` generate the same
`A`-algebra since `Dᵢ` is a unit in `A`).

* `exists_reesGensZ`: `r`, `gZ : Fin r → ℤ[Y]`, `δ : Fin r → ℕ` (`1 ≤ δᵢ ≤ d`) with `hgF`
  (`toAq (toQZ gZᵢ) ∈ F_{δᵢ}`) and `hgen` (every `C(f) Tʲ`, `f ∈ F_j`, in the `A`-algebra generated by
  `T⁻¹` and the `reesYL`), the hypotheses of `ChainLiftReesPres`/`ChainLiftReesRows`.
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open MvPolynomial BezoutCounterexample.Constructive
open LaurentPolynomial hiding C

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  [IsNoetherianRing A]

variable {I : Ideal A} (hI : I ≠ ⊥) {v₀ : ℕ → ℚ}
  (hmax : IsMaxInvPt I v₀)
  {𝔭 : Ideal A} (h𝔭 : LocusComp I v₀ 𝔭) (d : ℕ)
  (hd : 0 < d) (hw : ∀ i, ∃ w : ℕ, (w : ℚ) = d * v₀ i)
  {m n : ℕ} (G : List (MvPolynomial (Fin (m + n)) ℤ)) (e : SmoothCert.QB G ≃+* A)

omit [IsDomain A] [Algebra.Smooth ℚ A] [IsNoetherianRing A] in
/-- An element of `A` is a positive integer multiple of the image of an integer polynomial. -/
lemma exists_toAq_int (a : A) :
    ∃ (D : ℕ) (pZ : MvPolynomial (Fin (m + n)) ℤ), 0 < D ∧ toAq G e (toQZ pZ) = (D : A) * a := by
  obtain ⟨p, hp⟩ := toAq_surjective G e a
  obtain ⟨D, q, hD, hq⟩ := int_clear p
  refine ⟨D, q, hD, ?_⟩
  rw [hq, ← hp]
  simp only [toAq, map_mul, map_natCast]

include hI hmax h𝔭 hd hw in
/-- **Integer Rees generators** of `compFil`: the inputs `gZ`, `δ`, `hgF`, `hgen` of the presentation
of `ReesAlg (compFil …)` (`ChainLiftReesPres`) from `canonGenPairs`. -/
theorem exists_reesGensZ [Fact (HasPres A)] (en : ℕ → A) (hen : Function.Surjective en) :
    ∃ (r : ℕ) (gZ : Fin r → MvPolynomial (Fin (m + n)) ℤ) (δ : Fin r → ℕ),
      (∀ i, 1 ≤ δ i ∧ δ i ≤ d) ∧
      (∀ i, toAq G e (toQZ (gZ i)) ∈ (compFil hI hmax h𝔭 d).F (δ i)) ∧
      (∀ (j : ℤ) (f : A), f ∈ (compFil hI hmax h𝔭 d).F j →
        LaurentPolynomial.C f * T j ∈
          Algebra.adjoin A (insert (T (-1)) (Set.range (reesYL G e gZ δ)))) := by
  set L := canonGenPairs hI hmax h𝔭 d en hen
  obtain ⟨Dg, hDg⟩ := finite_choice_dep (ι := Fin L.length)
    (P := fun i (x : ℕ × MvPolynomial (Fin (m + n)) ℤ) =>
      0 < x.1 ∧ toAq G e (toQZ x.2) = (x.1 : A) * (L.get i).2)
    fun i => by
      obtain ⟨D, pZ, hD, h⟩ := exists_toAq_int G e (L.get i).2
      exact ⟨(D, pZ), hD, h⟩
  have hmem : ∀ i, 1 ≤ (L.get i).1 ∧ (L.get i).1 ≤ d ∧
      (L.get i).2 ∈ canonGensF hI hmax h𝔭 d en hen (L.get i).1 := fun i =>
    (mem_canonGenPairs hI hmax h𝔭 d en hen).1 (List.get_mem L i)
  have hδ : ∀ i, (((L.get i).1.toNat : ℕ) : ℤ) = (L.get i).1 := fun i => by
    have := (hmem i).1; omega
  refine ⟨L.length, fun i => (Dg i).2, fun i => (L.get i).1.toNat, fun i => ?_, fun i => ?_, ?_⟩
  · have h1 := (hmem i).1
    have h2 := (hmem i).2.1
    show 1 ≤ (L.get i).1.toNat ∧ (L.get i).1.toNat ≤ d
    exact ⟨by omega, by omega⟩
  · rw [(hDg i).2, hδ i]
    refine Ideal.mul_mem_left _ _ ?_
    rw [← lspan_canonGensF hI hmax h𝔭 d en hen]
    exact Ideal.subset_span (hmem i).2.2
  · intro j f hf
    refine Algebra.adjoin_le ?_ (C_mul_T_mem_adjoin_of hI hmax h𝔭 d hd hw
      (canonGensF hI hmax h𝔭 d en hen)
      (fun j _ _ => lspan_canonGensF hI hmax h𝔭 d en hen j) j f hf)
    intro x hx
    rcases hx with hx | hx
    · rw [Set.mem_singleton_iff] at hx
      subst hx
      exact Algebra.subset_adjoin (Set.mem_insert _ _)
    · simp only [Set.mem_iUnion, Set.mem_image, Set.mem_ofPred_eq] at hx
      obtain ⟨j, hj, g, hg, rfl⟩ := hx
      obtain ⟨h1, h2⟩ := Finset.mem_Icc.1 hj
      obtain ⟨i, hi⟩ := List.mem_iff_get.1
        ((mem_canonGenPairs hI hmax h𝔭 d en hen (q := (j, g))).2 ⟨h1, h2, hg⟩)
      -- `C g Tʲ = C(D⁻¹) · yᵢ`, with `D` a unit of `A`
      have hD : (((Dg i).1 : ℚ)) ≠ 0 := by exact_mod_cast (hDg i).1.ne'
      have hy : reesYL G e (fun i => (Dg i).2) (fun i => (L.get i).1.toNat) i =
          LaurentPolynomial.C (((Dg i).1 : A) * g) * T j := by
        rw [reesYL, (hDg i).2, hδ i, hi]
      have hx : LaurentPolynomial.C g * T j =
          LaurentPolynomial.C (algebraMap ℚ A ((Dg i).1 : ℚ)⁻¹) *
            reesYL G e (fun i => (Dg i).2) (fun i => (L.get i).1.toNat) i := by
        rw [hy, ← mul_assoc, ← map_mul, ← mul_assoc]
        congr 2
        rw [show ((Dg i).1 : A) = algebraMap ℚ A ((Dg i).1 : ℚ) by simp, ← map_mul,
          inv_mul_cancel₀ hD, map_one, one_mul]
      rw [hx, LaurentPolynomial.C_eq_algebraMap]
      exact Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ _)
        (Algebra.subset_adjoin (Set.mem_insert_of_mem _ ⟨i, rfl⟩))

end BezoutCounterexample.Principalization
