import Mathlib
import BezoutCounterexample.Constructive.ChainLiftSmoothCert
import BezoutCounterexample.Principalization.Spread

/-!
# Charts from smoothness certificates (Task B)

A certified square piece `S : SquarePiece m n G` gives an explicit chart with `n` coordinates on
`D(h)` of the presented ring `R = ℚ[Y_{m+n}]/(G)`:

* `SquarePiece.chart : Chart (Localization.Away (mkQ S.h)) n`, with coordinates the images of the
  last `n` functions of `S.F` and dual derivations the columns of the inverse Jacobian
  (`det J · U ≡ hᵉ`, so `det J` is a unit on `D(h)`, with explicit inverse `U · h⁻ᵉ`);
* `SquarePiece.derivation_eq_zero`: a derivation on `D(h)` vanishing on the coordinates is zero;
* `SmoothCert.chartAt`: the chart of piece `k` at a prime `𝔭` with `h_k ∉ 𝔭`.

No primes are quantified over and no choice is used: the derivations are built through the
trivial square-zero extension, as in `extLoc`.
-/

noncomputable section

set_option synthInstance.maxHeartbeats 400000

namespace BezoutCounterexample.Constructive

open BezoutCounterexample.Principalization MvPolynomial TrivSqZeroExt

variable {m n : ℕ} {G : List (MvPolynomial (Fin (m + n)) ℤ)}

namespace SquarePiece

/-- The image of an integer polynomial in `ℚ[Y]/(G)`. -/
abbrev mkQ (G : List (MvPolynomial (Fin (m + n)) ℤ)) (p : MvPolynomial (Fin (m + n)) ℤ) :
    SmoothCert.QB G :=
  Ideal.Quotient.mk _ (toQZ p)

variable (S : SquarePiece m n G)

/-- The localization `D(h)`. -/
abbrev Loc : Type := Localization.Away (mkQ G S.h)

/-- `ℚ[Y] → D(h)`. -/
abbrev img : MvPolynomial (Fin (m + n)) ℚ →+* S.Loc :=
  (algebraMap (SmoothCert.QB G) S.Loc).comp (Ideal.Quotient.mk _)

/-- Integer polynomials in `D(h)`. -/
abbrev φ : MvPolynomial (Fin (m + n)) ℤ →+* S.Loc := S.img.comp toQZ

lemma φ_eq_zero {p : MvPolynomial (Fin (m + n)) ℤ} (hp : p ∈ lspan G) : S.φ p = 0 := by
  have h1 : toQZ p ∈ lspan (G.map toQZ) := by
    have : (lspan G).map toQZ ≤ lspan (G.map toQZ) := by
      rw [lspan, lspan, Ideal.map_span, Ideal.span_le]
      rintro _ ⟨g, hg, rfl⟩
      exact Ideal.subset_span (List.mem_map_of_mem hg)
    exact this (Ideal.mem_map_of_mem _ hp)
  simp only [φ, img, RingHom.comp_apply, Ideal.Quotient.eq_zero_iff_mem.2 h1, map_zero]

lemma φ_eq {p q : MvPolynomial (Fin (m + n)) ℤ} (h : p - q ∈ lspan G) : S.φ p = S.φ q := by
  rw [← sub_eq_zero, ← map_sub]; exact S.φ_eq_zero h

/-- The Jacobian in `D(h)`. -/
abbrev JS : Matrix (Fin (m + n)) (Fin (m + n)) S.Loc := (jacPoly S.F).map S.φ

/-- The inverse of `det J`: `U · h⁻ᵉ`. -/
abbrev dinv : S.Loc :=
  S.φ S.U * IsLocalization.Away.invSelf (mkQ G S.h) ^ S.e

lemma φ_h : S.φ S.h = algebraMap (SmoothCert.QB G) S.Loc (mkQ G S.h) := rfl

lemma dinv_mul : S.dinv * S.JS.det = 1 := by
  have hd := S.φ_eq S.detc
  rw [map_mul, map_pow] at hd
  have hJ : S.JS.det = S.φ (jacPoly S.F).det := (RingHom.map_det _ _).symm
  rw [hJ, dinv, mul_comm (S.φ S.U), mul_assoc, mul_comm (S.φ S.U), hd, S.φ_h, ← mul_pow,
    mul_comm, IsLocalization.Away.mul_invSelf, one_pow]

/-- The inverse Jacobian `U h⁻ᵉ adj J`. -/
abbrev Jinv : Matrix (Fin (m + n)) (Fin (m + n)) S.Loc := S.dinv • S.JS.adjugate

lemma JS_mul_Jinv : S.JS * S.Jinv = 1 := by
  rw [Jinv, Matrix.mul_smul, Matrix.mul_adjugate, smul_smul, dinv_mul, one_smul]

lemma Jinv_mul_JS : S.Jinv * S.JS = 1 := by
  rw [Jinv, Matrix.smul_mul, Matrix.adjugate_mul, smul_smul, dinv_mul, one_smul]

/-- The vector field dual to the coordinate `i`: column `m + i` of the inverse Jacobian. -/
abbrev v (i : Fin n) (k : Fin (m + n)) : S.Loc := S.Jinv k (Fin.natAdd m i)

/-- The derivative along `v i` of an integer polynomial. -/
def Dv (i : Fin n) (p : MvPolynomial (Fin (m + n)) ℤ) : S.Loc :=
  ∑ k, S.v i k * S.φ (pderiv k p)

lemma Dv_add (i : Fin n) (p q : MvPolynomial (Fin (m + n)) ℤ) :
    S.Dv i (p + q) = S.Dv i p + S.Dv i q := by
  simp only [Dv, map_add, mul_add, Finset.sum_add_distrib]

lemma Dv_mul (i : Fin n) (p q : MvPolynomial (Fin (m + n)) ℤ) :
    S.Dv i (p * q) = S.φ p * S.Dv i q + S.φ q * S.Dv i p := by
  simp only [Dv, Derivation.leibniz, smul_eq_mul, map_add, map_mul, mul_add,
    Finset.sum_add_distrib, Finset.mul_sum]
  congr 1 <;> refine Finset.sum_congr rfl fun k _ => by ring

lemma Dv_F (i : Fin n) (a : Fin (m + n)) :
    S.Dv i (S.F a) = if a = Fin.natAdd m i then 1 else 0 := by
  have := congrFun (congrFun S.JS_mul_Jinv a) (Fin.natAdd m i)
  rw [Matrix.mul_apply, Matrix.one_apply] at this
  rw [← this, Dv]
  exact Finset.sum_congr rfl fun k _ => mul_comm _ _

/-- Vanishing on an ideal generated by a list of vanishing elements. -/
lemma vanish_of_mem_lspan (i : Fin n) {L : List (MvPolynomial (Fin (m + n)) ℤ)}
    (hL : ∀ l ∈ L, S.φ l = 0 ∧ S.Dv i l = 0) {x : MvPolynomial (Fin (m + n)) ℤ} (hx : x ∈ lspan L) :
    S.φ x = 0 ∧ S.Dv i x = 0 := by
  induction hx using Submodule.span_induction with
  | mem y hy => exact hL y hy
  | zero => exact ⟨map_zero _, by simp [Dv]⟩
  | add y z _ _ hy hz => exact ⟨by rw [map_add, hy.1, hz.1, add_zero], by rw [Dv_add, hy.2, hz.2, add_zero]⟩
  | smul r y _ hy =>
    rw [smul_eq_mul]
    exact ⟨by rw [map_mul, hy.1, mul_zero], by rw [Dv_mul, hy.1, hy.2, mul_zero, zero_mul, add_zero]⟩

lemma castAdd_ne_natAdd (a : Fin m) (i : Fin n) : Fin.castAdd n a ≠ Fin.natAdd m i := by
  intro h; have := congrArg Fin.val h; simp at this; omega

lemma isUnit_φ_h : IsUnit (S.φ S.h) := by
  rw [S.φ_h]; exact IsLocalization.Away.algebraMap_isUnit _

/-- **The vector fields are tangent to `V(G)`**: `Dᵢ g = 0` on `D(h)` for `g ∈ G`. -/
lemma Dv_G (i : Fin n) {g : MvPolynomial (Fin (m + n)) ℤ} (hg : g ∈ G) : S.Dv i g = 0 := by
  have hgG : S.φ g = 0 := S.φ_eq_zero (Ideal.subset_span hg)
  have hv := S.vanish_of_mem_lspan i (L := List.ofFn fun a : Fin m => S.F (Fin.castAdd n a))
    (fun l hl => by
      obtain ⟨a, rfl⟩ := List.mem_ofFn.1 hl
      exact ⟨S.φ_eq_zero (S.eqmem a), by rw [Dv_F, if_neg (castAdd_ne_natAdd a i)]⟩)
    (S.genc g hg)
  rw [Dv_mul, hgG, zero_mul, add_zero, map_pow] at hv
  exact ((S.isUnit_φ_h.pow S.f).mul_right_eq_zero).1 hv.2

/-- The derivative along `v i` of a rational polynomial. -/
def DQ (i : Fin n) (p : MvPolynomial (Fin (m + n)) ℚ) : S.Loc :=
  ∑ k, S.v i k * S.img (pderiv k p)

lemma DQ_toQZ (i : Fin n) (p : MvPolynomial (Fin (m + n)) ℤ) : S.DQ i (toQZ p) = S.Dv i p := by
  simp only [DQ, Dv, φ, RingHom.comp_apply, toQZ, pderiv_map]

lemma DQ_mul (i : Fin n) (p q : MvPolynomial (Fin (m + n)) ℚ) :
    S.DQ i (p * q) = S.img p * S.DQ i q + S.img q * S.DQ i p := by
  simp only [DQ, Derivation.leibniz, smul_eq_mul, map_add, map_mul, mul_add,
    Finset.sum_add_distrib, Finset.mul_sum]
  congr 1 <;> refine Finset.sum_congr rfl fun k _ => by ring

/-- `p ↦ (p, Dᵢ p)` into the trivial square-zero extension. -/
def Ψ (i : Fin n) : MvPolynomial (Fin (m + n)) ℚ →+* TrivSqZeroExt S.Loc S.Loc where
  toFun p := inl (S.img p) + inr (S.DQ i p)
  map_one' := by ext <;> simp [DQ]
  map_mul' p q := by
    ext
    · simp
    · simp only [snd_mul, fst_add, fst_inl, fst_inr, add_zero, snd_add, snd_inl, snd_inr,
        zero_add, smul_eq_mul, MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op, DQ_mul]
      ring
  map_zero' := by ext <;> simp [DQ]
  map_add' p q := by
    ext
    · simp
    · simp only [snd_add, snd_inl, snd_inr, zero_add, DQ, map_add, mul_add,
        Finset.sum_add_distrib]

@[simp] lemma fst_Ψ (i : Fin n) (p) : (S.Ψ i p).fst = S.img p := by simp [Ψ]
@[simp] lemma snd_Ψ (i : Fin n) (p) : (S.Ψ i p).snd = S.DQ i p := by simp [Ψ]

lemma Ψ_le_ker (i : Fin n) : lspan (G.map toQZ) ≤ RingHom.ker (S.Ψ i) := by
  refine Ideal.span_le.2 ?_
  rintro _ hx
  obtain ⟨g, hg, rfl⟩ := List.mem_map.1 hx
  rw [SetLike.mem_coe, RingHom.mem_ker]
  ext
  · rw [fst_Ψ, fst_zero]; exact S.φ_eq_zero (Ideal.subset_span hg)
  · rw [snd_Ψ, snd_zero, DQ_toQZ]; exact S.Dv_G i hg

/-- `Ψ` on `ℚ[Y]/(G)`. -/
def Ψbar (i : Fin n) : SmoothCert.QB G →+* TrivSqZeroExt S.Loc S.Loc :=
  Ideal.Quotient.lift _ (S.Ψ i) fun _ ha => RingHom.mem_ker.1 (S.Ψ_le_ker i ha)

lemma fst_Ψbar (i : Fin n) (r : SmoothCert.QB G) :
    (S.Ψbar i r).fst = algebraMap (SmoothCert.QB G) S.Loc r := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective r
  rw [Ψbar, Ideal.Quotient.lift_mk, fst_Ψ]; rfl

lemma isUnit_Ψbar_h (i : Fin n) : IsUnit (S.Ψbar i (mkQ G S.h)) := by
  rw [isUnit_iff_isUnit_fst, fst_Ψbar]; exact IsLocalization.Away.algebraMap_isUnit _

/-- `Ψ` on `D(h)`. -/
def L (i : Fin n) : S.Loc →+* TrivSqZeroExt S.Loc S.Loc :=
  IsLocalization.Away.lift (mkQ G S.h) (S.isUnit_Ψbar_h i)

lemma L_algebraMap (i : Fin n) (r : SmoothCert.QB G) :
    S.L i (algebraMap (SmoothCert.QB G) S.Loc r) = S.Ψbar i r :=
  IsLocalization.Away.lift_eq _ _ r

lemma fst_L (i : Fin n) (s : S.Loc) : (S.L i s).fst = s := by
  have : (fstHom S.Loc S.Loc S.Loc).toRingHom.comp (S.L i) = RingHom.id S.Loc :=
    IsLocalization.ringHom_ext (Submonoid.powers (mkQ G S.h)) (RingHom.ext fun r => by
      simp only [RingHom.comp_apply, L_algebraMap, RingHom.id_apply]
      exact S.fst_Ψbar i r)
  exact congrArg (fun f : S.Loc →+* S.Loc => f s) this

/-- `snd ∘ L` as an additive map. -/
def sndL (i : Fin n) : S.Loc →+ S.Loc where
  toFun s := (S.L i s).snd
  map_zero' := by rw [map_zero, snd_zero]
  map_add' s t := by rw [map_add, snd_add]

/-- **The dual derivation** `∂ᵢ` on `D(h)`. -/
def der (i : Fin n) : Derivation ℚ S.Loc S.Loc where
  toFun s := (S.L i s).snd
  map_add' s t := by rw [map_add, snd_add]
  map_smul' q s := map_rat_smul (S.sndL i) q s
  map_one_eq_zero' := by
    change (S.L i 1).snd = 0
    rw [map_one, snd_one]
  leibniz' s t := by
    change (S.L i (s * t)).snd = s • (S.L i t).snd + t • (S.L i s).snd
    rw [map_mul, snd_mul, fst_L, fst_L]
    simp only [smul_eq_mul, MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op]
    ring

lemma der_algebraMap_mkQ (i : Fin n) (p : MvPolynomial (Fin (m + n)) ℤ) :
    S.der i (algebraMap (SmoothCert.QB G) S.Loc (mkQ G p)) = S.Dv i p := by
  change (S.L i _).snd = _
  rw [L_algebraMap, Ψbar, Ideal.Quotient.lift_mk, snd_Ψ, DQ_toQZ]

/-- The chart coordinates. -/
abbrev xc (b : Fin n) : S.Loc := algebraMap (SmoothCert.QB G) S.Loc (mkQ G (S.F (Fin.natAdd m b)))

lemma der_xc (i b : Fin n) : S.der i (S.xc b) = if i = b then 1 else 0 := by
  rw [der_algebraMap_mkQ, Dv_F]
  by_cases h : i = b
  · subst h; simp
  · rw [if_neg (fun h' => h ((Fin.natAdd_inj m).1 h').symm), if_neg h]

section Zero

variable {M : Type*} [AddCommGroup M] [Module S.Loc M] [Module ℚ M] [IsScalarTower ℚ S.Loc M]

lemma img_C (a : ℚ) : S.img (C a) = algebraMap ℚ S.Loc a := by
  rw [IsScalarTower.algebraMap_apply ℚ (SmoothCert.QB G) S.Loc]
  rfl

/-- The chain rule on `D(h)`. -/
lemma img_formula (δ : Derivation ℚ S.Loc M) (p : MvPolynomial (Fin (m + n)) ℚ) :
    δ (S.img p) = ∑ k, S.img (pderiv k p) • δ (S.img (X k)) := by
  induction p using MvPolynomial.induction_on with
  | C a => rw [img_C, Derivation.map_algebraMap]; simp [pderiv_C]
  | add p q hp hq =>
    rw [map_add, map_add, hp, hq, ← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun k _ => by rw [map_add, map_add, add_smul]
  | mul_X p k hp =>
    have hX : ∑ j, S.img (pderiv j (X k)) • δ (S.img (X j)) = δ (S.img (X k)) := by
      rw [Finset.sum_eq_single k (fun j _ hj => by rw [pderiv_X_of_ne (Ne.symm hj), map_zero,
        zero_smul]) (fun h => absurd (Finset.mem_univ k) h), pderiv_X_self, map_one, one_smul]
    rw [map_mul, Derivation.leibniz, hp, ← hX]
    simp only [Derivation.leibniz, smul_eq_mul, map_add, map_mul, add_smul, mul_smul,
      Finset.sum_add_distrib, Finset.smul_sum]

/-- **A derivation on `D(h)` vanishing on the coordinates is zero.** -/
theorem derivation_eq_zero (δ : Derivation ℚ S.Loc M) (hδ : ∀ b, δ (S.xc b) = 0) : δ = 0 := by
  set w : Fin (m + n) → M := fun k => δ (S.img (X k))
  have hφ : ∀ p : MvPolynomial (Fin (m + n)) ℤ, δ (S.φ p) = ∑ k, S.φ (pderiv k p) • w k :=
    fun p => by
      rw [φ, RingHom.comp_apply, img_formula]
      exact Finset.sum_congr rfl fun k _ => by
        show S.img (pderiv k (MvPolynomial.map (Int.castRingHom ℚ) p)) • _ = _
        rw [pderiv_map]; rfl
  have hJw : ∀ a, ∑ k, S.JS a k • w k = 0 := fun a => by
    have h0 : δ (S.φ (S.F a)) = 0 := by
      induction a using Fin.addCases with
      | left a => rw [S.φ_eq_zero (S.eqmem a), map_zero]
      | right b => exact hδ b
    rw [hφ] at h0
    exact h0
  have hw : ∀ k, w k = 0 := fun k => by
    calc w k = ∑ j, (1 : Matrix (Fin (m + n)) (Fin (m + n)) S.Loc) k j • w j := by
            simp [Matrix.one_apply]
      _ = ∑ j, (S.Jinv * S.JS) k j • w j := by rw [Jinv_mul_JS]
      _ = ∑ a, S.Jinv k a • ∑ j, S.JS a j • w j := by
            simp only [Matrix.mul_apply, Finset.sum_smul, Finset.smul_sum, smul_smul]
            exact Finset.sum_comm
      _ = 0 := Finset.sum_eq_zero fun a _ => by rw [hJw a, smul_zero]
  have himg : ∀ p, δ (S.img p) = 0 := fun p => by
    rw [img_formula]; exact Finset.sum_eq_zero fun k _ => by
      rw [show δ (S.img (X k)) = w k from rfl, hw, smul_zero]
  have hR : ∀ r : SmoothCert.QB G, δ (algebraMap _ S.Loc r) = 0 := fun r => by
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective r
    exact himg p
  ext s
  obtain ⟨⟨r, y⟩, rfl⟩ := IsLocalization.mk'_surjective (Submonoid.powers (mkQ G S.h)) s
  have h1 := δ.leibniz (algebraMap _ S.Loc (y : SmoothCert.QB G)) (IsLocalization.mk' S.Loc r y)
  rw [IsLocalization.mk'_spec', hR, hR, smul_zero, add_zero] at h1
  rw [Derivation.zero_apply]
  exact ((IsLocalization.map_units (M := Submonoid.powers (mkQ G S.h)) S.Loc y).smul_left_cancel).1
    (by rw [← h1, smul_zero])

end Zero

/-- **The chart of a certified square piece** on `D(h)`. -/
def chart : Principalization.Chart S.Loc n where
  x := S.xc
  d := S.der
  d_x := S.der_xc
  span := by
    set N := Submodule.span S.Loc (Set.range fun i => KaehlerDifferential.D ℚ S.Loc (S.xc i))
    have h0 : N.mkQ.compDer (KaehlerDifferential.D ℚ S.Loc) = 0 :=
      S.derivation_eq_zero _ fun b => by
        change N.mkQ (KaehlerDifferential.D ℚ S.Loc (S.xc b)) = 0
        rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
        exact Submodule.subset_span ⟨b, rfl⟩
    rw [eq_top_iff, ← KaehlerDifferential.span_range_derivation, Submodule.span_le]
    rintro _ ⟨s, rfl⟩
    have : N.mkQ (KaehlerDifferential.D ℚ S.Loc s) = 0 :=
      congrArg (fun d : Derivation ℚ S.Loc (_ ⧸ N) => d s) h0
    rwa [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero] at this

@[simp] lemma chart_x (b : Fin n) :
    S.chart.x b = algebraMap (SmoothCert.QB G) S.Loc (mkQ G (S.F (Fin.natAdd m b))) := rfl

lemma chart_d (i : Fin n) : S.chart.d i = S.der i := rfl

end SquarePiece

namespace SmoothCert

/-- **The chart of piece `k` at a prime `𝔭` avoiding `h_k`.** -/
def chartAt (hG : SmoothCert m n G) (k : Fin hG.K) (𝔭 : Ideal (SmoothCert.QB G)) [𝔭.IsPrime]
    (hk : SquarePiece.mkQ G (hG.P k).h ∉ 𝔭) : Principalization.Chart (Localization.AtPrime 𝔭) n :=
  have hle : Submonoid.powers (SquarePiece.mkQ G (hG.P k).h) ≤ 𝔭.primeCompl :=
    (Submonoid.powers_le).2 hk
  letI := IsLocalization.localizationAlgebraOfSubmonoidLe (hG.P k).Loc (Localization.AtPrime 𝔭) _ _ hle
  haveI := IsLocalization.localization_isScalarTower_of_submonoid_le (hG.P k).Loc (Localization.AtPrime 𝔭) _ _ hle
  haveI := IsLocalization.isLocalization_of_submonoid_le (hG.P k).Loc (Localization.AtPrime 𝔭) _ _ hle
  haveI : IsScalarTower ℚ (hG.P k).Loc (Localization.AtPrime 𝔭) :=
    IsScalarTower.of_algebraMap_eq fun q => by
      have := RingHom.ext_rat (algebraMap ℚ (Localization.AtPrime 𝔭))
        ((algebraMap (hG.P k).Loc (Localization.AtPrime 𝔭)).comp (algebraMap ℚ (hG.P k).Loc))
      exact congrArg (fun f : ℚ →+* Localization.AtPrime 𝔭 => f q) this
  (hG.P k).chart.localization (𝔭.primeCompl.map (algebraMap _ (hG.P k).Loc))

end SmoothCert

end BezoutCounterexample.Constructive
