import Mathlib
import BezoutCounterexample.Principalization.ReesGlobal
import BezoutCounterexample.Principalization.MaxLocusPt

/-!
# Elements of `F_j` as combinations of generator monomials (bridge (e), Rees part)

For the component filtration and a family `g : ι → A` of degrees `deg : ι → ℤ` containing all the
Rees generators (`C g T^j`, `g ∈ gensF j`, `1 ≤ j ≤ d`): every `z ∈ F_j` (`j ≥ 1`) lies in
`RI j = (Π gᵢ^{γᵢ} : γ·deg ≥ j, γ ≠ 0)` (`mem_RI_of_mem_F`). The Rees algebra is generated by
`T⁻¹` and the `C g T^j` (`reesAlg_eq_adjoin`); the coefficients of positive degree of elements of
the algebra they generate lie in the `RI`, by induction on the adjoin.
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open LaurentPolynomial

section RI

variable {A : Type*} [CommRing A] {ι : Type*} [Fintype ι] (g : ι → A) (deg : ι → ℤ)

/-- The ideal of generator monomials of degree `≥ k`. -/
def RI (k : ℤ) : Ideal A :=
  Ideal.span {z | ∃ γ : ι → ℕ, k ≤ ∑ i, (γ i : ℤ) * deg i ∧ ∑ i, γ i ≠ 0 ∧ z = ∏ i, g i ^ γ i}

lemma RI_anti {k k' : ℤ} (h : k ≤ k') : RI g deg k' ≤ RI g deg k :=
  Ideal.span_mono fun _ ⟨γ, hγ, hne, hz⟩ => ⟨γ, h.trans hγ, hne, hz⟩

lemma RI_mul (a b : ℤ) : RI g deg a * RI g deg b ≤ RI g deg (a + b) := by
  rw [RI, RI, Ideal.span_mul_span']
  refine Ideal.span_mono ?_
  rintro _ ⟨x, ⟨γ, hγ, hne, rfl⟩, y, ⟨γ', hγ', hne', rfl⟩, rfl⟩
  refine ⟨γ + γ', ?_, ?_, ?_⟩
  · simp only [Pi.add_apply, Nat.cast_add, add_mul, Finset.sum_add_distrib]; omega
  · simp only [Pi.add_apply, Finset.sum_add_distrib]; omega
  · simp only [Pi.add_apply, pow_add, Finset.prod_mul_distrib]

lemma single_mem_RI (i : ι) [DecidableEq ι] {k : ℤ} (hk : k ≤ deg i) : g i ∈ RI g deg k := by
  refine Ideal.subset_span ⟨Pi.single i 1, ?_, ?_, ?_⟩
  · rw [Finset.sum_eq_single i]
    · simpa using hk
    · intro j _ hj; simp [Pi.single_apply, hj]
    · simp
  · rw [Finset.sum_eq_single i] <;> simp [Pi.single_apply]
  · rw [Finset.prod_eq_single i]
    · simp
    · intro j _ hj; simp [Pi.single_apply, hj]
    · simp

/-- The predicate: coefficients of positive degree lie in the `RI`. -/
def PosRI (p : A[T;T⁻¹]) : Prop := ∀ k : ℤ, 1 ≤ k → p.coeff k ∈ RI g deg k

lemma posRI_mul {p q : A[T;T⁻¹]} (hp : PosRI g deg p) (hq : PosRI g deg q) :
    PosRI g deg (p * q) := by
  classical
  intro k hk
  rw [AddMonoidAlgebra.coeff_mul]
  simp only [Finsupp.sum]
  refine Ideal.sum_mem _ fun a _ => Ideal.sum_mem _ fun b _ => ?_
  split_ifs with h
  · subst h
    rcases le_or_gt 1 a with ha | ha
    · rcases le_or_gt 1 b with hb | hb
      · exact RI_mul g deg a b (Ideal.mul_mem_mul (hp a ha) (hq b hb))
      · exact RI_anti g deg (by omega) (Ideal.mul_mem_right _ _ (hp a ha))
    · exact RI_anti g deg (by omega) (Ideal.mul_mem_left _ _ (hq b (by omega)))
  · exact zero_mem _

end RI

section Comp

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  [IsNoetherianRing A] [Fact (Constructive.HasPres A)] [Constructive.Enum A] {I : Ideal A} (hI : I ≠ ⊥) {v₀ : ℕ → ℚ}
  (hmax : IsMaxInvPt I v₀)
  {𝔭 : Ideal A} (h𝔭 : LocusComp I v₀ 𝔭) (d : ℕ) (hd : 0 < d)
  (hw : ∀ i, ∃ w : ℕ, (w : ℚ) = d * v₀ i)
  {ι : Type*} [Fintype ι] [DecidableEq ι] (g : ι → A) (deg : ι → ℤ)
  (hgen : ∀ j : ℤ, 1 ≤ j → j ≤ d → ∀ x ∈ gensF hI hmax h𝔭 d j, ∃ i, g i = x ∧ deg i = j)
include hd hw hgen

/-- **Elements of `F_j` are combinations of generator monomials of degree `≥ j`.** -/
theorem mem_RI_of_mem_F [Fact (Constructive.HasPres A)] {j : ℤ} (hj : 1 ≤ j) {z : A} (hz : z ∈ (compFil hI hmax h𝔭 d).F j) :
    z ∈ RI g deg j := by
  have hmem : LaurentPolynomial.C z * T j ∈ ReesAlg (compFil hI hmax h𝔭 d) :=
    C_mul_T_mem_ReesAlg hz
  rw [reesAlg_eq_adjoin hI hmax h𝔭 d hd hw] at hmem
  have key : PosRI g deg (LaurentPolynomial.C z * T j) := by
    refine Algebra.adjoin_induction (p := fun p _ => PosRI g deg p) ?_ ?_ ?_ ?_ hmem
    · intro x hx k hk
      rcases hx with hx | hx
      · rw [Set.mem_singleton_iff] at hx
        subst hx
        have : (T (-1) : A[T;T⁻¹]) = LaurentPolynomial.C 1 * T (-1) := by simp
        rw [this, coeff_C_mul_T, if_neg (by omega)]
        exact zero_mem _
      · simp only [Set.mem_iUnion, Set.mem_image] at hx
        obtain ⟨j', hj', x', hx', rfl⟩ := hx
        rw [coeff_C_mul_T]
        split_ifs with hkj
        · subst hkj
          obtain ⟨hj1, hjd⟩ := Finset.mem_Icc.1 hj'
          obtain ⟨i, hi, hdeg⟩ := hgen k hj1 hjd x' hx'
          rw [← hi]
          exact single_mem_RI g deg i hdeg.ge
        · exact zero_mem _
    · intro a k hk
      have : algebraMap A A[T;T⁻¹] a = LaurentPolynomial.C a * T 0 := by
        rw [T_zero, mul_one, LaurentPolynomial.C_eq_algebraMap]
      rw [this, coeff_C_mul_T, if_neg (by omega)]
      exact zero_mem _
    · intro p q _ _ hp hq k hk
      rw [AddMonoidAlgebra.coeff_add, Finsupp.add_apply]
      exact add_mem (hp k hk) (hq k hk)
    · intro p q _ _ hp hq
      exact posRI_mul g deg hp hq
  have := key j hj
  rwa [coeff_C_mul_T, if_pos rfl] at this

end Comp

end BezoutCounterexample.Principalization
