import Mathlib

/-!
# Charts on `ℚ`-algebras

A *chart* is a family `x : Fin n → R` whose differentials span `Ω[R⁄ℚ]`, with dual derivations
`∂ᵢ`.  We construct commuting multi-index derivatives `∂^β`, divided derivatives `∂^[β]`, the
formal Taylor expansion `taylor : R →+* R⟦X⟧` (a ring homomorphism, proved via flat sections of
`∂/∂Xᵢ - ∂ᵢ`), chart changes by an invertible Jacobian, and transport to localizations.

Foundations for Theorem 3.3 (`thm:invariant`) of the paper.
-/

noncomputable section


namespace BezoutCounterexample.Principalization

open MvPowerSeries

/-- A *chart* on a `ℚ`-algebra: `n` functions `x i` whose differentials span `Ω[R⁄ℚ]`, with
dual derivations `d i` (`d i (x j) = δᵢⱼ`). -/
structure Chart (R : Type*) [CommRing R] [Algebra ℚ R] (n : ℕ) where
  x : Fin n → R
  d : Fin n → Derivation ℚ R R
  d_x : ∀ i j, d i (x j) = if i = j then 1 else 0
  span : Submodule.span R (Set.range fun i => KaehlerDifferential.D ℚ R (x i)) = ⊤

namespace Chart

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ} (c : Chart R n)

/-- Derivations (into any module) are determined by their values on the chart functions. -/
lemma derivation_ext {M : Type*} [AddCommGroup M] [Module R M] [Module ℚ M]
    [IsScalarTower ℚ R M] {δ δ' : Derivation ℚ R M} (h : ∀ i, δ (c.x i) = δ' (c.x i)) :
    δ = δ' := by
  have hL : δ.liftKaehlerDifferential = δ'.liftKaehlerDifferential := by
    apply LinearMap.ext_on_range c.span
    intro i
    simp only [Derivation.liftKaehlerDifferential_comp_D, h]
  rw [← Derivation.liftKaehlerDifferential_comp δ, ← Derivation.liftKaehlerDifferential_comp δ',
    hL]

lemma ext (δ : Derivation ℚ R R) (h : ∀ i, δ (c.x i) = 0) : δ = 0 :=
  c.derivation_ext fun i => by rw [h i, Derivation.zero_apply]

lemma d_x_self (i : Fin n) : c.d i (c.x i) = 1 := by simp [c.d_x]

lemma d_x_ne {i j : Fin n} (h : i ≠ j) : c.d i (c.x j) = 0 := by simp [c.d_x, h]

omit [Algebra ℚ R] in
lemma _root_.Derivation.sum_apply' {S : Type*} [CommRing S] [Algebra S R] {ι : Type*}
    (s : Finset ι) (D : ι → Derivation S R R) (a : R) : (∑ i ∈ s, D i) a = ∑ i ∈ s, D i a := by
  rw [← Derivation.coeFnAddMonoidHom_apply, map_sum, Finset.sum_apply]
  rfl

/-- Every derivation is a combination of the chart derivations. -/
lemma eq_sum (δ : Derivation ℚ R R) : δ = ∑ i, δ (c.x i) • c.d i := by
  rw [← sub_eq_zero]
  refine c.ext _ fun j => ?_
  rw [Derivation.coe_sub, Pi.sub_apply, Derivation.sum_apply']
  simp only [Derivation.smul_apply, c.d_x, smul_eq_mul, mul_ite, mul_one, mul_zero,
    Finset.sum_ite_eq', Finset.mem_univ, ite_true, sub_self]

/-- The chart derivations commute. -/
lemma comm (i j : Fin n) (f : R) : c.d i (c.d j f) = c.d j (c.d i f) := by
  have h : ⁅c.d i, c.d j⁆ = 0 := c.ext _ fun l => by
    rw [Derivation.commutator_apply, c.d_x, c.d_x]
    split_ifs <;> simp
  have := congrArg (fun δ : Derivation ℚ R R => δ f) h
  simpa [Derivation.commutator_apply, sub_eq_zero] using this

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries

namespace Chart

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ} (c : Chart R n)

/-- The chart derivations as linear endomorphisms. -/
def dl (i : Fin n) : Module.End ℚ R := (c.d i : R →ₗ[ℚ] R)

@[simp] lemma dl_apply (i : Fin n) (f : R) : c.dl i f = c.d i f := rfl

lemma dl_comm (i j : Fin n) : Commute (c.dl i) (c.dl j) := LinearMap.ext fun f => c.comm i j f

lemma range_dl_pairwise : (Set.range c.dl).Pairwise Commute := by
  rintro _ ⟨i, rfl⟩ _ ⟨j, rfl⟩ _
  exact c.dl_comm i j

/-- The commutative subalgebra of endomorphisms generated by the chart derivations. -/
abbrev DA : Subalgebra ℚ (Module.End ℚ R) := Algebra.adjoin ℚ (Set.range c.dl)

open scoped IsMulCommutative in
instance : CommRing c.DA :=
  have := Algebra.isMulCommutative_adjoin ℚ c.range_dl_pairwise
  inferInstance

/-- `∂ᵢ` as an element of `DA`. -/
def dd (i : Fin n) : c.DA := ⟨c.dl i, Algebra.subset_adjoin ⟨i, rfl⟩⟩

/-- `∂^β = ∏ ∂ᵢ^{βᵢ}`. -/
def dpow (β : Fin n →₀ ℕ) : c.DA := ∏ i, c.dd i ^ β i

lemma dpow_zero : c.dpow 0 = 1 := by simp [dpow]

lemma dpow_add (β γ : Fin n →₀ ℕ) : c.dpow (β + γ) = c.dpow β * c.dpow γ := by
  simp only [dpow, Finsupp.add_apply, pow_add, Finset.prod_mul_distrib]

lemma dpow_single (i : Fin n) (k : ℕ) : c.dpow (Finsupp.single i k) = c.dd i ^ k := by
  rw [dpow, Finset.prod_eq_single i]
  · rw [Finsupp.single_eq_same]
  · intro j _ hj; rw [Finsupp.single_apply, ite_eq_right (Ne.symm hj), pow_zero]
  · intro h; exact absurd (Finset.mem_univ i) h

/-- Multi-index derivative `∂^β f`. -/
def D (β : Fin n →₀ ℕ) (f : R) : R := ((c.dpow β : c.DA) : Module.End ℚ R) f

lemma D_zero (f : R) : c.D 0 f = f := by
  simp only [D, dpow_zero]; rfl

lemma D_add_single (β : Fin n →₀ ℕ) (i : Fin n) (f : R) :
    c.D (β + Finsupp.single i 1) f = c.d i (c.D β f) := by
  simp only [D, dpow_add, dpow_single, pow_one, mul_comm (c.dpow β)]
  rfl

lemma D_map_add (β : Fin n →₀ ℕ) (f g : R) : c.D β (f + g) = c.D β f + c.D β g := map_add _ _ _

omit [Algebra ℚ R] in
lemma _root_.BezoutCounterexample.Principalization.fact_add_single (β : Fin n →₀ ℕ) (i : Fin n) :
    ∏ j, ((β + Finsupp.single i 1 : Fin n →₀ ℕ) j).factorial =
      (∏ j, (β j).factorial) * (β i + 1) := by
  rw [← Finset.mul_prod_erase _ _ (Finset.mem_univ i),
    ← Finset.mul_prod_erase _ (fun j => (β j).factorial) (Finset.mem_univ i)]
  rw [Finset.prod_congr rfl fun j hj => by
    rw [Finsupp.add_apply, Finsupp.single_apply, ite_eq_right (Finset.ne_of_mem_erase hj).symm, add_zero]]
  simp only [Finsupp.add_apply, Finsupp.single_eq_same, Nat.factorial_succ]
  ring

/-- Divided derivative `∂^[β] f = (β!)⁻¹ ∂^β f`. -/
def Dv (β : Fin n →₀ ℕ) (f : R) : R := (((∏ i, (β i).factorial : ℕ) : ℚ)⁻¹) • c.D β f

lemma Dv_zero (f : R) : c.Dv 0 f = f := by simp [Dv, D_zero]

lemma d_Dv (β : Fin n →₀ ℕ) (i : Fin n) (f : R) :
    c.d i (c.Dv β f) = ((β i + 1 : ℕ) : ℚ) • c.Dv (β + Finsupp.single i 1) f := by
  simp only [Dv, Derivation.map_smul, D_add_single, fact_add_single, smul_smul]
  congr 1
  have h1 : ((∏ j, (β j).factorial : ℕ) : ℚ) ≠ 0 := by
    exact_mod_cast (Finset.prod_pos fun i _ => Nat.factorial_pos (β i)).ne'
  have h2 : ((β i + 1 : ℕ) : ℚ) ≠ 0 := by positivity
  push_cast
  field_simp

lemma Dv_map_add (β : Fin n →₀ ℕ) (f g : R) : c.Dv β (f + g) = c.Dv β f + c.Dv β g := by
  simp [Dv, D_map_add, smul_add]

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

/-- A power series from its coefficient function. -/
def mkPS (f : (Fin n →₀ ℕ) → R) : MvPowerSeries (Fin n) R := f

omit [Algebra ℚ R] in
@[simp] lemma coeff_mkPS (f : (Fin n →₀ ℕ) → R) (β : Fin n →₀ ℕ) : coeff β (mkPS f) = f β := rfl

/-- Coefficientwise application of a derivation to a power series. -/
def mapD (δ : Derivation ℚ R R) :
    Derivation ℚ (MvPowerSeries (Fin n) R) (MvPowerSeries (Fin n) R) where
  toFun Φ := mkPS fun β => δ (coeff β Φ)
  map_add' Φ Ψ := by ext β; simp
  map_smul' a Φ := by ext β; simp
  map_one_eq_zero' := by
    ext β
    simp only [LinearMap.coe_mk, AddHom.coe_mk, coeff_mkPS, coeff_one, map_zero]
    split_ifs <;> simp
  leibniz' Φ Ψ := by
    classical
    ext β
    simp only [LinearMap.coe_mk, AddHom.coe_mk, smul_eq_mul, map_add, coeff_mkPS]
    rw [mul_comm Ψ, coeff_mul, coeff_mul, coeff_mul, map_sum, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun p _ => ?_
    rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    simp only [coeff_mkPS]
    ring

@[simp] lemma coeff_mapD (δ : Derivation ℚ R R) (Φ : MvPowerSeries (Fin n) R) (β : Fin n →₀ ℕ) :
    coeff β (mapD δ Φ) = δ (coeff β Φ) := rfl

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

namespace Chart

variable (c : Chart R n)

/-- The flatness operator `Eᵢ = ∂/∂Xᵢ - ∂ᵢ` on power series with coefficients in `R`. -/
def E (i : Fin n) : Derivation ℚ (MvPowerSeries (Fin n) R) (MvPowerSeries (Fin n) R) :=
  (MvPowerSeries.pderiv i).restrictScalars ℚ - mapD (c.d i)

lemma coeff_E (i : Fin n) (Φ : MvPowerSeries (Fin n) R) (β : Fin n →₀ ℕ) :
    coeff β (c.E i Φ) = coeff (β + Finsupp.single i 1) Φ * (β i + 1) - c.d i (coeff β Φ) := by
  simp only [E, Derivation.coe_sub, Pi.sub_apply, map_sub, coeff_mapD,
    Derivation.coe_restrictScalars, coeff_pderiv]

/-- The formal Taylor expansion `f ↦ ∑ ∂^[β] f · X^β`. -/
def taylorFun (f : R) : MvPowerSeries (Fin n) R := mkPS fun β => c.Dv β f

@[simp] lemma coeff_taylorFun (f : R) (β : Fin n →₀ ℕ) : coeff β (c.taylorFun f) = c.Dv β f := rfl

lemma natCast_add_one_isUnit (k : ℕ) : IsUnit ((k : R) + 1) := by
  have : ((k : R) + 1) = algebraMap ℚ R ((k : ℚ) + 1) := by simp
  rw [this]
  exact (IsUnit.mk0 _ (by positivity)).map _

lemma E_taylorFun (i : Fin n) (f : R) : c.E i (c.taylorFun f) = 0 := by
  ext β
  rw [coeff_E, coeff_taylorFun, coeff_taylorFun, d_Dv, map_zero, sub_eq_zero]
  rw [Algebra.smul_def, mul_comm]
  congr 1
  simp

/-- A nonzero multi-index has a nonzero entry (a decided search over `Fin n`). -/
theorem _root_.BezoutCounterexample.Principalization.finsupp_exists_ne_zero {n : ℕ}
    {β : Fin n →₀ ℕ} (hβ : β ≠ 0) : ∃ i, β i ≠ 0 :=
  (Decidable.em (∃ i, β i ≠ 0)).resolve_right fun h =>
    hβ (Finsupp.ext fun i => Decidable.not_not.1 fun hi => h ⟨i, hi⟩)

/-- A flat power series with vanishing constant coefficient vanishes. -/
lemma eq_zero_of_flat {Φ : MvPowerSeries (Fin n) R} (hΦ : ∀ i, c.E i Φ = 0)
    (h0 : constantCoeff Φ = 0) : Φ = 0 := by
  ext β
  rw [map_zero]
  induction β using WellFoundedLT.induction with
  | ind β ih =>
    by_cases hβ : β = 0
    · subst hβ; rw [coeff_zero_eq_constantCoeff_apply, h0]
    · obtain ⟨i, hi⟩ := finsupp_exists_ne_zero hβ
      set β' := β - Finsupp.single i 1 with hβ'
      have hsum : β' + Finsupp.single i 1 = β := by
        ext j
        simp only [hβ', Finsupp.coe_add, Finsupp.coe_tsub, Pi.add_apply, Pi.sub_apply,
          Finsupp.single_apply]
        split_ifs with h
        · subst h; omega
        · omega
      have hlt : β' < β := by
        rw [← hsum]
        exact lt_add_of_pos_right _ (lt_of_le_of_ne zero_le
          (Ne.symm (Finsupp.single_ne_zero.2 one_ne_zero)))
      have h1 := congrArg (coeff β') (hΦ i)
      rw [coeff_E, map_zero, ih β' hlt, map_zero, sub_zero, hsum] at h1
      exact (natCast_add_one_isUnit (β' i)).mul_left_eq_zero.1 h1

lemma constantCoeff_taylorFun (f : R) : constantCoeff (c.taylorFun f) = f := by
  rw [← coeff_zero_eq_constantCoeff_apply, coeff_taylorFun, Dv_zero]

lemma taylorFun_add (f g : R) : c.taylorFun (f + g) = c.taylorFun f + c.taylorFun g := by
  ext β; simp [Dv_map_add]

/-- The formal Taylor expansion is a ring homomorphism. -/
def taylor : R →+* MvPowerSeries (Fin n) R where
  toFun := c.taylorFun
  map_one' := by
    rw [← sub_eq_zero]
    refine c.eq_zero_of_flat (fun i => ?_) ?_
    · rw [map_sub, E_taylorFun, Derivation.map_one_eq_zero, sub_zero]
    · rw [map_sub, constantCoeff_taylorFun, map_one, sub_self]
  map_mul' f g := by
    rw [← sub_eq_zero]
    refine c.eq_zero_of_flat (fun i => ?_) ?_
    · rw [map_sub, E_taylorFun, Derivation.leibniz, E_taylorFun, E_taylorFun, smul_zero,
        smul_zero, add_zero, sub_zero]
    · rw [map_sub, map_mul, constantCoeff_taylorFun, constantCoeff_taylorFun,
        constantCoeff_taylorFun, sub_self]
  map_zero' := by ext β; simp [Dv, D]
  map_add' := c.taylorFun_add

@[simp] lemma coeff_taylor (f : R) (β : Fin n →₀ ℕ) : coeff β (c.taylor f) = c.Dv β f := rfl

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

@[simp] lemma mapD_C (δ : Derivation ℚ R R) (a : R) :
    mapD δ (C a : MvPowerSeries (Fin n) R) = C (δ a) := by
  ext β; simp only [coeff_mapD, coeff_C]; split_ifs <;> simp

@[simp] lemma mapD_X (δ : Derivation ℚ R R) (j : Fin n) :
    mapD δ (X j : MvPowerSeries (Fin n) R) = 0 := by
  ext β; simp only [coeff_mapD, coeff_X, map_zero]; split_ifs <;> simp

namespace Chart

variable (c : Chart R n)

/-- A flat power series is the Taylor expansion of its constant coefficient. -/
lemma taylor_eq_of_flat {Φ : MvPowerSeries (Fin n) R} (hΦ : ∀ i, c.E i Φ = 0) :
    c.taylor (constantCoeff Φ) = Φ := by
  rw [← sub_eq_zero]
  refine c.eq_zero_of_flat (fun i => ?_) ?_
  · rw [map_sub, hΦ, sub_zero]; exact c.E_taylorFun i _
  · rw [map_sub, ← coeff_zero_eq_constantCoeff_apply (c.taylor _), coeff_taylor, Dv_zero,
      sub_self]

lemma taylor_x (j : Fin n) : c.taylor (c.x j) = C (c.x j) + X j := by
  have h := c.taylor_eq_of_flat (Φ := C (c.x j) + X j) fun i => by
    rw [E, Derivation.coe_sub, Pi.sub_apply, map_add, map_add, mapD_C, mapD_X, c.d_x]
    simp only [Derivation.coe_restrictScalars, pderiv_C, zero_add, add_zero, pderiv_X]
    split_ifs with h
    · subst h; simp
    · simp [Ne.symm h]
  rwa [map_add, constantCoeff_C, constantCoeff_X, add_zero] at h

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

namespace Chart

variable (c : Chart R n)

omit [Algebra ℚ R] in
lemma _root_.Derivation.sum_apply'' {S M : Type*} [CommRing S] [Algebra S R] [AddCommGroup M]
    [Module R M] [Module S M] {ι : Type*} (s : Finset ι) (D : ι → Derivation S R M) (a : R) :
    (∑ i ∈ s, D i) a = ∑ i ∈ s, D i a := by
  rw [← Derivation.coeFnAddMonoidHom_apply, map_sum, Finset.sum_apply]
  rfl

/-- The chain rule in `Ω[R⁄ℚ]`: `df = ∑ (∂ᵢ f) dxᵢ`. -/
lemma kD_eq_sum (f : R) :
    KaehlerDifferential.D ℚ R f = ∑ i, c.d i f • KaehlerDifferential.D ℚ R (c.x i) := by
  have : KaehlerDifferential.D ℚ R = ∑ i,
      (LinearMap.toSpanSingleton R _ (KaehlerDifferential.D ℚ R (c.x i))).compDer (c.d i) := by
    refine c.derivation_ext fun j => ?_
    rw [Derivation.sum_apply'']
    change _ = ∑ i, c.d i (c.x j) • KaehlerDifferential.D ℚ R (c.x i)
    simp only [c.d_x, ite_smul, one_smul, zero_smul, Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  conv_lhs => rw [this]
  rw [Derivation.sum_apply'']
  rfl

/-- The Jacobian matrix `Jᵢⱼ = ∂ᵢ yⱼ`. -/
def jac (y : Fin n → R) : Matrix (Fin n) (Fin n) R := Matrix.of fun i j => c.d i (y j)

/-- Change of chart to new functions `y` with invertible Jacobian. -/
def change (y : Fin n → R) (hy : IsUnit (c.jac y).det) : Chart R n where
  x := y
  d j := ∑ i, (c.jac y)⁻¹ j i • c.d i
  d_x j l := by
    rw [Derivation.sum_apply']
    simp only [Derivation.smul_apply, smul_eq_mul]
    have h := congrFun (congrFun (Matrix.nonsing_inv_mul (c.jac y) hy) j) l
    rw [Matrix.mul_apply] at h
    rw [show (∑ i, (c.jac y)⁻¹ j i * c.d i (y l)) = ∑ i, (c.jac y)⁻¹ j i * c.jac y i l from rfl,
      h, Matrix.one_apply]
  span := by
    rw [eq_top_iff, ← c.span, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    -- `dxᵢ = ∑ⱼ (J⁻¹)ᵢⱼ dyⱼ`
    have h : KaehlerDifferential.D ℚ R (c.x i) =
        ∑ j, (c.jac y)⁻¹ j i • KaehlerDifferential.D ℚ R (y j) := by
      simp only [c.kD_eq_sum (y _), Finset.smul_sum, smul_smul]
      rw [Finset.sum_comm]
      have hJ := Matrix.mul_nonsing_inv (c.jac y) hy
      rw [Finset.sum_eq_single i]
      · have := congrFun (congrFun hJ i) i
        rw [Matrix.mul_apply, Matrix.one_apply_eq] at this
        rw [← Finset.sum_smul]
        simp only [mul_comm ((c.jac y)⁻¹ _ i)]
        rw [show (∑ j, c.d i (y j) * (c.jac y)⁻¹ j i) = ∑ j, c.jac y i j * (c.jac y)⁻¹ j i from rfl,
          this, one_smul]
      · intro l _ hl
        have := congrFun (congrFun hJ l) i
        rw [Matrix.mul_apply, Matrix.one_apply_ne hl] at this
        rw [← Finset.sum_smul]
        simp only [mul_comm ((c.jac y)⁻¹ _ i)]
        rw [show (∑ j, c.d l (y j) * (c.jac y)⁻¹ j i) = ∑ j, c.jac y l j * (c.jac y)⁻¹ j i from rfl,
          this, zero_smul]
      · simp
    change KaehlerDifferential.D ℚ R (c.x i) ∈ _
    rw [h]
    exact Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨j, rfl⟩)

@[simp] lemma change_x (y : Fin n → R) (hy : IsUnit (c.jac y).det) : (c.change y hy).x = y := rfl

end Chart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open TrivSqZeroExt

section Loc

variable {R S : Type*} [CommRing R] [Algebra ℚ R] [CommRing S] [Algebra ℚ S] [Algebra R S]
  [IsScalarTower ℚ R S] (M : Submonoid R) [IsLocalization M S]

/-- `r ↦ (r, δ r)` as a ring map to the trivial square-zero extension. -/
def derivToTsze (δ : Derivation ℚ R R) : R →+* TrivSqZeroExt S S where
  toFun r := inl (algebraMap R S r) + inr (algebraMap R S (δ r))
  map_one' := by ext <;> simp
  map_mul' r r' := by
    ext
    · simp
    · simp only [snd_mul, fst_add, fst_inl, fst_inr, add_zero, snd_add, snd_inl, snd_inr,
        zero_add, smul_eq_mul, MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op]
      rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, map_add, map_mul, map_mul]; ring
  map_zero' := by ext <;> simp
  map_add' r r' := by
    ext
    · simp only [fst_add, fst_inl, fst_inr, add_zero, map_add]
    · simp only [snd_add, snd_inl, snd_inr, zero_add, map_add]

omit [Algebra ℚ S] [IsScalarTower ℚ R S] in
@[simp] lemma fst_derivToTsze (δ : Derivation ℚ R R) (r : R) :
    (derivToTsze (S := S) δ r).fst = algebraMap R S r := by
  simp [derivToTsze]

omit [Algebra ℚ S] [IsScalarTower ℚ R S] in
@[simp] lemma snd_derivToTsze (δ : Derivation ℚ R R) (r : R) :
    (derivToTsze (S := S) δ r).snd = algebraMap R S (δ r) := by
  simp only [derivToTsze, RingHom.coe_mk, MonoidHom.coe_mk, OneHom.coe_mk, snd_add, snd_inl,
    snd_inr, zero_add]

variable {M} in
omit [Algebra ℚ S] [IsScalarTower ℚ R S] in
lemma derivToTsze_isUnit (δ : Derivation ℚ R R) (m : M) : IsUnit (derivToTsze (S := S) δ m) := by
  rw [isUnit_iff_isUnit_fst, fst_derivToTsze]
  exact IsLocalization.map_units S m

/-- The lift of `derivToTsze δ` to the localization. -/
def liftTsze (δ : Derivation ℚ R R) : S →+* TrivSqZeroExt S S :=
  IsLocalization.lift (M := M) (derivToTsze_isUnit δ)

omit [Algebra ℚ S] [IsScalarTower ℚ R S] in
lemma liftTsze_algebraMap (δ : Derivation ℚ R R) (r : R) :
    liftTsze (S := S) M δ (algebraMap R S r) = derivToTsze δ r :=
  IsLocalization.lift_eq _ _

omit [Algebra ℚ S] [IsScalarTower ℚ R S] in
lemma fst_liftTsze (δ : Derivation ℚ R R) (s : S) : (liftTsze M δ s).fst = s := by
  have : (fstHom S S S).toRingHom.comp (liftTsze M δ) = RingHom.id S :=
    IsLocalization.ringHom_ext M (RingHom.ext fun r => by
      simp only [RingHom.comp_apply, liftTsze_algebraMap, RingHom.id_apply]
      exact fst_derivToTsze δ r)
  exact congrArg (fun f : S →+* S => f s) this

/-- Extension of a derivation to a localization. -/
def extLoc (δ : Derivation ℚ R R) : Derivation ℚ S S where
  toFun s := (liftTsze M δ s).snd
  map_add' s t := by simp
  map_smul' q s := by
    change (liftTsze M δ (q • s)).snd = q • (liftTsze M δ s).snd
    rw [Algebra.smul_def, map_mul, snd_mul, fst_liftTsze, smul_eq_mul]
    have h0 : (liftTsze M δ (algebraMap ℚ S q)).snd = 0 := by
      rw [IsScalarTower.algebraMap_apply ℚ R S, liftTsze_algebraMap, snd_derivToTsze,
        Derivation.map_algebraMap, map_zero]
    rw [h0, smul_zero, add_zero, ← Algebra.smul_def]
  map_one_eq_zero' := by
    change (liftTsze M δ 1).snd = 0
    rw [map_one, snd_one]
  leibniz' s t := by
    change (liftTsze M δ (s * t)).snd = s • (liftTsze M δ t).snd + t • (liftTsze M δ s).snd
    rw [map_mul, snd_mul, fst_liftTsze, fst_liftTsze]
    simp only [smul_eq_mul, MulOpposite.smul_eq_mul_unop, MulOpposite.unop_op]
    ring

end Loc

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open TrivSqZeroExt

section Loc

variable {R S : Type*} [CommRing R] [Algebra ℚ R] [CommRing S] [Algebra ℚ S] [Algebra R S]
  [IsScalarTower ℚ R S] (M : Submonoid R) [IsLocalization M S]

lemma extLoc_algebraMap (δ : Derivation ℚ R R) (r : R) :
    extLoc M δ (algebraMap R S r) = algebraMap R S (δ r) := by
  change (liftTsze M δ (algebraMap R S r)).snd = _
  rw [liftTsze_algebraMap, snd_derivToTsze]

variable {n : ℕ}

/-- Transport of a chart to a localization. -/
def Chart.localization (c : Chart R n) : Chart S n where
  x i := algebraMap R S (c.x i)
  d i := extLoc M (c.d i)
  d_x i j := by rw [extLoc_algebraMap, c.d_x]; split_ifs <;> simp
  span := by
    have h := KaehlerDifferential.span_range_map_derivation_of_isLocalization ℚ R S M
    rw [eq_top_iff, ← h, Submodule.span_le]
    rintro _ ⟨r, rfl⟩
    simp only [Function.comp_apply, c.kD_eq_sum r, map_sum, map_smul, KaehlerDifferential.map_D]
    refine Submodule.sum_mem _ fun i _ => ?_
    exact Submodule.smul_of_tower_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

@[simp] lemma Chart.localization_x (c : Chart R n) (i : Fin n) :
    (c.localization (S := S) M).x i = algebraMap R S (c.x i) := rfl

lemma Chart.localization_d (c : Chart R n) (i : Fin n) (r : R) :
    (c.localization (S := S) M).d i (algebraMap R S r) = algebraMap R S (c.d i r) :=
  extLoc_algebraMap M _ r

end Loc

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing

variable {R : Type*} [CommRing R] [Algebra ℚ R] {n : ℕ}

namespace Chart

variable (c : Chart R n)

section Local

variable [IsLocalRing R]

/-- The residual Taylor expansion `f ↦ ∑ (∂^[β] f mod 𝔪) X^β ∈ κ⟦X⟧`. -/
def tau : R →+* MvPowerSeries (Fin n) (ResidueField R) :=
  (MvPowerSeries.map (residue R)).comp c.taylor

@[simp] lemma coeff_tau (f : R) (β : Fin n →₀ ℕ) : coeff β (c.tau f) = residue R (c.Dv β f) := rfl

lemma coeff_tau_eq_zero_iff (f : R) (β : Fin n →₀ ℕ) :
    coeff β (c.tau f) = 0 ↔ c.Dv β f ∈ maximalIdeal R := by
  rw [coeff_tau, residue_eq_zero_iff]

/-- A chart is *centred* if its functions generate the maximal ideal. -/
def IsCentred : Prop := maximalIdeal R = Ideal.span (Set.range c.x)

variable {c}

lemma IsCentred.x_mem (hc : c.IsCentred) (i : Fin n) : c.x i ∈ maximalIdeal R := by
  rw [hc]; exact Ideal.subset_span ⟨i, rfl⟩

lemma IsCentred.tau_x (hc : c.IsCentred) (i : Fin n) : c.tau (c.x i) = X i := by
  rw [tau, RingHom.comp_apply, taylor_x, map_add, map_C, map_X,
    (residue_eq_zero_iff _).2 (hc.x_mem i), map_zero, zero_add]

lemma IsCentred.tau_monomial (hc : c.IsCentred) (α : Fin n →₀ ℕ) :
    c.tau (∏ i, c.x i ^ α i) = monomial α 1 := by
  rw [map_prod]
  simp only [map_pow, hc.tau_x]
  rw [MvPowerSeries.monomial_eq', map_one, one_mul, Finsupp.prod_fintype _ _ (fun i => pow_zero _)]

end Local

end Chart

end BezoutCounterexample.Principalization
