import BezoutCounterexample.Principalization.MaxLocus

/-!
# Finite covers by certified basic opens (leaf; plan `docs/maxlocus-plan.md`, (P1))

`exists_maxInv` (MaxLocus) chooses, for every maximal ideal `𝔪 ⊇ I`, a good `g ∉ 𝔪`
(`choose` over the type of maximal ideals), proves `I ⊔ (g) = ⊤` by Zorn
(`Ideal.exists_le_maximal`), and then decides `g ∈ 𝔪` for the finitely many `g` of a relation
`1 = i + ∑ aₖ gₖ`. Here:

* `CertGen I g` — `D(g)` carries a certificate: an invariant `v` attained at some point of
  `V(I) ∩ D(g)` and bounding the invariant at every point of `D(g)` (the output of
  `invAt_semicont`, kept as a property of `g`; no `choose`);
* `Cert I` — the ideal generated by the certified `g`;
* `NNMax A` — every proper ideal is `¬¬`-contained in a maximal ideal. For a f.t. `ℚ`-algebra this
  is the Nullstellensatz under `¬¬` (`¬¬`-f.g. ideal, a point over a finite extension with a basis,
  `FGKer` for its maximal ideal); `nnMax_of_classical` is the classical source (Zorn) and the one
  place to swap;
* `not_not_one_mem_cert` — `¬¬ (1 ∈ I ⊔ Cert I)`, from `NNMax` and `local_inv` at one point;
* `exists_maxInv_C` — from a cover `1 ∈ I ⊔ Cert I`, `¬¬` a maximal invariant exists, with the
  pointwise bound in the `¬¬`-stable form `¬ (v < v₀)`. No decision of `g ∈ 𝔪` is made: from
  `v < v₀` one gets `¬¬ (gₖ ∈ 𝔪)` for each `k`, contradicting `1 ∉ 𝔪`. The minimum over the cover
  uses only `¬¬`-totality of the lexicographic order (`nn_le_total`);
* `exists_maxInv_NN` — the combination: `NNMax A → ¬¬ ∃ v₀, …`;
* `CertC`, `not_not_one_mem_certC` — the cover of `V(𝔭)` by local data `LocData` (plan Step 2);
* `mem_cRF_of_cover` — **gluing by partition of unity**: membership in all chart ideals of a cover
  `1 = i + ∑ fₖ gₖ` (`i ∈ 𝔭`) gives membership in `cRF I 𝔪' t` at *every* point `𝔪' ⊇ 𝔭`,
  positively: each `gₖ` is in the radical of `{y | y x ∈ cRF}` (spreading), so `(1 - i)ᴷ`, which
  avoids `𝔪'`, lies in it. This sidesteps the double-negation shift;
* `compF_map_C` — `compF_map` from the cover (no `choose`, no Zorn, no `by_contra`; common
  exponent by `exists_uniform`, finite choice by induction); `compF_map_NN` under `¬¬`.
  `exists_pow_mul_mem` (spreading) still uses the Jacobson property (plan (P2)), and `LocData`
  existence still uses `IsNoetherianRing A` for `𝔪.FG` (to be switched to `exists_centred_N`).

Everything downstream is used toward the goal `⊥` (non-EDD is negative), so the `¬¬` costs nothing
there; `not_lt` turns `¬ (v < v₀)` back into `v₀ ≤ v` classically.
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open IsLocalRing IsLocalization

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]

/-- `D(g)` carries a certificate for the invariant of `I`. -/
def CertGen (I : Ideal A) (g : A) : Prop :=
  ∃ v : ℕ → ℚ, (∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal), I ≤ 𝔪 ∧ g ∉ 𝔪 ∧ InvAt I 𝔪 v) ∧
    ∀ (𝔪' : Ideal A) [𝔪'.IsMaximal], g ∉ 𝔪' → ∀ v', InvAt I 𝔪' v' → toLex v ≤ toLex v'

/-- The ideal generated by the certified elements. -/
def Cert (I : Ideal A) : Ideal A := Ideal.span {g | CertGen I g}

/-- Every proper ideal lies, under `¬¬`, in a maximal ideal (the Nullstellensatz under `¬¬` for
f.t. `ℚ`-algebras). -/
def NNMax (A : Type) [CommRing A] : Prop :=
  ∀ K : Ideal A, K ≠ ⊤ → ¬¬ ∃ 𝔪 : Ideal A, 𝔪.IsMaximal ∧ K ≤ 𝔪

/-- Classical source of `NNMax` (Zorn); to be replaced by the Nullstellensatz. -/
theorem nnMax_of_classical (A : Type) [CommRing A] : NNMax A := fun K hK h =>
  h (Ideal.exists_le_maximal K hK)

omit [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A] in
/-- `¬¬`-totality of the lexicographic order on `ℕ → ℚ` (constructively valid: `¬¬` of the
search for the first difference, which is decidable at each index). -/
theorem nn_le_total (a b : Lex (ℕ → ℚ)) : ¬¬ (a ≤ b ∨ b ≤ a) := fun h => h (le_total a b)

/-- **The cover is `¬¬`-total.** -/
theorem not_not_one_mem_cert {I : Ideal A} (hI : I ≠ ⊥) (hNS : NNMax A) :
    ¬¬ ((1 : A) ∈ I ⊔ Cert I) := by
  intro h
  have hne : I ⊔ Cert I ≠ ⊤ := fun ht => h (by rw [ht]; trivial)
  refine hNS _ hne fun ⟨𝔪, h𝔪, hle⟩ => ?_
  have hI𝔪 : I ≤ 𝔪 := le_sup_left.trans hle
  obtain ⟨v, hv⟩ := exists_invAt hI 𝔪 hI𝔪
  obtain ⟨g, hg, hbound⟩ := invAt_semicont hI 𝔪 hI𝔪 hv
  have hcert : CertGen I g := ⟨v, ⟨𝔪, h𝔪, hI𝔪, hg, hv⟩, hbound⟩
  exact hg (hle (le_sup_right (a := I) (Ideal.subset_span hcert)))

omit [IsDomain A] [Algebra.Smooth ℚ A] in
/-- The minimum over a nonempty finite family of certified elements, under `¬¬`. -/
theorem cert_min {I : Ideal A} : ∀ (n : ℕ) (g : Fin (n + 1) → A), (∀ k, CertGen I (g k)) →
    ¬¬ ∃ v₀ : ℕ → ℚ, (∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal), I ≤ 𝔪 ∧ InvAt I 𝔪 v₀) ∧
      ∀ (𝔪 : Ideal A) [𝔪.IsMaximal], ¬ (∀ k, g k ∈ 𝔪) → ∀ v, InvAt I 𝔪 v →
        ¬ toLex v < toLex v₀ := by
  intro n
  induction n with
  | zero =>
    intro g hg hneg
    obtain ⟨v₂, ⟨𝔪₂, h𝔪₂, hI₂, -, hv₂⟩, B₂⟩ := hg 0
    refine hneg ⟨v₂, ⟨𝔪₂, h𝔪₂, hI₂, hv₂⟩, fun 𝔪 _ hn v hv hlt => ?_⟩
    refine (fun h0 : g 0 ∉ 𝔪 => lt_irrefl _ (hlt.trans_le (B₂ 𝔪 h0 v hv))) fun h0 => hn ?_
    intro k
    rwa [Fin.fin_one_eq_zero k]
  | succ n ih =>
    intro g hg hneg
    obtain ⟨v₂, ⟨𝔪₂, h𝔪₂, hI₂, -, hv₂⟩, B₂⟩ := hg 0
    refine ih (fun k => g k.succ) (fun k => hg k.succ) fun ⟨v₁, att₁, bnd₁⟩ => ?_
    -- both halves: `¬¬ (g 0 ∈ 𝔪)` and `¬¬ (∀ k, g k.succ ∈ 𝔪)` contradict `¬ ∀ k, g k ∈ 𝔪`
    have hcomb : ∀ (𝔪 : Ideal A), ¬ (∀ k, g k ∈ 𝔪) → ¬¬ (g 0 ∈ 𝔪) →
        ¬¬ (∀ k : Fin (n + 1), g k.succ ∈ 𝔪) → False := fun 𝔪 hn h0 hr =>
      h0 fun h0 => hr fun hr => hn fun k => Fin.cases h0 hr k
    refine nn_le_total (toLex v₁) (toLex v₂) fun h => ?_
    rcases h with h12 | h21
    · refine hneg ⟨v₁, att₁, fun 𝔪 _ hn v hv hlt => hcomb 𝔪 hn ?_ ?_⟩
      · exact fun h0 => lt_irrefl _ ((hlt.trans_le h12).trans_le (B₂ 𝔪 h0 v hv))
      · exact fun hr => bnd₁ 𝔪 hr v hv hlt
    · refine hneg ⟨v₂, ⟨𝔪₂, h𝔪₂, hI₂, hv₂⟩, fun 𝔪 _ hn v hv hlt => hcomb 𝔪 hn ?_ ?_⟩
      · exact fun h0 => lt_irrefl _ (hlt.trans_le (B₂ 𝔪 h0 v hv))
      · exact fun hr => bnd₁ 𝔪 hr v hv (hlt.trans_le h21)

omit [IsDomain A] [Algebra.Smooth ℚ A] in
/-- **The maximal invariant exists**, from a cover by certified basic opens. No `choose` over
maximal ideals, no Zorn, no decision of membership in a maximal ideal. -/
theorem exists_maxInv_C {I : Ideal A} (hItop : I ≠ ⊤) (hcov : (1 : A) ∈ I ⊔ Cert I) :
    ¬¬ ∃ v₀ : ℕ → ℚ, (∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal), I ≤ 𝔪 ∧ InvAt I 𝔪 v₀) ∧
      ∀ (𝔪 : Ideal A) [𝔪.IsMaximal], I ≤ 𝔪 → ∀ v, InvAt I 𝔪 v → ¬ toLex v < toLex v₀ := by
  obtain ⟨i, hi, y, hy, hiy⟩ := Submodule.mem_sup.1 hcov
  obtain ⟨n, f, g, hfg⟩ := Submodule.mem_span_set'.1 hy
  cases n with
  | zero =>
    rw [Finset.univ_eq_empty, Finset.sum_empty] at hfg
    rw [← hfg, add_zero] at hiy
    exact absurd ((Ideal.eq_top_iff_one I).2 (hiy ▸ hi)) hItop
  | succ n =>
    intro hneg
    refine cert_min n (fun k => (g k).1) (fun k => (g k).2) fun ⟨v₀, att, bnd⟩ => hneg ?_
    refine ⟨v₀, att, fun 𝔪 h𝔪 hI𝔪 v hv => bnd 𝔪 (fun hall => ?_) v hv⟩
    have h1 : (1 : A) ∈ 𝔪 := by
      rw [← hiy, ← hfg]
      exact Ideal.add_mem _ (hI𝔪 hi)
        (Ideal.sum_mem _ fun k _ => by rw [smul_eq_mul]; exact Ideal.mul_mem_left _ _ (hall k))
    exact h𝔪.ne_top ((Ideal.eq_top_iff_one _).2 h1)

/-- **The maximal invariant exists, under `¬¬`**, from `NNMax` alone. -/
theorem exists_maxInv_NN {I : Ideal A} (hI : I ≠ ⊥) (hItop : I ≠ ⊤) (hNS : NNMax A) :
    ¬¬ ∃ v₀ : ℕ → ℚ, (∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal), I ≤ 𝔪 ∧ InvAt I 𝔪 v₀) ∧
      ∀ (𝔪 : Ideal A) [𝔪.IsMaximal], I ≤ 𝔪 → ∀ v, InvAt I 𝔪 v → ¬ toLex v < toLex v₀ :=
  fun h => not_not_one_mem_cert hI hNS fun hcov => exists_maxInv_C hItop hcov h

end BezoutCounterexample.Principalization


/-! ## The component filtration by partition of unity -/

namespace BezoutCounterexample.Principalization

open IsLocalRing IsLocalization

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]

omit [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A] in
/-- Finitely many monotone bounds have a common bound (finite choice, by induction). -/
theorem exists_uniform : ∀ {n : ℕ} (P : Fin n → ℕ → Prop),
    (∀ k N N', N ≤ N' → P k N → P k N') → (∀ k, ∃ N, P k N) → ∃ M, ∀ k, P k M
  | 0, _, _, _ => ⟨0, fun k => k.elim0⟩
  | n + 1, P, hmono, h => by
    obtain ⟨M₁, hM₁⟩ := exists_uniform (fun k => P k.succ) (fun k => hmono k.succ)
      (fun k => h k.succ)
    obtain ⟨M₀, hM₀⟩ := h 0
    refine ⟨max M₀ M₁, fun k => Fin.cases ?_ (fun k => ?_) k⟩
    · exact hmono 0 _ _ (le_max_left _ _) hM₀
    · exact hmono k.succ _ _ (le_max_right _ _) (hM₁ k)

/-- `D(g)` carries local data of the maximal locus at a point of `V(𝔭)`. -/
def CertC (I : Ideal A) (v₀ : ℕ → ℚ) (𝔭 : Ideal A) (g : A) : Prop :=
  ∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal), 𝔭 ≤ 𝔪 ∧ ∃ D : LocData I v₀ 𝔪, D.g = g

/- The component `V(𝔭)` enters only through `hZ`: its points lie in the maximal locus. For a
minimal prime of `locusIdeal` this is `mem_maxLocus_of_minimal hI hmax h𝔭`; for the explicit
components `D.p` it is `LocData.mem_of_le_p_S` (`Components.lean`). -/
variable [IsNoetherianRing A] {I : Ideal A} (hI : I ≠ ⊥) {v₀ : ℕ → ℚ} {𝔭 : Ideal A}
  (hZ : ∀ (𝔪 : Ideal A) [𝔪.IsMaximal], 𝔭 ≤ 𝔪 → I ≤ 𝔪 ∧ InvAt I 𝔪 v₀)
include hI hZ

/-- **The cover of `V(𝔭)` by local data is `¬¬`-total.** -/
theorem not_not_one_mem_certC (hNS : NNMax A) :
    ¬¬ ((1 : A) ∈ 𝔭 ⊔ Ideal.span {g | CertC I v₀ 𝔭 g}) := by
  intro h
  have hne : 𝔭 ⊔ Ideal.span {g | CertC I v₀ 𝔭 g} ≠ ⊤ := fun ht => h (by rw [ht]; trivial)
  refine hNS _ hne fun ⟨𝔪, h𝔪, hle⟩ => ?_
  have h𝔭𝔪 : 𝔭 ≤ 𝔪 := le_sup_left.trans hle
  have hZ := hZ 𝔪 h𝔭𝔪
  obtain ⟨D⟩ := LocData.nonempty hI 𝔪 hZ.1 hZ.2
  exact D.hg (hle (le_sup_right (a := 𝔭) (Ideal.subset_span ⟨𝔪, h𝔪, h𝔭𝔪, D, rfl⟩)))

/-- **Gluing at a point.** If `x` lies in the chart ideals of every member of a cover of `V(𝔭)`,
it lies in the maximal centre at every point `𝔪' ⊇ 𝔭`. Partition of unity: each `gₖ` is in the
radical of `{y | y x ∈ cRF}` (spreading to the local data at `𝔪'`), `i ∈ 𝔭 ⊆ 𝔪'`, so
`1 = i + ∑ fₖ gₖ` puts an element outside `𝔪'` into that ideal. No decision of `gₖ ∈ 𝔪'`. -/
theorem mem_cRF_of_cover {n : ℕ} (f : Fin n → A) (g : Fin n → A) {i : A} (hi : i ∈ 𝔭)
    (hone : i + ∑ k, f k * g k = 1) (t : ℚ) {x : A}
    (hx : ∀ k, ∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal) (D : LocData I v₀ 𝔪), D.g = g k ∧
      algebraMap A D.B x ∈ D.RFB t)
    (𝔪' : Ideal A) [𝔪'.IsMaximal] (h𝔭𝔪' : 𝔭 ≤ 𝔪') :
    algebraMap A (Localization.AtPrime 𝔪') x ∈ cRF I 𝔪' t := by
  set φ := algebraMap A (Localization.AtPrime 𝔪')
  have hZ' := hZ 𝔪' h𝔭𝔪'
  obtain ⟨D'⟩ := LocData.nonempty hI 𝔪' hZ'.1 hZ'.2
  let 𝔠 : Ideal A :=
    { carrier := {y | φ (y * x) ∈ cRF I 𝔪' t}
      add_mem' := fun {y z} hy hz => by
        simp only [Set.mem_ofPred_eq, add_mul, map_add] at hy hz ⊢; exact add_mem hy hz
      zero_mem' := by simp only [Set.mem_ofPred_eq, zero_mul, map_zero]; exact zero_mem _
      smul_mem' := fun c y hy => by
        simp only [Set.mem_ofPred_eq, smul_eq_mul, mul_assoc, map_mul] at hy ⊢
        exact Ideal.mul_mem_left _ _ hy }
  have hc : ∀ y, φ (y * x) ∈ cRF I 𝔪' t → y ∈ 𝔠 := fun _ hy => hy
  -- each `gₖ` is in the radical of `𝔠`
  have hg : ∀ k, g k ∈ 𝔠.radical := by
    intro k
    obtain ⟨𝔪, _, D, hDg, hxD⟩ := hx k
    obtain ⟨N, hN⟩ := D.exists_pow_mul_mem hI D' x t hxD
    have h4 := Ideal.mem_map_of_mem (Loc.map (D'.ctrlN 𝔪' D'.hg)) hN
    rw [D'.RFB_map_of_mem hI D'.hg hZ'.1 hZ'.2, D'.map_algebraMap_B D'.hg] at h4
    rw [hDg] at h4
    exact ⟨N, hc _ h4⟩
  have hr : ∑ k, f k * g k ∈ 𝔠.radical :=
    Ideal.sum_mem _ fun k _ => Ideal.mul_mem_left _ _ (hg k)
  obtain ⟨K, hK⟩ := hr
  have hsum : ∑ k, f k * g k = 1 - i := by rw [← hone]; ring
  rw [hsum] at hK
  have hout : (1 - i) ^ K ∉ 𝔪' := fun h =>
    (Ideal.IsMaximal.ne_top ‹_›) ((Ideal.eq_top_iff_one _).2 (by
      have h1 := Ideal.IsPrime.mem_of_pow_mem inferInstance K h
      have h2 := Ideal.add_mem _ h1 (h𝔭𝔪' hi)
      rwa [sub_add_cancel] at h2))
  have hunit : IsUnit (φ ((1 - i) ^ K)) :=
    IsLocalization.map_units _ (⟨(1 - i) ^ K, hout⟩ : 𝔪'.primeCompl)
  have h5 : φ ((1 - i) ^ K * x) ∈ cRF I 𝔪' t := hK
  rw [map_mul] at h5
  exact (Ideal.unit_mul_mem_iff_mem _ hunit).1 h5

/-- **The component filtration localizes to the maximal centres**, from a cover of `V(𝔭)` by
local data: no `choose` over maximal ideals, no Zorn, no decision of membership in a maximal
ideal (`compF_map` with Steps 2 and 4 replaced by the cover and `mem_cRF_of_cover`). -/
theorem compF_map_C (hcov : (1 : A) ∈ 𝔭 ⊔ Ideal.span {g | CertC I v₀ 𝔭 g})
    (𝔪₀ : Ideal A) [𝔪₀.IsMaximal] (h𝔭𝔪 : 𝔭 ≤ 𝔪₀) (t : ℚ) :
    (compF I 𝔭 t).map (algebraMap A (Localization.AtPrime 𝔪₀)) = cRF I 𝔪₀ t := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro f hf
    exact mem_compF.1 hf 𝔪₀ h𝔭𝔪
  intro z hz
  obtain ⟨a, s, rfl⟩ := IsLocalization.exists_mk'_eq 𝔪₀.primeCompl z
  have ha : algebraMap A (Localization.AtPrime 𝔪₀) a ∈ cRF I 𝔪₀ t := by
    have := (cRF I 𝔪₀ t).mul_mem_right (algebraMap A _ s) hz
    rwa [IsLocalization.mk'_spec] at this
  suffices h : algebraMap A (Localization.AtPrime 𝔪₀) a ∈
      (compF I 𝔭 t).map (algebraMap A (Localization.AtPrime 𝔪₀)) by
    rw [IsLocalization.mk'_eq_mul_mk'_one]
    exact Ideal.mul_mem_right _ _ h
  -- the chart at `𝔪₀`
  have hZ₀ := hZ 𝔪₀ h𝔭𝔪
  obtain ⟨D₀⟩ := LocData.nonempty hI 𝔪₀ hZ₀.1 hZ₀.2
  -- Step 1: a multiple of `a` lies in the chart ideal at `𝔪₀`
  have h1 : algebraMap A (Localization.AtPrime 𝔪₀) a ∈
      (D₀.RFB t).map (Loc.map (D₀.ctrlN 𝔪₀ D₀.hg)) := by
    rw [D₀.RFB_map_of_mem hI D₀.hg hZ₀.1 hZ₀.2]; exact ha
  obtain ⟨s₁, hs₁, hs₁a⟩ := D₀.exists_of_mem_map D₀.hg _ h1
  -- Step 2: the cover, as a finite relation
  obtain ⟨i, hi, y, hy, hiy⟩ := Submodule.mem_sup.1 hcov
  obtain ⟨n, f, g, hfg⟩ := Submodule.mem_span_set'.1 hy
  have hone : i + ∑ k, f k * (g k : A) = 1 := by
    rw [← hiy, ← hfg]; simp only [smul_eq_mul]
  -- Step 3: spread to each chart of the cover, with a common exponent
  set P : Fin n → ℕ → Prop := fun k N => ∃ (𝔪 : Ideal A) (_ : 𝔪.IsMaximal)
    (D : LocData I v₀ 𝔪), D.g = g k ∧ algebraMap A D.B (D₀.g ^ N * (s₁ * a)) ∈ D.RFB t
  have hmono : ∀ k N N', N ≤ N' → P k N → P k N' := by
    rintro k N N' hNN' ⟨𝔪, h𝔪, D, hDg, hD⟩
    refine ⟨𝔪, h𝔪, D, hDg, ?_⟩
    rw [show D₀.g ^ N' * (s₁ * a) = D₀.g ^ (N' - N) * (D₀.g ^ N * (s₁ * a)) by
      rw [← mul_assoc (D₀.g ^ (N' - N)), ← pow_add, Nat.sub_add_cancel hNN'], map_mul]
    exact Ideal.mul_mem_left _ _ hD
  have h3 : ∀ k, ∃ N, P k N := by
    intro k
    obtain ⟨𝔪, h𝔪, -, D, hDg⟩ := (g k).2
    obtain ⟨N, hN⟩ := D₀.exists_pow_mul_mem hI D (s₁ * a) t hs₁a
    exact ⟨N, 𝔪, h𝔪, D, hDg, hN⟩
  obtain ⟨M, hM⟩ := exists_uniform P hmono h3
  -- Step 4: the global element, by gluing at each point
  have hmem : D₀.g ^ M * (s₁ * a) ∈ compF I 𝔭 t := by
    rw [mem_compF]
    intro 𝔪' _ h𝔭𝔪'
    exact mem_cRF_of_cover hI hZ f (fun k => (g k : A)) hi hone t hM 𝔪' h𝔭𝔪'
  have hunit : IsUnit (algebraMap A (Localization.AtPrime 𝔪₀) (D₀.g ^ M * s₁)) :=
    IsLocalization.map_units _ (⟨D₀.g ^ M * s₁, 𝔪₀.primeCompl.mul_mem
      (𝔪₀.primeCompl.pow_mem D₀.hg M) hs₁⟩ : 𝔪₀.primeCompl)
  have h5 := Ideal.mem_map_of_mem (algebraMap A (Localization.AtPrime 𝔪₀)) hmem
  rw [← mul_assoc, map_mul] at h5
  exact (Ideal.unit_mul_mem_iff_mem _ hunit).1 h5

/-- `compF_map` under `¬¬`, from `NNMax` alone. -/
theorem compF_map_NN (hNS : NNMax A) (𝔪₀ : Ideal A) [𝔪₀.IsMaximal] (h𝔭𝔪 : 𝔭 ≤ 𝔪₀) (t : ℚ) :
    ¬¬ ((compF I 𝔭 t).map (algebraMap A (Localization.AtPrime 𝔪₀)) = cRF I 𝔪₀ t) :=
  fun h => not_not_one_mem_certC hI hZ hNS fun hcov =>
    h (compF_map_C hI hZ hcov 𝔪₀ h𝔭𝔪 t)

end BezoutCounterexample.Principalization
