import BezoutCounterexample.Principalization.LocDataPtProd
import BezoutCounterexample.Principalization.ComponentFilPtL
import BezoutCounterexample.Principalization.GCDStep

/-!
# The divisorial component at explicit points (leaf, top chain stage 3)

`div_eq_span`, `div_le_span_pow` (Divisorial) and `div_eq_span_G` (GCDStep) read the component off
classical local data (`LocData.nonempty` through `local_structure`, `cRF_eq_transport` through
`cRF_eq`; for `div_eq_span_G` also a maximal ideal from `Ideal.exists_le_maximal`). Here the same
statements are proved at an explicit point of `𝔭` (`HasPres.exists_pt` on generators of `𝔭`) with
`LocDataPt.nonempty` (`l`, `hl`, `hchart`), `LocusComp.mem_ptL`, `eq_p_ptL` and `cRF_eq_pt`:

* `LocDataPt.n_pos`, `LocDataPt.supp_zero`, `LocDataPt.P_eq_span` (twins of the `LocData` lemmas);
* `LocusComp.exists_locDataPt`: local data at an explicit point of `𝔭`, with `𝔭 = D.p`;
* `div_eq_span_ptL`, `div_le_span_pow_ptL`, `div_eq_span_G_ptL`.

Leaf module.
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open IsLocalRing IsLocalization Constructive

section DivSpanPt

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]

namespace LocDataPt

variable {I : Ideal A} {v₀ : ℕ → ℚ} {𝔪 : Ideal A} [𝔪.IsMaximal] (D : LocDataPt I v₀ 𝔪)

omit [IsDomain A] [Algebra.Smooth ℚ A] in
lemma n_pos (h0 : v₀ 0 ≠ 0) : 0 < D.n := by
  rcases Nat.eq_zero_or_pos D.n with h | h
  · exfalso
    apply h0
    have := congrFun D.hv 0
    simp only [ext0, dite_eq_right (show ¬ 0 < D.n by omega)] at this
    exact this.symm
  · exact h

omit [IsDomain A] [Algebra.Smooth ℚ A] in
/-- In the divisorial case the support of the weights is `{0}`. -/
lemma supp_zero (h0 : v₀ 0 ≠ 0) (hk1 : v₀ 1 = 0) (i : Fin D.n) : D.ek i ≠ 0 ↔ (i : ℕ) = 0 := by
  have hv : ∀ j : Fin D.n, D.ek j = v₀ j := fun j => by
    have := congrFun D.hv (j : ℕ); rw [ext0_apply] at this; exact this
  constructor
  · intro hne
    rcases Nat.eq_zero_or_pos (i : ℕ) with hi | hi
    · exact hi
    · exfalso
      have h1 : (1 : ℕ) < D.n := by have := i.2; omega
      have hle : D.ek i ≤ D.ek ⟨1, h1⟩ := D.inv.anti (Fin.le_def.2 (by simp; omega))
      rw [hv ⟨1, h1⟩, hk1] at hle
      exact hne (le_antisymm hle (D.inv.nonneg i))
  · intro hi
    rw [hv i, show (i : ℕ) = 0 from hi]
    exact h0

omit [IsDomain A] [Algebra.Smooth ℚ A] in
/-- In the divisorial case the component is locally generated by the first coordinate. -/
lemma P_eq_span (h0 : v₀ 0 ≠ 0) (hk1 : v₀ 1 = 0) :
    D.P = Ideal.span {(Loc.transport (D.ctrl 𝔪 D.hg) D.ck).x ⟨0, D.n_pos h0⟩} := by
  have hset : {i : Fin D.n | (i : ℕ) < D.k} = {⟨0, D.n_pos h0⟩} := by
    ext i
    simp only [Set.mem_ofPred_eq, Set.mem_singleton_iff]
    rw [← D.supp i, D.supp_zero h0 hk1 i, Fin.ext_iff]
  rw [LocDataPt.P, hset, Set.image_singleton]

end LocDataPt

variable [IsNoetherianRing A]

variable {I : Ideal A} (hI : I ≠ ⊥) (l : List A) (hl : I = lspan l)
  (hchart : ∀ p : Pt A, ∃ f : A, f ∉ p.ker ∧ ∃ n : ℕ, Nonempty (Chart (Localization.Away f) n))
  {v₀ : ℕ → ℚ}
  (hmax : IsMaxInvPt I v₀)
  {𝔭 : Ideal A} (h𝔭 : LocusComp I v₀ 𝔭)

include hI hl hchart hmax h𝔭 in
/-- **Local data at an explicit point of the component**, with `𝔭 = D.p`. -/
theorem LocusComp.exists_locDataPt [Fact (HasPres A)] :
    ∃ (q : Pt A) (D : LocDataPt I v₀ q.ker), 𝔭 ≤ q.ker ∧ 𝔭 = D.p := by
  have := h𝔭.isPrime
  obtain ⟨C, hC, -⟩ := h𝔭.gens
  obtain ⟨q, hle⟩ := HasPres.exists_pt (Fact.out : HasPres A) C fun h =>
    (Ideal.IsPrime.ne_top ‹_›) ((Ideal.eq_top_iff_one _).2 (hC ▸ h))
  rw [← hC] at hle
  obtain ⟨hIq, hv⟩ := h𝔭.mem_ptL hI l hl hchart hmax q hle
  obtain ⟨f, hf, n, ⟨c₀⟩⟩ := hchart q
  obtain ⟨D⟩ := LocDataPt.nonempty hI l hl q hIq hv hf c₀
  exact ⟨q, D, hle, h𝔭.eq_p_ptL D hle⟩

include hI hl hchart hmax h𝔭 in
/-- **In the divisorial case the component is principal** (at an explicit point). -/
theorem div_eq_span_ptL [Fact (HasPres A)] (h0 : v₀ 0 ≠ 0) (hk1 : v₀ 1 = 0) {π : A}
    (hπ : Prime π) (hπ𝔭 : π ∈ 𝔭) : 𝔭 = Ideal.span {π} := by
  have := h𝔭.isPrime
  obtain ⟨q, D, hle, hp⟩ := h𝔭.exists_locDataPt hI l hl hchart hmax
  have hloc : 𝔭.map (algebraMap A (Localization.AtPrime q.ker)) =
      Ideal.span {(Loc.transport (D.ctrl q.ker D.hg) D.ck).x ⟨0, D.n_pos h0⟩} := by
    rw [hp, D.map_p, D.P_eq_span h0 hk1]
  exact eq_span_of_loc_principal hle hπ hπ𝔭 (D.cent.x_mem _) hloc

include hI hl hchart hmax h𝔭 in
/-- **Divisorial step, GCD form, at an explicit point.** -/
theorem div_eq_span_G_ptL [Fact (HasPres A)] (hG : HasGcd A) (hz : ∀ a : A, a = 0 ∨ a ≠ 0) (h0 : v₀ 0 ≠ 0)
    (hk1 : v₀ 1 = 0) {r : ℕ} (a : Fin r → A) (ha : Ideal.span (Set.range a) = 𝔭) {δ : A}
    (hδ : IsGcdFam δ a) : 𝔭 = Ideal.span {δ} := by
  have := h𝔭.isPrime
  obtain ⟨q, D, hle, hp⟩ := h𝔭.exists_locDataPt hI l hl hchart hmax
  set 𝔪 := q.ker
  set x := (Loc.transport (D.ctrl 𝔪 D.hg) D.ck).x ⟨0, D.n_pos h0⟩
  have hloc : 𝔭.map (algebraMap A (Localization.AtPrime 𝔪)) = Ideal.span {x} := by
    rw [hp, D.map_p, D.P_eq_span h0 hk1]
  have hmapa : Ideal.span (Set.range fun j => algebraMap A (Localization.AtPrime 𝔪) (a j)) =
      Ideal.span {x} := by
    rw [← hloc, ← ha, Ideal.map_span, ← Set.range_comp]; rfl
  have hδL := isGcdFam_map_of_isLocalization 𝔪.primeCompl (Localization.AtPrime 𝔪) hG hz hδ
  -- `x` is a gcd of the images, hence associated to the image of `δ`
  have hxa : ∀ j, x ∣ algebraMap A (Localization.AtPrime 𝔪) (a j) := fun j =>
    Ideal.mem_span_singleton.1 (hmapa ▸ Ideal.subset_span ⟨j, rfl⟩)
  have hδx : algebraMap A (Localization.AtPrime 𝔪) δ ∈ Ideal.span {x} :=
    Ideal.mem_span_singleton.2 (hδL.2 x hxa)
  have hδ𝔭 : δ ∈ 𝔭 := by
    rw [← hloc] at hδx
    have hdisj : Disjoint (𝔪.primeCompl : Set A) (𝔭 : Set A) := by
      rw [Set.disjoint_left]; intro b hb hb'; exact hb (hle hb')
    have hc := IsLocalization.comap_map_of_isPrime_disjoint 𝔪.primeCompl
      (Localization.AtPrime 𝔪) ‹𝔭.IsPrime› hdisj
    rw [← Ideal.mem_comap] at hδx
    exact (Ideal.ext_iff.1 hc δ).1 hδx
  refine le_antisymm ?_ ((Ideal.span_singleton_le_iff_mem _).2 hδ𝔭)
  rw [← ha, Ideal.span_le]
  rintro _ ⟨j, rfl⟩
  exact Ideal.mem_span_singleton.2 (hδ.1 j)

variable {d : ℕ} (hd : 0 < d)

include hI hl hchart hmax h𝔭 hd in
/-- **In the divisorial case `I ⊆ (π^a)`** (at explicit points). -/
theorem div_le_span_pow_ptL [Fact (Constructive.HasPres A)] (h0 : v₀ 0 ≠ 0) (hk1 : v₀ 1 = 0) {π : A} (hπ : Prime π) (hπ𝔭 : π ∈ 𝔭)
    {a : ℕ} (ha : v₀ 0 = 1 / a) : I ≤ Ideal.span {π ^ a} := by
  have h𝔭π := div_eq_span_ptL hI l hl hchart hmax h𝔭 h0 hk1 hπ hπ𝔭
  refine (I_le_compFil hI hmax h𝔭 hd).trans ?_
  rw [compFil_F, show ((d : ℤ) : ℚ) / d = 1 by
    have : (d : ℚ) ≠ 0 := by exact_mod_cast hd.ne'
    push_cast; field_simp]
  refine Ideal.le_of_forall_pt ⟨[π ^ a], by rw [Constructive.lspan_singleton]⟩ fun p => ?_
  rcases p.mem_ker_dec π with hπp | hπp
  · have h𝔭𝔪 : 𝔭 ≤ p.ker := h𝔭π ▸ Ideal.span_le.2 (Set.singleton_subset_iff.2 hπp)
    have hle1 : (compFPt I 𝔭 1).map (algebraMap A (Localization.AtPrime p.ker)) ≤ cRF I p.ker 1 :=
      Ideal.map_le_iff_le_comap.2 fun x hx => mem_compFPt.1 hx p h𝔭𝔪
    refine hle1.trans ?_
    obtain ⟨hI𝔪, hv⟩ := h𝔭.mem_ptL hI l hl hchart hmax p h𝔭𝔪
    obtain ⟨f, hf, n, ⟨c₀⟩⟩ := hchart p
    obtain ⟨D⟩ := LocDataPt.nonempty hI l hl p hI𝔪 hv hf c₀
    rw [D.cRF_eq_pt 1]
    have h0' := D.n_pos h0
    have hek : D.ek ⟨0, h0'⟩ = 1 / a := by
      have := congrFun D.hv 0
      rw [ext0, dite_eq_left h0'] at this
      rw [this, ha]
    refine (RF_le_pow_of_single _ h0' (D.supp_zero h0 hk1) hek).trans ?_
    have hx : Ideal.span {(Loc.transport (D.ctrl p.ker D.hg) D.ck).x ⟨0, h0'⟩} =
        (Ideal.span {π}).map (algebraMap A (Localization.AtPrime p.ker)) := by
      rw [← D.P_eq_span h0 hk1, ← D.map_p, ← h𝔭.eq_p_ptL D h𝔭𝔪, h𝔭π]
    rw [hx, ← Ideal.map_pow, Ideal.span_singleton_pow]
  · have hu : IsUnit (algebraMap A (Localization.AtPrime p.ker) (π ^ a)) :=
      IsLocalization.map_units _ (⟨π ^ a, p.ker.primeCompl.pow_mem hπp a⟩ : p.ker.primeCompl)
    rw [Ideal.map_span, Set.image_singleton, Ideal.span_singleton_eq_top.2 hu]
    exact le_top

end DivSpanPt

end BezoutCounterexample.Principalization
