import BezoutCounterexample.Principalization.Torsor
import BezoutCounterexample.Principalization.Divisorial
import BezoutCounterexample.Constructive.JouGCD
import BezoutCounterexample.Constructive.InvPrinc
import BezoutCounterexample.Constructive.DecTransfer

/-!
# The principalization steps over GCD domains (`~/COLL/bezout-gcd.tex`, §4–6)

GCD versions of the three places where HM use factoriality of `A`.

* `div_eq_span_G` (divisorial step, `k = 1`): the component `𝔭` is generated by the gcd `δ` of
  any generating family; `δ` is then prime. Replaces Kaplansky's prime (`exists_prime_mem`) and
  `div_eq_span`. One point of `V(𝔭)` suffices: there `𝔭` is locally principal, and gcds of
  families are preserved by localisation (`isGcdFam_map_of_isLocalization`).
* `gens_gcd_isUnit` (Lemma gcd1, `k ≥ 2`): the generators `G₁` of `F₁ = 𝔭` have no common
  non-unit divisor. GCD form of `exists_gen_not_dvd`.
* `torsor_gcd` (Corollary torsor): the torsor `U` has gcds. `U[1/s] = J_{A[T^±]}(h)` has gcds by
  `hasGcd_jou` (generic prime inside the proof, row gcd `1` from `gens_gcd_isUnit` and
  `laurent_dvd_C`); then Nagata at the prime `s` (`hasGcd_of_away`) with the valuation from the
  bar (`IndNoeth.exists_val`). `π` only has to be a nonzero element of `F₁`.

This layer is classical (like the rest of `Principalization/`): the decisions that the
constructive leaves take as hypotheses (zero tests and divisibility in `U` and in the auxiliary
Jouanolou rings) are supplied here by `Classical.em`; in the finitely presented case they are
provided by `Constructive/Groebner.lean`.
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open IsLocalRing IsLocalization LaurentPolynomial Constructive

section Fam

variable {R : Type*} [CommRing R] [IsDomain R] (S : Submonoid R) (L : Type*) [CommRing L]
  [Algebra R L] [IsLocalization S L]

include S in
/-- **Gcds of families are preserved by localisation.** -/
theorem isGcdFam_map_of_isLocalization (hG : HasGcd R) (hz : ∀ a : R, a = 0 ∨ a ≠ 0) {r : ℕ}
    {d : R} {a : Fin r → R} (hd : IsGcdFam d a) :
    IsGcdFam (algebraMap R L d) (fun j => algebraMap R L (a j)) := by
  refine ⟨fun j => _root_.map_dvd _ (hd.1 j), fun z hz' => ?_⟩
  obtain ⟨⟨c, u⟩, rfl⟩ := IsLocalization.mk'_surjective S z
  have hc : ∀ j, algebraMap R L c ∣ algebraMap R L (a j) := fun j => by
    rw [← IsLocalization.mk'_spec L c u, (IsLocalization.map_units L u).mul_right_dvd]
    exact hz' j
  have hσ : ∀ j, ∃ σ ∈ S, c ∣ σ * a j := fun j => exists_dvd_of_dvd_localization S L (hc j)
  obtain ⟨σ, hσ'⟩ := exists_fun_fin (fun j s => s ∈ S ∧ c ∣ s * a j)
    (fun j => by obtain ⟨s, hs, hs'⟩ := hσ j; exact ⟨s, hs, hs'⟩)
  have hσS : ∀ j, σ j ∈ S := fun j => (hσ' j).1
  replace hσ : ∀ j, c ∣ σ j * a j := fun j => (hσ' j).2
  set σ' : R := ∏ j, σ j
  have hσ'S : σ' ∈ S := Submonoid.prod_mem S fun j _ => hσS j
  have hcj : ∀ j, c ∣ σ' * a j := fun j => by
    obtain ⟨t, ht⟩ : σ j ∣ σ' := Finset.dvd_prod_of_mem _ (Finset.mem_univ j)
    rw [ht, mul_comm (σ j) t, mul_assoc]
    exact dvd_mul_of_dvd_right (hσ j) t
  have hcd : c ∣ σ' * d := (isGcdFam_mul_left hG hz hd σ').2 c hcj
  have hu : IsUnit (algebraMap R L σ') := IsLocalization.map_units L (⟨σ', hσ'S⟩ : S)
  have h1 : algebraMap R L c ∣ algebraMap R L d := by
    rw [← hu.dvd_mul_left, ← map_mul]; exact _root_.map_dvd _ hcd
  exact (show IsLocalization.mk' L c u ∣ algebraMap R L c from
    ⟨algebraMap R L u, (IsLocalization.mk'_spec L c u).symm⟩).trans h1

end Fam

section Laurent

variable {B : Type*} [CommRing B] [IsDomain B]

/-- In `B[X]`, a polynomial not divisible by `X` and dividing `C a Xᴺ` divides `C a`. -/
lemma dvd_C_of_dvd_C_mul_X_pow {f : Polynomial B} (hX : ¬ Polynomial.X ∣ f) (a : B) :
    ∀ N : ℕ, f ∣ Polynomial.C a * Polynomial.X ^ N → f ∣ Polynomial.C a
  | 0, h => by simpa using h
  | N + 1, ⟨g, hg⟩ => by
    have hXg : Polynomial.X ∣ f * g := ⟨Polynomial.C a * Polynomial.X ^ N, by rw [← hg]; ring⟩
    rcases Polynomial.prime_X.dvd_or_dvd hXg with h | ⟨g', rfl⟩
    · exact absurd h hX
    · refine dvd_C_of_dvd_C_mul_X_pow hX a N ⟨g', ?_⟩
      have : (Polynomial.C a * Polynomial.X ^ N - f * g') * Polynomial.X = 0 := by
        rw [sub_mul, mul_assoc, ← pow_succ, hg]; ring
      exact sub_eq_zero.1 ((mul_eq_zero.1 this).resolve_right Polynomial.X_ne_zero)

/-- **Divisors of constants in `B[T^±]` are monomials.** -/
theorem laurent_dvd_C {e : B[T;T⁻¹]} {a : B} (ha : a ≠ 0) (h : e ∣ LaurentPolynomial.C a) :
    ∃ b : B, ∃ n : ℤ, e = LaurentPolynomial.C b * T n := by
  obtain ⟨q, hq⟩ := h
  obtain ⟨n, f, hf⟩ := e.exists_T_pow
  obtain ⟨m, g, hg⟩ := q.exists_T_pow
  have hfg : f * g = Polynomial.C a * Polynomial.X ^ (n + m) := by
    apply Polynomial.toLaurent_injective
    rw [map_mul, hf, hg, Polynomial.toLaurent_C_mul_X_pow]
    calc e * T ↑n * (q * T ↑m) = e * q * (T ↑n * T ↑m) := by ring
      _ = _ := by rw [← hq, ← T_add]; push_cast; rfl
  have hf0 : f ≠ 0 := by
    rintro rfl
    rw [zero_mul] at hfg
    exact ha (by simpa using congrArg (fun p => p.coeff (n + m)) hfg.symm)
  obtain ⟨f₁, hf₁, hX⟩ := f.exists_eq_pow_rootMultiplicity_mul_and_not_dvd hf0 0
  simp only [map_zero, sub_zero] at hf₁ hX
  generalize f.rootMultiplicity 0 = i at hf₁
  have hdvd : f₁ ∣ Polynomial.C a := dvd_C_of_dvd_C_mul_X_pow hX a (n + m)
    ⟨Polynomial.X ^ i * g, by rw [← hfg, hf₁]; ring⟩
  obtain ⟨k, hk⟩ := hdvd
  have hk0 : k ≠ 0 := by rintro rfl; rw [mul_zero, Polynomial.C_eq_zero] at hk; exact ha hk
  have hf₁0 : f₁ ≠ 0 := by rintro rfl; rw [zero_mul, Polynomial.C_eq_zero] at hk; exact ha hk
  have hdeg : f₁.natDegree = 0 := by
    have := Polynomial.natDegree_mul hf₁0 hk0
    rw [← hk, Polynomial.natDegree_C] at this
    omega
  rw [Polynomial.eq_C_of_natDegree_eq_zero hdeg] at hf₁
  refine ⟨f₁.coeff 0, (i : ℤ) - n, ?_⟩
  have hTn : T (n : ℤ) * T (-(n : ℤ)) = (1 : B[T;T⁻¹]) := by rw [← T_add]; simp
  calc e = e * T ↑n * T (-(n : ℤ)) := by rw [mul_assoc, hTn, mul_one]
    _ = Polynomial.toLaurent f * T (-(n : ℤ)) := by rw [hf]
    _ = _ := by
      rw [hf₁, map_mul, map_pow, Polynomial.toLaurent_X, Polynomial.toLaurent_C, T_pow, mul_one,
        sub_eq_add_neg, T_add]
      ring

omit [IsDomain B] in
/-- A monomial divisor: `C b T^n ∣ C g T^j` gives `b ∣ g`. -/
lemma dvd_of_C_mul_T_dvd {b g : B} {n j : ℤ}
    (h : LaurentPolynomial.C b * T n ∣ LaurentPolynomial.C g * T j) : b ∣ g := by
  obtain ⟨q, hq⟩ := h
  have hT : ∀ k : ℤ, (T k : B[T;T⁻¹]) * T (-k) = 1 := fun k => by rw [← T_add]; simp
  have h1 : LaurentPolynomial.C g = LaurentPolynomial.C b * (q * T (n - j)) := by
    calc LaurentPolynomial.C g = LaurentPolynomial.C g * T j * T (-j) := by
          rw [mul_assoc, hT, mul_one]
      _ = LaurentPolynomial.C b * T n * q * T (-j) := by rw [hq]
      _ = LaurentPolynomial.C b * (q * T (n - j)) := by
          rw [sub_eq_add_neg, T_add]; ring
  have h2 := congrArg (fun p : B[T;T⁻¹] => p.coeff 0) h1
  simp only [LaurentPolynomial.C_apply, coeff_C_mul'] at h2
  exact ⟨_, h2⟩

end Laurent

section Steps

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  [IsNoetherianRing A]

variable {I : Ideal A} (hI : I ≠ ⊥) {v₀ : ℕ → ℚ}
  (hmax : IsMaxInvPt I v₀)
  {𝔭 : Ideal A} (h𝔭 : LocusComp I v₀ 𝔭)

include hI hmax h𝔭 in
/-- **Divisorial step, GCD form**: in the divisorial case the component is generated by the gcd
of any generating family. -/
theorem div_eq_span_G [Fact (HasPres A)] (hG : HasGcd A) (hz : ∀ a : A, a = 0 ∨ a ≠ 0) (h0 : v₀ 0 ≠ 0)
    (hk1 : v₀ 1 = 0) {r : ℕ} (a : Fin r → A) (ha : Ideal.span (Set.range a) = 𝔭) {δ : A}
    (hδ : IsGcdFam δ a) : 𝔭 = Ideal.span {δ} := by
  have := h𝔭.isPrime
  obtain ⟨𝔪, h𝔪, hle⟩ := Ideal.exists_le_maximal 𝔭 (Ideal.IsPrime.ne_top ‹_›)
  have := h𝔪
  obtain ⟨hI𝔪, hv⟩ := h𝔭.mem_max hI hmax 𝔪 hle
  obtain ⟨D⟩ := LocData.nonempty hI 𝔪 hI𝔪 hv
  have hp : 𝔭 = D.p := h𝔭.eq_p D hle
  set x := (Loc.transport (D.ctrl 𝔪 D.hg) D.ck).x ⟨0, D.n_pos h0⟩
  have hloc : 𝔭.map (algebraMap A (Localization.AtPrime 𝔪)) = Ideal.span {x} := by
    rw [hp, D.map_p, D.P_eq_span h0 hk1]
  have hmapa : Ideal.span (Set.range fun j => algebraMap A (Localization.AtPrime 𝔪) (a j)) =
      Ideal.span {x} := by
    rw [← hloc, ← ha, Ideal.map_span, ← Set.range_comp]; rfl
  have hδL := isGcdFam_map_of_isLocalization 𝔪.primeCompl (Localization.AtPrime 𝔪) hG hz hδ
  -- `x` is a gcd of the images, hence associated to the image of `δ`
  have hxa : ∀ j, x ∣ algebraMap A (Localization.AtPrime 𝔪) (a j) := fun j =>
    Ideal.mem_span_singleton.1 (hmapa ▸ Ideal.subset_span ⟨j, rfl⟩)
  have hδx : algebraMap A (Localization.AtPrime 𝔪) δ ∈ Ideal.span {x} :=
    Ideal.mem_span_singleton.2 (hδL.2 x hxa)
  have hδ𝔭 : δ ∈ 𝔭 := by
    rw [← hloc] at hδx
    have hdisj : Disjoint (𝔪.primeCompl : Set A) (𝔭 : Set A) := by
      rw [Set.disjoint_left]; intro b hb hb'; exact hb (hle hb')
    have hc := IsLocalization.comap_map_of_isPrime_disjoint 𝔪.primeCompl
      (Localization.AtPrime 𝔪) ‹𝔭.IsPrime› hdisj
    rw [← Ideal.mem_comap] at hδx
    exact (Ideal.ext_iff.1 hc δ).1 hδx
  refine le_antisymm ?_ ((Ideal.span_singleton_le_iff_mem _).2 hδ𝔭)
  rw [← ha, Ideal.span_le]
  rintro _ ⟨j, rfl⟩
  exact Ideal.mem_span_singleton.2 (hδ.1 j)

variable {d : ℕ} (hd : 0 < d) (hw : ∀ i, ∃ w : ℕ, (w : ℚ) = d * v₀ i)

include hI hmax h𝔭 hd hw in
/-- **Lemma gcd1**: if `k ≥ 2`, the generators of `F₁ = 𝔭` have no common non-unit divisor. -/
theorem gens_gcd_isUnit [Constructive.Enum A] [hpA : Fact (HasPres A)] (hk2 : v₀ 1 ≠ 0) {b : A} (hb : ∀ g ∈ gensF hI hmax h𝔭 d 1, b ∣ g) :
    IsUnit b := by
  have h1 : (compFil hI hmax h𝔭 d).F 1 = 𝔭 := by
    rw [compFil_F, show ((1 : ℤ) : ℚ) / d = 1 / d by push_cast; ring,
      h𝔭.compFPt_one_divP hI hmax hd hw]
  have hgen : ∀ g ∈ gensF hI hmax h𝔭 d 1, g ∈ 𝔭 := fun g hg => by
    rw [← h1, ← span_gensF]; exact Ideal.subset_span hg
  have hle : 𝔭 ≤ Ideal.span {b} := by
    rw [← h1, ← span_gensF, Ideal.span_le]
    intro g hg; exact Ideal.mem_span_singleton.2 (hb g hg)
  -- a nonzero element of `𝔭`
  obtain ⟨g₀, hg₀, hg₀0⟩ := exists_gen_not_dvd hI hmax h𝔭 hd hw hk2 (zero_mem 𝔭)
  have hg₀ne : g₀ ≠ 0 := by rintro rfl; exact hg₀0 dvd_rfl
  -- `b ∈ 𝔭` is decided from generators of the component
  obtain ⟨C, hC, -⟩ := h𝔭.gens
  rcases hpA.out.mem_dec C b with hb𝔭 | hb𝔭 <;> rw [← hC] at hb𝔭
  · obtain ⟨g, hg, hgb⟩ := exists_gen_not_dvd hI hmax h𝔭 hd hw hk2 hb𝔭
    exact absurd (hb g hg) hgb
  · have := h𝔭.isPrime
    have hsmul : (𝔭 : Submodule A A) ≤ Ideal.span {b} • (𝔭 : Submodule A A) := by
      intro y hy
      obtain ⟨t, rfl⟩ := Ideal.mem_span_singleton'.1 (hle hy)
      have ht : t ∈ 𝔭 := (‹𝔭.IsPrime›.mem_or_mem hy).resolve_right hb𝔭
      rw [mul_comm]
      exact Submodule.smul_mem_smul (Ideal.mem_span_singleton_self b) ht
    obtain ⟨r, hr1, hr0⟩ := Submodule.exists_sub_one_mem_and_smul_eq_zero_of_fg_of_le_smul
      (Ideal.span {b}) (𝔭 : Submodule A A) (IsNoetherian.noetherian _) hsmul
    have hr : r = 0 := (mul_eq_zero.1 (hr0 g₀ (hgen g₀ hg₀))).resolve_right hg₀ne
    rw [hr, zero_sub, neg_mem_iff] at hr1
    exact isUnit_of_dvd_one (Ideal.mem_span_singleton.1 hr1)

variable {π : A} (hπ : π ∈ (compFil hI hmax h𝔭 d).F 1)

include hd hw in
set_option maxHeartbeats 2000000 in
/-- **Corollary torsor**: the torsor has gcds. -/
theorem torsor_gcd [Constructive.Enum A] [Fact (HasPres A)] [Fact (∃ k, ChartDim A k)] (hG : HasGcd A) (hz : ∀ a : A, a = 0 ∨ a ≠ 0) (hk2 : v₀ 1 ≠ 0)
    (hπ0 : π ≠ 0) : HasGcd (Torsor hI hmax h𝔭 d hπ) := by
  classical
  set R := ReesAlg (compFil hI hmax h𝔭 d)
  set s := reesS (compFil hI hmax h𝔭 d) (fun j hj => compFil_F_nonpos hI hmax h𝔭 d hj)
  set y := torsorY hI hmax h𝔭 d hπ
  have := torsor_isDomain hI hmax h𝔭 hπ hπ0
  have : Algebra.FiniteType ℚ (Torsor hI hmax h𝔭 d hπ) := torsor_finiteType hI hmax h𝔭 hd hw hπ
  have : IsLocalization.Away s A[T;T⁻¹] := isLocalization_away_s _ _
  set c : Fin (nGen hI hmax h𝔭 d + 1) → A[T;T⁻¹] := algebraMap R A[T;T⁻¹] ∘ y
  let : Algebra (Torsor hI hmax h𝔭 d hπ) (Jou.J c) := (Jou.map (algebraMap R A[T;T⁻¹]) y).toAlgebra
  have hloc : IsLocalization ((Submonoid.powers s).map (algebraMap R (Jou.J y))) (Jou.J c) :=
    Jou.isLocalization_map y (Submonoid.powers s)
  have : IsLocalization.Away (algebraMap R (Torsor hI hmax h𝔭 d hπ) s) (Jou.J c) := by
    rw [Submonoid.map_powers] at hloc; exact hloc
  -- the base `A[T^±]`
  have hGB : HasGcd A[T;T⁻¹] := hasGcd_laurent hG hz
  have hzB : ∀ b : A[T;T⁻¹], b = 0 ∨ b ≠ 0 := fun b => em _
  have hNB : PolyIndNoeth A[T;T⁻¹] := by
    have hA : PolyIndNoeth A := polyIndNoeth_of_finiteType A
    have hAX : PolyIndNoeth (Polynomial A) := hA.of_finiteType
    exact hAX.of_isLocalization (Submonoid.powers (Polynomial.X : Polynomial A))
  have hcj : ∀ i, c i = LaurentPolynomial.C (genCoeff hI hmax h𝔭 d π i) *
      T (genDeg hI hmax h𝔭 d i) := fun i => rfl
  have hc0 : c 0 ≠ 0 := by
    rw [hcj]
    simp only [genCoeff, genDeg, Fin.cons_zero]
    intro h
    have := congrArg (fun p : A[T;T⁻¹] => p * T (-1)) h
    simp only [zero_mul, mul_assoc, ← T_add, add_neg_cancel, T_zero, mul_one] at this
    exact hπ0 (by simpa using congrArg (fun p : A[T;T⁻¹] => p.coeff 0) this)
  -- the row has no common non-unit divisor
  have hrel : ∀ e : A[T;T⁻¹], (∀ i, e ∣ c i) → IsUnit e := by
    intro e he
    have hdiv : ∀ g ∈ gensF hI hmax h𝔭 d 1, e ∣ LaurentPolynomial.C g * T 1 := fun g hg => by
      obtain ⟨m, hm1, hm2⟩ := exists_index hI hmax h𝔭 (π := π) le_rfl (by exact_mod_cast hd) hg
      have := he m
      rwa [hcj, hm1, hm2] at this
    obtain ⟨g₀, hg₀, hg₀0⟩ := exists_gen_not_dvd hI hmax h𝔭 hd hw hk2 (zero_mem 𝔭)
    have hg₀ne : g₀ ≠ 0 := by rintro rfl; exact hg₀0 dvd_rfl
    have hT1 : (T 1 : A[T;T⁻¹]) * T (-1) = 1 := by rw [← T_add]; simp
    have he0 : e ∣ LaurentPolynomial.C g₀ := by
      obtain ⟨q, hq⟩ := hdiv g₀ hg₀
      exact ⟨q * T (-1), by rw [← mul_assoc, ← hq, mul_assoc, hT1, mul_one]⟩
    obtain ⟨b, n, rfl⟩ := laurent_dvd_C hg₀ne he0
    have hb : IsUnit b := gens_gcd_isUnit hI hmax h𝔭 hd hw hk2 fun g hg =>
      dvd_of_C_mul_T_dvd (hdiv g hg)
    exact (hb.map LaurentPolynomial.C).mul (isUnit_T n)
  have hJ : HasGcd (Jou.J c) := hasGcd_jou c hGB hzB hNB hc0 hrel (fun _ => em _) (fun _ => em _)
  -- Nagata at the prime `s`
  have hs := torsor_s_prime hI hmax h𝔭 hd hw hπ hπ0
  have hIN : IndNoeth (Torsor hI hmax h𝔭 d hπ) :=
    (polyIndNoeth_of_finiteType (Torsor hI hmax h𝔭 d hπ)).indNoeth
  exact hasGcd_of_away hs (Jou.J c) (fun _ => em _)
    (fun a ha => hIN.exists_val hs.not_unit (fun _ _ => em _) ha) hJ

include hd hw in
set_option maxHeartbeats 4000000 in
/-- **Corollary torsor with computed decisions**: if `A` is a GCD domain with a zero test and
decidable divisibility, then `U` has gcds, a zero test and decidable divisibility, given only the
decision of divisibility by `s` in `U` (`hs`). Everything else is computed
(`Constructive/DecTransfer.lean`): the zero test of `U ⊆ R[1/y₀][σ]`, and the decisions of
`U[1/s] = J_{A[T^±]}(h)` from those of `A[T^±] = A[X][1/X]`. The decision `hs` is the zero test of
`U/sU = J_{gr}(h̄)`, i.e. membership in the filtration ideals `F_j` of `A`. -/
theorem torsor_dec [Constructive.Enum A] [Fact (HasPres A)] [Fact (∃ k, ChartDim A k)] (hG : HasGcd A) (hz : ∀ a : A, a = 0 ∨ a ≠ 0) (hdA : DvdDec A)
    (hk2 : v₀ 1 ≠ 0) (hπ0 : π ≠ 0)
    (hs : ∀ x : Torsor hI hmax h𝔭 d hπ,
      algebraMap (ReesAlg (compFil hI hmax h𝔭 d)) (Torsor hI hmax h𝔭 d hπ)
        (reesS (compFil hI hmax h𝔭 d) (fun _j hj => compFil_F_nonpos hI hmax h𝔭 d hj)) ∣ x ∨
      ¬ algebraMap (ReesAlg (compFil hI hmax h𝔭 d)) (Torsor hI hmax h𝔭 d hπ)
        (reesS (compFil hI hmax h𝔭 d) (fun _j hj => compFil_F_nonpos hI hmax h𝔭 d hj)) ∣ x) :
    HasGcd (Torsor hI hmax h𝔭 d hπ) ∧ (∀ x : Torsor hI hmax h𝔭 d hπ, x = 0 ∨ x ≠ 0) ∧
      DvdDec (Torsor hI hmax h𝔭 d hπ) := by
  set R := ReesAlg (compFil hI hmax h𝔭 d)
  set s := reesS (compFil hI hmax h𝔭 d) (fun j hj => compFil_F_nonpos hI hmax h𝔭 d hj)
  set y := torsorY hI hmax h𝔭 d hπ
  have := torsor_isDomain hI hmax h𝔭 hπ hπ0
  have : IsLocalization.Away s A[T;T⁻¹] := isLocalization_away_s _ _
  set c : Fin (nGen hI hmax h𝔭 d + 1) → A[T;T⁻¹] := algebraMap R A[T;T⁻¹] ∘ y
  let : Algebra (Torsor hI hmax h𝔭 d hπ) (Jou.J c) := (Jou.map (algebraMap R A[T;T⁻¹]) y).toAlgebra
  have hloc : IsLocalization ((Submonoid.powers s).map (algebraMap R (Jou.J y))) (Jou.J c) :=
    Jou.isLocalization_map y (Submonoid.powers s)
  have : IsLocalization.Away (algebraMap R (Torsor hI hmax h𝔭 d hπ) s) (Jou.J c) := by
    rw [Submonoid.map_powers] at hloc; exact hloc
  -- the base `A[T^±] = A[X][1/X]`, with computed decisions
  have hGB : HasGcd A[T;T⁻¹] := hasGcd_laurent hG hz
  have hzX := polynomial_eq_zero_or hz
  have hdX : DvdDec (Polynomial A) := dvdDec_polynomial hz hdA
  have hzB : ∀ b : A[T;T⁻¹], b = 0 ∨ b ≠ 0 :=
    localization_eq_zero_or hzX (Submonoid.powers (Polynomial.X : Polynomial A))
      (powers_le_nonZeroDivisors_of_noZeroDivisors Polynomial.X_ne_zero) _
  have hA : PolyIndNoeth A := polyIndNoeth_of_finiteType A
  have hAX : PolyIndNoeth (Polynomial A) := hA.of_finiteType
  have hNB : PolyIndNoeth A[T;T⁻¹] :=
    hAX.of_isLocalization (Submonoid.powers (Polynomial.X : Polynomial A))
  have hdB : DvdDec A[T;T⁻¹] :=
    dvdDec_away A[T;T⁻¹] Polynomial.prime_X hzX hdX fun a ha =>
      hAX.indNoeth.exists_val Polynomial.prime_X.not_unit hdX ha
  -- the row, as in `torsor_gcd`
  have hcj : ∀ i, c i = LaurentPolynomial.C (genCoeff hI hmax h𝔭 d π i) *
      T (genDeg hI hmax h𝔭 d i) := fun i => rfl
  have hc0 : c 0 ≠ 0 := by
    rw [hcj]
    simp only [genCoeff, genDeg, Fin.cons_zero]
    intro h
    have := congrArg (fun p : A[T;T⁻¹] => p * T (-1)) h
    simp only [zero_mul, mul_assoc, ← T_add, add_neg_cancel, T_zero, mul_one] at this
    exact hπ0 (by simpa using congrArg (fun p : A[T;T⁻¹] => p.coeff 0) this)
  have hrel : ∀ e : A[T;T⁻¹], (∀ i, e ∣ c i) → IsUnit e := by
    intro e he
    have hdiv : ∀ g ∈ gensF hI hmax h𝔭 d 1, e ∣ LaurentPolynomial.C g * T 1 := fun g hg => by
      obtain ⟨m, hm1, hm2⟩ := exists_index hI hmax h𝔭 (π := π) le_rfl (by exact_mod_cast hd) hg
      have := he m
      rwa [hcj, hm1, hm2] at this
    obtain ⟨g₀, hg₀, hg₀0⟩ := exists_gen_not_dvd hI hmax h𝔭 hd hw hk2 (zero_mem 𝔭)
    have hg₀ne : g₀ ≠ 0 := by rintro rfl; exact hg₀0 dvd_rfl
    have hT1 : (T 1 : A[T;T⁻¹]) * T (-1) = 1 := by rw [← T_add]; simp
    have he0 : e ∣ LaurentPolynomial.C g₀ := by
      obtain ⟨q, hq⟩ := hdiv g₀ hg₀
      exact ⟨q * T (-1), by rw [← mul_assoc, ← hq, mul_assoc, hT1, mul_one]⟩
    obtain ⟨b, n, rfl⟩ := laurent_dvd_C hg₀ne he0
    have hb : IsUnit b := gens_gcd_isUnit hI hmax h𝔭 hd hw hk2 fun g hg =>
      dvd_of_C_mul_T_dvd (hdiv g hg)
    exact (hb.map LaurentPolynomial.C).mul (isUnit_T n)
  obtain ⟨hJ, -, hdJ⟩ := jou_dec c hGB hzB hdB hNB hc0 hrel
  -- the zero test of `U = J_R(y)`, `R ⊆ A[T^±]`
  have hzR : ∀ x : R, x = 0 ∨ x ≠ 0 := fun x => by
    rcases hzB (x : A[T;T⁻¹]) with h | h
    · exact Or.inl (Subtype.ext h)
    · exact Or.inr fun h' => h (by rw [h']; rfl)
  have hzU : ∀ x : Torsor hI hmax h𝔭 d hπ, x = 0 ∨ x ≠ 0 :=
    zeroTest_jou hzR (torsorY_zero_ne hI hmax h𝔭 hπ hπ0)
  -- Nagata at the prime `s`
  have hsp := torsor_s_prime hI hmax h𝔭 hd hw hπ hπ0
  have hdU : DvdDec (Torsor hI hmax h𝔭 d hπ) :=
    dvdDec_of_away (Jou.J c) hsp.ne_zero hzU hs hdJ
  have hIN : IndNoeth (Torsor hI hmax h𝔭 d hπ) := by
    have : Algebra.FiniteType ℚ (Torsor hI hmax h𝔭 d hπ) := torsor_finiteType hI hmax h𝔭 hd hw hπ
    exact (polyIndNoeth_of_finiteType (Torsor hI hmax h𝔭 d hπ)).indNoeth
  exact ⟨hasGcd_of_away hsp (Jou.J c) hzU (fun a ha => hIN.exists_val hsp.not_unit hdU ha) hJ,
    hzU, hdU⟩

end Steps

end BezoutCounterexample.Principalization
