import BezoutCounterexample.Principalization.CentreK
import BezoutCounterexample.Principalization.DualityDec0
import BezoutCounterexample.Constructive.PolyBar

/-!
# Method 1 from one chain condition

The Noetherian hypothesis of HM's Method 1 (`MC.SA.step_data`, `MC.SA.step`, `MC.exists_adm`,
`MC.exists_max`) is used only through (F1) and (F2) of `bezout-direct.tex`. Both follow from one
ring-level hypothesis, `QuotSeqCond R`: the Rees ring of the maximal ideal of every local quotient
of `R`, when finitely generated, satisfies `SeqCond`. (F1) is the case `S = ∅` of (F2), since
then the ideal `(xᵢ : i ∈ S)` is `0`.

`quotSeqCond_of_finiteType`: `QuotSeqCond` holds for every localisation of a finitely generated
`ℚ`-algebra, given `Constructive.PolyBar` (inductive Noetherianity of `ℚ[Y₁, …, Y_N]`,
Coquand–Persson), proved as `Constructive.polyBar`. Hence `MC.exists_max_FT`: Method 1 at a point
of a finitely generated `ℚ`-algebra, without the Noetherian hypothesis.

The downstream files take the hypothesis as an instance `[Fact (QuotSeqCond R)]`, with two
sources:

* `fact_quotSeqCond_atPrime`: `R = Localization.AtPrime P`, `P` a prime of a finitely generated
  `ℚ`-algebra (from `polyBar`; this is the constructive route);
* `fact_quotSeqCond_of_isNoetherianRing` (low priority): any Noetherian `R` (classical: ACC on the
  Rees ring of a f.g. ideal, `seqCond_of_isNoetherianRing`), so that HM's call sites with
  Noetherian local rings keep working unchanged.

The proofs are HM's (copied from `Centre`, suffix `_Q`) with `IsCentred.mem_span_iff` replaced by
`IsCentred.mem_span_iff_of_seqCond` (Perdry–Kuroki, `CentreK`).
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing Constructive

/-- The chain condition behind (F1) and (F2): for every ideal `J` with `R ⧸ J` local and its
maximal ideal finitely generated, the Rees ring of that maximal ideal satisfies `SeqCond`. -/
def QuotSeqCond (R : Type*) [CommRing R] : Prop :=
  ∀ (J : Ideal R) [IsLocalRing (R ⧸ J)] {k : ℕ} (y : Fin k → R ⧸ J),
    maximalIdeal (R ⧸ J) = Ideal.span (Set.range y) →
      SeqCond (reesSubring (maximalIdeal (R ⧸ J)))

/-- **`QuotSeqCond` for localisations of finitely generated `ℚ`-algebras**, from the Hilbert
basis theorem in inductive form. -/
theorem quotSeqCond_of_finiteType (hP : PolyBar) {A : Type*} [CommRing A] [Algebra ℚ A]
    [Algebra.FiniteType ℚ A] (M : Submonoid A) {R : Type*} [CommRing R] [Algebra A R]
    [IsLocalization M R] : QuotSeqCond R := fun J _ _ y hy => by
  rw [hy]; exact seqCond_rees_of_finiteType hP M J y

section Duality

variable {R : Type*} [CommRing R] [Algebra ℚ R] [IsLocalRing R] {n : ℕ}

namespace Chart

variable {c : Chart R n}

/-- The maximal ideal of a local quotient is generated by the images of the coordinates. -/
lemma IsCentred.maximalIdeal_quot (hc : c.IsCentred) (J : Ideal R) [IsLocalRing (R ⧸ J)] :
    maximalIdeal (R ⧸ J) = Ideal.span (Set.range fun i => Ideal.Quotient.mk J (c.x i)) := by
  have hJ : J ≠ ⊤ := Ideal.Quotient.nontrivial_iff.1 inferInstance
  have hrange : Set.range (fun i => Ideal.Quotient.mk J (c.x i)) =
      Ideal.Quotient.mk J '' Set.range c.x := (Set.range_comp _ _)
  rw [hrange, ← Ideal.map_span, ← hc]
  rcases Ideal.map_eq_top_or_isMaximal_of_surjective _ (Ideal.Quotient.mk_surjective (I := J))
    (maximalIdeal.isMaximal R) with htop | hmax
  · exfalso
    have h1 : (1 : R ⧸ J) ∈ Ideal.map (Ideal.Quotient.mk J) (maximalIdeal R) := by
      rw [htop]; trivial
    rw [Ideal.mem_map_iff_of_surjective _ Ideal.Quotient.mk_surjective] at h1
    obtain ⟨r, hr, hr1⟩ := h1
    have h2 : 1 - r ∈ J := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, map_one, hr1, sub_self]
    exact (maximalIdeal.isMaximal R).ne_top ((Ideal.eq_top_iff_one _).2
      (by simpa using add_mem (le_maximalIdeal hJ h2) hr))
  · exact (IsLocalRing.eq_maximalIdeal hmax).symm

/-- **(F2)** from `QuotSeqCond`. -/
theorem IsCentred.mem_span_iff_Q (hc : c.IsCentred) (hQ : QuotSeqCond R) (S : Set (Fin n))
    (g : R) : g ∈ Ideal.span (c.x '' S) ↔
      ∀ δ : Fin n →₀ ℕ, (∀ i ∈ S, δ i = 0) → coeff δ (c.tau g) = 0 :=
  hc.mem_span_iff_of_seqCond S g (hQ _ _ (hc.maximalIdeal_quot _))

/-- **(F2)** from `QuotSeqCond`, for a decidable coordinate set (`mem_span_iff_of_seqCond_dec`,
DualityDec0). -/
theorem IsCentred.mem_span_iff_Q_dec (hc : c.IsCentred) (hQ : QuotSeqCond R) (S : Set (Fin n))
    [DecidablePred (· ∈ S)] (g : R) : g ∈ Ideal.span (c.x '' S) ↔
      ∀ δ : Fin n →₀ ℕ, (∀ i ∈ S, δ i = 0) → coeff δ (c.tau g) = 0 :=
  hc.mem_span_iff_of_seqCond_dec S g (hQ _ _ (hc.maximalIdeal_quot _))

/-- **(F1)** from `QuotSeqCond`: the case `S = ∅` of (F2). -/
lemma IsCentred.tau_injective_Q (hc : c.IsCentred) (hQ : QuotSeqCond R) :
    Function.Injective c.tau := by
  rw [injective_iff_map_eq_zero]
  intro f hf
  have h := (hc.mem_span_iff_Q_dec hQ ∅ f).2 fun δ _ => by rw [hf, map_zero]
  rwa [Set.image_empty, Ideal.span_empty, Ideal.mem_bot] at h

/-- **Rational weighted duality** (residue form) from `QuotSeqCond`. -/
theorem IsCentred.mem_RF_iff_Q (hc : c.IsCentred) (hQ : QuotSeqCond R) {e : Fin n → ℚ}
    (he : ∀ i, 0 ≤ e i) (t : ℚ) (f : R) :
    f ∈ c.RF e t ↔ ∀ β : Fin n →₀ ℕ, lam e β < t → coeff β (c.tau f) = 0 := by
  refine ⟨fun hf β hβ => hc.coeff_tau_eq_zero_of_mem_RF he hf β hβ, fun h => ?_⟩
  rw [c.mem_RF_iff_P he]
  intro β _ hβ
  refine (hc.mem_span_iff_Q_dec hQ {i | e i ≠ 0} _).2 fun δ hδ => ?_
  have hlam : lam e δ = 0 := Finset.sum_eq_zero fun i _ => by
    by_cases hi : e i = 0
    · rw [hi, mul_zero]
    · rw [hδ i hi, Nat.cast_zero, zero_mul]
  rw [← D_mem_max_iff, ← D_add]
  exact (D_mem_max_iff _ _).2 (h _ (by rw [lam_add, hlam, zero_add]; exact hβ))

end Chart

end Duality

section Method1

variable {R : Type*} [CommRing R] [Algebra ℚ R] [IsLocalRing R] {n : ℕ}

namespace MC

variable {I : Ideal R} {j : ℕ} {J : MC R n}


/-- Data of the Method-1 step: the next weight `b₊` and a minimizer `βs`. -/
lemma SA.step_data_Q (hQ : QuotSeqCond R) (hSA : SA I j J) (hna : ¬ J.Adm I) :
    ∃ (hj : j < n) (βs : Fin n →₀ ℕ) (f : R), f ∈ I ∧ coeff βs (J.c.tau f) ≠ 0 ∧
      lam J.e βs < 1 ∧ 0 < tailSum j βs ∧
      (∀ β : Fin n →₀ ℕ, (∃ g ∈ I, coeff β (J.c.tau g) ≠ 0) → lam J.e β < 1 →
        Xi J.e j βs ≤ Xi J.e j β) ∧
      (∀ J' : MC R n, J'.Adm I → (∀ i : Fin n, (i : ℕ) < j → J'.e i = J.e i) →
        0 < J'.e ⟨j, hj⟩ ∧ (1 - lam J.e βs) / tailSum j βs ≤ J'.e ⟨j, hj⟩) ∧
      (∀ i : Fin n, (i : ℕ) < j → (1 - lam J.e βs) / tailSum j βs ≤ J.e i) := by
  classical
  obtain ⟨J₀, hJ₀, hag₀⟩ := hSA.dom0
  obtain ⟨hj, hb₀⟩ := hSA.next_pos hna J₀ hJ₀ hag₀
  have hzero : ∀ i : Fin n, j ≤ (i : ℕ) → J.e i = 0 := fun i hi => hSA.e_eq_zero hi
  set S : Set (Fin n →₀ ℕ) := {β | (∃ g ∈ I, coeff β (J.c.tau g) ≠ 0) ∧ lam J.e β < 1} with hSdef
  -- (F2) enters here, through `IsCentred.mem_RF_iff_Q` for weights with zeros
  have hS : S.Nonempty := by
    by_contra hS
    apply hna
    intro f hf
    rw [RF, J.centred.mem_RF_iff_Q hQ J.nonneg]
    intro β hβ
    by_contra hne
    exact hS ⟨β, ⟨f, hf, hne⟩, hβ⟩
  -- general bound from admissible completions
  have hbound : ∀ J' : MC R n, J'.Adm I → (∀ i : Fin n, (i : ℕ) < j → J'.e i = J.e i) →
      ∀ β ∈ S, 1 ≤ lam J.e β + J'.e ⟨j, hj⟩ * tailSum j β := by
    intro J' hJ' hag β hβ
    obtain ⟨hj', hb'⟩ := hSA.next_pos hna J' hJ' hag
    have hc := hSA.compl_adm J' hJ' hag hj hb'
    have hnn : ∀ i, 0 ≤ compl J.e j (J'.e ⟨j, hj⟩) i := fun i => by
      simp only [compl]; split_ifs
      · exact J.nonneg i
      · exact hb'.le
    obtain ⟨⟨g, hg, hne⟩, -⟩ := hβ
    have := fun hlt => J.centred.coeff_tau_eq_zero_of_mem_RF hnn (hc hg) β hlt
    rw [← lam_compl hzero]
    by_contra hlt; push Not at hlt
    exact hne (this hlt)
  obtain ⟨βs, hβs, hmin⟩ := exists_min_Xi J.nonneg j S hS (fun β hβ => hβ.2)
  obtain ⟨⟨f, hf, hfne⟩, hlt⟩ := hβs
  have h1 := hbound J₀ hJ₀ hag₀ βs ⟨⟨f, hf, hfne⟩, hlt⟩
  have hN : 0 < tailSum j βs := by
    by_contra h0; push Not at h0
    have : tailSum j βs = 0 := by omega
    rw [this, Nat.cast_zero, mul_zero, add_zero] at h1; linarith
  have hNq : (0 : ℚ) < tailSum j βs := by exact_mod_cast hN
  refine ⟨hj, βs, f, hf, hfne, hlt, hN, fun β hβ hβlt => hmin β ⟨hβ, hβlt⟩, ?_, ?_⟩
  · intro J' hJ' hag
    obtain ⟨hj', hb'⟩ := hSA.next_pos hna J' hJ' hag
    refine ⟨hb', ?_⟩
    have := hbound J' hJ' hag βs ⟨⟨f, hf, hfne⟩, hlt⟩
    rw [div_le_iff₀ hNq]; linarith
  · intro i hi
    have hle : (1 - lam J.e βs) / tailSum j βs ≤ J₀.e ⟨j, hj⟩ := by
      rw [div_le_iff₀ hNq]; linarith
    refine hle.trans ?_
    rw [← hag₀ i hi]
    exact J₀.anti (Fin.le_def.2 (by simp only; omega))


/-- **Method 1, inductive step** (Brais, Prop. 3.2.7): a non-admissible `j`-semi-associated marked
centre extends to a `(j+1)`-semi-associated one. -/
theorem SA.step_Q (hQ : QuotSeqCond R) (hSA : SA I j J) (hna : ¬ J.Adm I) :
    ∃ Jp : MC R n, SA I (j + 1) Jp := by
  classical
  obtain ⟨hj, βs, f, hf, hfne, hlt, hN, hmin, hnext, hbJ⟩ := hSA.step_data_Q hQ hna
  set jj : Fin n := ⟨j, hj⟩ with hjj
  set bp : ℚ := (1 - lam J.e βs) / tailSum j βs with hbpdef
  have hNq : (0 : ℚ) < tailSum j βs := by exact_mod_cast hN
  have hbp : 0 < bp := div_pos (by linarith) hNq
  have hzero : ∀ i : Fin n, j ≤ (i : ℕ) → J.e i = 0 := fun i hi => hSA.e_eq_zero hi
  have hkey : lam J.e βs + bp * tailSum j βs = 1 := by
    rw [hbpdef]; field_simp; ring
  have hS_bound : ∀ β : Fin n →₀ ℕ, (∃ g ∈ I, coeff β (J.c.tau g) ≠ 0) → lam J.e β < 1 →
      1 ≤ lam J.e β + bp * tailSum j β := by
    intro β hβ hβlt
    have hX := hmin β hβ hβlt
    simp only [Xi] at hX
    have h1 : 0 < 1 - lam J.e β := by linarith
    have h2 : 0 < 1 - lam J.e βs := by linarith
    rw [div_le_div_iff₀ h2 h1] at hX
    have : 1 - lam J.e β ≤ bp * tailSum j β := by
      rw [hbpdef, div_mul_eq_mul_div, le_div_iff₀ hNq]; linarith
    linarith
  -- the completion is an admissible marked centre
  have hc_nonneg : ∀ i, 0 ≤ compl J.e j bp i := fun i => by
    simp only [compl]; split_ifs
    · exact J.nonneg i
    · exact hbp.le
  have hc_ne : ∀ i, compl J.e j bp i ≠ 0 := fun i => by
    simp only [compl]; split_ifs with h
    · exact (hSA.e_pos h).ne'
    · exact hbp.ne'
  have hc_anti : Antitone (compl J.e j bp) := by
    intro i i' hii'
    simp only [compl]
    by_cases h1 : (i' : ℕ) < j
    · have h2 : (i : ℕ) < j := lt_of_le_of_lt (Fin.le_def.1 hii') h1
      rw [ite_eq_left h1, ite_eq_left h2]; exact J.anti hii'
    · rw [ite_eq_right h1]
      by_cases h2 : (i : ℕ) < j
      · rw [ite_eq_left h2]; exact hbJ i h2
      · rw [ite_eq_right h2]
  have hc_adm : I ≤ J.c.RF (compl J.e j bp) 1 := by
    intro g hg
    rw [J.centred.mem_RF_iff_of_ne hc_nonneg hc_ne]
    intro β hβ
    by_contra hne
    rw [lam_compl hzero] at hβ
    by_cases hβ1 : lam J.e β < 1
    · have := hS_bound β ⟨g, hg, hne⟩ hβ1; linarith
    · have : 0 ≤ bp * tailSum j β := mul_nonneg hbp.le (Nat.cast_nonneg _)
      linarith
  -- the new parameter
  obtain ⟨l, hl, hβl⟩ := tailSum_pos_exists hN
  set γ := βs - Finsupp.single l 1 with hγdef
  have hγ : γ + Finsupp.single l 1 = βs := add_single_sub hβl
  have hlamγ : lam J.e γ = lam J.e βs := by
    rw [← hγ, lam_add, lam_single, hzero l hl, mul_zero, add_zero]
  have htailγ : tailSum j γ + 1 = tailSum j βs := tailSum_sub_single hl hβl
  set xb := J.c.Dv γ f with hxb
  have hdl : J.c.d l xb = ((γ l + 1 : ℕ) : ℚ) • J.c.Dv βs f := by rw [hxb, Chart.d_Dv, hγ]
  have hdl_nm : J.c.d l xb ∉ maximalIdeal R := by
    intro hmem
    rw [hdl, ← residue_eq_zero_iff, map_rat_smul] at hmem
    rw [← Chart.coeff_tau] at hmem
    exact hfne ((smul_eq_zero.1 hmem).resolve_left (by positivity))
  have hxb_mem : xb ∈ maximalIdeal R := by
    rw [hxb, ← residue_eq_zero_iff, ← Chart.coeff_tau]
    by_contra hne
    have hX := hmin γ ⟨f, hf, hne⟩ (by rw [hlamγ]; exact hlt)
    simp only [Xi, hlamγ] at hX
    have h2 : 0 < 1 - lam J.e βs := by linarith
    rw [div_le_div_iff_of_pos_right h2] at hX
    have : ((tailSum j γ : ℕ) : ℚ) + 1 = tailSum j βs := by exact_mod_cast htailγ
    linarith
  obtain ⟨u, hu⟩ := notMem_maximalIdeal.1 hdl_nm
  -- the new chart and weights
  set cp := (J.c.replace l xb u hu.symm).reindex (Equiv.swap jj l) with hcp
  have hcp_centred : cp.IsCentred := (J.centred.replace l xb u hu.symm hxb_mem).reindex _
  set ep : Fin n → ℚ := fun i => if (i : ℕ) < j then J.e i else if (i : ℕ) = j then bp else 0
    with hep
  have hep_nonneg : ∀ i, 0 ≤ ep i := fun i => by
    simp only [hep]; split_ifs
    · exact J.nonneg i
    · exact hbp.le
    · exact le_rfl
  have hep_anti : Antitone ep := by
    intro i i' hii'
    have hle := Fin.le_def.1 hii'
    simp only [hep]
    by_cases h1 : (i' : ℕ) < j
    · rw [ite_eq_left h1, ite_eq_left (lt_of_le_of_lt hle h1)]; exact J.anti hii'
    · rw [ite_eq_right h1]
      by_cases h2 : (i' : ℕ) = j
      · rw [ite_eq_left h2]
        by_cases h3 : (i : ℕ) < j
        · rw [ite_eq_left h3]; exact hbJ i h3
        · rw [ite_eq_right h3, ite_eq_left (by omega)]
      · rw [ite_eq_right h2]
        split_ifs
        · exact J.nonneg i
        · exact hbp.le
        · exact le_rfl
  have hcp_x_lt : ∀ i : Fin n, (i : ℕ) < j → cp.x i = J.c.x i := by
    intro i hi
    have h1 : i ≠ jj := fun h => by rw [h] at hi; simp [hjj] at hi
    have h2 : i ≠ l := fun h => by rw [h] at hi; omega
    rw [hcp, Chart.reindex_x, Equiv.swap_apply_of_ne_of_ne h1 h2, J.c.replace_x_ne _ _ _ _ h2]
  have hcp_x_j : cp.x jj = xb := by
    rw [hcp, Chart.reindex_x, Equiv.swap_apply_left, J.c.replace_x_self]
  refine ⟨⟨cp, ep, hcp_centred, hep_nonneg, hep_anti⟩, ⟨?_, ?_, ?_, ?_⟩⟩
  · -- support
    intro i
    simp only [hep]
    by_cases h1 : (i : ℕ) < j
    · rw [ite_eq_left h1]; exact ⟨fun _ => by omega, fun _ => (hSA.supp i).2 h1⟩
    · rw [ite_eq_right h1]
      by_cases h2 : (i : ℕ) = j
      · rw [ite_eq_left h2]; exact ⟨fun _ => by omega, fun _ => hbp.ne'⟩
      · rw [ite_eq_right h2]; exact ⟨fun h => absurd rfl h, fun h => by omega⟩
  · -- domination by an admissible centre: the completion
    refine ⟨⟨J.c, compl J.e j bp, J.centred, hc_nonneg, hc_anti⟩, hc_adm, fun i hi => ?_⟩
    show compl J.e j bp i = ep i
    simp only [compl, hep]
    by_cases h1 : (i : ℕ) < j
    · rw [ite_eq_left h1, ite_eq_left h1]
    · rw [ite_eq_right h1, ite_eq_right h1, ite_eq_left (by omega)]
  · -- maximality
    intro J' hJ' i hi hbelow
    by_cases h1 : (i : ℕ) < j
    · have : ep i = J.e i := by simp only [hep, ite_eq_left h1]
      show ep i ≤ J'.e i
      rw [this]
      refine hSA.max J' hJ' i h1 fun i' hi' => ?_
      rw [hbelow i' hi']
      simp only [hep, ite_eq_left (lt_trans (Fin.lt_def.1 hi') h1)]
    · have hij : (i : ℕ) = j := by omega
      have hieq : i = jj := Fin.ext hij
      subst hieq
      have hag : ∀ i' : Fin n, (i' : ℕ) < j → J'.e i' = J.e i' := fun i' hi' => by
        rw [hbelow i' (Fin.lt_def.2 hi')]
        simp only [hep, ite_eq_left hi']
      have := (hnext J' hJ' hag).2
      show ep jj ≤ J'.e jj
      simp only [hep, ite_eq_right h1, ite_eq_left hij]
      exact this
  · -- domination
    intro J' hJ' hag
    have hag_j : ∀ i : Fin n, (i : ℕ) < j → J'.e i = J.e i := fun i hi => by
      rw [hag i (by omega)]; show ep i = J.e i; simp only [hep, ite_eq_left hi]
    have hJ'j : J'.e jj = bp := by
      rw [hag jj (by simp [hjj])]; show ep jj = bp; simp [hep, hjj]
    obtain ⟨c'', hc'', hRF, hx⟩ := hSA.dom J' hJ' hag_j
    have hf' : f ∈ c''.RF J'.e 1 := by rw [hRF]; exact hJ' hf
    -- lowering bounds for the derivations of `J.c` with respect to `(c'', J'.e)`
    have hlow : ∀ i, c''.LowersBy J'.e (J.c.d i) (compl J.e j bp i) := by
      intro i
      by_cases hi : (i : ℕ) < j
      · have := hc''.lowersBy_lt (c := J.c) J'.nonneg J'.anti (fun i' hi' => (hx i' hi').symm) i hi
        simp only [compl, ite_eq_left hi]
        rwa [hag_j i hi] at this
      · simp only [compl, ite_eq_right hi]
        refine hc''.lowersBy_ge (c := J.c) J'.nonneg (fun i' hi' => (hx i' hi').symm) i (by omega)
          fun m hm => ?_
        rw [← hJ'j]; exact J'.anti (Fin.le_def.2 (by simp only [hjj, Fin.val_mk]; omega))
    have hxb_RF : xb ∈ c''.RF J'.e bp := by
      have hm1 := Chart.Dv_mem_RF_of_lowersBy c'' J.c J'.e (compl J.e j bp) hlow γ hf'
      rw [lam_compl hzero, hlamγ] at hm1
      have htq : ((tailSum j γ : ℕ) : ℚ) + 1 = tailSum j βs := by exact_mod_cast htailγ
      have hm2 : 1 - (lam J.e βs + bp * (tailSum j γ : ℚ)) = bp := by
        have := hkey; rw [← htq] at this; linarith
      rw [hm2] at hm1
      exact hm1
    -- a coordinate of `c''` in which `xb` has a linear term
    obtain ⟨m, hm, hmnm⟩ : ∃ m : Fin n, j ≤ (m : ℕ) ∧ c''.d m xb ∉ maximalIdeal R := by
      by_contra hcon
      push Not at hcon
      apply hdl_nm
      rw [c''.eq_sum (J.c.d l), Derivation.sum_apply']
      refine Ideal.sum_mem _ fun m _ => ?_
      rw [Derivation.smul_apply, smul_eq_mul]
      by_cases hmj : (m : ℕ) < j
      · rw [hx m hmj, J.c.d_x, ite_eq_right (fun h => by rw [h] at hl; omega), zero_mul]
        exact zero_mem _
      · exact Ideal.mul_mem_left _ _ (hcon m (by omega))
    have hJ'm : J'.e m = bp := by
      refine le_antisymm ?_ ?_
      · rw [← hJ'j]; exact J'.anti (Fin.le_def.2 (by simp only [hjj, Fin.val_mk]; omega))
      · by_contra hlt'
        push Not at hlt'
        have := hc''.coeff_tau_eq_zero_of_mem_RF J'.nonneg hxb_RF (Finsupp.single m 1) (by
          rw [lam_single]; simpa using hlt')
        rw [Chart.coeff_tau_eq_zero_iff, Chart.Dv_single_one] at this
        exact hmnm this
    obtain ⟨u', hu'⟩ := notMem_maximalIdeal.1 hmnm
    refine ⟨(c''.replace m xb u' hu'.symm).reindex (Equiv.swap jj m),
      (hc''.replace m xb u' hu'.symm hxb_mem).reindex _, fun t => ?_, fun i hi => ?_⟩
    · rw [Chart.RF_reindex _ _ (fun i => by
          rcases eq_or_ne i jj with h | h
          · rw [h, Equiv.swap_apply_left, hJ'm, hJ'j]
          · rcases eq_or_ne i m with h' | h'
            · rw [h', Equiv.swap_apply_right, hJ'm, hJ'j]
            · rw [Equiv.swap_apply_of_ne_of_ne h h'])]
      rw [hc''.RF_replace J'.nonneg m xb u' hu'.symm hxb_mem (by rw [hJ'm]; exact hxb_RF), hRF]
    · show ((c''.replace m xb u' hu'.symm).reindex (Equiv.swap jj m)).x i = cp.x i
      by_cases hij : (i : ℕ) < j
      · have h1 : i ≠ jj := fun h => by rw [h] at hij; simp [hjj] at hij
        have h2 : i ≠ m := fun h => by rw [h] at hij; omega
        rw [Chart.reindex_x, Equiv.swap_apply_of_ne_of_ne h1 h2, c''.replace_x_ne _ _ _ _ h2,
          hx i hij, hcp_x_lt i hij]
      · have hieq : i = jj := Fin.ext (by simp [hjj]; omega)
        subst hieq
        rw [Chart.reindex_x, Equiv.swap_apply_left, c''.replace_x_self, hcp_x_j]


/-- An admissible centre exists for a nonzero ideal contained in `𝔪`. -/
lemma exists_adm_Q (hQ : QuotSeqCond R) (hI : I ≠ ⊥) (hIm : I ≤ maximalIdeal R)
    (c : Chart R n) (hc : c.IsCentred) :
    ∃ J : MC R n, J.Adm I := by
  classical
  obtain ⟨f, hfI, hf0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hI
  have hτ : c.tau f ≠ 0 := fun h => hf0 (hc.tau_injective_Q hQ (by rw [h, map_zero]))
  obtain ⟨β, hβ⟩ : ∃ β, coeff β (c.tau f) ≠ 0 := by
    by_contra h; push Not at h; exact hτ (MvPowerSeries.ext fun β => by rw [h β, map_zero])
  have hex : ∃ N : ℕ, ∃ g ∈ I, ∃ β : Fin n →₀ ℕ, coeff β (c.tau g) ≠ 0 ∧ β.degree = N :=
    ⟨_, f, hfI, β, hβ, rfl⟩
  set N := Nat.find hex with hN
  obtain ⟨g, hgI, βg, hβg, hdeg⟩ := Nat.find_spec hex
  have hdeg' : βg.degree = N := hdeg
  have hN1 : 1 ≤ N := by
    by_contra h0
    have : N = 0 := by omega
    rw [this] at hdeg'
    have hdeg := hdeg'
    rw [Finsupp.degree_eq_zero_iff] at hdeg
    subst hdeg
    apply hβg
    rw [coeff_zero_eq_constantCoeff_apply, Chart.constantCoeff_tau, residue_eq_zero_iff]
    exact hIm hgI
  have hNq : (0 : ℚ) < N := by exact_mod_cast hN1
  refine ⟨⟨c, fun _ => 1 / N, hc, fun _ => by positivity, fun _ _ _ => le_rfl⟩, fun h hh => ?_⟩
  rw [RF, hc.mem_RF_iff_of_ne (fun _ => by positivity) (fun _ => (div_pos one_pos hNq).ne')]
  intro β' hβ'
  by_contra hne
  have hlam : lam (fun _ => (1 : ℚ) / N) β' = β'.degree / N := by
    simp only [lam, Finsupp.degree_eq_sum, Nat.cast_sum]
    rw [Finset.sum_div]
    exact Finset.sum_congr rfl fun i _ => by ring
  rw [hlam, div_lt_one hNq] at hβ'
  have : N ≤ β'.degree := Nat.find_min' hex ⟨h, hh, β', hne, rfl⟩
  have : (N : ℚ) ≤ β'.degree := by exact_mod_cast this
  linarith

/-- The zero centre is `0`-semi-associated. -/
lemma sa_zero_Q (hQ : QuotSeqCond R) (hI : I ≠ ⊥) (hIm : I ≤ maximalIdeal R)
    (c : Chart R n) (hc : c.IsCentred) :
    SA I 0 ⟨c, 0, hc, fun _ => le_rfl, fun _ _ _ => le_rfl⟩ := by
  obtain ⟨J₁, hJ₁⟩ := exists_adm_Q hQ hI hIm c hc
  refine ⟨fun i => by simp, ⟨J₁, hJ₁, fun i hi => absurd hi (Nat.not_lt_zero _)⟩,
    fun J' _ i hi => absurd hi (Nat.not_lt_zero _),
    fun J' _ _ => ⟨J'.c, J'.centred, fun _ => rfl, fun i hi => absurd hi (Nat.not_lt_zero _)⟩⟩

/-- Iterating Method 1 produces an admissible semi-associated centre. -/
lemma exists_sa_adm_Q (hQ : QuotSeqCond R) (hI : I ≠ ⊥) (hIm : I ≤ maximalIdeal R)
    (c : Chart R n) (hc : c.IsCentred) :
    ∃ (k : ℕ) (J : MC R n), SA I k J ∧ J.Adm I := by
  have key : ∀ d j, n - j = d → ∀ J : MC R n, SA I j J →
      ∃ (k : ℕ) (J : MC R n), SA I k J ∧ J.Adm I := by
    intro d
    induction d with
    | zero =>
      intro j hj J hJ
      by_cases ha : J.Adm I
      · exact ⟨j, J, hJ, ha⟩
      · obtain ⟨hjn, -⟩ := hJ.step_data_Q hQ ha
        omega
    | succ d ih =>
      intro j hj J hJ
      by_cases ha : J.Adm I
      · exact ⟨j, J, hJ, ha⟩
      · obtain ⟨Jp, hJp⟩ := hJ.step_Q hQ ha
        exact ih (j + 1) (by omega) Jp hJp
  exact key (n - 0) 0 rfl _ (sa_zero_Q hQ hI hIm c hc)

/-- **Uniqueness of the maximal admissible marked centre** (Abramovich–Temkin–Włodarczyk,
Thm. 5.3.1; Brais, Thm. 3.1.1).  For a nonzero ideal `I ⊆ 𝔪` of a local `ℚ`-algebra with
`QuotSeqCond` (instead of Noetherian) and a centred chart, there is an admissible marked centre
whose weights are lexicographically minimal (i.e. whose invariant is maximal), and every
admissible marked centre with the same weights has the same weighted ideals. -/
theorem exists_max_Q (hQ : QuotSeqCond R) (hI : I ≠ ⊥) (hIm : I ≤ maximalIdeal R)
    (c : Chart R n) (hc : c.IsCentred) :
    ∃ J : MC R n, J.Adm I ∧ ∀ J' : MC R n, J'.Adm I →
      toLex J.e ≤ toLex J'.e ∧ (J'.e = J.e → ∀ t, J'.RF t = J.RF t) := by
  obtain ⟨k, J, hSA, hadm⟩ := exists_sa_adm_Q hQ hI hIm c hc
  refine ⟨J, hadm, fun J' hJ' => ⟨?_, fun he t => ?_⟩⟩
  · rw [← not_lt]
    rintro ⟨i, hbelow, hlt⟩
    simp only [Pi.toLex_apply] at hbelow hlt
    by_cases hik : (i : ℕ) < k
    · exact absurd (hSA.max J' hJ' i hik fun i' hi' => hbelow i' hi') (not_le.2 hlt)
    · rw [hSA.e_eq_zero (not_lt.1 hik)] at hlt
      exact absurd (J'.nonneg i) (not_le.2 hlt)
  · obtain ⟨c'', -, hRF, hx⟩ := hSA.dom J' hJ' (fun i _ => by rw [he])
    rw [← hRF, he, RF]
    exact Chart.RF_congr (fun i hi => hx i ((hSA.supp i).1 hi)) t


/-- **Maximal admissible centre at a point of a finitely generated `ℚ`-algebra**, without the
Noetherian hypothesis, from `PolyBar`. -/
theorem exists_max_PB (hP : PolyBar) {A : Type*} [CommRing A] [Algebra ℚ A]
    [Algebra.FiniteType ℚ A] (P : Ideal A) [P.IsPrime] {I : Ideal (Localization.AtPrime P)}
    (hI : I ≠ ⊥) (hIm : I ≤ maximalIdeal _) (c : Chart (Localization.AtPrime P) n)
    (hc : c.IsCentred) :
    ∃ J : MC (Localization.AtPrime P) n, J.Adm I ∧ ∀ J' : MC (Localization.AtPrime P) n,
      J'.Adm I → toLex J.e ≤ toLex J'.e ∧ (J'.e = J.e → ∀ t, J'.RF t = J.RF t) :=
  exists_max_Q (quotSeqCond_of_finiteType hP P.primeCompl) hI hIm c hc

/-- `exists_max_PB` with `PolyBar` discharged (`Constructive.polyBar`). -/
theorem exists_max_FT {A : Type*} [CommRing A] [Algebra ℚ A] [Algebra.FiniteType ℚ A]
    (P : Ideal A) [P.IsPrime] {I : Ideal (Localization.AtPrime P)}
    (hI : I ≠ ⊥) (hIm : I ≤ maximalIdeal _) (c : Chart (Localization.AtPrime P) n)
    (hc : c.IsCentred) :
    ∃ J : MC (Localization.AtPrime P) n, J.Adm I ∧ ∀ J' : MC (Localization.AtPrime P) n,
      J'.Adm I → toLex J.e ≤ toLex J'.e ∧ (J'.e = J.e → ∀ t, J'.RF t = J.RF t) :=
  exists_max_PB polyBar P hI hIm c hc

end MC

end Method1

/-! ### Instances -/

section Instances

/-- ACC gives `SeqCond` (classical). -/
theorem seqCond_of_isNoetherianRing (A : Type*) [CommRing A] [IsNoetherianRing A] :
    SeqCond A := by
  intro s
  let f : ℕ →o Ideal A :=
    ⟨fun m => Ideal.span (Set.range fun i : Fin (m + 1) => s i), fun a b hab =>
      Ideal.span_mono (by rintro _ ⟨i, rfl⟩; exact ⟨⟨i, by omega⟩, rfl⟩)⟩
  obtain ⟨m, hm⟩ := (monotone_stabilizes_iff_noetherian.2 inferInstance) f
  refine ⟨m, ?_⟩
  have h : s (m + 1) ∈ f (m + 1) := Ideal.subset_span ⟨Fin.last _, rfl⟩
  rwa [← hm (m + 1) (Nat.le_succ m)] at h

/-- Noetherian rings satisfy `QuotSeqCond` (classical). -/
theorem quotSeqCond_of_isNoetherianRing (R : Type*) [CommRing R] [IsNoetherianRing R] :
    QuotSeqCond R := fun J _ k y hy => by
  rw [hy]
  have : IsNoetherianRing (reesSubring (Ideal.span (Set.range y))) :=
    isNoetherianRing_of_surjective _ _ (reesHom y) (reesHom_surjective y)
  exact seqCond_of_isNoetherianRing _

instance (priority := 100) fact_quotSeqCond_of_isNoetherianRing (R : Type*) [CommRing R]
    [IsNoetherianRing R] : Fact (QuotSeqCond R) :=
  ⟨quotSeqCond_of_isNoetherianRing R⟩

/-- Points of finitely generated `ℚ`-algebras satisfy `QuotSeqCond`, constructively
(`Constructive.polyBar`). -/
instance fact_quotSeqCond_atPrime {A : Type*} [CommRing A] [Algebra ℚ A]
    [Algebra.FiniteType ℚ A] (P : Ideal A) [P.IsPrime] :
    Fact (QuotSeqCond (Localization.AtPrime P)) :=
  ⟨quotSeqCond_of_finiteType polyBar P.primeCompl⟩

end Instances

end BezoutCounterexample.Principalization
