import BezoutCounterexample.Principalization.Stable

/-!
# The extended Rees algebra of a weighted centre and its chart

Notation 3.4 (`not:rees`) of the paper, locally at a point; used for Lemma 3.5 and Theorem 3.6.

* `MC.SA.step_run_of`: a Method-1 step with a prescribed minimizer.
* `Chart.laurent`: the chart `(x, T)` on `B[T, T⁻¹]`.
* `WFil`, `ReesAlg`: the extended Rees algebra `⊕ F_j T^j` of a multiplicative filtration;
  `chartFil c e d`: the filtration `𝓕_{j/d}` of a weighted chart.
* `reesChart`: the chart `(xᵢ T^{wᵢ}, T⁻¹)` on the Rees algebra (dual derivations
  `T^{-wᵢ} ∂ᵢ` and `T (∑ wᵢ xᵢ ∂ᵢ - T ∂_T)`; `eulerD_sub_mem` is the weighted Euler lemma).
* `rees_adjoin`, `rees_noetherian`: the Rees algebra is generated by the Rees coordinates.
* `vertex`: the vertex point over the closed point of a local ring, generated by the Rees
  coordinates (`vertex_eq_span`), so the localized Rees chart is centred (`reesLoc_isCentred`).
* `reesChart_D_hom`: derivatives of homogeneous elements.
-/

noncomputable section


namespace BezoutCounterexample.Principalization

open MvPowerSeries IsLocalRing

variable {R : Type*} [CommRing R] [Algebra ℚ R] [IsLocalRing R] [Fact (QuotSeqCond R)] {n : ℕ}

namespace MC

variable {I : Ideal R} {j : ℕ} {J : MC R n}

/-- A Method-1 step with a *given* minimizer `βs` (and witness `f`, coordinate `l`). -/
theorem SA.step_run_of (hSA : SA I j J) (hna : ¬ J.Adm I) (βs : Fin n →₀ ℕ) (f : R) (hf : f ∈ I)
    (hfne : coeff βs (J.c.tau f) ≠ 0) (hlt : lam J.e βs < 1) (hN : 0 < tailSum j βs)
    (hmin : ∀ β : Fin n →₀ ℕ, (∃ g ∈ I, coeff β (J.c.tau g) ≠ 0) → lam J.e β < 1 →
      Xi J.e j βs ≤ Xi J.e j β) (l : Fin n) (hl : j ≤ (l : ℕ)) (hβl : βs l ≠ 0) :
    ∃ (hj : j < n) (_ : IsUnit (J.c.D βs f))
      (_ : ∀ i : Fin n, (i : ℕ) < j → nextW J.e j βs ≤ J.e i)
      (u : Rˣ) (hu : J.c.d l (J.c.Dv (βs - Finsupp.single l 1) f) = u)
      (hc : (nextChart J.c ⟨j, hj⟩ l (J.c.Dv (βs - Finsupp.single l 1) f) u hu).IsCentred)
      (hnn : ∀ i, 0 ≤ nextE J.e j (nextW J.e j βs) i)
      (ha : Antitone (nextE J.e j (nextW J.e j βs))),
      SA I (j + 1) ⟨nextChart J.c ⟨j, hj⟩ l (J.c.Dv (βs - Finsupp.single l 1) f) u hu,
        nextE J.e j (nextW J.e j βs), hc, hnn, ha⟩ := by
  classical
  obtain ⟨hj, β₀, f₀, hf₀, hf₀ne, hlt₀, hN₀, hmin₀, hnext₀, hbJ₀⟩ := hSA.step_data_Q Fact.out hna
  have hXi : Xi J.e j βs = Xi J.e j β₀ :=
    le_antisymm (hmin β₀ ⟨f₀, hf₀, hf₀ne⟩ hlt₀) (hmin₀ βs ⟨f, hf, hfne⟩ hlt)
  have hW : (1 - lam J.e βs) / tailSum j βs = (1 - lam J.e β₀) / tailSum j β₀ := by
    have h1 : (1 - lam J.e βs) / tailSum j βs = (Xi J.e j βs)⁻¹ := by rw [Xi, inv_div]
    have h2 : (1 - lam J.e β₀) / tailSum j β₀ = (Xi J.e j β₀)⁻¹ := by rw [Xi, inv_div]
    rw [h1, h2, hXi]
  have hnext : ∀ J' : MC R n, J'.Adm I → (∀ i : Fin n, (i : ℕ) < j → J'.e i = J.e i) →
      0 < J'.e ⟨j, hj⟩ ∧ (1 - lam J.e βs) / tailSum j βs ≤ J'.e ⟨j, hj⟩ := by
    intro J' hJ' hag; rw [hW]; exact hnext₀ J' hJ' hag
  have hbJ : ∀ i : Fin n, (i : ℕ) < j → (1 - lam J.e βs) / tailSum j βs ≤ J.e i := by
    intro i hi; rw [hW]; exact hbJ₀ i hi
  set jj : Fin n := ⟨j, hj⟩ with hjj
  set bp : ℚ := (1 - lam J.e βs) / tailSum j βs with hbpdef
  have hNq : (0 : ℚ) < tailSum j βs := by exact_mod_cast hN
  have hbp : 0 < bp := div_pos (by linarith) hNq
  have hzero : ∀ i : Fin n, j ≤ (i : ℕ) → J.e i = 0 := fun i hi => hSA.e_eq_zero hi
  have hkey : lam J.e βs + bp * tailSum j βs = 1 := by
    rw [hbpdef]; field_simp; ring
  have hS_bound : ∀ β : Fin n →₀ ℕ, (∃ g ∈ I, coeff β (J.c.tau g) ≠ 0) → lam J.e β < 1 →
      1 ≤ lam J.e β + bp * tailSum j β := by
    intro β hβ hβlt
    have hX := hmin β hβ hβlt
    simp only [Xi] at hX
    have h1 : 0 < 1 - lam J.e β := by linarith
    have h2 : 0 < 1 - lam J.e βs := by linarith
    rw [div_le_div_iff₀ h2 h1] at hX
    have : 1 - lam J.e β ≤ bp * tailSum j β := by
      rw [hbpdef, div_mul_eq_mul_div, le_div_iff₀ hNq]; linarith
    linarith
  -- the completion is an admissible marked centre
  have hc_nonneg : ∀ i, 0 ≤ compl J.e j bp i := fun i => by
    simp only [compl]; split_ifs
    · exact J.nonneg i
    · exact hbp.le
  have hc_ne : ∀ i, compl J.e j bp i ≠ 0 := fun i => by
    simp only [compl]; split_ifs with h
    · exact (hSA.e_pos h).ne'
    · exact hbp.ne'
  have hc_anti : Antitone (compl J.e j bp) := by
    intro i i' hii'
    simp only [compl]
    by_cases h1 : (i' : ℕ) < j
    · have h2 : (i : ℕ) < j := lt_of_le_of_lt (Fin.le_def.1 hii') h1
      rw [ite_eq_left h1, ite_eq_left h2]; exact J.anti hii'
    · rw [ite_eq_right h1]
      by_cases h2 : (i : ℕ) < j
      · rw [ite_eq_left h2]; exact hbJ i h2
      · rw [ite_eq_right h2]
  have hc_adm : I ≤ J.c.RF (compl J.e j bp) 1 := by
    intro g hg
    rw [J.centred.mem_RF_iff_of_ne hc_nonneg hc_ne]
    intro β hβ
    by_contra hne
    rw [lam_compl hzero] at hβ
    by_cases hβ1 : lam J.e β < 1
    · have := hS_bound β ⟨g, hg, hne⟩ hβ1; linarith
    · have : 0 ≤ bp * tailSum j β := mul_nonneg hbp.le (Nat.cast_nonneg _)
      linarith
  -- the new parameter
  set γ := βs - Finsupp.single l 1 with hγdef
  have hγ : γ + Finsupp.single l 1 = βs := add_single_sub hβl
  have hlamγ : lam J.e γ = lam J.e βs := by
    rw [← hγ, lam_add, lam_single, hzero l hl, mul_zero, add_zero]
  have htailγ : tailSum j γ + 1 = tailSum j βs := tailSum_sub_single hl hβl
  set xb := J.c.Dv γ f with hxb
  have hdl : J.c.d l xb = ((γ l + 1 : ℕ) : ℚ) • J.c.Dv βs f := by rw [hxb, Chart.d_Dv, hγ]
  have hdl_nm : J.c.d l xb ∉ maximalIdeal R := by
    intro hmem
    rw [hdl, ← residue_eq_zero_iff, map_rat_smul] at hmem
    rw [← Chart.coeff_tau] at hmem
    exact hfne ((smul_eq_zero.1 hmem).resolve_left (by positivity))
  have hxb_mem : xb ∈ maximalIdeal R := by
    rw [hxb, ← residue_eq_zero_iff, ← Chart.coeff_tau]
    by_contra hne
    have hX := hmin γ ⟨f, hf, hne⟩ (by rw [hlamγ]; exact hlt)
    simp only [Xi, hlamγ] at hX
    have h2 : 0 < 1 - lam J.e βs := by linarith
    rw [div_le_div_iff_of_pos_right h2] at hX
    have : ((tailSum j γ : ℕ) : ℚ) + 1 = tailSum j βs := by exact_mod_cast htailγ
    linarith
  obtain ⟨u, hu⟩ := notMem_maximalIdeal.1 hdl_nm
  -- the new chart and weights
  set cp := (J.c.replace l xb u hu.symm).reindex (Equiv.swap jj l) with hcp
  have hcp_centred : cp.IsCentred := (J.centred.replace l xb u hu.symm hxb_mem).reindex _
  set ep : Fin n → ℚ := fun i => if (i : ℕ) < j then J.e i else if (i : ℕ) = j then bp else 0
    with hep
  have hep_nonneg : ∀ i, 0 ≤ ep i := fun i => by
    simp only [hep]; split_ifs
    · exact J.nonneg i
    · exact hbp.le
    · exact le_rfl
  have hep_anti : Antitone ep := by
    intro i i' hii'
    have hle := Fin.le_def.1 hii'
    simp only [hep]
    by_cases h1 : (i' : ℕ) < j
    · rw [ite_eq_left h1, ite_eq_left (lt_of_le_of_lt hle h1)]; exact J.anti hii'
    · rw [ite_eq_right h1]
      by_cases h2 : (i' : ℕ) = j
      · rw [ite_eq_left h2]
        by_cases h3 : (i : ℕ) < j
        · rw [ite_eq_left h3]; exact hbJ i h3
        · rw [ite_eq_right h3, ite_eq_left (by omega)]
      · rw [ite_eq_right h2]
        split_ifs
        · exact J.nonneg i
        · exact hbp.le
        · exact le_rfl
  have hcp_x_lt : ∀ i : Fin n, (i : ℕ) < j → cp.x i = J.c.x i := by
    intro i hi
    have h1 : i ≠ jj := fun h => by rw [h] at hi; simp [hjj] at hi
    have h2 : i ≠ l := fun h => by rw [h] at hi; omega
    rw [hcp, Chart.reindex_x, Equiv.swap_apply_of_ne_of_ne h1 h2, J.c.replace_x_ne _ _ _ _ h2]
  have hcp_x_j : cp.x jj = xb := by
    rw [hcp, Chart.reindex_x, Equiv.swap_apply_left, J.c.replace_x_self]
  have hunitD : IsUnit (J.c.D βs f) := by
    rw [← notMem_maximalIdeal]
    intro hmem
    apply hfne
    rw [Chart.coeff_tau, residue_eq_zero_iff, Chart.Dv, Algebra.smul_def]
    exact Ideal.mul_mem_left _ _ hmem
  refine ⟨hj, hunitD, hbJ, u, hu.symm, hcp_centred, hep_nonneg,
    hep_anti, ⟨?_, ?_, ?_, ?_⟩⟩
  · -- support
    intro i
    show ep i ≠ 0 ↔ (i : ℕ) < j + 1
    simp only [hep]
    by_cases h1 : (i : ℕ) < j
    · rw [ite_eq_left h1]; exact ⟨fun _ => by omega, fun _ => (hSA.supp i).2 h1⟩
    · rw [ite_eq_right h1]
      by_cases h2 : (i : ℕ) = j
      · rw [ite_eq_left h2]; exact ⟨fun _ => by omega, fun _ => hbp.ne'⟩
      · rw [ite_eq_right h2]; exact ⟨fun h => absurd rfl h, fun h => by omega⟩
  · -- domination by an admissible centre: the completion
    refine ⟨⟨J.c, compl J.e j bp, J.centred, hc_nonneg, hc_anti⟩, hc_adm, fun i hi => ?_⟩
    show compl J.e j bp i = ep i
    simp only [compl, hep]
    by_cases h1 : (i : ℕ) < j
    · rw [ite_eq_left h1, ite_eq_left h1]
    · rw [ite_eq_right h1, ite_eq_right h1, ite_eq_left (by omega)]
  · -- maximality
    intro J' hJ' i hi hbelow
    by_cases h1 : (i : ℕ) < j
    · have : ep i = J.e i := by simp only [hep, ite_eq_left h1]
      show ep i ≤ J'.e i
      rw [this]
      refine hSA.max J' hJ' i h1 fun i' hi' => ?_
      rw [hbelow i' hi']
      show ep i' = J.e i'
      simp only [hep, ite_eq_left (lt_trans (Fin.lt_def.1 hi') h1)]
    · have hij : (i : ℕ) = j := by omega
      have hieq : i = jj := Fin.ext hij
      subst hieq
      have hag : ∀ i' : Fin n, (i' : ℕ) < j → J'.e i' = J.e i' := fun i' hi' => by
        rw [hbelow i' (Fin.lt_def.2 hi')]
        show ep i' = J.e i'
        simp only [hep, ite_eq_left hi']
      have := (hnext J' hJ' hag).2
      show ep jj ≤ J'.e jj
      simp only [hep, ite_eq_right h1, ite_eq_left hij]
      exact this
  · -- domination
    intro J' hJ' hag
    have hag_j : ∀ i : Fin n, (i : ℕ) < j → J'.e i = J.e i := fun i hi => by
      rw [hag i (by omega)]; show ep i = J.e i; simp only [hep, ite_eq_left hi]
    have hJ'j : J'.e jj = bp := by
      rw [hag jj (by simp [hjj])]; show ep jj = bp; simp [hep, hjj]
    obtain ⟨c'', hc'', hRF, hx⟩ := hSA.dom J' hJ' hag_j
    have hf' : f ∈ c''.RF J'.e 1 := by rw [hRF]; exact hJ' hf
    -- lowering bounds for the derivations of `J.c` with respect to `(c'', J'.e)`
    have hlow : ∀ i, c''.LowersBy J'.e (J.c.d i) (compl J.e j bp i) := by
      intro i
      by_cases hi : (i : ℕ) < j
      · have := hc''.lowersBy_lt (c := J.c) J'.nonneg J'.anti (fun i' hi' => (hx i' hi').symm) i hi
        simp only [compl, ite_eq_left hi]
        rwa [hag_j i hi] at this
      · simp only [compl, ite_eq_right hi]
        refine hc''.lowersBy_ge (c := J.c) J'.nonneg (fun i' hi' => (hx i' hi').symm) i (by omega)
          fun m hm => ?_
        rw [← hJ'j]; exact J'.anti (Fin.le_def.2 (by simp only [hjj, Fin.val_mk]; omega))
    have hxb_RF : xb ∈ c''.RF J'.e bp := by
      have hm1 := Chart.Dv_mem_RF_of_lowersBy c'' J.c J'.e (compl J.e j bp) hlow γ hf'
      rw [lam_compl hzero, hlamγ] at hm1
      have htq : ((tailSum j γ : ℕ) : ℚ) + 1 = tailSum j βs := by exact_mod_cast htailγ
      have hm2 : 1 - (lam J.e βs + bp * (tailSum j γ : ℚ)) = bp := by
        have := hkey; rw [← htq] at this; linarith
      rw [hm2] at hm1
      exact hm1
    -- a coordinate of `c''` in which `xb` has a linear term
    obtain ⟨m, hm, hmnm⟩ : ∃ m : Fin n, j ≤ (m : ℕ) ∧ c''.d m xb ∉ maximalIdeal R := by
      by_contra hcon
      push Not at hcon
      apply hdl_nm
      rw [c''.eq_sum (J.c.d l), Derivation.sum_apply']
      refine Ideal.sum_mem _ fun m _ => ?_
      rw [Derivation.smul_apply, smul_eq_mul]
      by_cases hmj : (m : ℕ) < j
      · rw [hx m hmj, J.c.d_x, ite_eq_right (fun h => by rw [h] at hl; omega), zero_mul]
        exact zero_mem _
      · exact Ideal.mul_mem_left _ _ (hcon m (by omega))
    have hJ'm : J'.e m = bp := by
      refine le_antisymm ?_ ?_
      · rw [← hJ'j]; exact J'.anti (Fin.le_def.2 (by simp only [hjj, Fin.val_mk]; omega))
      · by_contra hlt'
        push Not at hlt'
        have := hc''.coeff_tau_eq_zero_of_mem_RF J'.nonneg hxb_RF (Finsupp.single m 1) (by
          rw [lam_single]; simpa using hlt')
        rw [Chart.coeff_tau_eq_zero_iff, Chart.Dv_single_one] at this
        exact hmnm this
    obtain ⟨u', hu'⟩ := notMem_maximalIdeal.1 hmnm
    refine ⟨(c''.replace m xb u' hu'.symm).reindex (Equiv.swap jj m),
      (hc''.replace m xb u' hu'.symm hxb_mem).reindex _, fun t => ?_, fun i hi => ?_⟩
    · rw [Chart.RF_reindex _ _ (fun i => by
          rcases eq_or_ne i jj with h | h
          · rw [h, Equiv.swap_apply_left, hJ'm, hJ'j]
          · rcases eq_or_ne i m with h' | h'
            · rw [h', Equiv.swap_apply_right, hJ'm, hJ'j]
            · rw [Equiv.swap_apply_of_ne_of_ne h h'])]
      rw [hc''.RF_replace J'.nonneg m xb u' hu'.symm hxb_mem (by rw [hJ'm]; exact hxb_RF), hRF]
    · show ((c''.replace m xb u' hu'.symm).reindex (Equiv.swap jj m)).x i = cp.x i
      by_cases hij : (i : ℕ) < j
      · have h1 : i ≠ jj := fun h => by rw [h] at hij; simp [hjj] at hij
        have h2 : i ≠ m := fun h => by rw [h] at hij; omega
        rw [Chart.reindex_x, Equiv.swap_apply_of_ne_of_ne h1 h2, c''.replace_x_ne _ _ _ _ h2,
          hx i hij, hcp_x_lt i hij]
      · have hieq : i = jj := Fin.ext (by simp [hjj]; omega)
        subst hieq
        rw [Chart.reindex_x, Equiv.swap_apply_left, c''.replace_x_self, hcp_x_j]


end MC

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section Laurent

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}

instance : IsScalarTower ℚ B[X] B[T;T⁻¹] := IsScalarTower.of_algebraMap_eq fun q => by
  simp only [Polynomial.algebraMap_apply, algebraMap_eq_toLaurent, Polynomial.toLaurent_C]
  rfl

/-- The chart `(x, T)` on `B[T, T⁻¹]`. -/
def Chart.laurent (c : Chart B n) : Chart B[T;T⁻¹] (n + 1) :=
  c.polynomial.localization (Submonoid.powers (X : B[X]))

lemma Chart.laurent_x_last (c : Chart B n) : c.laurent.x (Fin.last n) = T 1 := by
  simp [Chart.laurent]

/-- The coefficientwise derivation. -/
lemma Chart.laurent_d_C (c : Chart B n) (i : Fin n) (b : B) :
    c.laurent.d (Fin.castSucc i) (LaurentPolynomial.C b) = LaurentPolynomial.C (c.d i b) := by
  have h := Chart.localization_d (S := B[T;T⁻¹]) (Submonoid.powers (X : B[X])) c.polynomial
    (Fin.castSucc i) (Polynomial.C b)
  simp only [algebraMap_eq_toLaurent, Polynomial.toLaurent_C, Chart.polynomial_d_castSucc,
    polyExt_C] at h
  exact h

/-- Derivations killing `T` kill all its powers. -/
lemma derivation_T_of {D : Derivation ℚ B[T;T⁻¹] B[T;T⁻¹]} (h : D (T 1) = 0) (m : ℤ) :
    D (T m) = 0 := by
  have hnat : ∀ k : ℕ, D (T k) = 0 := by
    intro k
    have : (T k : B[T;T⁻¹]) = T 1 ^ k := by rw [T_pow, mul_one]
    rw [this, Derivation.leibniz_pow, h]; simp
  rcases Int.eq_nat_or_neg m with ⟨k, rfl | rfl⟩
  · exact hnat k
  · have h1 : (T (-(k : ℤ)) : B[T;T⁻¹]) * T k = 1 := by rw [← T_add, neg_add_cancel, T_zero]
    have h2 := congrArg D h1
    rw [Derivation.leibniz, hnat k, smul_zero, zero_add, Derivation.map_one_eq_zero,
      smul_eq_mul] at h2
    have hu : IsUnit (T k : B[T;T⁻¹]) := isUnit_T _
    exact hu.mul_right_eq_zero.1 h2

/-- The derivative of `T m`. -/
lemma derivation_T_of_one {D : Derivation ℚ B[T;T⁻¹] B[T;T⁻¹]} (h : D (T 1) = 1) (m : ℤ) :
    D (T m) = (m : B[T;T⁻¹]) * T (m - 1) := by
  have hnat : ∀ k : ℕ, D (T k) = (k : B[T;T⁻¹]) * T (k - 1) := by
    intro k
    induction k with
    | zero => simp [T_zero]
    | succ k ih =>
      have : (T ((k + 1 : ℕ) : ℤ) : B[T;T⁻¹]) = T k * T 1 := by rw [← T_add]; push_cast; rfl
      rw [this, Derivation.leibniz, ih, h, smul_eq_mul, smul_eq_mul, mul_one]
      have e1 : (T 1 : B[T;T⁻¹]) * ((k : B[T;T⁻¹]) * T (k - 1)) = (k : B[T;T⁻¹]) * T k := by
        rw [mul_left_comm, ← T_add]; congr 2; ring
      rw [e1]; push_cast
      rw [show ((k : ℤ) + 1 - 1) = k by ring]; ring
  rcases Int.eq_nat_or_neg m with ⟨k, rfl | rfl⟩
  · rw [Int.cast_natCast]; exact hnat k
  · have h1 : (T (-(k : ℤ)) : B[T;T⁻¹]) * T k = 1 := by rw [← T_add, neg_add_cancel, T_zero]
    have h2 := congrArg D h1
    rw [Derivation.leibniz, hnat k, Derivation.map_one_eq_zero, smul_eq_mul, smul_eq_mul] at h2
    have hu : IsUnit (T k : B[T;T⁻¹]) := isUnit_T _
    have e1 : (T (-(k : ℤ)) : B[T;T⁻¹]) * ((k : B[T;T⁻¹]) * T (k - 1)) =
        (k : B[T;T⁻¹]) * T (-1) := by
      rw [mul_left_comm, ← T_add]; congr 2; ring
    have e2 : (T k : B[T;T⁻¹]) * ((((-(k : ℤ)) : ℤ) : B[T;T⁻¹]) * T (-(k : ℤ) - 1)) =
        -((k : B[T;T⁻¹]) * T (-1)) := by
      rw [mul_left_comm, ← T_add, show (k : ℤ) + (-(k : ℤ) - 1) = -1 by ring]
      push_cast; ring
    have h3 : (T k : B[T;T⁻¹]) * D (T (-(k : ℤ))) =
        T k * ((((-(k : ℤ)) : ℤ) : B[T;T⁻¹]) * T (-(k : ℤ) - 1)) := by
      rw [e2]; linear_combination h2 - e1
    exact hu.mul_left_cancel h3

lemma Chart.laurent_d_castSucc_T (c : Chart B n) (i : Fin n) (m : ℤ) :
    c.laurent.d (Fin.castSucc i) (T m) = 0 :=
  derivation_T_of (by rw [← c.laurent_x_last, c.laurent.d_x, ite_eq_right (Fin.castSucc_lt_last i).ne]) m

lemma Chart.laurent_d_last_T (c : Chart B n) (m : ℤ) :
    c.laurent.d (Fin.last n) (T m) = (m : B[T;T⁻¹]) * T (m - 1) :=
  derivation_T_of_one (by rw [← c.laurent_x_last, c.laurent.d_x, ite_eq_left rfl]) m

lemma Chart.laurent_d_last_C (c : Chart B n) (b : B) :
    c.laurent.d (Fin.last n) (LaurentPolynomial.C b) = 0 := by
  have h := Chart.localization_d (S := B[T;T⁻¹]) (Submonoid.powers (X : B[X])) c.polynomial
    (Fin.last n) (Polynomial.C b)
  simp only [algebraMap_eq_toLaurent, Polynomial.toLaurent_C, Chart.polynomial_d_last,
    polyExt_C, Derivation.zero_apply, map_zero] at h
  exact h

end Laurent

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section LaurentCoeff

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}

omit [Algebra ℚ B] in
lemma coeff_C_mul_T (a : B) (m j : ℤ) :
    (LaurentPolynomial.C a * T m : B[T;T⁻¹]).coeff j = if j = m then a else 0 := by
  rw [← single_eq_C_mul_T, AddMonoidAlgebra.coeff_single, Finsupp.single_apply]
  by_cases h : j = m
  · subst h; simp
  · rw [ite_eq_right (Ne.symm h), ite_eq_right h]

omit [Algebra ℚ B] in
lemma coeff_T_mul (p : B[T;T⁻¹]) (m j : ℤ) : (T m * p).coeff j = p.coeff (j - m) := by
  induction p using LaurentPolynomial.induction_on' with
  | add p q hp hq => rw [mul_add, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hp, hq,
      AddMonoidAlgebra.coeff_add, Finsupp.add_apply]
  | C_mul_T l a =>
    rw [mul_left_comm, ← T_add, coeff_C_mul_T, coeff_C_mul_T]
    simp only [sub_eq_iff_eq_add']

lemma Chart.laurent_d_castSucc_coeff (c : Chart B n) (i : Fin n) (p : B[T;T⁻¹]) (j : ℤ) :
    (c.laurent.d (Fin.castSucc i) p).coeff j = c.d i (p.coeff j) := by
  induction p using LaurentPolynomial.induction_on' with
  | add p q hp hq => rw [map_add, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hp, hq,
      AddMonoidAlgebra.coeff_add, Finsupp.add_apply, map_add]
  | C_mul_T m a =>
    rw [Derivation.leibniz, c.laurent_d_castSucc_T, smul_zero, zero_add, c.laurent_d_C,
      smul_eq_mul, mul_comm, coeff_C_mul_T, coeff_C_mul_T]
    split_ifs <;> simp

lemma Chart.laurent_d_last_coeff (c : Chart B n) (p : B[T;T⁻¹]) (j : ℤ) :
    (c.laurent.d (Fin.last n) p).coeff j = ((j + 1 : ℤ) : B) * p.coeff (j + 1) := by
  induction p using LaurentPolynomial.induction_on' with
  | add p q hp hq => rw [map_add, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hp, hq,
      AddMonoidAlgebra.coeff_add, Finsupp.add_apply, mul_add]
  | C_mul_T m a =>
    rw [Derivation.leibniz, c.laurent_d_last_T, c.laurent_d_last_C, smul_zero, add_zero,
      smul_eq_mul, ← mul_assoc, mul_comm (LaurentPolynomial.C a), ← map_intCast
      (LaurentPolynomial.C : B →+* B[T;T⁻¹]), ← map_mul, coeff_C_mul_T, coeff_C_mul_T]
    by_cases h : j = m - 1
    · rw [ite_eq_left h, ite_eq_left (by omega), h]; ring_nf
    · rw [ite_eq_right h, ite_eq_right (by omega), mul_zero]

end LaurentCoeff

section RFlow

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}

/-- Chart derivations lower weighted ideals by the weight of the coordinate (no centredness
needed). -/
lemma Chart.d_mono_mem_RF (c : Chart B n) (e : Fin n → ℚ) (i : Fin n) :
    ∀ α : Fin n →₀ ℕ, (∀ l, e l = 0 → α l = 0) →
      c.d i (∏ l, c.x l ^ α l) ∈ c.RF e (lam e α - e i) := by
  classical
  refine Finsupp.induction_single ?_ fun β j ih => ?_
  · intro _; simp
  · intro hα
    have hβ : ∀ l, e l = 0 → β l = 0 := fun l hl => by
      have := hα l hl; simp only [Finsupp.add_apply] at this; omega
    have hej : e j ≠ 0 := fun h => by
      have := hα j h; simp at this
    rw [prod_pow_add_single, Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.d_x]
    refine add_mem ?_ ?_
    · by_cases hij : i = j
      · subst hij
        rw [ite_eq_left rfl, mul_one]
        refine Ideal.subset_span ⟨β, hβ, ?_, rfl⟩
        rw [lam_add, lam_single]; simp
      · rw [ite_eq_right hij, mul_zero]; exact zero_mem _
    · have h1 := ih hβ
      have h2 := c.x_mem_RF e j hej
      have := c.RF_mul_le e _ _ (Ideal.mul_mem_mul h2 h1)
      convert this using 2
      rw [lam_add, lam_single]; ring

lemma Chart.lowersBy_self (c : Chart B n) {e : Fin n → ℚ} (he : ∀ i, 0 ≤ e i) (i : Fin n) :
    c.LowersBy e (c.d i) (e i) := by
  intro t f hf
  induction hf using Submodule.span_induction with
  | mem g hg =>
    obtain ⟨α, hα0, hαt, rfl⟩ := hg
    exact c.RF_antitone e (by linarith) (c.d_mono_mem_RF e i α hα0)
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul a x hxm hx =>
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    refine add_mem (Ideal.mul_mem_left _ _ hx) ?_
    exact Ideal.mul_mem_right _ _ (c.RF_antitone e (by linarith [he i]) hxm)

end RFlow

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section Rees

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}

omit [Algebra ℚ B] in
lemma coeff_C_mul' (a : B) (p : B[T;T⁻¹]) (m : ℤ) :
    (LaurentPolynomial.C a * p).coeff m = a * p.coeff m := by
  induction p using LaurentPolynomial.induction_on' with
  | add p q hp hq => rw [mul_add, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, hp, hq,
      AddMonoidAlgebra.coeff_add, Finsupp.add_apply, mul_add]
  | C_mul_T l b =>
    rw [← mul_assoc, ← map_mul, coeff_C_mul_T, coeff_C_mul_T]
    split_ifs <;> simp

/-- A multiplicative `ℤ`-filtration by ideals with `F_0 = B`. -/
structure WFil (B : Type*) [CommRing B] where
  F : ℤ → Ideal B
  mul_le : ∀ a b, F a * F b ≤ F (a + b)
  zero_eq : F 0 = ⊤

/-- The extended Rees algebra `⊕_j F_j T^j` of a multiplicative filtration with `F_0 = B`. -/
def ReesAlg (Φ : WFil B) : Subalgebra B B[T;T⁻¹] where
  carrier := {p | ∀ j, p.coeff j ∈ Φ.F j}
  mul_mem' {p q} hp hq j := by
    classical
    rw [AddMonoidAlgebra.coeff_mul]
    simp only [Finsupp.sum]
    refine Ideal.sum_mem _ fun a _ => Ideal.sum_mem _ fun b _ => ?_
    split_ifs with h
    · subst h; exact Φ.mul_le a b (Ideal.mul_mem_mul (hp a) (hq b))
    · exact zero_mem _
  add_mem' {p q} hp hq j := by
    rw [AddMonoidAlgebra.coeff_add, Finsupp.add_apply]; exact add_mem (hp j) (hq j)
  algebraMap_mem' b j := by
    rw [← LaurentPolynomial.C_eq_algebraMap, C_apply]
    split_ifs with h
    · subst h; rw [Φ.zero_eq]; trivial
    · exact zero_mem _

variable {Φ : WFil B}

omit [Algebra ℚ B] in
lemma C_mul_T_mem_ReesAlg {f : B} {j : ℤ} (hf : f ∈ Φ.F j) :
    LaurentPolynomial.C f * T j ∈ ReesAlg Φ := by
  intro m
  rw [coeff_C_mul_T]
  split_ifs with h
  · subst h; exact hf
  · exact zero_mem _

/-- The filtration of a chart with weights `e = w / d`. -/
def chartFil (c : Chart B n) (e : Fin n → ℚ) (d : ℕ) (j : ℤ) : Ideal B := c.RF e ((j : ℚ) / d)

lemma chartFil_mul (c : Chart B n) (e : Fin n → ℚ) (d : ℕ) (a b : ℤ) :
    chartFil c e d a * chartFil c e d b ≤ chartFil c e d (a + b) := by
  refine (c.RF_mul_le e _ _).trans (le_of_eq ?_)
  unfold chartFil; congr 1; push_cast; ring

/-- The weighted Euler operator `E = ∑ wᵢ xᵢ ∂ᵢ`. -/
def eulerD (c : Chart B n) (w : Fin n → ℕ) : Derivation ℚ B B :=
  ∑ i, ((w i : B) * c.x i) • c.d i

lemma eulerD_apply (c : Chart B n) (w : Fin n → ℕ) (f : B) :
    eulerD c w f = ∑ i, (w i : B) * c.x i * c.d i f := by
  rw [eulerD, Derivation.sum_apply']
  simp only [Derivation.smul_apply, smul_eq_mul]

lemma eulerD_mono (c : Chart B n) (w : Fin n → ℕ) :
    ∀ α : Fin n →₀ ℕ, eulerD c w (∏ l, c.x l ^ α l) =
      ((Finsupp.weight w α : ℕ) : B) * ∏ l, c.x l ^ α l := by
  classical
  refine Finsupp.induction_single ?_ fun β j ih => ?_
  · simp
  · rw [prod_pow_add_single, Derivation.leibniz, ih, smul_eq_mul, smul_eq_mul]
    have hx : eulerD c w (c.x j) = (w j : B) * c.x j := by
      rw [eulerD_apply, Finset.sum_eq_single j]
      · rw [c.d_x, ite_eq_left rfl, mul_one]
      · intro b _ hb; rw [c.d_x, ite_eq_right hb, mul_zero]
      · simp
    rw [hx, map_add, Finsupp.weight_single]
    push_cast; ring_nf

/-- **Weighted Euler lemma**: `(E - m)` raises the weight of `𝓕_{m/d}` by `1/d`. -/
lemma eulerD_sub_mem (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} (hd : 0 < d) {w : Fin n → ℕ}
    (hw : ∀ i, (w i : ℚ) = d * e i) (m : ℕ) {f : B} (hf : f ∈ chartFil c e d m) :
    eulerD c w f - (m : B) * f ∈ chartFil c e d (m + 1) := by
  classical
  have hdq : (0 : ℚ) < d := by exact_mod_cast hd
  have hlamw : ∀ α : Fin n →₀ ℕ, lam e α = (Finsupp.weight w α : ℚ) / d := by
    intro α
    rw [lam, Finsupp.weight_eq_sum, eq_div_iff hdq.ne']
    push_cast
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [smul_eq_mul, Nat.cast_mul, hw i]; ring
  -- `E` maps everything into `𝓕_{1/d}`
  have hE1 : ∀ r : B, eulerD c w r ∈ chartFil c e d 1 := by
    intro r
    rw [eulerD_apply]
    refine Ideal.sum_mem _ fun i _ => ?_
    by_cases hwi : w i = 0
    · rw [hwi, Nat.cast_zero, zero_mul, zero_mul]; exact zero_mem _
    · have hei : e i ≠ 0 := by
        intro h; apply hwi; have := hw i; rw [h, mul_zero] at this; exact_mod_cast this
      have hx := c.x_mem_RF e i hei
      have : c.x i ∈ chartFil c e d 1 := by
        refine c.RF_antitone e ?_ hx
        have := hw i
        have h1 : (1 : ℚ) ≤ w i := by exact_mod_cast Nat.one_le_iff_ne_zero.2 hwi
        rw [Int.cast_one, div_le_iff₀ hdq]; linarith
      exact Ideal.mul_mem_right _ _ (Ideal.mul_mem_left _ _ this)
  -- span induction
  have key : ∀ g ∈ chartFil c e d m, eulerD c w g - (m : B) * g ∈ chartFil c e d (m + 1) := by
    intro g hg
    induction hg using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨α, hα0, hαt, rfl⟩ := hx
      rw [eulerD_mono, ← sub_mul]
      have hmono : ∏ l, c.x l ^ α l ∈ c.RF e (lam e α) :=
        Ideal.subset_span ⟨α, hα0, le_rfl, rfl⟩
      have hαt' : (m : ℚ) ≤ Finsupp.weight w α := by
        have h1 := hαt
        rw [hlamw, Int.cast_natCast, div_le_div_iff_of_pos_right hdq] at h1
        exact h1
      rcases Nat.lt_or_ge m (Finsupp.weight w α) with hlt | hge
      · refine Ideal.mul_mem_left _ _ (c.RF_antitone e ?_ hmono)
        rw [hlamw]; push_cast
        rw [div_le_div_iff_of_pos_right hdq]; exact_mod_cast hlt
      · have : Finsupp.weight w α = m := le_antisymm hge (by exact_mod_cast hαt')
        rw [this, sub_self, zero_mul]; exact zero_mem _
    | zero => simp
    | add x y _ _ hx hy =>
      rw [map_add, mul_add, add_sub_add_comm]; exact add_mem hx hy
    | smul a x hxm hx =>
      rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      have e1 : a * eulerD c w x + x * eulerD c w a - (m : B) * (a * x) =
          a * (eulerD c w x - (m : B) * x) + x * eulerD c w a := by ring
      rw [e1]
      refine add_mem (Ideal.mul_mem_left _ _ hx) ?_
      have := chartFil_mul c e d m 1 (Ideal.mul_mem_mul hxm (hE1 a))
      exact this
  exact key f hf

end Rees

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section ReesDer

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}

/-- Restriction of a derivation to a subalgebra it preserves. -/
def derivRestrict {L : Type*} [CommRing L] [Algebra B L] [Algebra ℚ L] [IsScalarTower ℚ B L]
    (A : Subalgebra B L) (D : Derivation ℚ L L) (h : ∀ x ∈ A, D x ∈ A) : Derivation ℚ A A where
  toFun x := ⟨D (x : L), h _ x.2⟩
  map_add' x y := Subtype.ext (map_add D (x : L) y)
  map_smul' q x := Subtype.ext (by
    change D (q • (x : L)) = q • D (x : L)
    exact D.map_smul q (x : L))
  map_one_eq_zero' := Subtype.ext D.map_one_eq_zero
  leibniz' x y := Subtype.ext (by
    change D ((x : L) * y) = (x : L) * D y + (y : L) * D x
    rw [D.leibniz, smul_eq_mul, smul_eq_mul])

@[simp] lemma derivRestrict_apply {L : Type*} [CommRing L] [Algebra B L] [Algebra ℚ L]
    [IsScalarTower ℚ B L] (A : Subalgebra B L) (D : Derivation ℚ L L) (h : ∀ x ∈ A, D x ∈ A)
    (x : A) : (derivRestrict A D h x : L) = D (x : L) := rfl

/-- The `u`-derivations of the Rees chart on `B[T, T⁻¹]`. -/
def reesDu (c : Chart B n) (w : Fin n → ℕ) (i : Fin n) : Derivation ℚ B[T;T⁻¹] B[T;T⁻¹] :=
  (T (-(w i : ℤ)) : B[T;T⁻¹]) • c.laurent.d (Fin.castSucc i)

/-- The Euler operator `∑ wᵢ xᵢ ∂ᵢ` on `B[T, T⁻¹]`. -/
def reesEx (c : Chart B n) (w : Fin n → ℕ) : Derivation ℚ B[T;T⁻¹] B[T;T⁻¹] :=
  ∑ i, (LaurentPolynomial.C ((w i : B) * c.x i)) • c.laurent.d (Fin.castSucc i)

/-- The `s`-derivation of the Rees chart: `T (E_x - T ∂_T)`. -/
def reesDs (c : Chart B n) (w : Fin n → ℕ) : Derivation ℚ B[T;T⁻¹] B[T;T⁻¹] :=
  (T 1 : B[T;T⁻¹]) • (reesEx c w - (T 1 : B[T;T⁻¹]) • c.laurent.d (Fin.last n))

lemma reesDu_coeff (c : Chart B n) (w : Fin n → ℕ) (i : Fin n) (p : B[T;T⁻¹]) (j : ℤ) :
    (reesDu c w i p).coeff j = c.d i (p.coeff (j + w i)) := by
  rw [reesDu, Derivation.smul_apply, smul_eq_mul, coeff_T_mul, c.laurent_d_castSucc_coeff]
  congr 2; ring

lemma reesEx_coeff (c : Chart B n) (w : Fin n → ℕ) (p : B[T;T⁻¹]) (j : ℤ) :
    (reesEx c w p).coeff j = eulerD c w (p.coeff j) := by
  rw [reesEx, Derivation.sum_apply', eulerD_apply]
  rw [show (∑ i, ((LaurentPolynomial.C ((w i : B) * c.x i)) • c.laurent.d (Fin.castSucc i)) p) =
      ∑ i, LaurentPolynomial.C ((w i : B) * c.x i) * c.laurent.d (Fin.castSucc i) p from
    Finset.sum_congr rfl fun i _ => by rw [Derivation.smul_apply, smul_eq_mul]]
  rw [AddMonoidAlgebra.coeff_sum, Finset.sum_apply']
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [coeff_C_mul', c.laurent_d_castSucc_coeff]

lemma reesDs_coeff (c : Chart B n) (w : Fin n → ℕ) (p : B[T;T⁻¹]) (j : ℤ) :
    (reesDs c w p).coeff j =
      eulerD c w (p.coeff (j - 1)) - ((j - 1 : ℤ) : B) * p.coeff (j - 1) := by
  rw [reesDs, Derivation.smul_apply, smul_eq_mul, coeff_T_mul, Derivation.sub_apply,
    AddMonoidAlgebra.coeff_sub, Finsupp.sub_apply, reesEx_coeff, Derivation.smul_apply,
    smul_eq_mul, coeff_T_mul, c.laurent_d_last_coeff]
  congr 2
  · push_cast; ring
  · ring_nf

variable {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ} {Φ : WFil B}

lemma reesDu_mem (c : Chart B n) (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i)
    (hd : 0 < d) (hw : ∀ i, (w i : ℚ) = d * e i) (i : Fin n) :
    ∀ p ∈ ReesAlg Φ, reesDu c w i p ∈ ReesAlg Φ := by
  intro p hp j
  rw [reesDu_coeff, hF]
  have h := hp (j + w i)
  rw [hF] at h
  have h2 := c.lowersBy_self he i _ _ h
  have hdq : (0 : ℚ) < d := by exact_mod_cast hd
  convert h2 using 2
  rw [show e i = (w i : ℚ) / d by rw [hw i]; field_simp]
  push_cast; field_simp
  simp only [chartFil]; congr 1; ring

lemma reesDs_mem (c : Chart B n) (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i)
    (hd : 0 < d) (hw : ∀ i, (w i : ℚ) = d * e i) :
    ∀ p ∈ ReesAlg Φ, reesDs c w p ∈ ReesAlg Φ := by
  intro p hp j
  rw [reesDs_coeff]
  by_cases hj : j ≤ 0
  · rw [hF, chartFil, c.RF_of_nonpos he (by
      have : (j : ℚ) ≤ 0 := by exact_mod_cast hj
      exact div_nonpos_of_nonpos_of_nonneg this (Nat.cast_nonneg _))]
    trivial
  · obtain ⟨m, hm⟩ : ∃ m : ℕ, j - 1 = m := ⟨(j - 1).toNat, by omega⟩
    have h := hp (j - 1)
    rw [hF, hm] at h
    have := eulerD_sub_mem c hd hw m h
    rw [hF, hm, show j = ((m + 1 : ℕ) : ℤ) by omega]
    rw [Int.cast_natCast]
    exact this

lemma reesU_mem (c : Chart B n) (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i)
    (hd : 0 < d) (hw : ∀ i, (w i : ℚ) = d * e i) (i : Fin n) :
    LaurentPolynomial.C (c.x i) * T (w i) ∈ ReesAlg Φ := by
  apply C_mul_T_mem_ReesAlg
  rw [hF, chartFil]
  have hdq : (0 : ℚ) < d := by exact_mod_cast hd
  by_cases hei : e i = 0
  · rw [c.RF_of_nonpos he (by
      have : (w i : ℚ) = 0 := by rw [hw i, hei, mul_zero]
      rw [Int.cast_natCast, this, zero_div])]
    trivial
  · have h := c.x_mem_RF e i hei
    convert h using 2
    rw [Int.cast_natCast, hw i]; field_simp

lemma reesS_mem (c : Chart B n) (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) :
    (T (-1) : B[T;T⁻¹]) ∈ ReesAlg Φ := by
  have : (T (-1) : B[T;T⁻¹]) = LaurentPolynomial.C 1 * T (-1) := by rw [map_one, one_mul]
  rw [this]
  apply C_mul_T_mem_ReesAlg
  rw [hF, chartFil, c.RF_of_nonpos he (by
    have : ((-1 : ℤ) : ℚ) = -1 := by norm_num
    rw [this]; exact div_nonpos_of_nonpos_of_nonneg (by norm_num) (Nat.cast_nonneg _))]
  trivial

end ReesDer

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section ReesChart

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

lemma eulerD_x (w : Fin n → ℕ) (b : Fin n) : eulerD c w (c.x b) = (w b : B) * c.x b := by
  rw [eulerD_apply, Finset.sum_eq_single b]
  · rw [c.d_x, ite_eq_left rfl, mul_one]
  · intro a _ hab; rw [c.d_x, ite_eq_right hab, mul_zero]
  · simp

omit [Algebra ℚ B] in
lemma coeff_one_laurent (j : ℤ) : (1 : B[T;T⁻¹]).coeff j = if j = 0 then 1 else 0 := by
  rw [← T_zero, T_apply]; simp [eq_comm]

/-- The coordinates of the Rees chart: `uᵢ = xᵢ T^{wᵢ}` and `s = T⁻¹` (last). -/
def reesX : Fin (n + 1) → ReesAlg Φ :=
  Fin.lastCases ⟨T (-1), reesS_mem c hF he⟩
    (fun i => ⟨LaurentPolynomial.C (c.x i) * T (w i), reesU_mem c hF he hd hw i⟩)

/-- The derivations of the Rees chart. -/
def reesDer : Fin (n + 1) → Derivation ℚ (ReesAlg Φ) (ReesAlg Φ) :=
  Fin.lastCases (derivRestrict _ (reesDs c w) (reesDs_mem c hF he hd hw))
    (fun i => derivRestrict _ (reesDu c w i) (reesDu_mem c hF he hd hw i))

@[simp] lemma reesX_last : (reesX c hF he hd hw (Fin.last n) : B[T;T⁻¹]) = T (-1) := by
  simp [reesX]

@[simp] lemma reesX_castSucc (i : Fin n) :
    (reesX c hF he hd hw (Fin.castSucc i) : B[T;T⁻¹]) = LaurentPolynomial.C (c.x i) * T (w i) := by
  simp [reesX]

@[simp] lemma reesDer_last (p : ReesAlg Φ) :
    (reesDer c hF he hd hw (Fin.last n) p : B[T;T⁻¹]) = reesDs c w p := by
  simp [reesDer]

@[simp] lemma reesDer_castSucc (i : Fin n) (p : ReesAlg Φ) :
    (reesDer c hF he hd hw (Fin.castSucc i) p : B[T;T⁻¹]) = reesDu c w i p := by
  simp [reesDer]

lemma reesDer_reesX (i j : Fin (n + 1)) :
    reesDer c hF he hd hw i (reesX c hF he hd hw j) = if i = j then 1 else 0 := by
  apply Subtype.ext
  apply LaurentPolynomial.ext
  intro m
  have h1 : ((1 : ReesAlg Φ) : B[T;T⁻¹]) = 1 := rfl
  have h0' : ((0 : ReesAlg Φ) : B[T;T⁻¹]) = 0 := rfl
  cases i using Fin.lastCases with
  | last =>
    cases j using Fin.lastCases with
    | last =>
      rw [reesDer_last, reesX_last, reesDs_coeff, ite_eq_left rfl, h1, coeff_one_laurent, T_apply]
      by_cases hm : m = 0
      · subst hm; simp
      · rw [ite_eq_right (by omega), ite_eq_right hm]; simp
    | cast b =>
      rw [reesDer_last, reesX_castSucc, reesDs_coeff, ite_eq_right (Fin.castSucc_lt_last b).ne', h0',
        coeff_C_mul_T]
      split_ifs with h
      · rw [eulerD_x, h]; push_cast; simp
      · simp
  | cast a =>
    cases j using Fin.lastCases with
    | last =>
      rw [reesDer_castSucc, reesX_last, reesDu_coeff, ite_eq_right (Fin.castSucc_lt_last a).ne, h0',
        T_apply]
      split_ifs <;> simp
    | cast b =>
      rw [reesDer_castSucc, reesX_castSucc, reesDu_coeff, coeff_C_mul_T]
      by_cases hab : a = b
      · subst hab
        rw [ite_eq_left rfl, h1, coeff_one_laurent]
        by_cases hm : m = 0
        · subst hm; simp [c.d_x_self]
        · rw [ite_eq_right (by omega), ite_eq_right hm, map_zero]
      · rw [ite_eq_right (fun h => hab (Fin.castSucc_injective _ h)), h0']
        split_ifs
        · rw [c.d_x_ne hab]; simp
        · simp

end ReesChart

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section ReesSpan

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

local notation "RA" => ReesAlg Φ
local notation "Dk" => KaehlerDifferential.D ℚ (ReesAlg Φ)

lemma reesX_castSucc_mul_pow (i : Fin n) :
    algebraMap B RA (c.x i) =
      reesX c hF he hd hw (Fin.castSucc i) * reesX c hF he hd hw (Fin.last n) ^ w i := by
  apply Subtype.ext
  rw [Subalgebra.coe_mul, SubmonoidClass.coe_pow, reesX_castSucc, reesX_last, T_pow, mul_assoc,
    ← T_add, show (w i : ℤ) + ((w i : ℕ) : ℤ) * (-1) = 0 by ring, T_zero, mul_one,
    Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap]

end ReesSpan

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial

section ReesSpan2

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

omit [Algebra ℚ B] in
lemma prod_T_eq {ι : Type*} (s : Finset ι) (f : ι → ℤ) :
    ∏ i ∈ s, (T (f i) : B[T;T⁻¹]) = T (∑ i ∈ s, f i) := by
  show (s.val.map fun i => (T (f i) : B[T;T⁻¹])).prod = T ((s.val.map f).sum)
  induction s.val using Multiset.induction_on with
  | empty => simp [T_zero]
  | cons a m ih => rw [Multiset.map_cons, Multiset.map_cons, Multiset.prod_cons,
      Multiset.sum_cons, ih, ← T_add]

theorem reesX_span :
    Submodule.span (ReesAlg Φ) (Set.range fun i =>
      KaehlerDifferential.D ℚ (ReesAlg Φ) (reesX c hF he hd hw i)) = ⊤ := by
  classical
  set W := Submodule.span (ReesAlg Φ) (Set.range fun i =>
      KaehlerDifferential.D ℚ (ReesAlg Φ) (reesX c hF he hd hw i)) with hWdef
  have hX : ∀ i, KaehlerDifferential.D ℚ (ReesAlg Φ) (reesX c hF he hd hw i) ∈ W :=
    fun i => Submodule.subset_span ⟨i, rfl⟩
  have hmul : ∀ x y : ReesAlg Φ, KaehlerDifferential.D ℚ (ReesAlg Φ) x ∈ W →
      KaehlerDifferential.D ℚ (ReesAlg Φ) y ∈ W →
      KaehlerDifferential.D ℚ (ReesAlg Φ) (x * y) ∈ W := fun x y hx hy => by
    rw [Derivation.leibniz]; exact W.add_mem (W.smul_mem _ hy) (W.smul_mem _ hx)
  have hpow : ∀ (x : ReesAlg Φ) (k : ℕ), KaehlerDifferential.D ℚ (ReesAlg Φ) x ∈ W →
      KaehlerDifferential.D ℚ (ReesAlg Φ) (x ^ k) ∈ W := fun x k hx => by
    rw [Derivation.leibniz_pow]; exact nsmul_mem (W.smul_mem _ hx) _
  have hprod : ∀ (s : Finset (Fin n)) (g : Fin n → ReesAlg Φ),
      (∀ i ∈ s, KaehlerDifferential.D ℚ (ReesAlg Φ) (g i) ∈ W) →
      KaehlerDifferential.D ℚ (ReesAlg Φ) (∏ i ∈ s, g i) ∈ W := by
    intro s g hg
    induction s using Finset.induction_on with
    | empty => rw [Finset.prod_empty, Derivation.map_one_eq_zero]; exact W.zero_mem
    | insert a s ha ih =>
      rw [Finset.prod_insert ha]
      exact hmul _ _ (hg a (Finset.mem_insert_self _ _))
        (ih fun i hi => hg i (Finset.mem_insert_of_mem hi))
  -- Step 1: constants
  have hB : ∀ b : B, KaehlerDifferential.D ℚ (ReesAlg Φ) (algebraMap B (ReesAlg Φ) b) ∈ W := by
    intro b
    have h1 : KaehlerDifferential.D ℚ (ReesAlg Φ) (algebraMap B (ReesAlg Φ) b) =
        KaehlerDifferential.map ℚ ℚ B (ReesAlg Φ) (KaehlerDifferential.D ℚ B b) :=
      (KaehlerDifferential.map_D ℚ ℚ B (ReesAlg Φ) b).symm
    rw [h1, c.kD_eq_sum b, map_sum]
    refine W.sum_mem fun i _ => ?_
    rw [map_smul, KaehlerDifferential.map_D, ← algebraMap_smul (ReesAlg Φ) (c.d i b)]
    refine W.smul_mem _ ?_
    rw [reesX_castSucc_mul_pow c hF he hd hw i]
    exact hmul _ _ (hX _) (hpow _ _ (hX _))
  -- Step 2: homogeneous elements
  have hdq : (0 : ℚ) < d := by exact_mod_cast hd
  have hhom : ∀ (j : ℤ) (f : B) (hf : LaurentPolynomial.C f * T j ∈ ReesAlg Φ),
      f ∈ Φ.F j → KaehlerDifferential.D ℚ (ReesAlg Φ) ⟨_, hf⟩ ∈ W := by
    intro j f hf hfF
    by_cases hj : j ≤ 0
    · obtain ⟨k, hk⟩ : ∃ k : ℕ, j = -(k : ℤ) := ⟨(-j).toNat, by omega⟩
      have : (⟨_, hf⟩ : ReesAlg Φ) = algebraMap B (ReesAlg Φ) f *
          reesX c hF he hd hw (Fin.last n) ^ k := by
        apply Subtype.ext
        show LaurentPolynomial.C f * T j = _
        rw [Subalgebra.coe_mul, SubmonoidClass.coe_pow, reesX_last, T_pow,
          Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap, hk]
        congr 2; ring
      rw [this]; exact hmul _ _ (hB f) (hpow _ _ (hX _))
    · -- `f ∈ 𝓕_{j/d}` is a combination of monomials of weight `≥ j`
      have hmemF : ∀ x ∈ Submodule.span B {f | ∃ α : Fin n →₀ ℕ, (∀ i, e i = 0 → α i = 0) ∧
          ((j : ℚ) / d) ≤ lam e α ∧ f = ∏ i, c.x i ^ α i}, x ∈ Φ.F j := fun x hx => by
        rw [hF, chartFil, Chart.RF]; exact hx
      rw [hF, chartFil, Chart.RF] at hfF
      revert hf
      induction hfF using Submodule.span_induction with
      | mem g hg =>
        intro hf
        obtain ⟨α, hα0, hαt, rfl⟩ := hg
        have hwα : (j : ℤ) ≤ Finsupp.weight w α := by
          have hlamw : lam e α = (Finsupp.weight w α : ℚ) / d := by
            rw [lam, Finsupp.weight_eq_sum, eq_div_iff hdq.ne']
            push_cast
            rw [Finset.sum_mul]
            refine Finset.sum_congr rfl fun i _ => ?_
            rw [smul_eq_mul, Nat.cast_mul, hw i]; ring
          rw [hlamw, div_le_div_iff_of_pos_right hdq] at hαt
          exact_mod_cast hαt
        obtain ⟨m, hm⟩ : ∃ m : ℕ, (Finsupp.weight w α : ℤ) - j = m := ⟨_, (Int.toNat_of_nonneg
          (by omega)).symm⟩
        have : (⟨_, hf⟩ : ReesAlg Φ) = (∏ i, reesX c hF he hd hw (Fin.castSucc i) ^ α i) *
            reesX c hF he hd hw (Fin.last n) ^ m := by
          apply Subtype.ext
          show LaurentPolynomial.C (∏ i, c.x i ^ α i) * T j = _
          rw [Subalgebra.coe_mul, SubmonoidClass.coe_pow, reesX_last, T_pow,
            SubmonoidClass.coe_finsetProd]
          simp only [SubmonoidClass.coe_pow, reesX_castSucc, mul_pow, T_pow, ← map_pow]
          rw [Finset.prod_mul_distrib, ← map_prod, prod_T_eq, mul_assoc, ← T_add]
          congr 2
          have : ((Finsupp.weight w α : ℕ) : ℤ) = ∑ i, ((α i : ℕ) : ℤ) * ((w i : ℕ) : ℤ) := by
            rw [Finsupp.weight_eq_sum]; push_cast; rfl
          linarith
        rw [this]
        exact hmul _ _ (hprod _ _ fun i _ => hpow _ _ (hX _)) (hpow _ _ (hX _))
      | zero =>
        intro hf
        have : (⟨_, hf⟩ : ReesAlg Φ) = 0 := Subtype.ext (by simp)
        rw [this, map_zero]; exact W.zero_mem
      | add x y hx hy ihx ihy =>
        intro hf
        have hxR : LaurentPolynomial.C x * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF x hx)
        have hyR : LaurentPolynomial.C y * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF y hy)
        have : (⟨_, hf⟩ : ReesAlg Φ) = ⟨_, hxR⟩ + ⟨_, hyR⟩ :=
          Subtype.ext (by show LaurentPolynomial.C (x + y) * T j = _; rw [map_add, add_mul]; rfl)
        rw [this, map_add]; exact W.add_mem (ihx hxR) (ihy hyR)
      | smul a x hx ih =>
        intro hf
        have hxR : LaurentPolynomial.C x * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF x hx)
        have : (⟨_, hf⟩ : ReesAlg Φ) = algebraMap B (ReesAlg Φ) a * ⟨_, hxR⟩ :=
          Subtype.ext (by
            show LaurentPolynomial.C (a • x) * T j = _
            rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap,
              smul_eq_mul, map_mul, mul_assoc])
        rw [this]; exact hmul _ _ (hB a) (ih hxR)
  -- Step 3: every element is a finite sum of homogeneous ones
  rw [eq_top_iff, ← KaehlerDifferential.span_range_derivation, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  have hdecomp : p = ∑ j ∈ (p : B[T;T⁻¹]).coeff.support,
      (⟨LaurentPolynomial.C ((p : B[T;T⁻¹]).coeff j) * T j,
        C_mul_T_mem_ReesAlg (p.2 j)⟩ : ReesAlg Φ) := by
    apply Subtype.ext
    rw [AddSubmonoidClass.coe_finsetSum]
    conv_lhs => rw [← AddMonoidAlgebra.sum_coeff_single (p : B[T;T⁻¹])]
    rw [Finsupp.sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [single_eq_C_mul_T]
  rw [hdecomp, map_sum]
  exact W.sum_mem fun j _ => hhom j _ _ (p.2 j)

end ReesSpan2

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial IsLocalRing

section ReesChartDef

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

/-- **The Rees chart** `(xᵢ T^{wᵢ}, T⁻¹)` on the extended Rees algebra. -/
def reesChart : Chart (ReesAlg Φ) (n + 1) where
  x := reesX c hF he hd hw
  d := reesDer c hF he hd hw
  d_x := reesDer_reesX c hF he hd hw
  span := reesX_span c hF he hd hw

@[simp] lemma reesChart_x : (reesChart c hF he hd hw).x = reesX c hF he hd hw := rfl
@[simp] lemma reesChart_d : (reesChart c hF he hd hw).d = reesDer c hF he hd hw := rfl

end ReesChartDef

section Vertex

variable {B : Type*} [CommRing B] [Algebra ℚ B] [IsLocalRing B] {Φ : WFil B}

/-- The degree-`0` coefficient modulo `𝔪`, a ring map on the Rees algebra when `F_j ⊆ 𝔪` for
`j > 0`. -/
def vtx (hpos : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B) : ReesAlg Φ →+* ResidueField B where
  toFun p := residue B ((p : B[T;T⁻¹]).coeff 0)
  map_one' := by
    rw [show ((1 : ReesAlg Φ) : B[T;T⁻¹]) = 1 from rfl, coeff_one_laurent, ite_eq_left rfl, map_one]
  map_mul' p q := by
    classical
    rw [show ((p * q : ReesAlg Φ) : B[T;T⁻¹]) = (p : B[T;T⁻¹]) * q from rfl,
      AddMonoidAlgebra.coeff_mul]
    simp only [Finsupp.sum, map_sum]
    rw [Finset.sum_eq_single (0 : ℤ), Finset.sum_eq_single (0 : ℤ)]
    · simp
    · intro b _ hb; rw [ite_eq_right (by simpa using hb), map_zero]
    · intro h; rw [Finsupp.notMem_support_iff] at h; simp [h]
    · intro a _ ha
      refine Finset.sum_eq_zero fun b _ => ?_
      split_ifs with hab
      · rw [map_mul]
        rcases lt_or_gt_of_ne ha with ha' | ha'
        · have hb : 0 < b := by omega
          rw [(residue_eq_zero_iff _).2 (hpos b hb (q.2 b)), mul_zero]
        · rw [(residue_eq_zero_iff _).2 (hpos a ha' (p.2 a)), zero_mul]
      · exact map_zero _
    · intro h; rw [Finsupp.notMem_support_iff] at h
      refine Finset.sum_eq_zero fun b _ => ?_
      split_ifs <;> simp [h]
  map_zero' := by simp
  map_add' p q := by
    rw [show ((p + q : ReesAlg Φ) : B[T;T⁻¹]) = (p : B[T;T⁻¹]) + q from rfl,
      AddMonoidAlgebra.coeff_add, Finsupp.add_apply, map_add]

omit [Algebra ℚ B] in
lemma vtx_surjective (hpos : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B) :
    Function.Surjective (vtx hpos) := by
  intro a
  obtain ⟨b, rfl⟩ := residue_surjective a
  refine ⟨algebraMap B (ReesAlg Φ) b, ?_⟩
  show residue B ((algebraMap B B[T;T⁻¹] b).coeff 0) = residue B b
  rw [← LaurentPolynomial.C_eq_algebraMap, C_apply, ite_eq_left rfl]

/-- The vertex point `P₀` over the closed point of `B`. -/
def vertex (hpos : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B) : Ideal (ReesAlg Φ) :=
  RingHom.ker (vtx hpos)

instance vertex_isMaximal (hpos : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B) :
    (vertex hpos).IsMaximal :=
  RingHom.ker_isMaximal_of_surjective _ (vtx_surjective hpos)

omit [Algebra ℚ B] in
lemma mem_vertex (hpos : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B) (p : ReesAlg Φ) :
    p ∈ vertex hpos ↔ (p : B[T;T⁻¹]).coeff 0 ∈ maximalIdeal B := by
  rw [vertex, RingHom.mem_ker]
  exact residue_eq_zero_iff _

end Vertex

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial IsLocalRing

section ReesGen

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

omit [Algebra ℚ B] in
/-- Decomposition into homogeneous components. -/
lemma rees_decomp (p : ReesAlg Φ) : p = ∑ j ∈ (p : B[T;T⁻¹]).coeff.support,
    (⟨LaurentPolynomial.C ((p : B[T;T⁻¹]).coeff j) * T j,
      C_mul_T_mem_ReesAlg (p.2 j)⟩ : ReesAlg Φ) := by
  apply Subtype.ext
  rw [AddSubmonoidClass.coe_finsetSum]
  conv_lhs => rw [← AddMonoidAlgebra.sum_coeff_single (p : B[T;T⁻¹])]
  rw [Finsupp.sum]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [single_eq_C_mul_T]

include hd hw in
lemma weight_ge_of_mem {α : Fin n →₀ ℕ} {j : ℤ} (hαt : ((j : ℚ) / d) ≤ lam e α) :
    (j : ℤ) ≤ Finsupp.weight w α := by
  have hdq : (0 : ℚ) < d := by exact_mod_cast hd
  have hlamw : lam e α = (Finsupp.weight w α : ℚ) / d := by
    rw [lam, Finsupp.weight_eq_sum, eq_div_iff hdq.ne']
    push_cast
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [smul_eq_mul, Nat.cast_mul, hw i]; ring
  rw [hlamw, div_le_div_iff_of_pos_right hdq] at hαt
  exact_mod_cast hαt

/-- A monomial of weight `≥ j` times `T^j` is a monomial in the Rees coordinates. -/
lemma rees_mono_eq (α : Fin n →₀ ℕ) (j : ℤ) (m : ℕ) (hm : (Finsupp.weight w α : ℤ) - j = m)
    (hf : LaurentPolynomial.C (∏ i, c.x i ^ α i) * T j ∈ ReesAlg Φ) :
    (⟨_, hf⟩ : ReesAlg Φ) = (∏ i, reesX c hF he hd hw (Fin.castSucc i) ^ α i) *
      reesX c hF he hd hw (Fin.last n) ^ m := by
  apply Subtype.ext
  show LaurentPolynomial.C (∏ i, c.x i ^ α i) * T j = _
  rw [Subalgebra.coe_mul, SubmonoidClass.coe_pow, reesX_last, T_pow,
    SubmonoidClass.coe_finsetProd]
  simp only [SubmonoidClass.coe_pow, reesX_castSucc, mul_pow, T_pow, ← map_pow]
  rw [Finset.prod_mul_distrib, ← map_prod, prod_T_eq, mul_assoc, ← T_add]
  congr 2
  have : ((Finsupp.weight w α : ℕ) : ℤ) = ∑ i, ((α i : ℕ) : ℤ) * ((w i : ℕ) : ℤ) := by
    rw [Finsupp.weight_eq_sum]; push_cast; rfl
  linarith

/-- The Rees algebra is generated by the Rees coordinates. -/
theorem rees_adjoin : Algebra.adjoin B (Set.range (reesX c hF he hd hw)) = ⊤ := by
  classical
  set G := Algebra.adjoin B (Set.range (reesX c hF he hd hw))
  have hX : ∀ i, reesX c hF he hd hw i ∈ G := fun i => Algebra.subset_adjoin ⟨i, rfl⟩
  have hhom : ∀ (j : ℤ) (f : B) (hf : LaurentPolynomial.C f * T j ∈ ReesAlg Φ),
      f ∈ Φ.F j → (⟨_, hf⟩ : ReesAlg Φ) ∈ G := by
    intro j f hf hfF
    by_cases hj : j ≤ 0
    · obtain ⟨k, hk⟩ : ∃ k : ℕ, j = -(k : ℤ) := ⟨(-j).toNat, by omega⟩
      have : (⟨_, hf⟩ : ReesAlg Φ) = algebraMap B (ReesAlg Φ) f *
          reesX c hF he hd hw (Fin.last n) ^ k := by
        apply Subtype.ext
        show LaurentPolynomial.C f * T j = _
        rw [Subalgebra.coe_mul, SubmonoidClass.coe_pow, reesX_last, T_pow,
          Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap, hk]
        congr 2; ring
      rw [this]; exact G.mul_mem (G.algebraMap_mem f) (G.pow_mem (hX _) _)
    · have hmemF : ∀ x ∈ Submodule.span B {f | ∃ α : Fin n →₀ ℕ, (∀ i, e i = 0 → α i = 0) ∧
          ((j : ℚ) / d) ≤ lam e α ∧ f = ∏ i, c.x i ^ α i}, x ∈ Φ.F j := fun x hx => by
        rw [hF, chartFil, Chart.RF]; exact hx
      rw [hF, chartFil, Chart.RF] at hfF
      revert hf
      induction hfF using Submodule.span_induction with
      | mem g hg =>
        intro hf
        obtain ⟨α, hα0, hαt, rfl⟩ := hg
        have hwα := weight_ge_of_mem hd hw hαt
        obtain ⟨m, hm⟩ : ∃ m : ℕ, (Finsupp.weight w α : ℤ) - j = m :=
          ⟨_, (Int.toNat_of_nonneg (by omega)).symm⟩
        rw [rees_mono_eq c hF he hd hw α j m hm hf]
        exact G.mul_mem (G.prod_mem fun i _ => G.pow_mem (hX _) _) (G.pow_mem (hX _) _)
      | zero =>
        intro hf
        have : (⟨_, hf⟩ : ReesAlg Φ) = 0 := Subtype.ext (by simp)
        rw [this]; exact G.zero_mem
      | add x y hx hy ihx ihy =>
        intro hf
        have hxR : LaurentPolynomial.C x * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF x hx)
        have hyR : LaurentPolynomial.C y * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF y hy)
        have : (⟨_, hf⟩ : ReesAlg Φ) = ⟨_, hxR⟩ + ⟨_, hyR⟩ :=
          Subtype.ext (by show LaurentPolynomial.C (x + y) * T j = _; rw [map_add, add_mul]; rfl)
        rw [this]; exact G.add_mem (ihx hxR) (ihy hyR)
      | smul a x hx ih =>
        intro hf
        have hxR : LaurentPolynomial.C x * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF x hx)
        have : (⟨_, hf⟩ : ReesAlg Φ) = algebraMap B (ReesAlg Φ) a * ⟨_, hxR⟩ :=
          Subtype.ext (by
            show LaurentPolynomial.C (a • x) * T j = _
            rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap,
              smul_eq_mul, map_mul, mul_assoc])
        rw [this]; exact G.mul_mem (G.algebraMap_mem a) (ih hxR)
  rw [eq_top_iff]
  intro p _
  rw [rees_decomp p]
  exact G.sum_mem fun j _ => hhom j _ _ (p.2 j)

include c hF he hd hw in
theorem rees_finiteType : Algebra.FiniteType B (ReesAlg Φ) := by
  classical
  exact ⟨⟨Finset.univ.image (reesX c hF he hd hw), by
    rw [Finset.coe_image, Finset.coe_univ, Set.image_univ, rees_adjoin]⟩⟩

end ReesGen

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial IsLocalRing

section ReesVertex

variable {B : Type*} [CommRing B] [Algebra ℚ B] [IsLocalRing B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

include hF hd in
lemma fil_pos_le (hc : c.IsCentred) : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B := by
  intro j hj
  rw [hF, chartFil]
  exact hc.RF_le_maximalIdeal (div_pos (by exact_mod_cast hj) (by exact_mod_cast hd))

theorem vertex_eq_span (hc : c.IsCentred) :
    vertex (fil_pos_le c hF hd hc) = Ideal.span (Set.range (reesX c hF he hd hw)) := by
  classical
  set V := Ideal.span (Set.range (reesX c hF he hd hw)) with hVdef
  have hX : ∀ i, reesX c hF he hd hw i ∈ V := fun i => Ideal.subset_span ⟨i, rfl⟩
  apply le_antisymm
  · intro p hp
    rw [mem_vertex] at hp
    rw [rees_decomp p]
    refine Ideal.sum_mem _ fun j _ => ?_
    have hpj := p.2 j
    rcases lt_trichotomy j 0 with hj | hj | hj
    · -- negative degree: a multiple of `s`
      obtain ⟨k, hk⟩ : ∃ k : ℕ, j = -((k + 1 : ℕ) : ℤ) := ⟨(-j).toNat - 1, by omega⟩
      have : (⟨_, C_mul_T_mem_ReesAlg hpj⟩ : ReesAlg Φ) =
          algebraMap B (ReesAlg Φ) ((p : B[T;T⁻¹]).coeff j) *
            reesX c hF he hd hw (Fin.last n) ^ k * reesX c hF he hd hw (Fin.last n) := by
        apply Subtype.ext
        show LaurentPolynomial.C ((p : B[T;T⁻¹]).coeff j) * T j = _
        rw [Subalgebra.coe_mul, Subalgebra.coe_mul, SubmonoidClass.coe_pow, reesX_last, T_pow,
          Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap, mul_assoc, ← T_add, hk]
        congr 2; push_cast; ring
      rw [this]; exact Ideal.mul_mem_left _ _ (hX _)
    · -- degree `0`: a combination of the `xᵢ = uᵢ s^{wᵢ}`
      subst hj
      have h0 : (p : B[T;T⁻¹]).coeff 0 ∈ Ideal.span (Set.range c.x) := by rw [← hc]; exact hp
      have : (⟨_, C_mul_T_mem_ReesAlg hpj⟩ : ReesAlg Φ) =
          algebraMap B (ReesAlg Φ) ((p : B[T;T⁻¹]).coeff 0) := by
        apply Subtype.ext
        show LaurentPolynomial.C ((p : B[T;T⁻¹]).coeff 0) * T 0 = _
        rw [T_zero, mul_one, Subalgebra.coe_algebraMap, LaurentPolynomial.C_eq_algebraMap]
      rw [this]
      have hmap : Ideal.map (algebraMap B (ReesAlg Φ)) (Ideal.span (Set.range c.x)) ≤ V := by
        rw [Ideal.map_span, Ideal.span_le]
        rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
        rw [reesX_castSucc_mul_pow c hF he hd hw i]
        exact Ideal.mul_mem_right _ _ (hX _)
      exact hmap (Ideal.mem_map_of_mem _ h0)
    · -- positive degree: monomials in the `uᵢ`
      have hmemF : ∀ x ∈ Submodule.span B {f | ∃ α : Fin n →₀ ℕ, (∀ i, e i = 0 → α i = 0) ∧
          ((j : ℚ) / d) ≤ lam e α ∧ f = ∏ i, c.x i ^ α i}, x ∈ Φ.F j := fun x hx => by
        rw [hF, chartFil, Chart.RF]; exact hx
      have hmem : (p : B[T;T⁻¹]).coeff j ∈ Submodule.span B {f | ∃ α : Fin n →₀ ℕ,
          (∀ i, e i = 0 → α i = 0) ∧ ((j : ℚ) / d) ≤ lam e α ∧ f = ∏ i, c.x i ^ α i} := by
        have := hpj; rw [hF, chartFil, Chart.RF] at this; exact this
      generalize C_mul_T_mem_ReesAlg hpj = hf
      revert hf
      generalize (p : B[T;T⁻¹]).coeff j = q at hmem ⊢
      induction hmem using Submodule.span_induction with
      | mem g hg =>
        intro hf
        obtain ⟨α, hα0, hαt, rfl⟩ := hg
        have hwα := weight_ge_of_mem hd hw hαt
        obtain ⟨m, hm⟩ : ∃ m : ℕ, (Finsupp.weight w α : ℤ) - j = m :=
          ⟨_, (Int.toNat_of_nonneg (by omega)).symm⟩
        rw [rees_mono_eq c hF he hd hw α j m hm hf]
        refine Ideal.mul_mem_right _ _ ?_
        obtain ⟨i, hi⟩ : ∃ i, α i ≠ 0 := by
          rcases Decidable.em (∃ i, α i ≠ 0) with h | h
          · exact h
          have h' : ∀ i, α i = 0 := fun i => Nat.eq_zero_of_not_pos fun hp => h ⟨i, Nat.pos_iff_ne_zero.1 hp⟩
          have : Finsupp.weight w α = 0 := by
            rw [Finsupp.weight_eq_sum]; exact Finset.sum_eq_zero fun i _ => by rw [h' i, zero_smul]
          omega
        have hdvd : reesX c hF he hd hw (Fin.castSucc i) ∣
            ∏ l, reesX c hF he hd hw (Fin.castSucc l) ^ α l :=
          (dvd_pow_self _ hi).trans (Finset.dvd_prod_of_mem _ (Finset.mem_univ i))
        obtain ⟨r, hr⟩ := hdvd
        rw [hr]; exact Ideal.mul_mem_right _ _ (hX _)
      | zero =>
        intro hf
        have : (⟨_, hf⟩ : ReesAlg Φ) = 0 := Subtype.ext (by simp)
        rw [this]; exact zero_mem _
      | add x y hx hy ihx ihy =>
        intro hf
        have hxR : LaurentPolynomial.C x * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF x hx)
        have hyR : LaurentPolynomial.C y * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF y hy)
        have : (⟨_, hf⟩ : ReesAlg Φ) = ⟨_, hxR⟩ + ⟨_, hyR⟩ :=
          Subtype.ext (by show LaurentPolynomial.C (x + y) * T j = _; rw [map_add, add_mul]; rfl)
        rw [this]; exact add_mem (ihx hxR) (ihy hyR)
      | smul a x hx ih =>
        intro hf
        have hxR : LaurentPolynomial.C x * T j ∈ ReesAlg Φ := C_mul_T_mem_ReesAlg (hmemF x hx)
        have : (⟨_, hf⟩ : ReesAlg Φ) = algebraMap B (ReesAlg Φ) a * ⟨_, hxR⟩ :=
          Subtype.ext (by
            show LaurentPolynomial.C (a • x) * T j = _
            rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap, ← LaurentPolynomial.C_eq_algebraMap,
              smul_eq_mul, map_mul, mul_assoc])
        rw [this]; exact Ideal.mul_mem_left _ _ (ih hxR)
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    rw [SetLike.mem_coe, mem_vertex]
    cases i using Fin.lastCases with
    | last => rw [reesX_last, T_apply, ite_eq_right (by norm_num)]; exact zero_mem _
    | cast i =>
      rw [reesX_castSucc, coeff_C_mul_T]
      split_ifs
      · exact hc.x_mem i
      · exact zero_mem _

end ReesVertex

end BezoutCounterexample.Principalization


namespace BezoutCounterexample.Principalization

open LaurentPolynomial Polynomial IsLocalRing

section ReesLoc

variable {B : Type*} [CommRing B] [Algebra ℚ B] [IsLocalRing B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

/-- The Rees chart localized at the vertex. -/
abbrev reesLocChart (hc : c.IsCentred) :
    Chart (Localization.AtPrime (vertex (fil_pos_le c hF hd hc))) (n + 1) :=
  (reesChart c hF he hd hw).localization (vertex (fil_pos_le c hF hd hc)).primeCompl

theorem reesLoc_isCentred (hc : c.IsCentred) : (reesLocChart c hF he hd hw hc).IsCentred := by
  rw [Chart.IsCentred, ← Localization.AtPrime.map_eq_maximalIdeal]
  calc Ideal.map (algebraMap (ReesAlg Φ) _) (vertex (fil_pos_le c hF hd hc))
      = Ideal.map (algebraMap (ReesAlg Φ) (Localization.AtPrime
          (vertex (fil_pos_le c hF hd hc)))) (Ideal.span (Set.range (reesX c hF he hd hw))) :=
        congrArg (Ideal.map _) (vertex_eq_span c hF he hd hw hc)
    _ = Ideal.span (Set.range (reesLocChart c hF he hd hw hc).x) := by
        rw [Ideal.map_span, ← Set.range_comp]; rfl

include c hF he hd hw in
omit [IsLocalRing B] in
theorem rees_noetherian [IsNoetherianRing B] : IsNoetherianRing (ReesAlg Φ) := by
  have := rees_finiteType c hF he hd hw
  exact Algebra.FiniteType.isNoetherianRing B _

include c hF he hd hw in
omit [IsLocalRing B] in
/-- The Rees algebra is of finite type over `B`, hence inherits `PolyIndNoeth` (no choice). -/
theorem fact_polyIndNoeth_rees [Fact (Constructive.PolyIndNoeth B)] :
    Fact (Constructive.PolyIndNoeth (ReesAlg Φ)) :=
  have := rees_finiteType c hF he hd hw
  fact_polyIndNoeth_of_finiteType (R := B)

end ReesLoc

section ReesDeriv

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)

lemma reesDu_C_mul_T (i : Fin n) (a : B) (m : ℤ) :
    reesDu c w i (LaurentPolynomial.C a * T m) = LaurentPolynomial.C (c.d i a) * T (m - w i) := by
  rw [reesDu, Derivation.smul_apply, Derivation.leibniz, c.laurent_d_castSucc_T, smul_zero,
    zero_add, c.laurent_d_C, smul_eq_mul, smul_eq_mul, ← mul_assoc, ← T_add, mul_comm]
  congr 2; ring

/-- Derivatives of homogeneous elements in the Rees chart. -/
theorem reesChart_D_hom (γ : Fin n →₀ ℕ) (f : B) (j : ℤ)
    (h : LaurentPolynomial.C f * T j ∈ ReesAlg Φ) :
    (((reesChart c hF he hd hw).D (pushIdx (Nat.le_succ n) γ) ⟨_, h⟩ : ReesAlg Φ) : B[T;T⁻¹]) =
      LaurentPolynomial.C (c.D γ f) * T (j - Finsupp.weight w γ) := by
  induction γ using Finsupp.induction_single with
  | h0 => simp [pushIdx, Chart.D_zero]
  | hs β i ih =>
    rw [pushIdx_add_single, Chart.D_add_single, reesChart_d, castLE_succ_eq, reesDer_castSucc, ih,
      reesDu_C_mul_T, Chart.D_add_single, map_add, Finsupp.weight_single]
    congr 2; push_cast; ring_nf

end ReesDeriv

end BezoutCounterexample.Principalization

