import BezoutCounterexample.Principalization.CompFilGenPtL
import BezoutCounterexample.Principalization.DropPtBase

/-!
# I4 instances for the Rees algebra at its explicit points (leaf; hR4a, hR4c of `drop_pt`)

* `reesAlg_eq_adjoin_of`, `reesGenSetOf_finite`: the Rees algebra is generated over `A` by `T⁻¹`
  and `g Tʲ` for any lists `gens j` generating `F_j`, `1 ≤ j ≤ d` (`C_mul_T_mem_adjoin_of_ptL`);
* `reesAlg_finiteType_ptL`: `reesAlg_finiteType` with the generators of
  `LocusComp.exists_lspan_compFPt_ptL` (no `gensF`, i.e. no `IsNoetherian.noetherian.choose`, and
  no `exists_chartCoverPt`/`LocusComp.mem`);
* `rees_i4a_ptL`: `Fact (PolyIndNoeth R_q)` at every explicit point `q` of `R`
  (`fact_polyIndNoeth_atPrime`, `R` of finite type over `ℚ`);
* `Pt.formallySmooth_residueField`: at an explicit point of any `ℚ`-algebra the residue field is
  finite over `ℚ` (it embeds into the field of the point), so formally smooth
  (`Algebra.FormallySmooth.of_perfectField`).
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open IsLocalRing IsLocalization LaurentPolynomial Constructive

/-- **hR4c**: the residue field at an explicit point is formally smooth over `ℚ`. -/
theorem Pt.formallySmooth_residueField {S : Type} [CommRing S] [Algebra ℚ S] (q : Pt S) :
    Algebra.FormallySmooth ℚ (ResidueField (Localization.AtPrime q.ker)) := by
  have hinj : Function.Injective (q.resL.toRatAlgHom.toLinearMap) := (q.resL).injective
  have : Module.Finite ℚ (ResidueField (Localization.AtPrime q.ker)) :=
    Module.Finite.of_injective _ hinj
  infer_instance

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  [IsNoetherianRing A]

variable {I : Ideal A} (hI : I ≠ ⊥) (l : List A) (hl : I = lspan l) {v₀ : ℕ → ℚ}
  (hmax : IsMaxInvPt I v₀)
  {𝔭 : Ideal A} (h𝔭 : LocusComp I v₀ 𝔭) (d : ℕ)

omit [IsNoetherianRing A] in
include hI hmax h𝔭 in
lemma reesGenSetOf_subset (gens : ℤ → List A)
    (hgens : ∀ j : ℤ, 1 ≤ j → j ≤ d → lspan (gens j) = (compFil hI hmax h𝔭 d).F j) :
    reesGenSetOf d gens ⊆ ReesAlg (compFil hI hmax h𝔭 d) := by
  rintro _ (h | h)
  · rw [Set.mem_singleton_iff] at h
    subst h
    have : (T (-1) : A[T;T⁻¹]) = LaurentPolynomial.C 1 * T (-1) := by simp
    rw [this]
    exact C_mul_T_mem_ReesAlg (by rw [compFil_F_nonpos_gen hI hmax h𝔭 (by norm_num)]; trivial)
  · simp only [Set.mem_iUnion, Set.mem_image] at h
    obtain ⟨j, hj, g, hg, rfl⟩ := h
    rw [Finset.mem_Icc] at hj
    exact C_mul_T_mem_ReesAlg (by rw [← hgens j hj.1 hj.2]; exact Ideal.subset_span hg)

lemma reesGenSetOf_finite (gens : ℤ → List A) : (reesGenSetOf d gens).Finite := by
  refine (Set.finite_singleton _).union ?_
  refine Set.Finite.biUnion (Finset.finite_toSet _) fun j _ => ?_
  exact (List.finite_toSet (gens j)).image _

variable {d} (hd : 0 < d) (hw : ∀ i, ∃ w : ℕ, (w : ℚ) = d * v₀ i)
include hI hmax h𝔭 hd hw

variable {dim : ℕ}
  (hchartn : ∀ p : Pt A, ∃ f : A, f ∉ p.ker ∧ Nonempty (Chart (Localization.Away f) dim))
include l hl hchartn

/-- The Rees algebra is generated by any list family of generators of the steps. -/
theorem reesAlg_eq_adjoin_of [Fact (Constructive.HasPres A)] (gens : ℤ → List A)
    (hgens : ∀ j : ℤ, 1 ≤ j → j ≤ d → lspan (gens j) = (compFil hI hmax h𝔭 d).F j) :
    ReesAlg (compFil hI hmax h𝔭 d) = Algebra.adjoin A (reesGenSetOf d gens) := by
  apply le_antisymm
  · intro p hp
    have hp' : p = ∑ j ∈ p.coeff.support, LaurentPolynomial.C (p.coeff j) * T j := by
      conv_lhs => rw [← AddMonoidAlgebra.sum_coeff_single p]
      rw [Finsupp.sum]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [single_eq_C_mul_T]
    rw [hp']
    exact Subalgebra.sum_mem _ fun j _ =>
      C_mul_T_mem_adjoin_of_ptL hI l hl hmax h𝔭 hchartn hd hw gens hgens j _ (hp j)
  · rw [Algebra.adjoin_le_iff]
    exact reesGenSetOf_subset hI hmax h𝔭 d gens hgens


/-- **`reesAlg_finiteType` at points**: generators of the steps from
`exists_lspan_compFPt_ptL`. -/
theorem reesAlg_finiteType_ptL [Fact (Constructive.HasPres A)] :
    Algebra.FiniteType A (ReesAlg (compFil hI hmax h𝔭 d)) := by
  have hex : ∀ k : Fin d, ∃ L : List A,
      lspan L = (compFil hI hmax h𝔭 d).F ((k : ℕ) + 1 : ℕ) := fun k => by
    obtain ⟨L, hL⟩ := h𝔭.exists_lspan_compFPt_ptL hI l hl hmax hchartn ((((k : ℕ) + 1 : ℕ) : ℤ) / d)
    exact ⟨L, by rw [compFil_F, hL]⟩
  obtain ⟨L, hL⟩ := Constructive.finite_choice_dep hex
  let gens : ℤ → List A := fun j =>
    if h : 1 ≤ j ∧ j ≤ d then L ⟨(j - 1).toNat, by omega⟩ else []
  have hgens : ∀ j : ℤ, 1 ≤ j → j ≤ d → lspan (gens j) = (compFil hI hmax h𝔭 d).F j := by
    intro j h1 h2
    simp only [gens, dif_pos (And.intro h1 h2)]
    rw [hL]
    congr 1
    simp only [Fin.val_mk]
    omega
  have hfg : (ReesAlg (compFil hI hmax h𝔭 d)).FG := by
    rw [reesAlg_eq_adjoin_of hI l hl hmax h𝔭 hd hw hchartn gens hgens]
    exact Subalgebra.fg_def.2 ⟨_, reesGenSetOf_finite d gens, rfl⟩
  exact (Subalgebra.fg_iff_finiteType _).1 hfg

/-- **hR4a**: `PolyIndNoeth` at every explicit point of the Rees algebra. -/
theorem rees_i4a_ptL [Fact (Constructive.HasPres A)] [Algebra.FiniteType ℚ A]
    (q : Pt (ReesAlg (compFil hI hmax h𝔭 d))) :
    Fact (Constructive.PolyIndNoeth (Localization.AtPrime q.ker)) := by
  have := reesAlg_finiteType_ptL hI l hl hmax h𝔭 hd hw hchartn
  have : Algebra.FiniteType ℚ (ReesAlg (compFil hI hmax h𝔭 d)) :=
    Algebra.FiniteType.trans (S := A) inferInstance inferInstance
  exact fact_polyIndNoeth_atPrime q.ker

end BezoutCounterexample.Principalization
