import BezoutCounterexample.Principalization.SDiv
import BezoutCounterexample.Constructive.PresentedOps

/-!
# Presentations of the Rees algebra and of the torsor

If `A` is explicitly presented (`HasPres A`), so are the extended Rees algebra
`R = A[T⁻¹, g T^j] ⊆ A[T^±]` (`hasPres_reesAlg`) and the torsor `U = J_R(h)` (`hasPres_torsor`).

`hasPres_adjoin_over`: an `A`-subalgebra generated by a finite set `S` of a presented `A`-algebra
`B` is the `ℚ`-subalgebra generated by `S` and the images of the `ℚ`-generators of `A`, hence is
presented (`HasPres.adjoin`, kernel by elimination). For `R` this uses `reesAlg_eq_adjoin`; the
generators `gensF` of the `F_j` are, constructively, those computed from a chart cover
(`exists_contract`, `exists_inter_list`).
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open LaurentPolynomial Constructive

/-- The `ℚ`-generators of a presented ring. -/
theorem _root_.BezoutCounterexample.Constructive.HasPres.exists_gens {A : Type*} [CommRing A] [Algebra ℚ A] (hA : HasPres A) :
    ∃ (n : ℕ) (a : Fin n → A), ∀ x : A, x ∈ Algebra.adjoin ℚ (Set.range a) := by
  obtain ⟨n, G, ⟨e⟩⟩ := hA
  refine ⟨n, fun i => e (Ideal.Quotient.mk _ (MvPolynomial.X i)), fun x => ?_⟩
  obtain ⟨q, rfl⟩ := (e.surjective.comp Ideal.Quotient.mk_surjective) x
  rw [Algebra.adjoin_range_eq_range_aeval]
  refine ⟨q, ?_⟩
  have : (MvPolynomial.aeval fun i => e (Ideal.Quotient.mk (lspan G) (MvPolynomial.X i)) :
      MvPolynomial (Fin n) ℚ →ₐ[ℚ] A).toRingHom = e.toRingHom.comp (Ideal.Quotient.mk _) := by
    apply MvPolynomial.ringHom_ext
    · intro c
      exact RingHom.congr_fun (RingHom.ext_rat
        ((MvPolynomial.aeval fun i => e (Ideal.Quotient.mk (lspan G) (MvPolynomial.X i)) :
          MvPolynomial (Fin n) ℚ →ₐ[ℚ] A).toRingHom.comp MvPolynomial.C)
        ((e.toRingHom.comp (Ideal.Quotient.mk _)).comp MvPolynomial.C)) c
    · intro i; simp
  exact congrArg (fun φ : MvPolynomial (Fin n) ℚ →+* A => φ q) this

set_option maxHeartbeats 1000000 in
/-- **Finitely generated `A`-subalgebras of presented `A`-algebras are presented.** -/
theorem hasPres_adjoin_over {A B : Type*} [CommRing A] [Algebra ℚ A] [CommRing B] [Algebra ℚ B]
    [Algebra A B] [IsScalarTower ℚ A B] (hA : HasPres A) (hB : HasPres B) {S : Set B}
    (hS : S.Finite) : HasPres (Algebra.adjoin A S) := by
  obtain ⟨n, a, ha⟩ := hA.exists_gens
  -- a listing of `S` inside the proof (`Finite.exists_equiv_fin`; no `toFinset`/`toList`)
  haveI : Finite ↥S := Set.finite_coe_iff.2 hS
  obtain ⟨k, ⟨eS⟩⟩ := (Finite.exists_equiv_fin (↥S) : ∃ k, Nonempty (↥S ≃ Fin k))
  let l : List B := List.ofFn fun i : Fin k => (eS.symm i : B)
  have hlS : ∀ y, y ∈ l ↔ y ∈ S := fun y => by
    simp only [l, List.mem_ofFn]
    exact ⟨fun ⟨i, hi⟩ => hi ▸ (eS.symm i).2, fun hy => ⟨eS ⟨y, hy⟩, by simp⟩⟩
  let v : Fin (n + l.length) → B := Fin.append (fun i => algebraMap A B (a i)) (fun i => l.get i)
  have hvS : ∀ i, l.get i ∈ S := fun i => (hlS _).1 (List.get_mem l i)
  have hA_in : ∀ x : A, algebraMap A B x ∈ Algebra.adjoin ℚ (Set.range v) := by
    intro x
    have h1 : algebraMap A B x ∈ (Algebra.adjoin ℚ (Set.range a)).map (IsScalarTower.toAlgHom ℚ A B) :=
      Subalgebra.mem_map.2 ⟨x, ha x, rfl⟩
    rw [AlgHom.map_adjoin] at h1
    refine Algebra.adjoin_mono ?_ h1
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    exact ⟨Fin.castAdd _ i, Fin.append_left _ _ i⟩
  let T' : Subalgebra A B :=
    { carrier := (Algebra.adjoin ℚ (Set.range v) : Set B)
      mul_mem' := fun ha hb => Subalgebra.mul_mem _ ha hb
      add_mem' := fun ha hb => Subalgebra.add_mem _ ha hb
      algebraMap_mem' := hA_in }
  have hle1 : Algebra.adjoin A S ≤ T' := by
    rw [Algebra.adjoin_le_iff]
    intro y hy
    have : y ∈ l := (hlS y).2 hy
    obtain ⟨i, rfl⟩ := List.mem_iff_get.1 this
    show l.get i ∈ (Algebra.adjoin ℚ (Set.range v) : Set B)
    exact Algebra.subset_adjoin ⟨Fin.natAdd _ i, Fin.append_right _ _ i⟩
  have hle2 : Algebra.adjoin ℚ (Set.range v) ≤ (Algebra.adjoin A S).restrictScalars ℚ := by
    rw [Algebra.adjoin_le_iff]
    rintro _ ⟨i, rfl⟩
    refine Fin.addCases (fun i => ?_) (fun i => ?_) i
    · show v (Fin.castAdd _ i) ∈ _
      rw [show v (Fin.castAdd _ i) = algebraMap A B (a i) from Fin.append_left _ _ i]
      exact (Algebra.adjoin A S).algebraMap_mem _
    · show v (Fin.natAdd _ i) ∈ _
      rw [show v (Fin.natAdd _ i) = l.get i from Fin.append_right _ _ i]
      exact (Algebra.subset_adjoin (hvS i) : l.get i ∈ Algebra.adjoin A S)
  have heq : (Algebra.adjoin A S).toSubring = (Algebra.adjoin ℚ (Set.range v)).toSubring := by
    ext y
    exact ⟨fun hy => (hle1 hy : y ∈ (Algebra.adjoin ℚ (Set.range v) : Set B)),
      fun hy => (hle2 hy : y ∈ (Algebra.adjoin A S : Set B))⟩
  exact (hB.adjoin v).of_ringEquiv (RingEquiv.subringCongr heq).symm

variable {A : Type} [CommRing A] [IsDomain A] [Algebra ℚ A] [Algebra.Smooth ℚ A]
  [IsNoetherianRing A]

variable {I : Ideal A} (hI : I ≠ ⊥) {v₀ : ℕ → ℚ}
  (hmax : IsMaxInvPt I v₀)
  {𝔭 : Ideal A} (h𝔭 : LocusComp I v₀ 𝔭) {d : ℕ} (hd : 0 < d)
  (hw : ∀ i, ∃ w : ℕ, (w : ℚ) = d * v₀ i)

include hd hw in
/-- **The Rees algebra of a presented ring is presented.** -/
theorem hasPres_reesAlg [Fact (Constructive.HasPres A)] (hA : HasPres A) : HasPres (ReesAlg (compFil hI hmax h𝔭 d)) := by
  obtain ⟨_E⟩ := Constructive.HasPres.nonempty_enum hA
  letI := _E
  exact (hasPres_adjoin_over hA hA.laurent (reesGenSet_finite hI hmax h𝔭 d)).of_ringEquiv
    (Subalgebra.equivOfEq _ _ (reesAlg_eq_adjoin hI hmax h𝔭 d hd hw).symm).toRingEquiv

include hd hw in
/-- **The torsor over a presented ring is presented.** -/
theorem hasPres_torsor [Constructive.Enum A] [Fact (Constructive.HasPres A)] (hA : HasPres A) {π : A} (hπ : π ∈ (compFil hI hmax h𝔭 d).F 1) :
    HasPres (Torsor hI hmax h𝔭 d hπ) :=
  (hasPres_reesAlg hI hmax h𝔭 hd hw hA).jou _

end BezoutCounterexample.Principalization
