import BezoutCounterexample.Principalization.Vertex

/-!
# The vertex local ring, decided (leaf; (B) steps B1–B3)

Inputs of the Method-1 run at the vertex at an explicit point (twin of `vertex_invariant`):

* `rees_finiteType_dec`, `VLoc_polyIndNoeth_dec`: `rees_finiteType` without `classical`
  (`Subalgebra.fg_def` with `Set.range` instead of `Finset.image`), then `PolyIndNoeth` of the
  vertex localisation;
* `VLoc_dec`: the residue field of the vertex localisation is decided when that of `B` is
  (`p ∈ vertex ↔ p₀ ∈ 𝔪_B`, `mem_vertex`);
* `weakGens`, `weakV_eq_lspan`: for `I = (l)`, the weak transform at the vertex is generated by the
  images of `f Tᵈ`, `f ∈ l`.
-/

noncomputable section

namespace BezoutCounterexample.Principalization

open LaurentPolynomial IsLocalRing Constructive

section ReesGenDec

variable {B : Type*} [CommRing B] [Algebra ℚ B] {n : ℕ}
variable (c : Chart B n) {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ}
  {Φ : WFil B} (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
  (hw : ∀ i, (w i : ℚ) = d * e i)
include hF he hd hw

/-- `rees_finiteType` without `classical`. -/
theorem rees_finiteType_dec : Algebra.FiniteType B (ReesAlg Φ) :=
  ⟨Subalgebra.fg_def.2 ⟨Set.range (reesX c hF he hd hw), Set.finite_range _,
    rees_adjoin c hF he hd hw⟩⟩

/-- `fact_polyIndNoeth_rees` through `rees_finiteType_dec`. -/
theorem fact_polyIndNoeth_rees_dec [Fact (Constructive.PolyIndNoeth B)] :
    Fact (Constructive.PolyIndNoeth (ReesAlg Φ)) :=
  have := rees_finiteType_dec c hF he hd hw
  fact_polyIndNoeth_of_finiteType (R := B)

end ReesGenDec

section VLocDec

variable {B : Type*} [CommRing B] [Algebra ℚ B] [IsLocalRing B] {n : ℕ}
  {e : Fin n → ℚ} {d : ℕ} {w : Fin n → ℕ} {Φ : WFil B}
  (hpos : ∀ j : ℤ, 0 < j → Φ.F j ≤ maximalIdeal B)

/-- `VLoc_polyIndNoeth` through `rees_finiteType_dec`. -/
theorem VLoc_polyIndNoeth_dec [Fact (Constructive.PolyIndNoeth B)] (c : Chart B n)
    (hF : ∀ j, Φ.F j = chartFil c e d j) (he : ∀ i, 0 ≤ e i) (hd : 0 < d)
    (hw : ∀ i, (w i : ℚ) = d * e i) :
    Fact (Constructive.PolyIndNoeth (VLoc hpos)) := by
  have := fact_polyIndNoeth_rees_dec c hF he hd hw
  exact fact_polyIndNoeth_localization (vertex hpos).primeCompl

/-- **The residue field at the vertex is decided** when that of `B` is. -/
theorem VLoc_dec (hdec : ∀ x : B, x ∈ maximalIdeal B ∨ IsUnit x) (x : VLoc hpos) :
    x ∈ maximalIdeal (VLoc hpos) ∨ IsUnit x := by
  obtain ⟨⟨p, s⟩, rfl⟩ := IsLocalization.mk'_surjective (vertex hpos).primeCompl x
  rcases hdec ((p : B[T;T⁻¹]).coeff 0) with h | h
  · exact Or.inl ((IsLocalization.AtPrime.mk'_mem_maximal_iff _ (vertex hpos) p s).2
      ((mem_vertex hpos p).2 h))
  · refine Or.inr ((IsLocalRing.notMem_maximalIdeal).1 fun h' => ?_)
    have := (mem_vertex hpos p).1 ((IsLocalization.AtPrime.mk'_mem_maximal_iff _ (vertex hpos) p s).1 h')
    exact (IsLocalRing.notMem_maximalIdeal.2 h) this

/-- The generators `f Tᵈ` (`f ∈ l`) of the weak transform at the vertex. -/
def weakGens {d : ℕ} (l : List B) (hl : ∀ f ∈ l, f ∈ Φ.F d) : List (VLoc hpos) :=
  l.attach.map fun f => algebraMap (ReesAlg Φ) (VLoc hpos)
    ⟨LaurentPolynomial.C f.1 * T d, C_mul_T_mem_ReesAlg (hl f.1 f.2)⟩

omit [IsLocalRing B] [Algebra ℚ B] in
lemma weakIdeal_eq_span {d : ℕ} (I : Ideal B) (hId : I ≤ Φ.F d) (l : List B) (hlI : I = lspan l) :
    weakIdeal I hId = Ideal.span {p : ReesAlg Φ | ∃ f, ∃ (hf : f ∈ l),
      p = ⟨LaurentPolynomial.C f * T d, C_mul_T_mem_ReesAlg (hId (hlI ▸ Ideal.subset_span hf))⟩} := by
  set S := {p : ReesAlg Φ | ∃ f, ∃ (hf : f ∈ l),
      p = ⟨LaurentPolynomial.C f * T d, C_mul_T_mem_ReesAlg (hId (hlI ▸ Ideal.subset_span hf))⟩}
  apply le_antisymm
  · rw [weakIdeal, Ideal.span_le]
    rintro _ ⟨⟨f, hfI⟩, rfl⟩
    have hfl : f ∈ lspan l := hlI ▸ hfI
    suffices H : ∀ hx : f ∈ Φ.F d,
        (⟨LaurentPolynomial.C f * T d, C_mul_T_mem_ReesAlg hx⟩ : ReesAlg Φ) ∈ Ideal.span S from
      H (hId hfI)
    refine Submodule.span_induction (p := fun x _ => ∀ hx : x ∈ Φ.F d,
        (⟨LaurentPolynomial.C x * T d, C_mul_T_mem_ReesAlg hx⟩ : ReesAlg Φ) ∈ Ideal.span S)
      ?_ ?_ ?_ ?_ hfl
    · intro x hx _
      exact Ideal.subset_span ⟨x, hx, rfl⟩
    · intro _
      have : (⟨LaurentPolynomial.C (0 : B) * T d, C_mul_T_mem_ReesAlg (zero_mem _)⟩ :
          ReesAlg Φ) = 0 := Subtype.ext (by simp)
      rw [this]; exact zero_mem _
    · intro x y hx' hy' hx hy hxy
      have : (⟨LaurentPolynomial.C (x + y) * T d, C_mul_T_mem_ReesAlg hxy⟩ : ReesAlg Φ) =
          ⟨LaurentPolynomial.C x * T d, C_mul_T_mem_ReesAlg (hId (hlI ▸ hx'))⟩ +
          ⟨LaurentPolynomial.C y * T d, C_mul_T_mem_ReesAlg (hId (hlI ▸ hy'))⟩ :=
        Subtype.ext (by simp [add_mul])
      rw [this]
      exact add_mem (hx (hId (hlI ▸ hx'))) (hy (hId (hlI ▸ hy')))
    · intro a x hx' hx hax
      have : (⟨LaurentPolynomial.C (a • x) * T d, C_mul_T_mem_ReesAlg hax⟩ : ReesAlg Φ) =
          algebraMap B (ReesAlg Φ) a *
            ⟨LaurentPolynomial.C x * T d, C_mul_T_mem_ReesAlg (hId (hlI ▸ hx'))⟩ :=
        Subtype.ext (by
          simp only [smul_eq_mul, map_mul, Subalgebra.coe_mul, Subalgebra.coe_algebraMap,
            ← LaurentPolynomial.C_eq_algebraMap, mul_assoc])
      rw [this]
      exact Ideal.mul_mem_left _ _ (hx (hId (hlI ▸ hx')))
  · rw [Ideal.span_le]
    rintro _ ⟨f, hf, rfl⟩
    exact Ideal.subset_span ⟨⟨f, hlI ▸ Ideal.subset_span hf⟩, rfl⟩

/-- **The weak transform at the vertex is explicitly generated.** -/
theorem weakV_eq_lspan {d : ℕ} (I : Ideal B) (hId : I ≤ Φ.F d) (l : List B) (hlI : I = lspan l) :
    weakV hpos I hId = lspan (weakGens hpos l fun f hf => hId (hlI ▸ Ideal.subset_span hf)) := by
  rw [weakV, weakIdeal_eq_span I hId l hlI, Ideal.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨p, ⟨f, hf, rfl⟩, rfl⟩
    exact List.mem_map.2 ⟨⟨f, hf⟩, List.mem_attach _ _, rfl⟩
  · intro hx
    obtain ⟨⟨f, hf⟩, -, rfl⟩ := List.mem_map.1 hx
    exact ⟨_, ⟨f, hf, rfl⟩, rfl⟩

end VLocDec

end BezoutCounterexample.Principalization
